### ISSUE TITLE
ArrayIndexOutOfBoundsException for 1 channel file

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#102]
I get this with the attached file:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4841
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader$YCbCrConverter.convertYCbCr2RGB(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader$YCbCrConverter.convertYCbCr2RGB(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readImageAsRasterAndReplaceColorProfile(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)

the "standard" jpeg reader of java is able to read the file.

The file has no meta data, but other jpeg files in the same series have this meta:

    <?xml version="1.0" encoding="UTF-8"?><javax_imageio_1.0>
      <Chroma>
        <ColorSpaceType name="YCbCr"/>
        <NumChannels value="1"/>
      </Chroma>
      <Compression>
        <CompressionTypeName value="JPEG"/>
        <Lossless value="FALSE"/>
        <NumProgressiveScans value="1"/>
      </Compression>
      <Dimension>
        <ImageOrientation value="normal"/>
      </Dimension>
    </javax_imageio_1.0>

(I'm doing a mass test with PDF files. I'm reporting the few embedded JPEG files that bring errors but didn't have errors with the sun reader)
![176936-p154-2](https://cloud.githubusercontent.com/assets/6665575/6420702/cdedebe0-bec8-11e4-8fc4-887efdc9981e.jpg)

**Comment by haraldk** [comment]
Hi again,

Thanks for reporting these issues! The sample files, although broken, are good for testing that the reader fails gracefully. I'll fix.

-- 
Harald K

**Comment by THausherr** [comment]
Thanks; I forgot to mention why I'm doing these mass tests: to evaluate whether we can replace the default jpeg reader in PDFBox, and it looks promising. I've now created an issue about this:
https://issues.apache.org/jira/browse/PDFBOX-2694

**Comment by haraldk** [comment]
Okay, cool.

I know someone who would be happy about that. :-)
Let me know if there's anything else I can do to help you guys (apart from fixing the issues reported).


Regards,

-- 
Harald K

**Comment by haraldk** [comment]
Fix in 1f990409278453cf5ce51d3cf43bef7a49011a20.

The attached image is now readable.

Accessing the meta data will still fail though. You might want to report a bug on one of the other image in the series, if they still have issues (ie. if the metadata still says YCbCr and 1 channel, which obviously can't happen). 

-- 
Harald K
