### ISSUE TITLE
Upgrade to Junit5

### ISSUE THREAD

**Issue by puthusseri** [haraldk/TwelveMonkeys#1051]
Adding unit test in junit5 is more readable.
This pull request contains the changes required for upgrading to junit5 from junit4.
[Junit 5 Documentation](https://junit.org/junit5/docs/current/user-guide/)

**Comment by puthusseri** [comment]
#1050

**Comment by haraldk** [comment]
Thanks! 

This has been on my todo-list for quite a while, thank you for taking the time to actually do it and create a PR! Much appreciated! 😀 

I will look through and review the changes as soon as I find the time.
