### ISSUE TITLE
Some YCbCr encoded JPEGs have ColorSpaceType "RGB" in the standard metadata

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#108]
The following test resources fail to report correct color space using the standard metadata: jpeg/exif-jpeg-thumbnail-sony-dsc-p150-inverted-colors.jpg, jpeg/exif-pspro-13-inverted-colors.jpg and jpeg/no-jfif-ycbcr.jpg. The first two are Exif files, the last one is not (might be two different issues).

Update: The first two reads correctly, while the last one has inverted colors using the standard `JPEGImageReader`. Seems the Exif segment presence makes the native code interpret color space correctly, even though the Java part does not (thus the incorrect value in the metadata).

The images are all non-subsampled, with component ids 1-3. That means they _should_ be identified as YCbCr according to [the metadata API doc](http://docs.oracle.com/javase/7/docs/api/javax/imageio/metadata/doc-files/jpeg_metadata.html#color):

>  If neither [JFIF or Adobe] marker segment is present [...and the component count is 3 or 4...] the component ids are consulted. If these values are 1-3 for a 3-channel image, then the image is assumed to be YCbCr.

However, they are not...

**Comment by haraldk** [comment]
Great...

It turns out that the following code can be found in `com.sun...JPEGMetadata.getStandardChromaNode()` (comments by me): 

        boolean idsAreJFIF = true;

        for (int i = 0; i < sof.componentSpecs.length; i++) {
            int id = sof.componentSpecs[i].componentId;
            if ((id < 1) || (id >= sof.componentSpecs.length)) { // <-- n comps must be in range [1...n-1]?!
                idsAreJFIF = false;
            }
        }

        if (idsAreJFIF) { // <-- Never true..
            csType.setAttribute("name", "YCbCr");
            // ...
        }



-- 
Harald K

**Comment by haraldk** [comment]
Submitted bug through the Oracle bug tracker. Awaiting bug id...

**Comment by haraldk** [comment]
I'm afraid the only thing we can do for now, is creating a complete replacement for the `JPEGMetadata` class, which I really hoped to avoid...

A possible workaround for client code, would be using the native metadata, and see that the SOF component ids are 1-3, and in that case figure out that the data is in YCbCr format rather than RGB.

**Comment by haraldk** [comment]
https://bugs.openjdk.java.net/browse/JDK-8074967

**Comment by haraldk** [comment]
One option would be to insert a fake JFIF marker, to "help" the reader see this as a YCbCr JPEG. Should be fully compatible.

**Comment by haraldk** [comment]
Seems the original JDK issue is actually fixed in Java 9.

**Comment by albms** [comment]
Hi Harald thanks for the quick feedback. I don't know yet what software produced the images but I'll try to find out. I do know that there was a batch of images received from the same source, and about half of them had caused this problem, and the other half were fine, but of course that may have been because some had been processed by some software prior to submission and some had not. I will get back to you if I find out any more.

**Comment by haraldk** [comment]
Should be fixed now, via 5cc201b4.
