### ISSUE TITLE
SVGImageReader only reads the first image

### ISSUE THREAD

**Issue by JavadocMD** [haraldk/TwelveMonkeys#125]
I noticed that an `SVGImageReader` instance that was used to read multiple SVG files was only returning the first image. I tracked this to the internal `Rasterizer` which was caching the image and not resetting when `setInput(...)` was called.

I've got a PR ready which includes a test case illustrating the issue and a proposed fix: creating the Rasterizer anew each time. I don't have a good sense of whether or not this is an efficient approach -- perhaps simply clearing the Rasterizer's state would be better -- but this does work.

**Comment by haraldk** [comment]
Hi Tyler!

Sorry for the late response, I just got back from easter holidays (with family, without computer ;-).

Thanks a lot for your contribution! 

I'll look into your PR as soon as possible, hopefully tomorrow.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Looks good! 

I moved the creation of the new rasterizer to `resetMembers` method, apart from that looks fine!

I also found a bug in my Spi class using your sample files, it doesn't properly recognize SVG files without `DOCTYPE`. I'll try to fix that as well, before closing the issue.

-- 
Harald K

**Comment by haraldk** [comment]
Done.

**Comment by JavadocMD** [comment]
Looks great! Thanks again.
