### ISSUE TITLE
Latest Maven version is 3.0.2

### ISSUE THREAD

**Issue by Quurks** [haraldk/TwelveMonkeys#129]
http://mvnrepository.com/artifact/com.twelvemonkeys.imageio

**Comment by haraldk** [comment]
Hi Quurks,

It looks good to me, using the official site (Central):
http://search.maven.org/#search%7Cga%7C1%7Ccom.twelvemonkeys

Not sure how mvnrepository.com synchronizes with Central. My guess is, it's just not up to date (yet). Do you have any problems using the dependencies in your Maven project?


Best regards,

-- 
Harald K

**Comment by Quurks** [comment]
Yes, its working correctly.
The main problem was that gradle treats 3.1 and 3.1.0 differently, and I didn't think it was a problem on my end because mvnrepository.com didn't show 3.1.0 either. 

Thanks for your help!

**Comment by haraldk** [comment]
All good then! Thanks for reporting back!

-- 
Harald K
