### ISSUE TITLE
Investigate the Java 8 LCMS error 13 multithread issue

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#130]
See:

* http://stackoverflow.com/questions/26535842/multithreaded-jpeg-image-processing-in-java 
* https://bugs.openjdk.java.net/browse/JDK-8032243?page=com.atlassian.streams.streams-jira-plugin:activity-stream-issue-tab

The SO question contains multiple suggested workaround, see if we should integrate any of those (if they really work, that is...).

**Comment by rmuller** [comment]
Note I tried all suggestion found at [SO](http://stackoverflow.com/questions/26535842/), but for one image, no resolution is possible. Attached it for your research.
![8797055-66_42320_tif](https://cloud.githubusercontent.com/assets/754040/9444059/c6394000-4a84-11e5-83ea-693310b4fb28.png)

**Comment by haraldk** [comment]
Hi Ronald,

Thanks for reporting! However, the problem with the image is not related to the *multithread-issue* in question. I can reproduce an exception using a single thread. I also get an exception on Java 1.7/KCMS, but with a different error message?

Can you please file another issue for this? 

We might have to ignore the ICC profile in this case, or see if there's anything we can do to patch it at runtime.

-- 
Harald K

**Comment by rmuller** [comment]
Okay, done, see #170

**Comment by haraldk** [comment]
Closing for now, unable to reproduce.
