### ISSUE TITLE
provided jar-files craches our application on java 1.6

### ISSUE THREAD

**Issue by runholen** [haraldk/TwelveMonkeys#131]
We tried using this project for tif-support in our application, and it seemed to work fine, unfortunately it crashed our application for many customers with the following error:
java.lang.UnsupportedClassVersionError: com/twelvemonkeys/imageio/plugins/tiff/TIFFImageReaderSpi : Unsupported major.minor version 51.0
This happened at application start, when trying to read image files, before any tif-support we integrated, as ImageIO.read initialization is affected.
We used the provided 3.1.0-jar-files and these customers ran java 1.6. We don't want to upgrade java on all their computers (they are running on posready-systems with few updates). Could you change the target vm for the jar-files to include support for java 1.6?

**Comment by haraldk** [comment]
Hi Runar,

You really should get your customers to upgrade to a more recent and secure Java version. Java 6 is long dead, and [Java 7 has just entered end-of-life as of April 2015](http://www.oracle.com/technetwork/java/eol-135779.html#Java6-end-public-updates). *I* **strongly** *recommend that you update Java on these computers* (sorry, just had to say that).

Anyway, the official 3.0.x releases are built with Java 6 support. If this is an option for you, you could continue using that release, if you only need TIFF read support (write support was introduced in 3.1.0).
The official 3.1.x releases will require at least Java 7. 

I'm a single person maintaining this project on my spare time, and unfortunately I don't have the time and resources to maintain backwards compatibility with multiple Java versions. However, most of the source code will still build using Java 5 or 6.  You should be able to just change the Java versions in the `pom.xml` to 1.6 or 1.5, try to build and fix the issues from there. Apparently, [this guy](https://github.com/carlislehenning) was able to compile it for Java 5 (see issue #122).

Please let me know if any of these options work for you! :-)

Best regards,

-- 
Harald K

**Comment by runholen** [comment]
Thank you. Where can I find a link to the 3.0.x.jar -files?

**Comment by haraldk** [comment]
Common dependencies
* [common-lang-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/common/common-lang/3.0.2/common-lang-3.0.2.jar)
* [common-io-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/common/common-io/3.0.2/common-io-3.0.2.jar)
* [common-image-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/common/common-image/3.0.2/common-image-3.0.2.jar)
 
ImageIO dependencies
* [imageio-core-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-core/3.0.2/imageio-core-3.0.2.jar)
* [imageio-metadata-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-metadata/3.0.2/imageio-metadata-3.0.2.jar)
 
ImageIO plugins
* [imageio-jpeg-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-jpeg/3.0.2/imageio-jpeg-3.0.2.jar)
* [imageio-tiff-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-tiff/3.0.2/imageio-tiff-3.0.2.jar)
* [imageio-psd-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-psd/3.0.2/imageio-psd-3.0.2.jar)
* [imageio-pict-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-pict/3.0.2/imageio-pict-3.0.2.jar)
* [imageio-iff-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-iff/3.0.2/imageio-iff-3.0.2.jar)
* [imageio-icns-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-icns/3.0.2/imageio-icns-3.0.2.jar)
* [imageio-ico-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-ico/3.0.2/imageio-ico-3.0.2.jar)
* [imageio-thumbsdb-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-thumbsdb/3.0.2/imageio-thumbsdb-3.0.2.jar)
 
ImageIO plugins requiring 3rd party libs
* [imageio-batik-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-batik/3.0.2/imageio-batik-3.0.2.jar)
* [imageio-jmagick-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-jmagick/3.0.2/imageio-jmagick-3.0.2.jar)
 
Servlet support
* [servlet-3.0.2.jar](http://search.maven.org/remotecontent?filepath=com/twelvemonkeys/servlet/servlet/3.0.2/servlet-3.0.2.jar)

PS: I'll add these links to the README.md file.

-- 
Harald K
