### ISSUE TITLE
javax.imageio.IIOException: Unsupported Image Type on JPEG

### ISSUE THREAD

**Issue by Svantulden** [haraldk/TwelveMonkeys#133]
Hi, 

When I try to read a specific JPEG with `ImageIO.read(inputStream);`, I am getting an `javax.imageio.IIOException: Unsupported Image Type` Exception.     

I have only added the TwelveMonkeys `imageio-jpeg version 3.1.0` dependency via Maven, this should be enough to be used by `ImageIO.read(inputStream);` right? 

I think the image is in CMYK, but I don't know that much about image types and formats. Am I doing something wrong, or is this image just not parsable? 

Relevant stacktrace: 

```
at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1068) [rt.jar:1.8.0_40]
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039) [rt.jar:1.8.0_40]
	at javax.imageio.ImageIO.read(ImageIO.java:1448) [rt.jar:1.8.0_40]
	at javax.imageio.ImageIO.read(ImageIO.java:1352) [rt.jar:1.8.0_40]
``` 

The image in question: http://imgur.com/N49O3Xp (I hope imgur doesn't change the image in some way?)

**Comment by haraldk** [comment]
Hi Sander,

Yes, your image is CMYK. It seems imgur keeps the format unchanged. 

However, the stack trace you posted shows that only the `com.sun....JPEGImageReader` is used, not the `com.twelvemonkeys` one. I can read it without problems here, using the correct `JPEGImageReader`.

Can you try running the following code (in the same context as you tried `ImageIO.read`):

    Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("JPEG");
    while (readers.hasNext()) {
        System.out.println("reader: " + readers.next());
    }

...and update with the output? Unless the first line reads:

    reader: com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader@somehash

...the JPEG plugin isn't properly installed.

I think adding a dependency on `imageio-jpeg` should do, and the rest should be taken care of via transitive dependencies. You could try executing:

    mvn dependency:tree

...and see if it looks okay. 


Best regards,

-- 
Harald K

**Comment by Svantulden** [comment]
Thanks alot for helping and responding so fast!

Yeah I only get the `com.sun.imageio.plugins.jpeg.JPEGImageReader@4b3683eb` in the output. 

Running `mvn dependency:tree` gives: 
```
[INFO] \- com.twelvemonkeys.imageio:imageio-jpeg:jar:3.1.0:compile
[INFO]    +- com.twelvemonkeys.imageio:imageio-core:jar:3.1.0:compile
[INFO]    +- com.twelvemonkeys.imageio:imageio-metadata:jar:3.1.0:compile
[INFO]    +- com.twelvemonkeys.common:common-lang:jar:3.1.0:compile
[INFO]    +- com.twelvemonkeys.common:common-io:jar:3.1.0:compile
[INFO]    \- com.twelvemonkeys.common:common-image:jar:3.1.0:compile
```

This seems like the imageio plugin fails to load then? Do I need to add custom import to twelvemonkeys' imageio? I now have `import javax.imageio.ImageIO;` in my class.

**Comment by haraldk** [comment]
Thanks,

No, you shouldn't need to import anything. `ImageIO.read` should work. 

Can you give me some more context? Are you by any chance creating a web application, or anything else that uses dynamic class loaders (OSGI etc)? Or do you get the same problem from a simple command-line program?


-- 
Harald K

**Comment by Svantulden** [comment]
Sure. 

Yeah I am using this in an image uploader in our web application. The context is that it is being called in an injected service (RequestScoped and Named Java EE bean).

```Java
@Named
@RequestScoped
public class PictureService
```

And we inject it like this: 

```Java
@Inject
private PictureService pictureService;
``` 

Then we call a method in the `PictureService` that gets the image `InputStream` and tries to read it into a `BufferedImage`. 

```Java
public Picture edit(Picture picture, InputStream inputStream, String submittedFileName, String mimeType) 
            throws AttributeNotUniqueException, VersionConflictException, 
            UnsupportedMimeTypeException, IOException, InterruptedException {
...
    BufferedImage originalBufferedImage = ImageIO.read(inputStream);
...
}
```

**Comment by haraldk** [comment]
Okay,

Starting to make sense. :-)

I don't have any experience using the library in an EJB context, but I think it should work. Basically, you have at least three options:

1. Install all of the dependent TwelveMonkeys JARs into your application servers `lib` folder (making them server global), and change your maven dependencies' scope to `provided`.
2. Install the `IIOProviderContextListener` as described, in your web application. If you deploy the web part and your beans as one unit (i.e. an EAR or a WAR), you should be good I think.
3. Create another bean, probably a `@Singleton` with `@Startup`. Then add `@PostConstruct` and `@PreDestroy` methods, that basically does the same as the [`IIOProviderContextListener`](https://github.com/haraldk/TwelveMonkeys/blob/master/servlet/src/main/java/com/twelvemonkeys/servlet/image/IIOProviderContextListener.java)'s `contextInitialized` and `contextDestroyed` methods. Have this bean `@Inject`ed to your `PictureService`, just to make sure it's fully initialized before you start handling requests. This is of course completely untested and unsupported, but in theory it could work. :-)


Good luck,

-- 
Harald K

**Comment by Svantulden** [comment]
Amazing, thanks a lot! It works by using your option 3. I tried option 2 but I got a `ClassNotFoundException` for some reason. 

I did not see the [Deploying plugins in a web app](https://github.com/haraldk/TwelveMonkeys#deploying-the-plugins-in-a-web-app) part of the README before, my bad. Thanks for pointing me in the right direction!

**Comment by haraldk** [comment]
You're welcome!

Glad it worked out. :-)

-- 
Harald K
