### ISSUE TITLE
how to read gif and png?

### ISSUE THREAD

**Issue by sanatmastan** [haraldk/TwelveMonkeys#137]
HI, Probably this is not an issue just want to clarify myself, is there a twelmonkeys reader for gif and png?

when i use 
        Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("gif");
        while (readers.hasNext()) {
            System.out.println("reader: " + readers.next());
        }

i see only 
reader: com.sun.imageio.plugins.gif.GIFImageReader@2b9c1dc4

**Comment by haraldk** [comment]
Hi Sanatmastan,

You are right, there is no TwelveMonkeys GIF or PNG plugin as of yet. Simply because there's never been a need, and the JRE supplied versions are working just fine.

If you find a PNG or GIF the JRE can't read (but still can be read in most other software), I'm interested!

I'm also considering writing a `PNGImageWriter` at some point, because the JRE `PNGImageWriter` is unnecessary slow, but it's not a huge priority just now. 


Regards,

-- 
Harald K

**Comment by sanatmastan** [comment]
Actually i see some discrepancies in reading image parameters from different softwares.

When i verify the image size using jvms GIFImageReader i got width as 73, actually it is 97
/Users/syelchuri/Documents/Project/media_docs/work/invalid_width.gif
com.sun.imageio.plugins.gif.GIFImageReader
FileFormat:gif
Height:73
Width:73
size:2655
Quality:-1.0
isJPEG:false
Date creation:null
IMG_READ::ExeTime=0:0:0:001 
-----------------------------
Where as if i use direct stream to read initial bytes to read image parameters i got
Height:73
Width:97
mimetype:image/gif
filesize:2655

This happens only for few images, i attached one.
![invalid_width](https://cloud.githubusercontent.com/assets/2852925/7805693/957cf6e6-0394-11e5-80fa-46763d1988fc.gif)

May i know the reason?

Thanks
Sanat.

**Comment by haraldk** [comment]
Hi Sanat,

This isn't really a general help forum, so your question might be better asked on StackOverflow. :-)

That said, both are "correct". The raster in the file is really 97 by 73. However, the image descriptor in the GIF has x offset of 12, and logical width of 73. The 12 pixel border on each side is not supposed to be displayed. The `GIFImageReader` does the correct thing, as far as I can understand.

See [GIF format example (Wikipiedia)](http://en.wikipedia.org/wiki/GIF#Example_GIF_file) for more details, and difference between "Logical Screen Descriptor" and "Image Descriptor". 


Regards,

-- 
Harald K

**Comment by sanatmastan** [comment]
Thanks Harald for quick reply.
