### ISSUE TITLE
java.awt.color.CMMException: Cannot get color transform

### ISSUE THREAD

**Issue by thesunshinerain** [haraldk/TwelveMonkeys#140]
The attached image was found on this following Java bug ticket:
http://bugs.java.com/view_bug.do?bug_id=6829549
http://farm1.static.flickr.com/130/413993721_0894d0328d_b.jpg

Oracle Java 7 and 8 work fine with this image:

Using imageio-jpeg-3.1.0.jar, I get:
SEVERE        2015.05.28.11.43.59.068T-0500 java.awt.color.CMMException: Cannot get color transform
SEVERE        2015.05.28.11.43.59.068T-0500     at sun.java2d.cmm.lcms.LCMS.createNativeTransform(Native Method)
SEVERE        2015.05.28.11.43.59.068T-0500     at sun.java2d.cmm.lcms.LCMSTransform.doTransform(LCMSTransform.java:149)
SEVERE        2015.05.28.11.43.59.068T-0500     at sun.java2d.cmm.lcms.LCMSTransform.colorConvert(LCMSTransform.java:526)
SEVERE        2015.05.28.11.43.59.068T-0500     at java.awt.image.ColorConvertOp.filter(ColorConvertOp.java:571)
SEVERE        2015.05.28.11.43.59.068T-0500     at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readImageAsRasterAndReplaceColorProfile(Unknown Source)
SEVERE        2015.05.28.11.43.59.068T-0500     at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
![badtest](https://cloud.githubusercontent.com/assets/12647056/7869256/258b11ba-0547-11e5-9b4b-69c4f82a6397.jpg)

**Comment by haraldk** [comment]
Thanks a lot for finding this!

I'll fix! :-)

I have something working locally (ignoring the profile, quite similar to what the JRE now does). Just need to create test cases and clean up the code a little, before submitting a patch.


-- 
Harald K

**Comment by thesunshinerain** [comment]
Awesome! I appreciate the work ya’ll do. Now just need Lossless JPEG support!

see ya,
Robbie

**Comment by haraldk** [comment]
Fixed in bbaa3e1186f5e38b2198d754fd4683f30c2adc81.

Re: JPEG Lossless; if only there were more hours in a day... ;-)

-- 
Harald K

**Comment by haraldk** [comment]
Released in [3.1.1](https://github.com/haraldk/TwelveMonkeys/releases/tag/twelvemonkeys-3.1.1) (bugfix release).
