### ISSUE TITLE
Read support for TIFF with CMYK JPEG

### ISSUE THREAD

**Issue by lucasgessoni** [haraldk/TwelveMonkeys#143]
Hello!
 
  Sometimes I must read TIFF images which contain CMYK JPEG but it throws an Exception. Checking the code for the TIFFImageReader.createJPEGDelegate method I saw that the standard JPEG reader is used, with the following comment: "TIFF is strictly ISO JPEG, so we should probably stick to the standard reader".  The default ImageIO JPEG reader has no support for CMYK JPEG.  

  Would it be possible to change the TIFFImageReader class code of the TwelveMonkeys API to use the custom TwelveMonkey JPEG reader that is able to read CMYK JPEGs? If you don't want to change the default behaviour would you consider making it possible to configure the TIFFImageReader class in some way, because I did not find anything that I could do (besides changing the TwelveMonkey code itself) to change the behaviour to be able to read such files properly. Is there something that I am missing?

Thanks!

**Comment by haraldk** [comment]
Hi Lucas,

Thanks for the suggestion!

If you send me some sample CMYK TIFFs, I'm sure we can make that happen. :-)

The TIFFs need to be redistributable, and and at least one that is not too large that I can use for a test case.

Just rename the files from `foo.tif` to `foo_tif.jpg` or similar, to be able to attach it using the GitHub issue tracker (as it only supports PNG, JPEG and GIF for some reason...).


Best regards,

-- 
Harald K

**Comment by lucasgessoni** [comment]
I made two test files using ImageMagick (ie: "convert img.bmp -compress jpeg -colorspace cmyk -profile profile.icc img2.tif"). One of then has an embedded color profile. Unfortunately the original file is too big to add here, but I can send it to you if needed.

![test_with_profile tif](https://cloud.githubusercontent.com/assets/6775234/8059041/19e23888-0e94-11e5-89f2-318cc07c06a2.jpg)

![test_no_profile tif](https://cloud.githubusercontent.com/assets/6775234/8059040/19e0ade2-0e94-11e5-8d41-f87d49412665.jpg)

**Comment by haraldk** [comment]
Thanks!

I'll have a look at it!

Unfortunately, it's not just to switch to the TwelveMonkeys `JPEGImageReader`, as the CMYK data in the JPEG stream does not seem to be stored "inverted", as is usual for standalone CMYK JPEGs. Also, the color profile (ICC profile) is stored in the TIFF structure, not in the JPEG APP2 segment, so we need to take that into account.

It's certainly doable, I will just need some time to implement it. Unless you want to have a go yourself, of course?

-- 
Harald K

**Comment by lucasgessoni** [comment]
Hello!

  Maybe the original files I had a problem with contains CMYK and profile data in the usual manner, in which case the TwelveMonkeys JPEGImageReader should work. I will have a look at it.

Can you guess how much time you think I may need If a would try to implement the suggested changes? (ie: some hours, some days, some months). I have some basic understanding of image data, like what a color profile is and what compressions are often used, but don’t have experience with the particulars of JPEG or TIFF specification.

Also, if a wanted to change the TIFF reader to use the TwelveMonkeys JPEGImageReader (as I understand this would be required anyway), what would be the best way? Just remove the code that diverts the flow to the default reader or make something that lets users configure the behavior?

Thanks for your time!

  Lucas

**Comment by haraldk** [comment]
You should be able to do it in slightly less than 2 hours. ;-)

It was a lot easier than I thought, so I just implemented it. Fixed in da8a013. 

Seems to work fine for both of your samples, plus some more I downloaded from the ImageMagick site.

-- 
Harald K

**Comment by lucasgessoni** [comment]
Thanks! :)
