### ISSUE TITLE
Problematic JPEG image

### ISSUE THREAD

**Issue by Karnifexx** [haraldk/TwelveMonkeys#144]
I am having trouble handling a particular JPEG image using this awesome library!

For 99% of JPEGs everything works great and then I have the following (http://md1.libe.com/photo/781249-hidalgo-soutient-le-qatar-contre-philippot.jpg):

![problemimage](https://cloud.githubusercontent.com/assets/3837303/8041317/3edc33da-0e0f-11e5-87eb-05480fd74d1b.jpg)

Which after loading and saving in JAVA appears as follows:

![problemimage2](https://cloud.githubusercontent.com/assets/3837303/8041321/49e0a89c-0e0f-11e5-99e6-a97544c30877.jpg)

Code to repoduce:

```java
//Image source is http://md1.libe.com/photo/781249-hidalgo-soutient-le-qatar-contre-philippot.jpg
File inFile = new File("problemImage.jpg");
File outFile  = new File("problemImage2.jpg");
BufferedImage image = ImageIO.read(inFile);
ImageIO.write(image, "jpg", outFile);
```

Any help handling such JPEGs using this library would be greatly appreciated.

Regards,
Marc

**Comment by haraldk** [comment]
Hi Marc,

Thanks for your feedback! :-)

Your image however, is not a JPEG. It is a PNG. And the PNG is in ARGB format. This is what is causing the problem. Remove the alpha channel (ie. convert the image to `TYPE_INT_RGB` or `TYPE_3BYTE_BGR`) like this, and the image should be stored okay:

    BufferedImage image = ImageIO.read(inFile);
    if (image.getTransparency() != Transparency.OPAQUE) {
        BufferedImage temp = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_INT_RGB);

        Graphics2D g = temp.createGraphics();
        try {
            g.drawImage(image, 0, 0, null);
        }
        finally {
            g.dispose();
        }

        image = temp;
    }

    ImageIO.write(image, "JPEG", outFile);


Regards,

-- 
Harald K

**Comment by haraldk** [comment]
PS: Could be possible to add such a check to the `JPEGImageWriter`, and scan through the image to see if it really has any transparent pixels. If it doesn't, remove the alpha, as it's not needed, and plain RGB is more compatible.

-- 
Harald K

**Comment by Karnifexx** [comment]
Brilliant. Can confirm this works my end. Many thanks for the v. quick response.

**Comment by haraldk** [comment]
Good stuff!

-- 
Harald K
