### ISSUE TITLE
Usage in RESTful api 

### ISSUE THREAD

**Issue by tcigler** [haraldk/TwelveMonkeys#149]
Hi,
I would like to use this plugin in method called by Jersey's RESTful interface. I have defined the listener in web.xml and imported dependencies of imageio-jpeg and servlet artifacts in versions 3.1.1 to maven's pom.xml, but when I check readers in method anotated by GET and Path, the plugin is not present. 
When I create test case, reader is loaded properly, so dependencies are correct.
I don't know if it's possibble to make it work so please, let me know.

Thanks, Tomas

**Comment by haraldk** [comment]
Hi Tomas,

Yes, it is possible. I know of multiple projects that have used the plugins successfully.

What JARs do you have in your web app's `WEB-INF/lib`? 

What messages do you have in the log from the context startup? That should be able to tell you something.

-- 
Harald K

**Comment by tcigler** [comment]
Thanks for quick response :)
I have these dependencies:
```xml
    <dependency>
        <groupId>com.twelvemonkeys.imageio</groupId>
        <artifactId>imageio-jpeg</artifactId>
        <version>3.1.1</version>
    </dependency>
    <dependency>
        <groupId>com.twelvemonkeys.servlet</groupId>
        <artifactId>servlet</artifactId>
        <version>3.1.1</version>
    </dependency>
```
Which downloaded these jars to WEB-INF/lib:
```
common-image-3.1.1
common-io-3.1.1
common-lang-3.1.1
servlet-3.1.1
```
I'm using Wildfly 9.0 CR1 and during start it prints warnings for all these jars like:
`Class Path entry servlet-3.1.1.jar in /content/vpImageEar.ear/vpImageREST-1.0.war does not point to a valid jar for a Class-Path reference.`
No other relevant logs are present during request, it just doesn't load the plugin..
T

**Comment by haraldk** [comment]
Okay... 

The most obvious problem here, is that you don't have the `imageio-jpeg-Xxx.jar` or its transitive dependencies `imageio-core-Xxx.jar` and  `imageio-metadata-Xxx.jar` present in `WEB-INF/lib`. These JARs are required.

Most likely there's a problem with your Maven module setup, or how you are packaging the EAR/WAR.

-- 
Harald K

**Comment by tcigler** [comment]
Sorry, my bad, I accidentally messed up dependency scope. Now it's working.
One more thing - when I redeploy ear to JBoss, the plugin initialises again and for now I had 8 instances of JPEG reader + one sun's untill restart of server. It's normal or should I handle it somehow?

**Comment by haraldk** [comment]
Good stuff! :-)

Re. 8 instances: It depends... If you have 8 applications using the plugin running in the container, this is expected. If you have a single application running, and have 8 instances of the plugin after 8 (re)starts, that's not so good.

The redeploy issue is what the context listener is *supposed to* fix. I know it works for a web app only (WAR), using Tomcat or Jetty. Never tried it myself using EAR or JBoss. If possible, try debugging the  `IIOProviderContextListener` (add breakpoints in `contextInitialized` and `contextDestroyed`), to see if the context `ClassLoader` instance is different between the two method calls. If the `ClassLoader` differs, it won't work...

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now. 

Feel free to reopen, if you have further details/more issues.

-- 
Harald K
