### ISSUE TITLE
Support for reading Radiance RGBE (.hdr) format

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#157]
See [imageIO to open .HDR file](http://stackoverflow.com/questions/31412662/imageio-to-open-hdr-file) from StackOverflow.

Work in progress.

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in 9bb67742b7232d4cf0c1d7a55bfb4bcf116437df.

-- 
Harald K

**Comment by giovannifs** [comment]
Hi @haraldk,

I was looking for a way to read .HDR file and I have found this StackOverflow topic (http://stackoverflow.com/questions/31412662/imageio-to-open-hdr-file). I'm trying to build your master project to use your solution, but I can't. I get the following message:

Failed to execute goal on project common-io: Could not resolve dependencies for project com.twelvemonkeys.common:common-io:jar:3.2-SNAPSHOT: Failure to find com.twelvemonkeys.common:common-lang:jar:tests:3.2-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

Is that possible your maven repository is down?

I'd appreciate your help. =)

**Comment by haraldk** [comment]
Hi,

@giovannifs Please open a new issue if you have build problems (this issue is about adding .HDR format support, and it is closed).


Regards,

-- 
Harald K

**Comment by giovannifs** [comment]
Ok @haraldk!
