### ISSUE TITLE
ArrayIndexOutOfBoundsException in CCITTFaxDecoderStream.decode2D

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#159]
Found a special multipage TIFF created by "Pixel Translations Inc., PIXTIFF Version 56.0.218.1093", that includes one page monochrome T.6/Group 4 encoded, and one page Old-style JPEG encoded.

The second page is read correctly using the `TIFFImageReader`, however the first page throws an exception while reading.
The first page is displayed correctly using Preview (although it ignores page 2), so it should be decodable.

Here's the relevant stack trace:

    java.lang.ArrayIndexOutOfBoundsException: 1648
    	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.decode2D(CCITTFaxDecoderStream.java:199)
    	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.decodeRowType6(CCITTFaxDecoderStream.java:255)
    	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.decodeRow(CCITTFaxDecoderStream.java:267)
    	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.fetch(CCITTFaxDecoderStream.java:111)
    	at com.twelvemonkeys.imageio.plugins.tiff.CCITTFaxDecoderStream.read(CCITTFaxDecoderStream.java:417)
    	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:423)
    	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:396)
    	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readStripTileData(TIFFImageReader.java:1266)
    	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:794)

The file in question (rename from `.png` to `.tif`):

![multipage-t6 old-jpeg-tiff](https://cloud.githubusercontent.com/assets/110299/9033487/a78a60da-39c7-11e5-8b0e-f321bed778a3.png)

-- 
Harald K

**Comment by muxmax** [comment]
Hello Harald,

using this library in a project I recognized seemingly the same error with reading single pages of a document where some pages are read and others not.
I just cloned the repository and tried to find the problem and workound it -- without success.
It would be really great when this can be fixed with the next release (3.2) as I have no idea what's going wrong.

Maybe it helps if you have another tiff file that allows reproducing this error: pages 1-3 don't work, but pages 4-5 can be loaded successfully.

![fivepages-scan-causingerrors](https://cloud.githubusercontent.com/assets/1533880/9250382/bfea385a-41cc-11e5-8500-272c0246a63f.png)

I also renamed the file ending from tiff to png, as github doesn't support that type.

Regards
Max

**Comment by haraldk** [comment]
@muxmax Thanks! 

Having more samples that can reproduce the problem, is always good!

I'll look into it and see if I can fix it, otherwise I'll have to reach out for some help from the original author who knows this part of the code better than me... :-)

Best regards,

-- 
Harald K

**Comment by Schmidor** [comment]
I found the problem. 
It seems i should always have additional chanching elements for V-Modes at the line end if there are not enough :)

**Comment by haraldk** [comment]
Great news! I'll look through changes and merge asap.

-- 
Harald K

**Comment by ssaring** [comment]
Awesome, looking forward to this bugfix - this issue blocks us too. Great work!

**Comment by haraldk** [comment]
Fixed (via #160). 

3.2 needs some more work, so I'll try to create a 3.1.2 bugfix release later today.

Anyway, many thanks @Schmidor for the good work!

-- 
Harald K

**Comment by ssaring** [comment]
A bugfix release would be awesome - Big Thanks for the great work!

**Comment by muxmax** [comment]
Hello,

it is really great, that this issue could be fixed that fast. Many thanks to @Schmidor and also to you @haraldk. :-)

**Comment by haraldk** [comment]
Sorry, just realized that CCITT decoding isn't yet released (so making a bugfix release wouldn't really help...). 

Making one anyway, but this fix will have to wait for 3.2 release. :-)

-- 
Harald K
