### ISSUE TITLE
ImageIO.getImageWriter(reader) not working inside tomcat

### ISSUE THREAD

**Issue by danieledepetrini** [haraldk/TwelveMonkeys#16]
Hello Harald,

I wrote a basic test code that does work in a standalone test class:

public class Test
{

```
public static void main(String[] arg)
{
    try
    {
        ImageInputStream iis = ImageIO.createImageInputStream(new FileInputStream(arg[0]));
        Iterator<ImageReader> readers = ImageIO.getImageReaders(iis);
        if (!readers.hasNext())
            throw new IOException("can't decode this image inputstream");

        ImageReader reader = readers.next();
        ImageReadParam param = reader.getDefaultReadParam();
        reader.setInput(iis, true, true);
        BufferedImage img = reader.read(0, param);

        ImageWriter writer = ImageIO.getImageWriter(reader);

        if (writer == null)
            throw new IOException("can't find writer, reader provider: " + reader.getOriginatingProvider());

        System.out.println("Writer: " + writer.getClass());
    }
    catch (Throwable t)
    {
        t.printStackTrace();
    }
}
```

}

The same code doesn't work inside a tomcat webapp, writer is null so an exception is thrown.

I have:
- added the listener as described in the guide
- fixed class name typos inside JPEGImageWriterSpi (class names were not starting with "com"

I have verified with a test loop that the ImageWriter is loaded:

```
static
{
    System.out.println("ImageIO, looking for writers");

    Iterator<ImageWriter> ite = ImageIO.getImageWritersByFormatName("jpeg");

    while (ite.hasNext())
        System.out.println("ImageIO writer: " + ite.next().getClass());
}
```

And the result:

logs/catalina.out:ImageIO, looking for writers
logs/catalina.out:ImageIO writer: class com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter
logs/catalina.out:ImageIO writer: class com.sun.imageio.plugins.jpeg.JPEGImageWriter

Any idea about why is not working just inside tomcat? How to debug further?

Thanks,

Daniele.

**Comment by kkofler** [comment]
If, like me, you are still stumbling upon this old issue, and wonder what the best fix/workaround is these days:
* You want to use the `com.twelvemonkeys.servlet.image.IIOProviderContextListener` (that is documented on the https://haraldk.github.io/TwelveMonkeys/ front page under "Deploying the plugins in a web app").
* To use this in a Maven project, you need this additional dependency:
```pom
    <dependency>
      <groupId>com.twelvemonkeys.servlet</groupId>
      <artifactId>servlet</artifactId>
      <version>3.3.2</version>
    </dependency>
```
* To use it in a Spring Boot project without a `web.xml` file, you want to add the following line to the `onStartup` method in your `SpringBootServletInitializer` subclass:
```java
servletContext.addListener(IIOProviderContextListener.class);
```
of course with the following import:
```java
import com.twelvemonkeys.servlet.image.IIOProviderContextListener;
```

With this, the standard ImageIO classes just work and you do not have to manually load any classes.

I hope this helps.

**Comment by stephanie-dm** [comment]
It would be great if @kkofler 's solution could be added to the documentation, because I think it costs people some time to find this...

**Comment by haraldk** [comment]
@stephanie-dm It certainly can! 😀 

Why not create a PR against `README.md`, and add the details about the dependency and Spring boot in the relevant section? 

-- 
Harald K
