### ISSUE TITLE
writing JPEG throwing exception java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by ahsandar** [haraldk/TwelveMonkeys#167]
trying to write a BufferedImage in scala causing following exception

**SBT**
```
libraryDependencies ++= Seq("com.twelvemonkeys.imageio" % "imageio" % "3.1.2",
                        "com.twelvemonkeys.imageio" % "imageio-jpeg" % "3.1.2")
```
**SCALA code**
```
 ImageIO.write(bufferedFrame, "jpg", outputFile)
```

**STACKTRACE**
```
java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageReaderSpiBase
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
[error] 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
[error] 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[error] 	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:210)
[error] 	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
[error] 	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
[error] 	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)

```

**Comment by marcuslinke** [comment]
I had the same issue and as I remember the cause of this was the incorrect handling of maven classifiers from sbt, so some of the dependencies are not in place. I've had work around this by manually include these dependencies also:

"com.twelvemonkeys.imageio" % "imageio-core" % "3.0.2",
"com.twelvemonkeys.common" % "common-lang" % "3.0.2",

**Comment by haraldk** [comment]
Hi,

Thanks Macus!

That makes sense. The missing class (`ImageReaderSpiBase`) should be in `imageio-core-xxx.jar`. 

I don't know or use sbt myself, but if there's anything I can do with Maven config/dependency management to make it more compatible with sbt, please let me know! :-)

Hoping Marcus' suggestion solved your problem!

-- 
Harald K

**Comment by ahsandar** [comment]
seems including the dependencies separately solved it, Cheers

**Comment by marcuslinke** [comment]
Hi Harald,

the problem is with `test` scoped dependencies and classifiers. Here is the related sbt issue: https://github.com/sbt/sbt/issues/1500. So as long as you use scope `test` together with a classifier this will cause problems with sbt. IMHO you shouln't use maven classifiers for test-jars, as it is not needed.

Regards

Marcus

**Comment by marcuslinke** [comment]
Related: http://maven.apache.org/guides/mini/guide-attached-tests.html

**Comment by marcuslinke** [comment]
See https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/pom.xml#L137

```
<dependency>
   <groupId>${project.groupId}</groupId>
   <artifactId>imageio-core</artifactId>
   <version>${project.version}</version>
   <classifier>tests</classifier>
   <scope>test</scope>
</dependency>
```

should be declared as

```
<dependency>
   <groupId>${project.groupId}</groupId>
   <artifactId>imageio-core</artifactId>
   <version>${project.version}</version>
   <type>test-jar</classifier>
   <scope>test</scope>
</dependency>
```

**Comment by haraldk** [comment]
Thanks @marcuslinke

I'll try your suggestions, and see how that works. 

-- 
Harald K
