### ISSUE TITLE
java.awt.color.CMMException: LCMS error 13: Couldn't link the profiles

### ISSUE THREAD

**Issue by rmuller** [haraldk/TwelveMonkeys#170]
With attached file I get this exception:

Also see #130 

    LCMS error 13: Couldn't link the profiles
    java.awt.color.CMMException
     at sun.java2d.cmm.lcms.LCMS.createNativeTransform(Native Method)
     at sun.java2d.cmm.lcms.LCMS.createTransform(LCMS.java:156)
     at sun.java2d.cmm.lcms.LCMSTransform.doTransform(LCMSTransform.java:155)
     at sun.java2d.cmm.lcms.LCMSTransform.colorConvert(LCMSTransform.java:629)
     at java.awt.color.ICC_ColorSpace.fromRGB(ICC_ColorSpace.java:232)
     at com.twelvemonkeys.imageio.color.ColorSpaces.getCachedOrCreateCS
     at com.twelvemonkeys.imageio.color.ColorSpaces.createColorSpace
     at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getRawImageType
     at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getImageTypes
     at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read

Environment:
Ubuntu 12.04 (x64)
Oracle Java 8u60
twelvemonkeys.imageio 3.1.2

![8797055-66_42320_tif](https://cloud.githubusercontent.com/assets/754040/9459739/25c239b2-4aff-11e5-9e1f-85e5d3dd06ef.png)

**Comment by haraldk** [comment]
Thanks Ronald,

I'll look into this! 

I think the proper solution will be that the `TIFFImageReader` issues a warning about the ICC profile being bad/incompatible, and then go on and patch the profile if possible, or just ignore the profile if not.

Should be doable in a few days time, I just need to find some time. :-)


Regards,

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in d4e34d6.

-- 
Harald K

**Comment by haraldk** [comment]
PS: Well, the current fix is to ignore the ICC profile altogether when this happens. I haven't found a way to patch the profile to something Java can live with.

-- 
Harald K
