### ISSUE TITLE
Would it be possible for you to add to the mvn build the production of one inclusive jar?

### ISSUE THREAD

**Issue by ramonjsantiago** [haraldk/TwelveMonkeys#174]
Just for the readers, not the tests, javadocs

**Comment by haraldk** [comment]
Hi,

Possibly, yes. Would this mainly be for easier deployment? Or, in other words, what is the use case for such a thing? I guess you could also create such a "fat" JAR yourself (there seems to be multiple Maven plugins that achieves this).


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Please have a look at this [StackOverflow Q & A](http://stackoverflow.com/questions/32633759/twelvemonkeys-3-1-1-3-1-2-not-working-with-maven-dependency-plugin) and see if it can be of help to you! 

-- 
Harald K
