### ISSUE TITLE
Can't build maven project

### ISSUE THREAD

**Issue by giovannifs** [haraldk/TwelveMonkeys#175]
I'm trying to build master project, but I can't. I have got the following message:

Failed to execute goal on project common-io: Could not resolve dependencies for project com.twelvemonkeys.common:common-io:jar:3.2-SNAPSHOT: Failure to find com.twelvemonkeys.common:common-lang:jar:tests:3.2-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

Is that possible your maven repository is down?

**Comment by haraldk** [comment]
Hi Giovanni,


Sorry about the first response, I just need to try to keep the issue somewhat separate. :-)

Thanks for your feedback!

I've been trying to reproduce the problem you are seeing, but I am unable to do so. Even with a clean checkout from the (Git) repository... 

The Maven repository mentioned in the error report is the Sonatype snapshot repository, but I never post snapshots there (I only push releases to OSSRH/Central). In any case, you should not need a Maven repository to build this, as the dependency is local within the project. 

Are you sure you have everything checked out? What folder are you building from? Are you trying to build only `common-io`? Can you please post the exact command/arguments you are using to build?

Also, can you post the output from the command:

    $ mvn -version

(I built successfully here, using Maven 3.2.3 and 3.3.3 on both Java 7 and 8).


Best regards,

-- 
Harald K

**Comment by rvsoni** [comment]
You need to use force maven to update all snapshots.

use
```
mvn clean install -U
```
**-U** will force maven to update all locally cached snapshots to fetch latest one.

You also have option to clean you local .m2 repository for this artifacts and rerun **mvn clean install -U**

I hope this will help you on this issue.
Ravi

**Comment by haraldk** [comment]
Thanks,

Feel free to try this, and see if it helps.

But as I say, the dependency is *part of the build*, so Maven should not even attempt to fetch it from an external repository (then again, I am not going to claim I full understand why Maven does what it does at times...). 

I can successfully build a clean checkout locally, even without network connection. 

@giovannifs Have you made any progress on this?


-- 
Harald K

**Comment by haraldk** [comment]
Closing as not reproducible.

Feel free to reopen if you have more information. 


Best regards,

-- 
Harald K

**Comment by giovannifs** [comment]
Hi @haraldk, 
I'm so sorry for delay.
I was off last days. I'm gonna retest it.
