### ISSUE TITLE
com.twelvemonkeys.servlet.image.IIOProviderContextListener Class not found error

### ISSUE THREAD

**Issue by jforjava1981** [haraldk/TwelveMonkeys#18]
I am getting class not found error for class com.twelvemonkeys.servlet.image.IIOProviderContextListener which is not downloaded with maven dependency. Do I need to download another jar  for that?

**Comment by Zhuinden** [comment]
It's in

		<dependency>
			<groupId>com.twelvemonkeys.servlet</groupId>
			<artifactId>servlet</artifactId>
			<version>3.2.1</version> 
		</dependency>
