### ISSUE TITLE
JPEG LOSSLESS

### ISSUE THREAD

**Issue by MrFeeze** [haraldk/TwelveMonkeys#182]
Hello Harald,

I am looking for a pure java support for the decoding of images with JPEG LOSSLESS since several months now. I am developing an open source DICOM visualizing and analysis tool; some medical imaging devices have JPEG LOSSLESS as default export so Id really love to support this otherwise not very convenient format.

I read that there are plans that the TwelveMonkey will support it. Is there any time plan yet? Or do you know of any alternatives how to handle it? Any help would be much appreciated.

Best Greetings;
Ingo

**Comment by haraldk** [comment]
Hi Ingo,

I really want to implement (or find a suitable implementation of) JPEG Lossless, and supporting it is in my plans. However my time budget is very limited these days, so I don't have a timeframe yet, for when to expect this feature.

If this feature is important to you or your company, maybe you would like to contribute to its development in some way? 

I do believe the native codec part of JAI ImageIO had support for JPEG Lossless, but if you really need a pure Java solution I don't know of any.


Best regards,

-- 
Harald K

**Comment by MrFeeze** [comment]
Hello Harald,

we will add a programmer to this task (native java JPEG Lossless support). May he contact you so that he can directly integrate the code to your lib?

Ingo

**Comment by haraldk** [comment]
Hi Ingo,

Great news!

Absolutely! He can get in contact either through this issue, or using email if he prefers (harald.kuhr at gmail).

I prefer using the normal GitHub workflow, that is you/he create a branch by cloning the repo, then creating a pull request to have the patches/new functionality applied. But I'm sure we can work out the details. 


Best regards,

-- 
Harald K

**Comment by HermannKroll** [comment]
Hi,

Mr. Freeze add this task to me. We currently need support for:
JPEG SOF type 0xc3.

I don't think, that you're currently support this format. Do you have any good suggestions to start/learn more about the different jpeg specifications (maybe a good paper/website e.g.)? Currently i am looking at http://www.dcmtk.org/dcmtk.php.en and try to find the parsing methods. 

If I find a good solution, I will create a pull request and contact you. 
Thanks & Best regards,
Hermann

**Comment by haraldk** [comment]
Hi Hermann,

Good stuff. The JPEG specification is quite large AFAIK, and so far I have only delegated any decoding/encoding to the IJG (libJPEG) decoder/encoder that comes with Java. 

The official JPEG [spec](http://jpeg.org/jpeg/workplan.html) and  [documentation](http://jpeg.org/jpeg/documentation.html) can be found on the official JPEG homepage.

Additional information can be found on the [IJG home page](http://ijg.org/) (Independent JPEG Group). 

Note that some of the documents can only be bought, and is not available for free download. 

There's already code (slightly duplicated unfortunately, I just haven't had the time to refactor back to one implementation) for parsing the JFIF (JPEG File Interchange Format) structure and some common JFIF segments in the library (`com.twelvemonkeys.imageio.metadata.jpeg` and `com.twelvemonkeys.imageio.plugins.jpeg` packages). Feel free to suggest refactorings and improvements there as well!

After you get into the high level stuff, you'll usually find most of the low level stuff explained by googling. That is at least my experience. 

If you have questions about the ImageIO API, I can probably answer most of them. If you have JPEG/DCT/Huffman decoding questions, I'm of less use at the moment. :-)


Good luck!

-- 
Harald K

**Comment by HermannKroll** [comment]
Good news, 

after hours of search and a first own implementation i found a good library here und GitHub which work for our DICOM Images. I ask the author, if i can implement the library into your structure, so we don't have to use two different libraries.

Here is the open Issue for the other library. ( https://github.com/rii-mango/JPEGLosslessDecoder/issues/1 ) I know he uses the MIT license but i wanted to ask for a personal ok.

Best regards
Hermann

**Comment by haraldk** [comment]
Hi Hermann,

I think the MIT and the BSD licenses are compatible, so should be doable.

I see the source originates from [Helmut Dersch](http://webuser.fh-furtwangen.de/~dersch/), we should  maybe ask him too, just to be nice. And I'll see if the pure Java decoder is any good for normal lossy DCT, would be nice to have a that too. :-)

-- 
Harald K

**Comment by HermannKroll** [comment]
Hi Harald,

i'm wondering what is the best way to integrate the code into this project. If you take a look at the JPEGLosslessDecoder library, you will see, that they are only supporting JPEG lossless for the DICOM standard. The Question is, if all lossless JPEGs format are covert by this library. I don't think so. A lossy DCT isn't covered too. 

One way would be to create a new package like com.twelvemonkeys.imageio.plugins.jpeg.lossless and a class called JPEGLosslessImageReader (e.g.) which provides the functionality of the JPEGLosslessDecoder to read this jpeg files and extends the ImageReaderBase.

What do you think would be the best way? I think the best way might be to integrate a complete JPEGLossless Decoder, but for that I would need to much time. 

Greetings
Hermann

**Comment by haraldk** [comment]
Hi Hermann,

I would believe that the DICOM standard has picked a subset of JPEG (lossless) and then this JPEG stream is wrapped in other DICOM data. Is this understanding correct? Unfortunately, my knowledge about DICOM is very limited.

My initial plan was to extend the current JPEGImageReader with functionality to read JPEG lossless, in a way that was completely transparent to the user. No new package needed. If the JPEGLosslessDecoder can be integrated that way, and in a way that doesn't prevent us from adding other types of lossless encodings later (ie. I  don't want to add anything DICOM specific to the reader), I think that is okay. Even if we only support the DICOM subset of JPEG lossless right now, we can add more support later. 

I'll be contacting the original author about the pure Java lossy DCT version anyway, we might be able to integrate that as well, if it helps. 

If you think it's faster to just create a new plugin that supports JPEG lossless only, you are of course free to do so. This means I might need more time to re-work everything to fit into the library, while you'll have to maintain the code yourself in the mean time, and probably have more hassle integrating the final version into your product later. But it's still a completely valid and understandable option. :-)


Best regards,

-- 
Harald K

**Comment by HermannKroll** [comment]
Hi,

you can imagine a DICOM File like a dictionary with different data elements. Some entries are the image streams. (DICOM Images: http://www.dicomlibrary.com/dicom/transfer-syntax/  ). We need support for 1.2.840.10008.1.2.4.57 , 1.2.840.10008.1.2.4.70 .  Your understanding is correct. 

I will take a look how to integrate the new lossless decoder code into your project. My knowledge about JPEG is limited. If I understand it correct, there is some SOF information in the JPEG header. Where do you check this information in the JPEGImageReader class? The most efficient way (in my opinion ) is to check the different image types in the .read(...) - method und delegate the work at the original ImageIO API or the JPEGLosslessLibrary. After that I have to convert the output of the JPEGLosslessLibrary to a BufferedImage, which should be simple. Do you agree with that or is there a better way ?

Greetings
Hermann

**Comment by haraldk** [comment]
Ok good,

Yes, the type of JPEG encoding is determined by the SOF segment, and I thin you want to decode the SOF3 (Lossless sequential, Huffman coding). The DICOM "Process" numbers in the above document are a little confusing to me, but I guess these are not the same as the SOF markers...

There's a `getSOF()` method in the reader that will give you the entire SOF (StartOfFrame) segment, but the information is already available in the `read(int, ImageReadParam)` method. I'm thinking perhaps adding:

    if (sof.marker == JPEG.SOF3) {
        // Delegate lossless decoding from here on....
    }

...right before:

        // We need to apply ICC profile unless the profile is sRGB/default gray (whatever that is)
        // - or only filter out the bad ICC profiles in the JPEGSegmentImageInputStream.
        if (delegate.canReadRaster() && (

...etc, (making the above an `else if (...)` clause) should do it.

We probably need to make some fixes to the `readRaster` methods and add some tweaks to the metadata as well, for ImageIO API correctness, but we can postpone that for later. 


-- 
Harald K

**Comment by haraldk** [comment]
PS: Good news! 
I just got a positive reply from Dr. Prof. Helmut Dersch to use his JPEGDecoder under BSD license, so we can add lossy support as well.

**Comment by HermannKroll** [comment]
Hey,
I had a few problems with integrating the JPEGLosslessDecoder to your library and know I think I found a problem, where I need your help.
I have written a short class (JPEGLosslessDecoderWrapper) which converts the decoded information from the JPEGLosslessDecoder (Library) to an BufferedImage (BufferedImage.TYPE_USHORT_GRAY).

I changed the code in the TwelveMonkeys like above:

        if(sof.marker == JPEG.SOF3){
        	System.out.println("Read an JPEG Lossless");
        	JPEGLosslessDecoderWrapper decoder = new JPEGLosslessDecoderWrapper();
        	ImageInputStream inputStream = (ImageInputStream) this.getInput();
        	
                //Get all bytes from the memory stream because .length() is not avaible
        	LinkedList<Byte> bytes = new LinkedList<Byte>();
        	byte b;
        	try{
        		while(true){
        			b = inputStream.readByte();
        			bytes.add(b);
        		}
        	} catch (EOFException ex){
        		
        	}
                //size seems to be correct
        	System.out.println("Bytes read:" + bytes.size());
        
        	byte[] imageRawData = new byte[bytes.size()];
        	for(int i = 0; i < bytes.size(); i++){
        		imageRawData[i] = bytes.removeFirst();
        	}
        	
        	System.out.println("Read sucessfully");
        	return decoder.readImage(imageRawData);
        }
        
        // We need to apply ICC profile unless the profile is sRGB/default gray (whatever that is)
        // - or only filter out the bad ICC profiles in the JPEGSegmentImageInputStream.
        else if (delegate.canReadRaster() && ( ...


In my project I used the code in the following way:
      
    //JPEGLosslessDecoderWrapper used from the library
    import com.twelvemonkeys.imageio.plugins.jpeg.lossless.JPEGLosslessDecoderWrapper;

    public static void main(String[] args){
        try {

            //read in test
            FileInputStream inStream = new FileInputStream("test0.pixeldata");
            int avaibleBytes = inStream.available();
            byte[] data = new byte[avaibleBytes];
            inStream.read(data);
            System.out.println("Size : " + data.length);

            //decode the image directly here from source
            JPEGLosslessDecoderWrapper wrapper = new JPEGLosslessDecoderWrapper();
            BufferedImage image = wrapper.readImage(data);

            //write the image
            File out = new File("testDirect.png");
            if (ImageIO.write(image, "png", out)) {
                System.out.println("File written under: " + out.getAbsolutePath());
            } else {
                System.out.println("Error while writting image.");
            }


            //try to read the image by the Twelve Monkeys
            ByteArrayInputStream in = new ByteArrayInputStream(data);
            BufferedImage img;
            String format_name = null;
            try {
                ImageInputStream iis = ImageIO.createImageInputStream(in);
                final Iterator<ImageReader> readers = ImageIO.getImageReaders(iis);
                final ImageReader reader;


                if (readers.hasNext()) {
                    reader = readers.next();
                    System.out.println("reader: " + reader);

                    format_name = reader.getFormatName();
                    reader.setInput(iis, true);
                    img = reader.read(0);

                    File out2 = new File("testTwelveMonkeys.png");

                    if (ImageIO.write(img, "png", out2)) {
                        System.out.println("File written under: " + out2.getAbsolutePath());
                    } else {
                        System.out.println("Error while writting image.");
                    }


                }
            }catch(Exception ex2) {
                System.err.println("ImageIO ImageReader for " + format_name + " failed");
                ex2.printStackTrace();
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }



Used Reader: reader: com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader@1b4fb997

Here are the results:
First image (direct JPEGLosslessDecoderWrapper called from source : )
![testdirect](https://cloud.githubusercontent.com/assets/6368738/11629097/4fab1cbe-9cf6-11e5-84a7-40dbb5a698ea.png)
Second image: (called via reader from TwelveMonkeys)
![testtwelvemonkeys](https://cloud.githubusercontent.com/assets/6368738/11629100/523b2b2c-9cf6-11e5-8d68-b671c0411672.png)

I used exactly the same source in TwelveMonkeys and direct in the project for testing. Why does the results differ? 



Here is the console output from the JPEGLosslessDecoderWrapper:

Size : 209584
NumComponents: 1
Precision    : 16
Width        : 512
Height       : 512
Decoded : 262144  /  262144
Max Int: 67007             <<<<<<  should be the same!?
Min Int: 63536          

File written under: testDirect.png
reader: com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader@2b05039f
Read an JPEG Lossless
Bytes read:209584
Read sucessfully
NumComponents: 1
Precision    : 16
Width        : 512
Height       : 512
Decoded : 262144  /  262144
Max Int: 66651        <<<<< should be the same?!
Min Int: 63536
File written under: testTwelveMonkeys.png



Best regards
Hermann

**Comment by HermannKroll** [comment]
There was a stupid typo in the last post, you could ignore the question. Everything is working like it should now. 

I will increase the performance of my code and check more different cases. Then I will create a pull request and you can decided, if you want to integrate my code.

**Comment by haraldk** [comment]
Hi Hermann,

Sorry I wasn't able to answer before. Glad you figured it out. :-)

I also want to comment on the performance. The following code is likely to be unnecessary slow, because of using a `LinkedList` and wrapping all native `byte`s in it's object wrapper `Byte` counterparts:

    //Get all bytes from the memory stream because .length() is not avaible
    LinkedList<Byte> bytes = new LinkedList<Byte>();
    byte b;
    try {
        while(true){
            b = inputStream.readByte();
            bytes.add(b);
        }
    } catch (EOFException ex){
    }

    ...

    byte[] imageRawData = new byte[bytes.size()];
    for(int i = 0; i < bytes.size(); i++) { //stupid type: must be imageRawData.length
        imageRawData[i] = bytes.removeFirst();  
    }

The Java idiom for doing this is something like:

    ByteArrayOutputStream bytes = new ByteArrayOutputStream(1024 * 1024 /* Provide a size close to what is likely the case for better performance*/);

   byte[] buffer = new byte[1024];
   int count;
   while ((count = inputStream.read(buffer)) > 0) {
       bytes.write(buffer, 0, count);
   }

   byte[] imageRawData = bytes.toByteArray();

(Accidentally, this would also have fixed your problem then, it seems.. ;-) ).

It would perhaps be even better to rewrite the code to accept an `InputStream`or `ImageInputStream` instead of the `byte[]`, to avoid too much in-memory buffering to just shuffle bytes around. But we can look at these things later

Also (I realize this is just test code, but still):

    int avaibleBytes = inStream.available();
    byte[] data = new byte[avaibleBytes];

This is not safe, as `available()` only returns how many bytes may be read *without blocking*, it does not return the size of the file/stream (these may be equal sometimes, but not always). Instead, copy from the file stream to a `ByteArrayOutputStream` as in the example above. 

Otherwise, good work!


Best regards,

-- 
Harald K

**Comment by HermannKroll** [comment]
Yeah, i only used this slow code to do no errors on this part :/ (Like you see, i doesn't help). 

I want to support both methods. If a length is available, i will use this, if not, i will read the stream blockwise, like you mentioned before. 

Thanks!

**Comment by HermannKroll** [comment]
Finally I created the pull request #215 into your project. I think this Issue can be closed. 
We are able read the JPEGLossless files, we want to read :) 

Best Regards & Thanks,
Hermann

**Comment by haraldk** [comment]
Great stuff!

I'll look into the pull request and try to integrate it as soon as possible!


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
PS: If you like, feel free to add yourself to the contributors list in the [project's root POM](https://github.com/haraldk/TwelveMonkeys/blob/master/pom.xml). :-)

**Comment by HermannKroll** [comment]
I added me, thanks!

**Comment by haraldk** [comment]
Hi Herman,

Sorry about the delay in integrating this, but I just haven't had the time...

Working on  it right now, though. **Do you have any JPEG lossless sample files that can go along with the code?** I don't see any test cases in the commits either, so I need to create those, to make sure things actually works as intended. :-)

Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Never mind, I found noe you had attached in another issue. Thanks! 😀

-- 
Harald K

**Comment by haraldk** [comment]
It's finally done! 

Thank you guys!

-- 
Harald K

**Comment by HermannKroll** [comment]
Sorry for late reply. Had lots of stuff to do in last time. 

Thanks for integrating!

**Comment by msfanous** [comment]
@haraldk @HermannKroll Thank you very much for adding this functionality!  I was hoping 

I am trying to create a BufferedImage from a DICOM (DCM) file containing JPEG Lossless data (transfer syntax: 1.2.840.10008.1.2.4.57).  

After including the Twelve Monkeys JPEG Plugin, I expected the following to work.
`BufferedImage img = ImageIO.read(dcmFile);
`

However, I still received  a codec error and soon realized that the Twelve Monkeys JPEG Reader was not being loaded.

I then tried to force my application to use the Twelve Monkeys JPEG Reader like this:
```
Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("JPEG");
if (readers.hasNext()) {
  ImageReader reader = readers.next();
  reader.setInput(iis, true);
  BufferedImage img = reader.read(0);
}
```

However, that triggered the following exception.
```
ImageIO ImageReader for JPEG failed
javax.imageio.IIOException: No SOF segment in stream
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:762)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:334)
	at javax.imageio.ImageReader.read(ImageReader.java:939
```

I feel like there is something simple that I might be missing, and I would appreciate any guidance.  Do I need to somehow extract the JPEG data from DCM prior to attempting the conversion to a BufferedImage?  If so, how would I go about doing that?

Thanks for any help!

**Comment by haraldk** [comment]
@msfanous Thank you! 

But: Please don't ask new questions on old, closed issues. Instead, open a new issue and describe your problem there. This is not a discussion forum. :-)

Best regards,

-- 
Harald K

**Comment by msfanous** [comment]
My apologies @haraldk! I just created a new issue for this.
