### ISSUE TITLE
not able to write  metadata for an adobe photoshop image 

### ISSUE THREAD

**Issue by bharaninunna** [haraldk/TwelveMonkeys#193]
Hi Harald,

I am getting an IOException while trying to save original metadata for an image having app13 segment.
Fetching the metadata from input image using 
IIOMetadata metadata = imgReader.getImageMetadata(0); and trying to write the output image with the same metadata using an imagewriter.  Below is the code.

            ImageWriteParam iwp = writers.getDefaultWriteParam();    
	    IIOMetadata metadata = imgReader.getImageMetadata(0);
	    IIOImage iioim = new IIOImage(img, null, metadata);//Retain input metadata again
        if(iwp instanceof JPEGImageWriteParam) 
        {        
			JPEGImageWriteParam writerParam = (JPEGImageWriteParam) writers.getDefaultWriteParam();
			writerParam.setOptimizeHuffmanTables(true);
			writers.write(metadata,iioim,writerParam);
        }

If I try to write default metadata using metadata = writer.getDefaultImageMetadata(ImageTypeSpecifier.createFromRenderedImage(img), null); it works but not for  IIOMetadata metadata = imgReader.getImageMetadata(0);

**Comment by haraldk** [comment]
Hi,

Thanks for reporting!

JPEG metadata writing isn't 100 % failsafe yet (it's all delegated to the Sun/Oracle `JPEGImageWriter` which is a little picky), but hopefully we can make it work.

Can you post a minimal test case that exposes the issue, along with a (small) test image?
Also, it would be useful to have a full stack trace of the `IOException` you see, and state which version of the library you are using. 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Closing this, as I haven't received any feedback in 2 weeks.

Don't hesitate to reopen once you have created a test case with a sample image. :-)

-- 
Harald K
