### ISSUE TITLE
CCITT Group 3 decoding example

### ISSUE THREAD

**Issue by peterprusi** [haraldk/TwelveMonkeys#194]
Hi Harald,

I saw the new feature for CCITT Group 3 decoding, but I have a problem to understand how it works. I have a G3 raw file and like to decode it and add a TIFF header to read it as an image file. Do you have some example code for this case ?
I tried wrapping the data in a TIFF container like here (http://stackoverflow.com/questions/33627364/need-help-getting-started-converting-raw-g3-fax-files-to-tiff-format-via-java), but I still cant read it as valid image file.

Thank you,

Peter

**Comment by haraldk** [comment]
Hi Peter,

Thank you for your interest in the TwelveMonkeys ImageIO library! 

The library does not currently support decoding raw G3 data. It only supports G3 data in TIFF. 

You can however, try using the `CCITTFaxDecoderStream` directly to decode the file into raw binary pixels (as I think I also suggested in the StackOverflow question you linked). As the G3 data does not contain dimensions, you need to know the height and width up front, or use one of the default widths defined for G3 and see which one fits best. This is a trial and error process.

The other alternative is to wrap the G3 data in a TIFF container, but again you need to know the width and height of the pixel data (and you've seen all the example code I have for this in my SO answer :-)). 

If none of these works for you, I suggest you ask a question on StackOverflow (please use the proper site), giving all information on how this does not work (incl. code, stack trace, screen shot of broken image etc), and add a sample G3 file.


Best regards,

-- 
Harald K

**Comment by Schmidor** [comment]
As a help if the G3 options must be guessed:
TIFFExtension.GROUP3OPT_FILLBITS is not necessary to be set if it was used when the image was encoded, the current implementation automatically skips fill bits.

TIFFExtension.GROUP3OPT_2DENCODING could be checked if "0" does not work as option-value, as the decoder doesn't detect it automatically.

**Comment by peterprusi** [comment]
Hi guys,
thanks, finally I dont decoded the image. I wrapped it in a TIFF container. Guessing the image height was no option, so I read the data bitwise and counted the 'EOL flags'. The number of 'EOL flags' was the height of the image and width was the default 1728.

**Comment by haraldk** [comment]
Good stuff! 

Thanks for reporting back! 

Consider providing an answer or comment on the SO answer as well, to let other people know of your solution. :-)


Best regards,

-- 
Harald K
