### ISSUE TITLE
writing a CMYK file

### ISSUE THREAD

**Issue by bharani-nunna** [haraldk/TwelveMonkeys#196]
writer.write(reader.getImageMetadata(0),iioim,writerParam); fails while writing a CMYK image.
Is the direct write for CMYK supported?

**Comment by haraldk** [comment]
Hi,

Thanks for your interest in the TwelveMonkeys ImageIO library!

There's no generic support for CMYK writing in all the `ImageWriter`s, as a lot of formats does not even support the concept of CMYK separation. Are you trying this for a specific format (or `ImageWriter` class), in case, which one? If you are looking for JPEG CMYK write support, please see #25.

If you want to report a bug please attach stack trace, and a preferably a failing test case. 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now. Feel free to reopen if you have further input on this issue.

-- 
Harald K

**Comment by leolux** [comment]
I have a BufferedImage in the generic CMYK ColorSpace. Now I would like to write this image to a JPEG file:
`ImageIO.write(bufferedCmyk, "jpg", file);`
It produces the following exception:
javax.imageio.IIOException: Invalid argument to native writeImage
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1063)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:365)
	at javax.imageio.ImageWriter.write(ImageWriter.java:615)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:160)
	at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
	at javax.imageio.ImageIO.write(ImageIO.java:1536)

What happend to the closed feature request for CMYK JPEG write support https://github.com/haraldk/TwelveMonkeys/issues/25 ?

**Comment by haraldk** [comment]
@leolux #25 is still open.

**Comment by leolux** [comment]
Ok, thanks!
My mistake was interpeting status indicator aside the referenced issues as the status of the issue itself^^
