### ISSUE TITLE
TwelveMonkeys ImageIO 3.2.x on Java 6

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#198]
@julioheitor wrote in #17:

> I just changed the java version to 1.7_80 and it worked. But i cannot do it because the whole project was compiled with java 1.6 and i have to make it work with it. Do you have any tip?

**Comment by haraldk** [comment]
Hi again,

Starting with version 3.1, you need to use Java 7 or later.

This leaves you with three options (at least):
 - Upgrade to Java 7 (or, better yet, Java 8 while you're at it). This is what I would recommend.
 - Fork the 3.2 branch, change the dependencies to Java 6, fix all compile problems and build your own 3.2-java-1.6 version.
 - Fork the latest 3.0.x branch (which is the latest that builds and runs on Java 6), backport the TIFF compression parts that you need from 3.2, and build your own 3.0.x-ccitt-backport version.

Also see issues #131 and #122 for some more tips and info.


Regards,

-- 
Harald K

**Comment by julioheitor** [comment]
@haraldk 

thank you for your attention. I will decide what solution i will might take.

Regards.

**Comment by haraldk** [comment]
Closing for now.

Let me know if you have further questions regarding this issue.

-- 
Harald K
