### ISSUE TITLE
javax.imageio.IIOException: Unknown Bitmap Information Header (size: -1111494822)

### ISSUE THREAD

**Issue by jansohn** [haraldk/TwelveMonkeys#203]
I'm trying to use your library to display an *.ico file in my Java FX 2.2 application (Java 7 compiler level). Unfortunately I'm getting always an exception "Unknown Bitmap Information Header" (tried it with different *.ico files already).

I'm using the Maven dependency:
```xml
<dependency>
	<groupId>com.twelvemonkeys.imageio</groupId>
	<artifactId>imageio-ico</artifactId>
	<version>3.0.2</version>
</dependency>
```

Here's my code (taken from your post http://stackoverflow.com/a/28474996/3375325):
```java
private List<Image> convertIcoToFxImages(String icoPath) throws IOException
    {
        Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("ICO");
        while (readers.hasNext())
        {
            log.info("reader: {}", readers.next());
        }

        ImageReader reader = null;
        try (InputStream inputStream = getClass().getClassLoader().getResourceAsStream(icoPath);
                ImageInputStream imageInputStream = ImageIO.createImageInputStream(inputStream))
        {
            reader = ImageIO.getImageReaders(imageInputStream).next();

            reader.setInput(imageInputStream);
            int count = reader.getNumImages(true);

            List<Image> fxImages = new ArrayList<>(count);

            for (int i = 0; i < count; i++)
            {
                BufferedImage bufferedImage = reader.read(i, null);
                Image fxImage = SwingFXUtils.toFXImage(bufferedImage, null);
                fxImages.add(fxImage);
            }

            return fxImages;
        }
        finally
        {
            reader.dispose();
        }
    }
```

Stacktrace:
```
javax.imageio.IIOException: Unknown Bitmap Information Header (size: -1111494822)
	at com.twelvemonkeys.imageio.plugins.ico.DIBHeader.createHeader(Unknown Source) ~[imageio-ico-3.0.2.jar:3.0.2]
	at com.twelvemonkeys.imageio.plugins.ico.DIBHeader.read(Unknown Source) ~[imageio-ico-3.0.2.jar:3.0.2]
	at com.twelvemonkeys.imageio.plugins.ico.DIBImageReader.getHeader(Unknown Source) ~[imageio-ico-3.0.2.jar:3.0.2]
	at com.twelvemonkeys.imageio.plugins.ico.DIBImageReader.readBitmap(Unknown Source) ~[imageio-ico-3.0.2.jar:3.0.2]
	at com.twelvemonkeys.imageio.plugins.ico.DIBImageReader.read(Unknown Source) ~[imageio-ico-3.0.2.jar:3.0.2]
	at com.twelvemonkeys.imageio.plugins.ico.ICOImageReader.read(Unknown Source) ~[imageio-ico-3.0.2.jar:3.0.2]
[...]
```

**Comment by jansohn** [comment]
Here's an axample ICO file that fails for me: http://files.softicons.com/download/social-media-icons/free-social-icons-by-icondrawer/ico/vkontakte.ico

**Comment by haraldk** [comment]
Hi Jansohn,

Thanks, I was just about to ask for a sample ICO file, that causes the problem. :-)

I can't reproduce the problem, using (a slightly modified version of) your code and the latest version of the plugin. The `ICOImageReader` is now part of the BMP plugin. I suggest you upgrade to this version:

    <dependency>
        <groupId>com.twelvemonkeys.imageio</groupId>
        <artifactId>imageio-bmp</artifactId>
        <version>3.2.1</version>
    </dependency>

A few bugs related to ICO files has been solved since 3.0.2:

* #150 
* #165 

Here's the exact code I used:

    public class ICOFoo {
        public static void main(String[] args) throws IOException {
            System.out.println("images: " + new ICOFoo().readImages(args[0]));
        }

        private List<BufferedImage> readImages(String icoPath) throws IOException {
            Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("ICO");
            while (readers.hasNext()) {
                System.out.println("readers: " + readers.next());
            }

            ImageReader reader = null;
            try (ImageInputStream imageInputStream = ImageIO.createImageInputStream(new File(icoPath))) {
                reader = ImageIO.getImageReaders(imageInputStream).next();

                reader.setInput(imageInputStream);
                int count = reader.getNumImages(true);

                List<BufferedImage> fxImages = new ArrayList<>(count);

                for (int i = 0; i < count; i++) {
                    BufferedImage bufferedImage = reader.read(i, null);
                    fxImages.add(bufferedImage);
                }

                return fxImages;
            }
            finally {
                if (reader != null) {
                    reader.dispose();
                }
            }
        }
    }

Hope that solves your problem!


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Hmmm.. I just realized I can't reproduce the problem using 3.0.2 version either. 

Perhaps there's something filtering your resources or anything, messing up your bundled ICO files (I notice you are using `Class.getResourceAsStream(...)` in your code).

You can test (path to local Maven repo may differ) the following command:

    $ java -cp .m2/repository/com/twelvemonkeys/common/common-lang/3.0.2/common-lang-3.0.2.jar:.m2/repository/com/twelvemonkeys/common/common-io/3.0.2/common-io-3.0.2.jar:.m2/repository/com/twelvemonkeys/common/common-image/3.0.2/common-image-3.0.2.jar:.m2/repository/com/twelvemonkeys/imageio/imageio-core/3.0.2/imageio-core-3.0.2.jar:.m2/repository/com/twelvemonkeys/imageio/imageio-metadata/3.0.2/imageio-metadata-3.0.2.jar:.m2/repository/com/twelvemonkeys/imageio/imageio-ico/3.0.2/imageio-ico-3.0.2.jar -Dcom.twelvemonkeys.imageio.plugins.tiff.debug=true -Dcom.twelvemonkeys.imageio.plugins.jpeg.debug=true -Dcom.twelvemonkeys.imageio.color.debug=true -Dcom.twelvemonkeys.imageio.plugins.psd.debug=true -Dcom.twelvemonkeys.imageio.plugins.pict.debug=true com.twelvemonkeys.imageio.plugins.ico.ICOImageReader  /Downloads/vkontakte.ico 

This perfectly loads all versions of your ICO file.

-- 
Harald K

**Comment by jansohn** [comment]
Hi Harald,

thank you for the quick response! I just tried it with `new File(...)` instead of `Class.getResourceAsStream(...)` and that works indeed. Any idea why it won't work when I try to load it from the classpath? I want to bundle the icon inside of the JAR...

Robin

**Comment by haraldk** [comment]
As I said, I think something is messing up you resources when the JAR is created (or copied to the folder the JAR is created from). Try inspecting the JAR file, and see if the ICO file is the same (compare the binary files).

Could of course also be other problems, if you have custom class loaders, custom `ImageInputStream` providers etc., but these sounds less likely.

I tried adding my `/Download` folder to class path and loading from there, worked fine as well.


-- 
Harald K

**Comment by jansohn** [comment]
I can rule out a problem with messed up resources as I can use the classloader without a problem if I use a PNG directly, e.g. `stage.getIcons().add(new Image(getClass().getClassLoader().getResourceAsStream(...)))`. I'm not really using any custom classes either, this is the only place I need ImageIO's `ImageInputStream`.
If I find the time I'll provide you with a minimal Maven project to reproduce the error.

**Comment by haraldk** [comment]
I would not rule that out, until you actually compared that the binary contents of the ICO files in the JAR are the same. I did try using `getResourceAsStream(...)` and it worked fine with the file you sent. I still think it's the most likely cause. :-)

Anyway, I'm awaiting a JAR or a minimal project then.


Regards,

-- 
Harald K

**Comment by jansohn** [comment]
There you go: https://github.com/jansohn/JavaFX-ICO

**Comment by jansohn** [comment]
You were right, something in the packaging phase is messing up the ICO file. Sorry to have bothered you with this!

**Comment by haraldk** [comment]
No problem!

Glad you made it work. 

Have a nice weekend!

-- 
Harald K
