### ISSUE TITLE
Invalid TIFF byte order mak '??', expected: 'II' or 'MM'

### ISSUE THREAD

**Issue by sevenguin** [haraldk/TwelveMonkeys#205]
when i used TIFFImageReader, the exception was throwed, some type is not supported?

**Comment by haraldk** [comment]
Hi Sevenguin,

From what you have posted, it seems you are trying to read a file that is *not* a TIFF file using the `TIFFImageReader`. This won't work. 

All TIFF files must start with the TIFF byte order mark, which is either "II" (for intel or little endian) or "MM" (for motorola or big endian). If the file doesn't match this criteria, it's not considered a TIFF.

To say more, I need you to tell me the following:

* Post a test case or a small code snippet that exposes the problem
* Attach or link the file you are trying to read 
* State the version of the library you are using, the Java version, OS and other relevant environment info
* It's also always good practice to post the stack trace from the exception you got, when reporting a possible issue.


Regards,

-- 
Harald K

**Comment by sevenguin** [comment]
Thanks, you are right, the file is not a tff file, the suffix is wrong.

**Comment by sevenguin** [comment]
Do you have some resource to describe the structure of every kind of image types. Thanks very much.

**Comment by haraldk** [comment]
Ok,

Good stuff! 

Note that all the `ImageReaderSpi`s have a method:

    boolean canDecodeInput(Object input);

This method determines whether the plugin can read the input by inspecting the input it self, and is used by `ImageIO.getImageReaders(...)` to get suitable readers. It's generally a better option than relying on the file suffix, which in many cases (like yours) is misleading.

To get more of an understanding of the internals of image structures and file formats, you could read the source code, or see [Wikipedia](https://en.wikipedia.org/wiki/Image_file_formats) or [Encyclopedia of Graphics File Formats](http://www.fileformat.info/mirror/egff/) for example. Other than that, Google is your friend. :-)


Good luck,

-- 
Harald K

**Comment by dbocsmaster** [comment]
Sir

I have one tiff file which I am trying to open in imaging software but it is not opening.

Kindly request you to help me out to solve this issue.

https://drive.google.com/file/d/0BzO_tZuBtbjLZzVENVVzMmNQYW8/view?usp=sharing

With Thanks & Regards
DB Bose

**Comment by haraldk** [comment]
@dbocsmaster 

1. Please do not comment on closed issues.
2. This is not a general forum about imaging software. Only report issues related to the TwelveMonkeys ImageIO library. 
3. The file you have shared is 751136 bytes of 0s. It's definitively not a TIFF file.

-- 
Harald K
