### ISSUE TITLE
Support for resize to different aspect ratio

### ISSUE THREAD

**Issue by wimdeblauwe** [haraldk/TwelveMonkeys#208]
As far as I could tell from looking at the code of `ResampleOp`, there is no option to resize to a different aspect ratio I guess?

What does currently happen if the requested width and height do not match in source aspect ratio?

Would it be possible to add this? There are basically 2 options for cleanly handling this without getting a distorted image:
1) You only take the requested width (or height) into account and calculate the other dimension using the source aspect ratio (This is what https://github.com/thebuzzmedia/imgscalr does)
2) You crop the image to the target aspect ratio and rescale it then. (This is available in PHP through the `fit` method of Image Intervention: http://image.intervention.io/api/fit)

**Comment by haraldk** [comment]
Hi Wim,

Thanks for your interest in the project!

Currently the image would be stretched (or distorted, if you like) in one of the dimensions, if the aspect ratio does not match. It's an "absolute" resize to the width/height you provide.

As you say, it's trivial to compute width/height given the opposite side and the aspect ratio, if you like to retain the aspect ratio after resize. In addition to "fit", I guess you also have a "box" option (given two dimensions, rescale to the largest image possible that fits inside the box, while maintaining aspect ratio). In other cases, you might want to allow a little distortion, to make images of different sizes fit a certain aspect ratio.

As the `ResampleOp` class is quite a low-level image-resampling component (in contrast to ImgScalr which is more like a one-stop solution), the intention has been to leave it to client code to implement the various options of how to calculate the target width/height, to fit a wider range of high-level use cases.

Perhaps you would like to implement some of the options above, create a nice API around it, and we could add it to the new `contrib` module? :-)


Best regards,

-- 
Harald K

**Comment by wimdeblauwe** [comment]
I have found this alternative in the mean time: https://coobird.github.io/thumbnailator/javadoc/0.4.8/net/coobird/thumbnailator/Thumbnails.Builder.html#crop(net.coobird.thumbnailator.geometry.Position)

It seems thumbnailator supports what I need judging from the docs.

**Comment by haraldk** [comment]
Ok,

Good stuff!

It's possible to build this functionality on top of `RescaleOp` and Java2D, but if you already found a library that suits your needs, that's probably a better option. :-)

Closing for now.


Regards,

-- 
Harald K
