### ISSUE TITLE
tiff exif writer

### ISSUE THREAD

**Issue by h920526** [haraldk/TwelveMonkeys#209]
Hi, I tried this sample to modify/rewrite my tiff's EXIF.
(https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-metadata/src/test/java/com/twelvemonkeys/imageio/metadata/exif/EXIFWriterTest.java)

It works but return an empty tiff image, how should I do to fix it?
thanks

**Comment by haraldk** [comment]
Hi,

The Exif package in the metadata module will only write the TIFF metadata, or "container structure" if you like. It doesn't know anything about image data. You could probably use it to modify the TIFF/Exif data though, but you would have to write the code to copy the image data, and probably change a few of the values, as they are offsets/lengths into the file, and will most likely change if the metadata changes.

The code for manipulating (read/write) full TIFF image files is in the TIFF module (`imageio-tiff` and the `com.twelvemonkeys.imageio.plugins.tiff` package). 

PS: The file you linked isn't a code sample, it's a unit test. It's a little unclear to me how you used that to modify your file... Feel free to attach your code, maybe that could clear up a few things. :-)


Best regards,

-- 
Harald K

**Comment by h920526** [comment]
Dear Harald,
thanks a lot for your help, here is my code,
I want to rewrite the exif data only

```java
InputStream input = null;
ImageOutputStream imageOutput = null;
try {
	input = this.getClass().getResource("/images/image.tiff").openStream();
	byte[] inputData = IOUtils.toByteArray(input);
	// replace orientation
	List<Entry> entries = Lists.newArrayList(new EXIFReader().read(ImageIO.createImageInputStream(new ByteArrayInputStream(inputData))));
	entries.add(new AbstractEntry(TIFF.TAG_ORIENTATION, (short) 6) {
	});
	// output
	imageOutput = ImageIO.createImageOutputStream(new FileOutputStream(new File("temp_test_result.tif")));
	imageOutput.write(inputData);
	new EXIFWriter().writeTIFFHeader(imageOutput);
	imageOutput.flush();
} catch (Exception e) {
	e.printStackTrace();
} finally {
	IOUtils.closeQuietly(input);
	IOUtils.closeQuietly(imageOutput);
}
```

I found this link (https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-tiff/src/test/java/com/twelvemonkeys/imageio/plugins/tiff/TIFFImageMetadataTest.java),
but it seems not working for me.

thanks a lot

**Comment by Schmidor** [comment]
The https://github.com/haraldk/TwelveMonkeys/blob/master/contrib/src/main/java/com/twelvemonkeys/contrib/tiff/TIFFUtilities.java support TIFF rotation by setting this tag. You could either build a snapshot or use the code from there.

**Comment by haraldk** [comment]
Thanks @Schmidor!

I would also advice you to either use directly, or look at the `TIFFUtilities` class and adapt it to your use case. It seems to be doing exactly what you are trying to achieve.

PS: It's still unclear to me how you would go about using a unit test to solve your problem, or how it's not working... 

-- 
Harald K

**Comment by h920526** [comment]
hi all, thanks a lot for your help.
I tried TIFFUtilities and it work very nice,
thanks a lot.
