### ISSUE TITLE
TIFFImageReader: Subsampling is incorrect

### ISSUE THREAD

**Issue by AlskiOnTheWeb** [haraldk/TwelveMonkeys#212]
If I setup the reader params to subsample a TIFF image using the Twelve Monkeys reader, I am seeing a strange result. The image width is too narrow. My code looks like:

```
// Get the scaled width and height we want to load
final int nWidth = reader.getWidth (nImage);
final int nHeight = reader.getHeight (nImage);
final float xScale = nWidth / THUMBNAIL_SIZE;
final float yScale = nHeight / THUMBNAIL_SIZE;
final float scale = Math.min (xScale, yScale);
final int nSampling = Math.max (1, (int)scale);
final ImageReadParam params = new ImageReadParam ();
params.setSourceSubsampling (nSampling, nSampling, 0, 0);
result = reader.read (nImage, params);
```

**Comment by haraldk** [comment]
Hi,

Can you please attach the file you are trying to subsample, and an also an image of the result and what you expected it to look like? Also, what is the type and value of your `THUMBNAIL_SIZE`? If it's not a float, there are some issues with the code above.


Regards,

-- 
Harald K

**Comment by AlskiOnTheWeb** [comment]
Hmmmm.... I think I need to do more digging. It appears that this image from the above routine is the right size. It's the serialization of it to a PNG from a BufferedImage through an ImageWriter that's the issue. Let me do some more digging. Thanks much for the quick response.

**Comment by AlskiOnTheWeb** [comment]
OK, I've tracked down more details here. THUMBNAIL_SIZE is a final static int with a value of 128. The code looks like below:

[DSC_0191.zip](https://github.com/haraldk/TwelveMonkeys/files/108289/DSC_0191.zip)

'
        BufferedImage result = null;

        if (file != null)
        {
            final String sExtension = FilenameUtils.getExtension (file.getName ());
            final Iterator<ImageReader> i = ImageIO.getImageReadersByFormatName (sExtension);
            while (result == null && i.hasNext ())
            {
                InputStream is = null;

                try
                {
                    // Get the reader and stream.
                    final ImageReader reader = i.next ();
                    m_logger.info ("Reading " + file + " with " + reader.getClass ());
                    is = file.open ();

                    // Read the image.
                    reader.setInput (ImageIO.createImageInputStream (is));

                    // Get the image index to use.
                    final int nImage = reader.getMinIndex ();

                    // First, see if there is an embedded thumbnail to use.
                    final int nThumbnails = reader.getNumThumbnails (nImage);
                    for (int nThumbnail = 0; nThumbnail < nThumbnails; nThumbnail++)
                    {
                        final int nThumbWidth = reader.getThumbnailWidth (nImage, nThumbnail);
                        final int nThumbHeight = reader.getThumbnailHeight (nImage, nThumbnail);
                        if (nThumbWidth >= THUMBNAIL_SIZE || nThumbHeight >= THUMBNAIL_SIZE)
                        {
                            result = reader.readThumbnail (nImage, nThumbnail);
                            break;
                        }
                    }

                    // If there is no thumbnail, read the whole file scaled down.
                    if (result == null)
                    {
                        // Get the scaled width and height we want to load
                        final int nWidth = reader.getWidth (nImage);
                        final int nHeight = reader.getHeight (nImage);
                        final float xScale = nWidth / THUMBNAIL_SIZE;
                        final float yScale = nHeight / THUMBNAIL_SIZE;
                        final float scale = Math.min (xScale, yScale);
                        final int nSampling = Math.max (1, (int)scale);
                        final ImageReadParam params = new ImageReadParam ();
                        params.setSourceSubsampling (nSampling, nSampling, 0, 0);
                        result = reader.read (nImage, params);
                    }
                }

                finally
                {
                    StreamUtils.closeSilently (is);
                }
            }
        }

        return (result);
'

For the example image, xScale is 10.0 and yScale is 15.0. The resulting BufferedImage from the reader.read() call is the right dimensions, but only the first 1/4 or so of the image columns are properly rendered into the BufferedImage. The rest of the image is white. The portion of the image that is rendered does look correct though.

Thanks for any help.

**Comment by haraldk** [comment]
Thanks for reporting & providing the extra details to reproduce!

I can see the issue now, even with some of my own test images. Not all of them though, so there's something odd going on. I need to add a test case for this, and investigate further.

PS: There's still some minor issues in the code, like `xScale` and `yScale` being `float`s, while the values are the result of an integer division, so you'll get 10.0/15.0 while the result is really 10.25/15.625. It doesn't matter though, as the value (`scale`) is cast to an `int` anyway. You should probably also `dispose()` of the `ImageReader` after use too.

Best regards,

-- 
Harald K

**Comment by AlskiOnTheWeb** [comment]
Thanks for the tip...I forgot about dispose(). Here's a question for you, if I ask ImageIO for an iterator of readers based on format (as I've done above), do I need to dispose all readers in that iterator even if I never retrieved it from the iterator? Just wondering as I can't seem to find info the API docs for it.

**Comment by haraldk** [comment]
The iterator is lazy (at least in the Oracle JRE), and in fact, you iterate over the `ImageReaderSpi`s, thus  you don't need to dispose the reader if you didn't invoke `next()` on the iterator. But for each time `next()` is invoked, a new `ImageReader` is  created and you should invoke `dispose()`.

**Comment by AlskiOnTheWeb** [comment]
Thanks!

**Comment by haraldk** [comment]
Update: After looking in all the wrong places, I finally figured why the subsampling was wrong. 

Unfortunately, I also found a related subsampling bug in the process. I'll try to create a proper test case and fix them all in one go. Just to let you know I'm working on it. :-)

-- 
Harald K

**Comment by AlskiOnTheWeb** [comment]
No worries...it's not a big rush on my end. Anyway, thanks for the update. Usually those types of odd bugs rear their ugly heads and their little brother crawls out too! :-)

**Comment by haraldk** [comment]
Fixed now in latest master.
