### ISSUE TITLE
PSDImageReader: Long layernames are not read

### ISSUE THREAD

**Issue by Eurybiadan** [haraldk/TwelveMonkeys#214]
Hello,

So far loving the API. Solid work.

However, it seems there is a problem when reading the large(er) layer names using the PSD reader plugin.

If my layer name is over 31 characters, then it is cut off. It seems this is happening when it is initially read/decoded (Line 73, PSDUtil.java in version 3.2.1). I've attached a simple 20x20 pixel "psd" file (just rename it), to illustrate the issue.

In this case, the actual layer name is:

"If_The_Layer_Name_Is_Really_Long_Oh_No_What_Do_I_Do"

But it only reads:

"If_The_Layer_Name_Is_Really_Lon"

The file was saved in CS6 Extended, for your reference. Any assistance would be welcome.

Regards,

Rob Cooper

![test-layername](https://cloud.githubusercontent.com/assets/5322065/12698612/5fd1ff42-c76f-11e5-85d1-34dfca9eb4fe.png)

**Comment by haraldk** [comment]
Hi Rob,

Thanks for reporting this issue and providing a sample file! 

I did some debugging of your file, and the "name" field in the [PSD LayerInfo section](http://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_16000) really has a length of 31, and contains only `If_The_Layer_Name_Is_Really_Lon`. However, as with anything PSD, this is a legacy thing, and the full layer name is stored somewhere else, in addition to the original place (the name field of the LayerInfo structure is documented as a Pascal string, so there's likely a full unicode representation of this name somewhere).

I'll see if I'll be able to parse the unicode representation of the layer name, and update the layer names. 


Regards,

-- 
Harald K

**Comment by Eurybiadan** [comment]
Interesting; I will look in to finding the possible location of the "full" layer name in parallel.

**Comment by haraldk** [comment]
Update: I found out how to read the layer name.

I assume you are obtaining it via the PSD metadata?

I'm thinking about just replacing the layer name in the metadata with the unicode name, if available. What do you think?


Regards,

-- 
Harald K

**Comment by Eurybiadan** [comment]
I am obtaining it via the metadata.

I can't think of a reason that the 31 character representation would be preferred, so I'd say using the unicode name makes the most sense.

Best,

Rob

**Comment by haraldk** [comment]
Agreed. 

I need to clean up the code a little, and add some test cases, but hopefully I'll have a fix soon.

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in eeeb226, will be part of the next release.

-- 
Harald K

**Comment by Eurybiadan** [comment]
Many thanks.
