### ISSUE TITLE
Handling iphone portrait image

### ISSUE THREAD

**Issue by lazee** [haraldk/TwelveMonkeys#216]
Hi Harald,

IPhone images contains exif information on whether the photo was shot in portrait or landscape. Out of the box TM doesn't seem to "respect" that info. So portrait images are read as landscape. A known issue or me doing something wrong?

/Jakob

**Comment by haraldk** [comment]
Hi Jakob!

Long time, no see. Hope you are doing well! :-)

Anyway, yes, this is a known issue, and something that is not easily fixable (given the ImageIO API). The current solution is to obtain the image metadata and rotate the image yourself, according to the orientation information.

iOS devices might be nice and good, but I know from doing Android development that not all devices are doing this consistently (ie. some devices will do the rotation before storing, some will set the Exif tag, and some just won't do it right). 

Related: [http://stackoverflow.com/questions/17254490/implementing-automatic-rotation-of-jpeg-images-according-to-exif-orientation-in](Implementing automatic rotation of JPEG images according to EXIF Orientation in ImageIO plugin)


-- 
Harald K

**Comment by lazee** [comment]
Thnx! I'll try to fix it myself then :)

**Comment by lazee** [comment]
And I'm doing fine btw :)

**Comment by haraldk** [comment]
Good & good! :-)

Anyway, if you can come up with a scheme that will work and not break the API in any way, I'm open for adding this as a new feature. 

-- 
Harald K

**Comment by lazee** [comment]
Ok. I'll play around a little bit here and get back to you.

**Comment by lazee** [comment]
@haraldk This is what I've found so far.

The Thumnailator has a way of handling this. I'm not that into the subject that I can judge whether this is a good approach or not.

See https://github.com/coobird/thumbnailator/blob/master/src/main/java/net/coobird/thumbnailator/tasks/io/FileImageSource.java and look for param.useExifOrientation().

What do you think?

I'm planning to use a similar approach inside our image server, unless you have a smarter idea?

**Comment by haraldk** [comment]
I think what Thumbnailator does, is just (if the param is specified) to rotate the image according to Exif orientation, before doing anything else. That should work. I don't see anything special about that approach making it good or bad. :-)

Who will set the parameter in the first place? The end user?

Another approach is not to rotate, but instead make sure you pass the Exif medata along when writing, keeping the original orientation. This is likely to be faster and use less memory. 

But it kind of depends on what other operations you are planning to do (it obviously won't work if you intend to convert the image to, say PNG, which always have top/left orientation).


Regards,

-- 
Harald K

**Comment by lazee** [comment]
I have thought of both these approaches as well. I think a mix of both might work on our image server. If original is jpeg and contains Orientation information, then we will pass that on. If converted to png we need to rotate it first. 
Passing on the exif-property will not work in scenarios where you have filters like crop. In these scenarios we need to rotate the image before we crop it.

also read : http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

**Comment by haraldk** [comment]
Good read! 

I think I have read it a while ago, but should probably re-read, should I ever attempt at implementing this feature. Also, the images at https://github.com/recurser/exif-orientation-examples is gold for testing.

Love the ending quote:

> If Google can’t handle images consistently across their own sites, on a browser that they built, what hope do the rest of us have?

:-)

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now. Feel free to reopen if you have further input.

-- 
Harald K
