### ISSUE TITLE
Incorrect default for PlanarConfiguration in TIFFImageReader

### ISSUE THREAD

**Issue by leolux** [haraldk/TwelveMonkeys#220]
I like to combine two tiff files into one. But the result image contains unwanted glitches. The issue only occurs when the tiff file that should be added has been written by TwelvekMonkeys before. In the opposite the issue does not occur when both tiffs have not been written by TwelvekMonkeys previously. So combining the two images is possible without glitches but only when the source files are "untouched".

I have created a reproducer for this issue: https://github.com/leolux/tmonkeys-issue-01

**Comment by haraldk** [comment]
Hi Leo,

Thanks for reporting and creating a test case for this. I'll investigate and report back as soon as possible.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Okay, here's what I have found so far...

It seems somehow the `TIFFImageReader` is unable to read the output from the `TIFFImageWriter`! Other software (like OS X Preview) seems to read the output without issues. 

I need to debug further to figure out why this happens, but I think I should be able to fix this soon.

-- 
Harald K

**Comment by haraldk** [comment]
Fixed. 

There was an incorrect default value for PlanarConfiguration, making the reader default to 2 (planar) instead of 1 (chunky). Most software seems to write this value, but my `TIFFImageWriter` doesn't write it in the default case.

Not sure why such an obvious bug has been in there for that long.. :-P

Good catch!


-- 
Harald K

**Comment by leolux** [comment]
:+1: Great job!

As a novice in image processing it makes me proud of having contributed to something obvious :-)
Thanks!

**Comment by haraldk** [comment]
@leolux This bugfix is now included in the official 3.3 release.
