### ISSUE TITLE
ImageReader loaded twice

### ISSUE THREAD

**Issue by bernji** [haraldk/TwelveMonkeys#221]
Hi,

I had the problem that the your image reader was not loaded in production war. This was strange because is was actually loaded on my test system. I could also find the jars in  the webapps/lib folder on both, the test system and production war

I followed your sollution by adding the com.twelvemonkeys.servlet.image.IIOProviderContextListener to my web.xml

Now, I have the problem that when I use you test code:

> Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("JPEG");
> while (readers.hasNext()) {
> 	System.out.println("reader: " + readers.next());
> }

I see that two instances are loaded (on the test sytem war):

> reader: com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader@7d0a0044
> reader: com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader@3c42e59
> reader: com.sun.imageio.plugins.jpeg.JPEGImageReader@4d149f4d

I assume that this is not the case on the prod war because without adding the listener there was no instance loaded (though I don't know why).

The question is:
1. How can I make sure that the Reader is not loaded twice
2. Is it a problem when the reader is loaded twice
3. How is it possible that the reader is loaded on the test system and not loaded on prod system although the servers are identically and the wars are also build nearly identical (only in prod and test environment)

**Comment by haraldk** [comment]
Hi,

1: If you are using the context listener, there will be one instance per web app loaded. If you didn't restart your server after adding the context listener, there might be more (old instances). I recommend restarting the server after enabling the listener.
2. Only the first one will be used normally, so there shouldn't be a problem. There could be a problem if the first one isn't from an "old" (unloaded) web app, but that should be taken care of by the context listener. 
3. Are you saying the Spis (service provider interfaces) are not registered even with the context listener? Without the context listener, it's a random thing, and comes down to whether or not the `ImageIO` static class initialization is run before or after your web app was loaded. Given that your test system is likely restarted more often, it could be even quite normal.

-- 
Harald K

**Comment by bernji** [comment]
Thank you. Restarting the server did the trick

**Comment by haraldk** [comment]
Good stuff!

Thanks for reporting back.

-- 
Harald K
