### ISSUE TITLE
TIFFImageWriter writes uncompressed files with incorrect "StripByteCounts" field

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#229]
The TIFFImageWriter does not correctly calculate `StripByteCounts` for uncompressed TIFFs (the default) if the bits per sample is not 8. Most tools will just ignore the value (as in the "Warning: Bogus StripByteCounts field") and compute it correctly anyway if the data is uncompressed, but it does cause problems for certain tools on the Windows platform.

See #226 for background & discussion.

**Comment by THausherr** [comment]
Why is "uncompressed" the default? Why not set G4 for bitonal and LZW for color images? These would be the best possible non-lossy formats for "dumb users".

**Comment by haraldk** [comment]
A lot of similar thoughts today... I just commented on #241 that we should consider changing these defaults. :-)

Will you file a separate issue for changing the default compression?

The reason for uncompressed is that it's the fastest, it's baseline (most compatible) and just works. The problem with defaulting to CCITT/G4 and LZW is they are not baseline options, even though I'm sure 99% of all TIFF software supports that.

In any case, a goal of the TIFF plugin is to be a drop-in replacement for the JAI TIFF plugin, so the defaults should be the same. But I'm sure we can tweak this by a system property or similar mechanism.

-- 
Harald K

**Comment by THausherr** [comment]
No, I am not planning to create an issue now, as we are not yet using the TIFF writing from twelvemonkeys (but we might in the future). We're still using JAI with some options.
https://svn.apache.org/viewvc/pdfbox/trunk/tools/src/main/java/org/apache/pdfbox/tools/imageio/TIFFUtil.java?revision=1709449&view=markup&sortby=date

**Comment by haraldk** [comment]
As far as I could tell from looking at the JAI source code, the defaults are always uncompressed.

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in 04a3915.

-- 
Harald K
