### ISSUE TITLE
Code Sample: Jpeg Exif writer

### ISSUE THREAD

**Issue by patrickfav** [haraldk/TwelveMonkeys#230]
Id like to write Exif data to a jpeg (I found the sample below on how to read it in another ticket)

```
try (ImageInputStream stream = ImageIO.createImageInputStream(input)) {
            List<JPEGSegment> exifSegment = JPEGSegmentUtil.readSegments(stream, JPEG.APP1, "Exif");
            InputStream exifData = exifSegment.get(0).data();
            exifData.read(); // Skip 0-pad for Exif in JFIF
            try (ImageInputStream exifStream = ImageIO.createImageInputStream(exifData)) {
                return new EXIFReader().read(exifStream);
            }
       }
```

therefore I have a CompoundDirectory with a bunch of Entry elements. But how do I use the ExifWriter to a jpeg. Using it to write to the outputstream just corrupts the jpeg (image viewers think it is a broken tiff)

This is also asked here:
http://stackoverflow.com/questions/36029295/how-to-write-exif-to-a-jpeg-with-twelvemonkeys-exifwriter-class

**Comment by haraldk** [comment]
I answered on StackOverflow, closing this. :-)
