### ISSUE TITLE
TIFF EOFException

### ISSUE THREAD

**Issue by simonsteiner1984** [haraldk/TwelveMonkeys#232]
Exception in thread "main" java.io.EOFException
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:426)
[CS1D2F.tif.zip](https://github.com/haraldk/TwelveMonkeys/files/185757/CS1D2F.tif.zip)

**Comment by Schmidor** [comment]
This seems to be the same problem as I had in #225 
At least I can read the document with my current version.

**Comment by haraldk** [comment]
Thanks for reporting!

I'll look into it as soon as possible, now that I'm back at work.

If @Schmidor 's patch works, this means we now also have a test case for the patch. :-)


-- 
Harald K

**Comment by haraldk** [comment]
Fixed in latest master. 

I've tested it with your file, and it seems fine!

-- 
Harald K

**Comment by haraldk** [comment]
This bugfix is now included in the official 3.3 release.
