### ISSUE TITLE
Typo in TIFFProviderInfo - class package should read as com.twelvemkonkeys.imageio.plugins.tiff.TIFFImageWriterSpi

### ISSUE THREAD

**Issue by balamuru** [haraldk/TwelveMonkeys#260]
final class TIFFProviderInfo extends ReaderWriterProviderInfo {
    protected TIFFProviderInfo() {
        super(
                TIFFProviderInfo.class,
                new String[] {"tiff", "TIFF", "tif", "TIF"},
                new String[] {"tif", "tiff"},
                new String[] {
                        "image/tiff", "image/x-tiff"
                },
                "com.twelvemkonkeys.imageio.plugins.tiff.TIFFImageReader",
                new String[] {"com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReaderSpi"},
                "com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter",
                new String[] {"com.twelvemkonkeys.imageio.plugins.**tif**.TIFFImageWriterSpi"}, =========> should read as "tiff", not "tif" to correctly resolve the class 
                false, TIFFMedataFormat.SUN_NATIVE_STREAM_METADATA_FORMAT_NAME, "TODO", null, null,
                true, TIFFMedataFormat.SUN_NATIVE_IMAGE_METADATA_FORMAT_NAME, "com.twelvemonkeys.imageio.plugins.tiff.TIFFImageMetadata", null, null
        );
    }
}

**Comment by haraldk** [comment]
Hi again,

Thanks for reporting!

Your findings made me add automated tests for the SPIs and fix quite a few minor other mistakes as well. Thanks! :-)

Fixed in e9388e5 ++

Best regards,

-- 
Harald K

**Comment by balamuru** [comment]
Hi

Thanks for the timely fixes.

The typo/future proof way to avoid the string reference typos is to derive them from the class name
eg.
new String[] {TIFFImageReaderSpi.class.getName()}, ...

which would resolve to

new String[] {"com.twelvemkonkeys.imageio.plugins.tiff.TIFFImageWriterSpi"}, ...

**Comment by haraldk** [comment]
Yes,

Normally I would use such code. :-)

Unfortunately, this code has side effects, like loading that class and running it's class initializers (which may again load and initialize more classes, which again.. you get the point). This takes time and memory even for classes that might never ever be used again (small amounts, but still). So, this is something one explicitly wants to avoid in service provider (Spi) code. That is why we are using strings, and instead, thanks to your reports, use test cases to make sure things are correct.


Best regards,

-- 
Harald K
