### ISSUE TITLE
JPEG2000

### ISSUE THREAD

**Issue by Sami32** [haraldk/TwelveMonkeys#262]
@haraldk  Hello Harald,

sorry i didn't find an other way to contact you as asked in your Readme file.

I am not sure if it will help you but just in case :
http://www.dclunie.com/jj2000/JPEG%202000%20implementation%20in%20Java.html
Their licence and source code look fine to me...but i am a newbie ;-)
Also this one : https://github.com/jai-imageio/jai-imageio-jpeg2000
And this one ? https://blog.idrsolutions.com/2015/04/how-to-read-jpeg2000-in-java/

Regards

**P.S.** Thank you very much for your great work, that is now include in my favorite media server https://github.com/UniversalMediaServer/UniversalMediaServer/ :-D
Feel free to close this post.

**Comment by haraldk** [comment]
Hi Samuel!

Thanks for the feedback!

I wasn't aware of the usage in UniversalMediaServer. Cool. :-)

Unfortunately, I just don't understand the JJ2000 license, and also the statements about patents infringements makes it a show stopper for me. What I have thought about, is to create a separate project for the JP2K plugin and release it with the current license. If only there was more time... ;-)


Thanks,

-- 
Harald K
