### ISSUE TITLE
JFIF .tec file

### ISSUE THREAD

**Issue by karlmortensen** [haraldk/TwelveMonkeys#263]
I have some JFIF .tec files that start like this:  FFD9 FFD8 FFE0  

Simply ignoring the leading EOI marker allows me to view the full image. Is this something that could be worked straight in to TwelveMonkeys?

I have worked around it in my code, but it would be a lot cleaner to do it here.

Thoughts?

**Comment by haraldk** [comment]
Hmm..

As I understand, this `.tec` file format, is an internal, undocumented Android cache format. It's not intended for general file interchange. These files do not conform to the JIF (JPEG Interchange Format)  normally used by all JPEG variants (like JFIF, Exif, SPIFF etc).

While it's possible, I'm not sure how much value it is to add such a thing to the library... And as you say, it's trivial to just skip the first two bytes, and then read the remainder of the stream like a normal JFIF.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Closing this for now, to focus resources on the existing plugins. 

Feel free to fork the library and/or provide a pull request with the suggested functionality though, if you like to contribute! :-)


Best regards,

-- 
Harald K
