### ISSUE TITLE
NPE when reading empty file

### ISSUE THREAD

**Issue by jpiperventuretech** [haraldk/TwelveMonkeys#266]
If you try to read an empty file you'll get a NullPointerException in JPEGSegmentImageInputStream#read when it tries to access #segment. I believe the problem is that since #repositionAsNecessary swallows the EOFException there is no way for #read to detect the problem. Just removing the catch isn't sufficient though since that causes the JPEGSegmentImageInputStreamTest.testEOFExceptionInSegmentParsingShouldNotCreateBadState test to fail. Having #read explicitly check if #segment is null and throw EOFException might be appropriate.

I've attached a test case for JPEGSegmentImageInputStreamTest that exercises this bug.

[JPEGSegmentImageInputStreamTest.txt](https://github.com/haraldk/TwelveMonkeys/files/328396/JPEGSegmentImageInputStreamTest.txt)

**Comment by haraldk** [comment]
Hi Justin,

Thanks for reporting and looking into the issue! Much appreciated.

NPEs are never good. I'll look into it as soon as possible, and hopefully have a fix soon!


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in 9a60966.

Best regards,

-- 
Harald K
