### ISSUE TITLE
TIFFImageReader: Monochrome image with grayscale profile

### ISSUE THREAD

**Issue by Schmidor** [haraldk/TwelveMonkeys#267]
The image contains 1bit/pixel monochrome data and also a grayscale profile and fails to read, because the BufferedImage tries to use 8bits/pixel.
[scan_17062016.zip](https://github.com/haraldk/TwelveMonkeys/files/329888/scan_17062016.zip)

The profile causes TIFFImageReader.getRawImageType to use ImageTypeSpecifiers.createInterleaved for creating the ImageTypeSpecifier, which I believe cannot handle 1/2/4bit width pixels and only uses the dataType.

**Comment by haraldk** [comment]
Interesting... :-)

You are right, there's actually a todo in the code:

    // TODO: Should use packed format for 1/2/4

I really wonder what good a color profile does to a monochrome image anyway... I guess we can ignore the color space in this case? I'll look into it.

-- 
Harald K

**Comment by Schmidor** [comment]
I believe this was either a Brother scanner or the software using it. :-)

In this case, with 1bit and a ColorSpace of type GRAY, ignoring the profile should be ok.
I tried to find a way to create a packed format that also could take the profile into account, but so far wasn't successful.

**Comment by haraldk** [comment]
I don't think there is a (standard) way... I guess we could use the color profile to look up the correct values to put into an `IndexColorModel` (which seems to be the only color model compatible with `MultiPixelPackedSampleModel`). For 2 or 4 bits, it might actually make sense...

-- 
Harald K

**Comment by haraldk** [comment]
Do you have more sample files like this? :-)

I found a way to create an `IndexColorModel` based on the possible input values to the `ColorSpace`, and the result turns out quite okay. The white isn't 100% white but sRGB #FEFFFE or so... Which I think is good enough? 

-- 
Harald K

**Comment by Schmidor** [comment]
Wow, sounds good :-)

I have only one other image with this profile that I can't pass along. Nothing with 2 or 4 bit samples which really uses colors.

**Comment by haraldk** [comment]
Okay,

Can you try the above fix with your other image, and see if it looks good?

-- 
Harald K

**Comment by Schmidor** [comment]
Thanks, both images look good.

**Comment by haraldk** [comment]
Great! I just love it when there's an easy fix. :-)

-- 
Harald K
