### ISSUE TITLE
JPEG Metadata Cleaner doesn't split DHT correctly

### ISSUE THREAD

**Issue by David-Keeffe** [haraldk/TwelveMonkeys#276]
File JPEGImage10MetadataCleaner.java, Line 278.

You remove the dht child, but don't compensate for the dht list becoming shorter. This means that if the list is, say, 8 elements long, you only deal with 2 of them.

The band-aid is to decrement i when you do that delete/append, so that it continues to point to the next valid element.

**Comment by haraldk** [comment]
Hi David,

Thanks for reporting!

Upon inspection, you might be correct (re-reading the `NodeList` API doc, it does state that `NodeList`s are live). :-)

Do you have a test case or sample file that exposes this problem?


Best regards,

-- 
Harald K

**Comment by David-Keeffe** [comment]
I do, but it's buried inside a PDF. I've been using twelvemonkeys in conjunction with jPod/jPodrender, and I fell over this trying to render images. By adding the i--, effectively NOT incrementing the index value, the images were rendered satisfactorily.

Can you work with PDFs, or should I try to extract the images from the culprit?

**Comment by haraldk** [comment]
If you can extract the JPEG stream only from the PDF, that would be the best, as my PDF knowledge is a little limited. It's also more useful for a test case.

I belive another decent fix, would be to simply loop backwards (and thus removing nodes from the end) would also work.

-- 
Harald K

**Comment by haraldk** [comment]
I think have a local fix for this now. Unfortunately, I don't have a test case, so I can't verify if it works. 

Have you been able to extract the JPEG stream from the PDF yet?

-- 
Harald K

**Comment by haraldk** [comment]
Never mind, found some samples. :-)

Fixed in latest master.

-- 
Harald K

**Comment by David-Keeffe** [comment]
Hi Harald

Sorry - the PDF is at a client office which I only visit occasionally and
not easily accessible. Glad you could find a sample.

David K

**Comment by haraldk** [comment]
@David-Keeffe This bugfix is now included in the official 3.3 release.
