### ISSUE TITLE
Exception reading JPEG: No SOF segment in stream

### ISSUE THREAD

**Issue by ediweissmann** [haraldk/TwelveMonkeys#278]
Can open the file fine with Mac's Preview.

```
Caused by: javax.imageio.IIOException: No SOF segment in stream
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:746)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:321)
	at javax.imageio.ImageReader.read(ImageReader.java:939)
```

**Comment by haraldk** [comment]
Hi Edi,

Thanks for reporting!
Do you have a sample file (and perhaps code) to reproduce the above exception?


Best regards,

-- 
Harald K

**Comment by ediweissmann** [comment]
Harald, thanks for the quick reply.
The issue seems to be these are actually PNG files, with `.jpeg` extension.

**Comment by ediweissmann** [comment]
For others running into the same issue, [a safer way to detect image type is to peek at the first bytes in the file](http://stackoverflow.com/a/21133764/156300) (rather than believing the extension)

**Comment by haraldk** [comment]
Actually, you don't need to (and probably should not), as the various `ImageIO` plugins does this for you already. 

All you need to do, is either:

    // Will decode the input, choosing the correct decoder by inspecting the bytes 
    BufferedImage image = ImageIO.read(input); 

Or

    // Will give you all reader implementations that claims to read the given input, 
    // again by inspecting the bytes (ImageIO.read() uses this method internally)
    Iterator<ImageReader> readers = ImageIO.getImageReaders(input); 

There really is no need to second-guess this.


Regards,

-- 
Harald K

**Comment by ediweissmann** [comment]
Thanks, didn't know that!

**Comment by pogopaule** [comment]
This is an example of a JPG that causes the exception mentioned above.
If I rename it to `.png` the exception does not get thrown.

![snowflakes-brushes-by-hawksmont](https://cloud.githubusercontent.com/assets/576949/18783159/9264ecaa-818a-11e6-8d3d-77f8ca10840a.jpg)

**Comment by delkant** [comment]
I am getting the same exception, but not always, after 20 tries I will get one success conversion using the same file.
```
javax.imageio.IIOException: No SOF segment in stream
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:792)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:364)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFOldJPEGDecompressor.decodeRaw(TIFFOldJPEGDecompressor.java:651)
	at com.github.jaiimageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2583)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:1144)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1414)
	at com.xx.xx.service.util.xx.ImageUtil.tif2png(ImageUtil.java:81)
```
ImageUtil line 81 will be:  BufferedImage bi = reader.read(i, null);

I am using mac os x.

This is the code I am trying.
```
    public static List<String> tif2png(String path) throws IOException {
        String outputFormat = "png";
        String outputPrefix = getOutPrefix(path);
        File outputFolder = new File(outputPrefix);
        if (outputFolder.exists()) {
            outputFolder.delete();
        }
        outputFolder.mkdirs();

        List<String> pages = new ArrayList<String>();

        File file = new File(path);
        ImageInputStream input = ImageIO.createImageInputStream(file);
        ImageReader reader = ImageIO.getImageReaders(input).next();

		int count = 0;
        try {
            reader.setInput(input);
            /* count no. of pages available inside input tiff file */
            int pageNum = reader.getNumImages(true);

            for (int i = 0; i < pageNum; i++) {
                int pageNumber = (i + 1);
                String pageName = "page." + pageNumber + "." + outputFormat; 
                BufferedImage bi = reader.read(i, null);
                ImageIO.write(ImageUtil.createGrayBufferedImage(bi), outputFormat, new File(outputPrefix + pageName));
                cleanAndCorrect(outputPrefix + pageName);
                pages.add(outputPrefix + pageName);

                count++;
            }
        }finally {
            reader.dispose();
        }
        return pages;
    }
```

Thanks!

**Comment by haraldk** [comment]
@delkant Please don't comment on old, closed issues with unrelated information.

The exception itself is not a sign of a bug. It's a sign of a malformed/corrupted JPEG stream. The original issue was that the file was that the file was actually a PNG.

In your case it seems you are trying to read a TIFF file (with "Old JPEG"/6 compression) using a third-party TIFF plugin. If you think this is a bug, please file a new issue. 

-- 
Harald K
