### ISSUE TITLE
Next release plan

### ISSUE THREAD

**Issue by thunkWaltz** [haraldk/TwelveMonkeys#279]
Hi Harald,

When are you planning for next release of imageIO?

We are using 3.2.1 in our project alongwith batik-1.6.
Recently we had to bump up batik to 1.8 but it seems imageio-batik 3.2.1 plugin needs few changes to work with batik-1.8.

I checked in commits to Master that these issue have already been fixed by you but they are not part of any latest release.

**Comment by haraldk** [comment]
Hi,

The plan is to release 3.3 as soon as possible. You can see [what's left to fix here](https://github.com/haraldk/TwelveMonkeys/milestone/5). I'm working quite hard these days to finish the JPEG lossless decoding, which will close 3 of those issues. This is currently a spare time project, so I can't commit to fixed dates, unfortunately.

If you need something before then, it should be quite safe to build the current master, and use it while waiting for the official release. Or perhaps you could back port the imageio-batik changes to the current 3.2.1 version.


Best regards,

-- 
Harald K

**Comment by thunkWaltz** [comment]
Thanks Harald for your quick response.
Kudos for all the work you putting in to make it possible. 
I understand it does require immense effort and time for such kind of a project, that is again if it is not your main project.

I would back-port imageio-batik changes for now.

**Comment by haraldk** [comment]
Good stuff!

-- 
Harald K
