### ISSUE TITLE
Unsupported SamplesPerPixels/BitsPerSample combination for RGB TIFF (expected 3/8, 4/8, 3/16 or 4/16): 3/12

### ISSUE THREAD

**Issue by fpedroza** [haraldk/TwelveMonkeys#280]
Does this mean anything to anyone? I'm able to load and display the same file fine locally. After pushing the file to AWS and trying to do the same, I'm getting the error. I've verified the md5sum value of both files is the same.

**Comment by haraldk** [comment]
The TIFF file format supports arbitrary samples per pixel as well as bit per sample. However, the TwelveMonkeys ImageIO `TIFFImageReader` only supports the more common combinations of either 3 (R, G and B) or 4 (R, G, B and Alpha) samples, and 8 or 16 bits per sample. TIFF "baseline" compliant readers are probably required to support even less combinations.

Your TIFF file, while probably a perfectly valid TIFF file, isn't in one of the supported combinations. It has 3 samples per pixel, but a less common *12 bits per sample* (this is what the `3/12` means in the error message). 

If you can provide a couple of such files, I might be able to add this as a new feature later.


Best regards,

-- 
Harald K

**Comment by fpedroza** [comment]
Here is a zip containing 2 of the troublesome images.
[troublesome-tiffs.zip](https://github.com/haraldk/TwelveMonkeys/files/445563/troublesome-tiffs.zip)

**Comment by haraldk** [comment]
Thank you!

I'll look into it at some point. Current focus is the next release.

-- 
Harald K

**Comment by haraldk** [comment]
Fixed in latest master.

Feel free to test with more sample images, and report back if you experience any problems. :-)

-- 
Harald K
