### ISSUE TITLE
TIFFReader EOFException when reading LZW RGB image

### ISSUE THREAD

**Issue by Eurybiadan** [haraldk/TwelveMonkeys#282]
Hi Harald,

Long time no issue. Thanks for all your good work.

I've run into an EOF exception when loading an LZW compressed RGB Tiff image, with stack trace:

`java.io.EOFException
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:426)
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:396)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readStripTileData(TIFFImageReader.java:1485)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:930)
	at javax.imageio.ImageReader.read(ImageReader.java:939)
	`

From what I can tell debugging it, it simply reads too much (hence the EOF), but appears to correctly detect the width/height of the image.

I am using your newest 3.3-SNAPSHOT, which (I thought) had a fix already in it for LZW compression. Unfortunately, I may have found another bug.

I've attached one of the tifs (naturally it won't allow me to upload the tif directly, so just change the extension as usual) that I can reliably reproduce this behavior with.

![tiffreadereof](https://cloud.githubusercontent.com/assets/5322065/18713073/0a772850-7fdf-11e6-9a34-79475b0e2d1c.png)

**Comment by haraldk** [comment]
Hi Robert,

Thanks for reporting and providing a sample file!

I'm a little busy trying to finish the next release at the moment, but I'll look into this as soon as possible!


Best regards,

-- 
Harald K

**Comment by Eurybiadan** [comment]
Hi Herald,

Thanks for figuring it out! I totally understand getting busy- been my life
lately as well.

Feel free to use that as a sample image.

Regards,

Rob

**Comment by haraldk** [comment]
Fixed in d4afbee.

-- 
Harald K

**Comment by dasdfjksdnf** [comment]
Hello,

Is there any chance of getting an official bug fix release of the library that includes this fix?

Thanks!

**Comment by haraldk** [comment]
@dasdfjksdnf Yes, I am working on that every minute of my spare time right now. Unfortunately, that is only so much. 

Maybe you would like to help out?


Thanks,

-- 
Harald K

**Comment by dasdfjksdnf** [comment]
How may I help?

**Comment by haraldk** [comment]
@Eurybiadan This bugfix is now included in the official 3.3 release.
