### ISSUE TITLE
Timeline for next release

### ISSUE THREAD

**Issue by davidlallen** [haraldk/TwelveMonkeys#284]
I don't really have an issue but a question.  Was wondering about the timeline for the next release.  I work on a system that handles pathology images and therefore deal with many image types and formats.  Currently we have some images that were produced using JPEG Lossless compression which is not handle by Java's ImageIO.  I reviewed one of your closed issues where there was a contributor that added this functionality but it is not in your current released version of 3.2.1.  I did clone your repository, built the project, and tested it within my own project and it did indeed resolve my issue.  My preference would be to use an official release rather than maintaining my own build but wondering about the timeline for the next release.  In reviewing the project's approach and functionality, as well as finding many positive reviews of the project, I would look to explorer how we can make use of much more of the project's functionality.  Since we deal with many image formats and challenges I can envision being able to contribute back to the project in the future.  We are especially interested in future JPEG2000 support and possible contribution.

**Comment by haraldk** [comment]
Hi David,

Thank you for your interest in the project! 

While I can't make any promises for exact dates, the 3.3 version is *very close* to release now. There's just [one single bug](https://github.com/haraldk/TwelveMonkeys/milestone/5) to be fixed, and I have the code ready, it just needs some clean up. Hope you will find it useful!

Contributions are always welcome! :-) 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Hi David,

New release is out. Please see [3.3 release notes](https://github.com/haraldk/TwelveMonkeys/releases/tag/twelvemonkeys-3.3) for details.


-- 
Harald K

**Comment by davidlallen** [comment]
Great news.


Dave
