### ISSUE TITLE
Get Bad SamplesPerPixel error for valid file

### ISSUE THREAD

**Issue by robert-olofsson** [haraldk/TwelveMonkeys#287]
Trying to read a small tiff I get 
Caused by: javax.imageio.IIOException: Bad SamplesPerPixel value for Palette TIFF (expected 1): 2
    at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getRawImageType(TIFFImageReader.java:455)
    at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getImageTypes(TIFFImageReader.java:691)
    at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:720)
    at javax.imageio.ImageIO.read(ImageIO.java:1448)
    at javax.imageio.ImageIO.read(ImageIO.java:1352)
    ... < custom code that calls ImageIO.read(FileInputStream) > ...

I have attached a small test image, please rename it to test.tif, the file upload here does not allow .tif.

I guess the problem here is that the image is a PhotometricInterpretation with RGB and /or transparency. The original image is of course a lot larger, but I get the exact same problem with this small part of the larger image.

![test tif](https://cloud.githubusercontent.com/assets/15566576/19811017/ffc5dea6-9d2f-11e6-8a11-36aa919a7378.png)

**Comment by haraldk** [comment]
Hi Robert,

Thanks for reporting!

I'll look into this as soon as possible. Right now, the main focus is to release 3.3, so it may not happen instantly. :-)
If it's a quickfix, it might make it into the release, if not it will have to wait. 

-- 
Harald K

**Comment by haraldk** [comment]
According to the IFD, the image has PhotometricInterpretation: 3 (Palette) and ColorMap, but seems to have a discrete alpha channel as well, given by SamplesPerPixel: 2, BitsPerSample: [8, 8] and ExtraSamples: 2 (Unassociated alpha)... I've never come across this combination of palette and alpha channel yet, so it's fore sure quite exotic. And definitively not supported at the moment.

It should be possible to read this at some point, but unfortunately Java2D has no good way of representing an image with colormap and discrete alpha channel. So, to read it the reader has to either throw away the alpha, or convert the values to full RGBA while reading. Or invent a completely custom ColorModel.  

Full IFD:

    IFD 0: IFD[256/ImageWidth: 10 (SHORT), 257/ImageHeight: 10 (SHORT), 
    258/BitsPerSample: [8, 8] (SHORT), 259/Compression: 5 (SHORT), 
    262/PhotometricInterpretation: 3 (SHORT), 269/DocumentName: test.tif (ASCII), 
    273/StripOffsets: 8 (LONG), 274/Orientation: 1 (SHORT), 277/SamplesPerPixels: 2 (SHORT), 
    278/RowsPerStrip: 409 (SHORT), 279/StripByteCounts: 139 (LONG), 
    284/PlanarConfiguration: 1 (SHORT), 297/PageNumber: [0, 1] (SHORT), 
    305/Software: GraphicsMagick 1.3.25 2016-09-05 Q16 http://www.GraphicsMagick.org/ (ASCII),
    320/ColorMap: [0, 256, 512, 768 ... 64512, 64768, 65024, 65280] (768) (SHORT), 
    338/ExtraSamples: 2 (SHORT), 339/SampleFormat: [1, 1] (SHORT)]

I'll look into it at some point. 


Best regards,

-- 
Harald K

**Comment by robert-olofsson** [comment]
Glad to hear that you have this one on the radar, for now we did use graphicsmagick and converted the tiffs to RGBA png images, that worked for us, so I am not in a hurry to get this fixed. The sample image was cropped from a large tiff, that is why the software is set to graphics magick, I am not sure what software created the original image.

It is probably a bit unusual combination, the actual images are photo heat maps for finding leaks in
district heating networks. The alpha channel is to remove areas that are out of bounds.

**Comment by haraldk** [comment]
Fixed in latest master. Feel free to test with more samples and report back.

-- 
Harald K

**Comment by robert-olofsson** [comment]
Seems to work for my pictures. Thank you!
