### ISSUE TITLE
TIFFImageWriter should support controlling byte order through stream metadata

### ISSUE THREAD

**Issue by aromanelli** [haraldk/TwelveMonkeys#290]
Hello.  When I call TIFFImageWriter's getDefaultStreamMetadata(ImageWriteParam) method, it always returns a null, instead of an IIOMetadata object.

Looking at the code, it does a super getDefaultStreamMetadata(ImageWriteParam) call to ImageWriterBase's getDefaultStreamMetadata method, which is hard-coded to always return a null.

Is the hard-coded null intentional, or a bug?

**Comment by haraldk** [comment]
Hi Adrian,

Yes, the `null` return-value for stream metadata is intentional. 

From the API doc of the base method `ImageWriter.getStreamMetadata`:

>  Writers that do not make use of stream metadata (_e.g._, writers for single-image formats) should return `null`.

And from the API doc of the `ImageWriter.write` method:

> `streamMetadata` - an `IIOMetadata` object representing stream metadata, or `null` to use default values.

The JAI `TIFFImageWriter` does probably return a value for this method, but uses stream metadata only to specify endianness, nothing else, so I haven't bothered to implement it. Instead the `TIFFImageWriter` does pick the endianness from the `ImageOutputStream` (`getByteOrder()` method) and writes the correct values based on that, if you need to explicitly control the byte order.

Let me know if this causes trouble for any of your use cases, and I'll look into it, or help find a workaround.


Best regards,

-- 
Harald K

**Comment by aromanelli** [comment]
Appreciate the reply.  Yea, JAI does return an IIOMetadata object, and yes, I need the IIOMetadata object to control endianness, so technically I'd say it needs to be supported.  :)

I worked around the returned null by instead calling ImageWriter's getDefaultImageMetadata method, passing in the return value of ImageTypeSpecifier.createFromBufferedImageType(image.getType()) (image is my BufferedImage object).  

For setting the endianness, I walked the IIOMetadata.getAsTree(String) root node, searching for the 'ByteOrder' child node, and changing its attribute 'value' if found to the endianness that I want.  If the 'ByteOrder' child node was not found, I did a appendChild call to add the endian node to the root node.  

Not sure if this is the "right" way of doing it or not, so if you happen to have a better way of setting endianness, I'd love to hear it.

And thank you for your work on this library, appreciate it.

**Comment by haraldk** [comment]
I see,

Well, using the image metadata for that will not work, as a TIFF file (the stream) has a single byte order. You can't specify the endianness per image in the file. The writer will also just ignore any stream metadata parameter...

For now, you can control the endianness of the TIFF output, by setting the byte order of the `ImageOutputStream` to the required endianness, something like:

    ImageOutputStream stream = ...
    stream.setByteOrder(ByteOrder.BIG_ENDIAN); // or LITTLE_ENDIAN

    imageWriter.setOutput(stream);
    imageWriter.write(...);

Personally, I find the above more explicit, however my aim is for the TIFF plugin to be a direct replacement for the JAI TIFF plugin, so supporting the stream metadata format used by JAI should probably be supported. I'll consider it for a later release.


-- 
Harald K

**Comment by aromanelli** [comment]
The ImageIO apis are brand new to me, so appreciate the "right/better way of doing what I want to do" code snippet.  

Its good news to hear about (future) support a 1 to 1 api equivalent with JAI, makes code porting easier (which we are doing, for Java 9; surprised more people are not screaming over a lack of JAI for Java 9).

Thanks for your help!

**Comment by haraldk** [comment]
Seems most of the metadata support was already built, it was just not used... Must have been a slip.
Added stream metadata support to latest master.

PS: Java 9 is supposed to contain the TIFF ImageIO plugin from JAI in base JDK. Although I doubt it is as good as ours.. 😉

-- 
Harald K
