### ISSUE TITLE
Performance of tif processing

### ISSUE THREAD

**Issue by FelixA** [haraldk/TwelveMonkeys#295]
Hi,

awesome libary you wrote! 
We have some very large tif files, over 50mb partly, which I'm trying to convert into png files. 
this is taking ages. 

I wanted to ask if there is a possibility to write out downscaled png files directly since some Quality loss is not an issue, or if you have some other tweaks to increase the performance. 

Thanks a lot in advance!

**Comment by haraldk** [comment]
Hi Felix,

Thanks! :-)

"Taking ages" is a very relative term, and the file size is only part of the equation. Compression, image dimensions and pixel layout matters a lot as well. And of course, writing a PNG using the built-in `PNGImageWriter` always uses the best possible compression, which is slower than necessary.

Anyway, if you want to write a downscaled version and quality loss is acceptable, I suggest reading the TIFF images using subsampling (see `ImageReadParam.setSourceSubsampling(...)`). This way you read less, save memory and process less data. This should perform better. The gain is dependent on how much quality loss you can live with.

However, my best "pro tip" would be to get out your favorite profiler, do some "real" profiling and figure out where the time is really spent. Optimize where you can get the biggest gains. And repeat, until its "fast enough".


Best regards,

-- 
Harald K

**Comment by FelixA** [comment]
Thanks a lot for your advices. I will play around with the ImageReadParams!
