### ISSUE TITLE
Tiff Image Rotation increases the size 6x times

### ISSUE THREAD

**Issue by Priyalks** [haraldk/TwelveMonkeys#310]
Hi,

we are using twelve monkeys for rotating tiff images. However, we see that after rotation, image size increases 6x times.

sample code:
BufferedImage bi = ImageIO.read(new File("C:\\builds\\sample.tif"));               
                AffineTransform at = new AffineTransform();
                at.translate(-(bi.getWidth() - bi.getHeight()) / 2, (bi.getWidth() - bi.getHeight()) / 2);
                at.rotate(Math.toRadians(90),bi.getWidth()/2,bi.getHeight() / 2);
                AffineTransformOp opRotated = new AffineTransformOp(at,
                        AffineTransformOp.TYPE_BILINEAR);
                BufferedImage img = opRotated.filter(bi, null);
                String str = "C:\\builds\\sample2.tif";
                File file = new File(str);
                ImageIO.write(img,"TIFF",new FileOutputStream(file));

**Comment by haraldk** [comment]
Hi,

Yes, this is expected, if your TIFF was compressed. The problem is that you don't (and can't) pass parameters controlling compression to `ImageIO.write(...)`, and thus it uses default settings, which is to write the TIFF uncompressed. 

If you want to write using compression, you need to obtain the writer instance, and : 

    ImageWriter writer = ImageIO.getImageWritersByFormatName("TIFF").next();
    writer.setOutput(output);

    ImageWriteParam param = writer.getDefaultWriteParam();
    param.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
    param.setCompressionType("Deflate"); // Allowed: None, LZW, Deflate/Zlib, PackBits, JPEG and the various CCITT compressions (black/white only)

    writer.write(null, new IIOImage(image, null, null), param);

See the [Advanced usage section](https://github.com/haraldk/TwelveMonkeys#advanced-usage)  of the documentation for more info. 

If you like, you can retain the compression of the original (in most cases), by using the `ImageReader.readAll(...)` method, and write using the metadata from the returned `IIOImage` (or read the metadata separately and pass it to the writer). There's also more code samples that might be relevant in the `TIFFImageWriterTest` JUnit test.


Best regards,

-- 
Harald K

**Comment by Priyalks** [comment]
Hi Harald,

As suggested to retain the compression of the original image, I tried to write the file with the metadata from the original file.
IIOImage ioimg = reader.readAll(0, null);
IIOMetadata metadata = ioimg.getMetadata();
writer.write(null, new IIOImage(image, null, metadata), null);

But I see some issues with Jpeg,olg jpeg,Binary CCITT compressions:

Jpeg compression file:  output file is corrupted
Old Jpeg compressed file : Exception : unsupported tiff compression type:6
Binary CCITT(TIFF Binary CCITT Group 3,PLEXUSTIFF Binary CCITT Group 4,PLEXUSTIFF Binary CCITT Group 3) : Exception:
CCITT T4-Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter.createCompressorStream(TIFFImageWriter.java:578)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter.writePage(TIFFImageWriter.java:430)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter.writeToSequence(TIFFImageWriter.java:975)

**Comment by haraldk** [comment]
Hi again,

"Old JPEG" (compression value 6)  is not supported by the writer, that is expected. I will not add support for this compression (except possibly for writing Exif JPEG thumbnails), for reasons explained in "TIFF TechNote 2". You will have to re-write these as a different compression, like JPEG (compression value 7).

JPEG ("new style JPEG") should work. Can you send me a sample file that shows this behavior using the code above? In what way is the file corrupted?

Also, same for CCITT compressions, they should work (as long as you retained the image in the same binary pixel format). The exception seems like a bug though, I need to look at that. Can you send me a sample file or two?

Best regards,

-- 
Harald K

**Comment by Priyalks** [comment]
![17 tiff binary ccitt group 3](https://cloud.githubusercontent.com/assets/12161296/21802904/b734638a-d74d-11e6-99d5-1be316f059dd.png)
![36 tiff 8 bit gray jpegintiff](https://cloud.githubusercontent.com/assets/12161296/21802910/be344538-d74d-11e6-815d-2c04c26694d8.png)
![51 tiff 24 bit color jpegintiff](https://cloud.githubusercontent.com/assets/12161296/21802913/c1dffd6c-d74d-11e6-809b-8c2332a8e898.png)
![58 plexustiff binary ccitt group 4](https://cloud.githubusercontent.com/assets/12161296/21802914/c498ec76-d74d-11e6-9581-07071d024677.png)
![59 plexustiff binary ccitt group 3](https://cloud.githubusercontent.com/assets/12161296/21802915/c733152e-d74d-11e6-97ef-91abdb0796ae.png)

Attached the sample files.
In the case of jpeg, when I try to open modified file in windows photo viewer, its not opening reports image corrupted.

code used:
ImageInputStream inputStream = ImageIO.createImageInputStream(file);
        Iterator<ImageReader> iterator = ImageIO.getImageReaders(inputStream);
        if (iterator == null || !iterator.hasNext()) {
            throw new IOException("Image file format not supported by ImageIO: ");
        }
        ImageReader reader = (ImageReader) iterator.next();
        reader.setInput(inputStream);

        int nbPages = reader.getNumImages(true);
        List<BufferedImage> imageList = new ArrayList<BufferedImage>();       
        IIOImage ioimg = reader.readAll(0, null);
        IIOMetadata metadata = ioimg.getMetadata();        
        for (int i = 0; i < nbPages; i++) {
            BufferedImage bi = reader.read(i);
            imageList.add(bi);
        }
Iterator writers = ImageIO.getImageWritersByFormatName("tiff");
        ImageWriter imageWriter = (ImageWriter) writers.next();
        ImageOutputStream ios = ImageIO.createImageOutputStream(new File("xx.tif"));
        imageWriter.setOutput(ios);
        imageWriter.prepareWriteSequence(null);
        for (BufferedImage image : imageList) {
            imageWriter.writeToSequence(new IIOImage(image, null, metadata), null);
        }

**Comment by haraldk** [comment]
Excellent, thanks! 

I'll look into this, and report back later.

-- 
Harald K

**Comment by haraldk** [comment]
Okay,

I have found two more bugs in the writer, as linked. One regarding the CCITT encoding, the other for JPEG gray data. Thank you very much for reporting and providing sample files for finding these!

However, the color JPEG sample you sent, re-encodes nicely for me, and produces an output that opens fine in Windows Photo Viewer. Are you sure you have a problem with that file? If so, can you please also attach the output after re-encoding this file?

PS: There were some minor bugs in your code that I had to fix. For multi-page files you are writing all pages using the metadata of the first page only. It is probably better to have a list of `IIOImage`s and write back using these:

````java
    int nbPages = reader.getNumImages(true);
    List<IIOImage> imageList = new ArrayList<>();
    for (int i = 0; i < nbPages; i++) {
        IIOImage image = reader.readAll(i, null);
        imageList.add(image);
    }

    // ....

    writer.prepareWriteSequence(null);
    for (IIOImage image : imageList) {
        imageWriter.writeToSequence(image, null);
    }
    writer.endWriteSequence(); // Added missing endWriteSequence
```` 

Best regards,

-- 
Harald K

**Comment by Priyalks** [comment]
![sample2](https://cloud.githubusercontent.com/assets/12161296/21836984/e4683c18-d7ee-11e6-9258-e4eae6e43fb7.png)

Attached the color Jpeg output file

**Comment by haraldk** [comment]
Hi,

I think the problem with the converted file, is that your rotation code somehow changes the `BufferedImage` type from RGB to RGBA. This is evident from the TIFF IFD, which has 277/SamplesPerPixel: 4 and 258/BitsPerSample: [8, 8, 8, 8]. Nothing wrong with this, and the TIFFImageReader can read it, however 4 channel RGBA JPEG isn't very common, so most other software (like Windows Photo Viewer) will choke on it. 

I suggest you change the rotation code to not change type, or convert back to non-alpha RGB before storing the image in a TIFF with JPEG compression.

Who says image formats and image processing should be simple? ;-)

-- 
Harald K

**Comment by Priyalks** [comment]
yes  :(

One more question
In the case of file(size:131KB) with None compression, the size of output file is 4.00MB.
Any idea how to retain the original size?
Is it something to do with compression level? Is there a way to read compressionlevel and set it via param.setCompressionQuality?
![24 tiff binary none](https://cloud.githubusercontent.com/assets/12161296/21846431/1ef03b78-d81d-11e6-90f5-b719ec02b4df.png)

**Comment by haraldk** [comment]
Hmmm... 

Well, for compression None, there really is no compression... So changing the compression level would make no difference. 

Again, I think it's the same problem as with the JPEG, the rotation changes the `BufferedImage` type (probably to RGBA, as 801 * 1313 * 4 bytes = 4 206 852 bytes or roughly 4 MB). When I just re-write the same image with no changes, the file size actually goes down a few bytes (134 528 to  132 865). For a binary image, you want the `BufferedImage` to be `TYPE_BYTE_BINARY`.

-- 
Harald K

**Comment by Priyalks** [comment]
Hi ,

via api how to do we distinguish between jpeg color or jpeg gray in Tiff?
In bufferedImage.getColorModel(), i dont see any api which specifies that

**Comment by haraldk** [comment]
Hi,

It's another bug. I filed a new bug for this, #314. These bugs are trivial to fix, I just needs some time to clean up and create good tests. Anyway, thanks for reporting!

PS: I guess you figured out the grayscale vs color in JPEG compressed TIFF? If not, you can either use the `ImageTypeSpecifier` from `ImageReader.getRawImageType(index)` and get the `ColorSpace` from that, or use the meta data from `getImageMetadata(index)`. In the native tree, there should be a tag for `PhotometricInterpretation` (tag id 262) with value 1 for grayscale or 6 for YCbCr (which will be converted to RGB automatically). In the standard tree, the "Chroma" node will contain a "ColorSpaceType" node with the "value" attribute set to either "GRAY" or "YCbCr".

**Comment by Priyalks** [comment]
Thanks Harald ,
Is this possible to get these bug fixes for version 3.3.1 ?

**Comment by haraldk** [comment]
Yes, I'll try to fix these bugs and create create a 3.3.2 bugfix release soon.

-- 
Harald K

**Comment by Priyalks** [comment]
In the case multipage LZW compressed Tiff file, when I try to re-read the file, I get EOF Exception
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readStripTileData(TIFFImageReader.java:1497)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:934)
	at javax.imageio.ImageReader.readAll(ImageReader.java:1067)
	at com.emc.xcp.datalist.FinalImageProcess.process(FinalImageProcess.java:48)
	at com.emc.xcp.datalist.FinalImageProcess.main(FinalImageProcess.java:105)

![132pages](https://cloud.githubusercontent.com/assets/12161296/21919706/7a007684-d982-11e6-8c73-20ec8e80b1dd.png)

I didn't even rotate, just read and wrote it into a file and the tried to read the new file.

**Comment by haraldk** [comment]
Wow, that's quite a few pages... Should still work though, I'll look into it! 

-- 
Harald K

**Comment by Priyalks** [comment]
Even for single page Tiff Images, third time when i read the files, almost for all compression Types I get EOFException:

`        ImageInputStream inputStream = ImageIO.createImageInputStream(listOfFiles[j]);
        Iterator<ImageReader> iterator = ImageIO.getImageReaders(inputStream);
        if (iterator == null || !iterator.hasNext()) {
            throw new IOException("Image file format not supported");
        }
        reader = (ImageReader) iterator.next();
        reader.setInput(inputStream);
        int nbPages = reader.getNumImages(true);
        List<BufferedImage> imageList = new ArrayList<BufferedImage>();
        List<IIOMetadata> metadataList = new ArrayList<IIOMetadata>();
        int angle;
        String compressionType = null;
        for (int i = 0; i < nbPages; i++) {
            IIOImage ioimg = reader.readAll(i, null);
            BufferedImage bi = (BufferedImage) ioimg.getRenderedImage();
            IIOMetadata metadata = ioimg.getMetadata();
            if (compressionType == null) {
                IIOMetadataNode tree = (IIOMetadataNode) metadata.getAsTree(IIOMetadataFormatImpl.standardMetadataFormatName);
                IIOMetadataNode compression = (IIOMetadataNode) tree.getElementsByTagName("CompressionTypeName").item(0);
                compressionType = compression.getAttribute("value");
            }

            if (pageRotationMap.get(i + 1) != null) {
                //rotate
                angle = pageRotationMap.get(i + 1);
                AffineTransform at = new AffineTransform();
                if (angle == 90 || angle == 270)
                    at.translate(-(bi.getWidth() - bi.getHeight()) / 2, (bi.getWidth() - bi.getHeight()) / 2);
                at.rotate(Math.toRadians(angle), bi.getWidth() / 2, bi.getHeight() / 2);
                AffineTransformOp opRotated = new AffineTransformOp(at,
                        AffineTransformOp.TYPE_NEAREST_NEIGHBOR);
                bi = opRotated.filter(bi, null);
            }
            imageList.add(bi);
            metadataList.add(metadata);
        }
        reader.dispose();
        Iterator writers = ImageIO.getImageWritersByFormatName("tiff");
        imageWriter = (ImageWriter) writers.next();
        imageWriter.setOutput(ImageIO.createImageOutputStream(listOfFiles[j])));
        imageWriter.prepareWriteSequence(null);
        for (int i = 0; i < imageList.size(); i++) {
            if (compressionType.equalsIgnoreCase("Old JPEG") && !isGrayJPEG(metadataList.get(i))) {
                ImageWriteParam param = imageWriter.getDefaultWriteParam();
                param.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
                param.setCompressionType("JPEG");
                imageWriter.writeToSequence(new IIOImage(imageList.get(i), null, null), param);
            } else if (compressionType.equalsIgnoreCase("Old JPEG") || (compressionType.equalsIgnoreCase("JPEG") && isGrayJPEG(metadataList.get(i))) || compressionType.contains("CCITT") || compressionType.equalsIgnoreCase("PackBits")) {
                ImageWriteParam param = imageWriter.getDefaultWriteParam();
                param.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
                param.setCompressionType("LZW");
                imageWriter.writeToSequence(new IIOImage(imageList.get(i), null, null), param);
            } else
                imageWriter.writeToSequence(new IIOImage(imageList.get(i), null, metadataList.get(i)), null);
        }
        imageWriter.endWriteSequence();
        imageWriter.dispose();
`

PS: bcoz of the bugs with old JPEG,JPEG gary,CCITT,Packbits have written the files in diff compression.
Even without rotation, I get EOF Exception.

**Comment by Priyalks** [comment]
Hi Harald,

Any updates on the above two issues?
Multipage LZW compressed file
reading almost all compressed files third time throws EOF Exception

**Comment by haraldk** [comment]
Hi,

No, sorry, haven't had the time to work on this during the weekend. 

I think the issue you see with the EOFExceptions might be the same as the one from #306, which I have a fix for locally, but isn't fully done with tests etc yet.

With some luck I'll be able to fix some of these bugs this week.

-- 
Harald K

**Comment by Priyalks** [comment]
Thanks Harald

**Comment by haraldk** [comment]
Hi,

I have fixed all the issues I've been able to reproduce so far. Can you create a build from the latest master, and see if that resolves your issues?

Best regards,

-- 
Harald K
