### ISSUE TITLE
Conserve based image ColorSpace

### ISSUE THREAD

**Issue by leobr29** [haraldk/TwelveMonkeys#321]
Hi,

I'm a newbie about ICC_Profiles and in want to resize image without changing the ColorSpace from th base to the resize image.

In my exemple I just read en rewrite an image with an ADOBE RGB ColorSpace but the image is rewrite with another ColorSpace (sRGB ColorSpace). Does somebody know how to simply conserve the based ColorSpace ? 

Here is my simple code :

```
//Reader
reader = ImageIO.getImageReadersBySuffix("jpg").next();
is = ImageIO.createImageInputStream(image.getPathRaw().toFile());
reader.setInput(is);

//Read Image
BufferedImage originalImage = reader.read(reader.getMinIndex());

//Read metadatas
IIOMetadata metadata = reader.getImageMetadata(reader.getMinIndex());
			
//Write image
ImageWriter writer = ImageIO.getImageWritersByFormatName("jpeg").next();
FileImageOutputStream ios = new FileImageOutputStream(image.getPathThumbnail().toFile());
writer.setOutput(ios);
writer.write(new IIOImage(originalImage, null, metadata));
ios.flush();
ios.close();
```
Based image :
![based_image](https://cloud.githubusercontent.com/assets/5701109/22748294/d9b32f2a-ee29-11e6-973b-7893aa2cd3b6.jpg)

Result image :
![result_image](https://cloud.githubusercontent.com/assets/5701109/22748317/f11d1d1a-ee29-11e6-8e28-6c40a0f37e15.jpg)

Best Reguards,
Leo.

**Comment by haraldk** [comment]
Hi Leo,

I've never had this use case before, but I think it *should* be possible.

First of all, I'd like to point out that the color space conversion that happens, in theory, shouldn't alter the image appearance, when displayed in software that supports color profiles. But of course, there are differences in CMS implementations, and there might be clipping if colors are outside the target profile's gamut etc. So unless you have a real need to preserve the exact color profile, I wouldn't worry too much about it. :-)

Now, if you want to keep the ICC profile, I think it should work if you read the image as raster (these are the "raw" pixels as contained in the file), using the `ImageReader.readRaster(...)` method.. With JPEG, the raster normally contains pixels in YCbCr so you might need to convert them to RGB first. Then you can get the ICC profile from the meta data. Create a `ColorSpace` from this profile, and a `ColorModel` from this color space, and the matching pixel layout. Finally, create a `BufferedImage` from the raster and the color model, using the `new BufferedImage(colorModel, raster, colorModel.isAlphaPremultiplied(), null)` constructor. If you write this image back, it should contain the correct ICC profile. Though I haven't testet it.

Another option that might work, is to use `ImageReader.getImageTypes(...)` and iterate over the types to see if you find one that uses the color profile of the original image. Then pass that type as the destination type in the `ImageReadParam` passed to `ImageReader.read(0, param)`. I'm not sure though, if this works reliably in all cases.


Best regards,

-- 
Harald K

**Comment by leobr29** [comment]
Fristly, thank you for your response haraldk, I will try that !

You're right, it's not explicitly supported in the library so it was not the best place to ask my question. 

So I would like to now where can I contact you (if it's possible obviously) if I have several questions concerning Java ImageIO ?

Best reguards,
Leo.

**Comment by haraldk** [comment]
Hi again Leo,

If you have questions regarding the library, this is the place. No problem asking here!

If you have general questions about ImageIO, I suggest asking them on StackOverflow or similar site. I'm on StackOverflow and answer most related questions there if I can. This is usually the best place, as you reach a broader audience. And a potential answer can help more people. :-)

If you want to contact me personally, I prefer email. 


Best regards,

-- 
Harald K
