### ISSUE TITLE
How I work with TIFF file with multiples pages?

### ISSUE THREAD

**Issue by richardfrk** [haraldk/TwelveMonkeys#322]
Hello,

I need convert Tiff (Multiple Pages) to JPEG file. How I do it?

**Comment by haraldk** [comment]
Hi Richard,

You can do this, using only the standard ImageIO API . First, obtain the `ImageReader` that can read TIFF, get the number of pages, read each page and ouput that page as JPEG. Something like this:

```
try (ImageInputStream input = ImageIO.createImageInputStream(new File(pathToTIFF))) {
    ImageReader reader = ImageIO.getImageReaders(input).next(); // Fill fail if no TIFF reader
    reader.setInput(input);

    ImageWriter writer = ImageIO.getImageWritersByFormatName("JPEG").next();

    // Get the number of pages
    int pages = reader.getNumImages(true);
    // Read the pages
    for (int i = 0; i < pages; i++) {
        BufferedImage image = reader.read(i, null);

        try (ImageOutputStream ouput = ImageIO.createImageOutputStream(new File(pathToJPEG +"_page_" + i + ".jpg"))) {
            writer.setOutput(output);
            writer.write(image);
        }
    }
}
```

This is the basics. You can expand on it to suit your needs.

Note that there is nothing in the code above that is specific to the TwelveMonkeys ImageIO library (although you will need the TIFF plugin installed at *run time*), this is all standard `javax.imageio` API. 

In the future, please ask general questions like this, on a Q/A site like StackOverflow or similar. This issue tracker is mainly for reporting bugs and request new features in the library.


Best regards,

-- 
Harald K

**Comment by richardfrk** [comment]
Oh Man, Sorry about this! Your code save me! Really! You are best! Thx a lot!
