### ISSUE TITLE
JFIF JPEG with non-spec grayscale thumbail fail to load

### ISSUE THREAD

**Issue by gregkotsaftis** [haraldk/TwelveMonkeys#326]
When trying to display any JPEGs created from a scanner, an error occurs!

Jars included in classpath:
```
  common-image-3.3.2.jar
  common-io-3.3.2.jar
  common-lang-3.3.2.jar
  imageio-bmp-3.3.2.jar
  imageio-core-3.3.2.jar
  imageio-jpeg-3.3.2.jar
  imageio-metadata-3.3.2.jar
  imageio-tiff-3.3.2.jar

```
Exception:
```
java.nio.BufferUnderflowException
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
	at java.nio.ByteBuffer.get(ByteBuffer.java:715)
	at com.twelvemonkeys.imageio.plugins.jpeg.JFIF.getBytes(JFIF.java:125)
	at com.twelvemonkeys.imageio.plugins.jpeg.JFIF.read(JFIF.java:106)
	at com.twelvemonkeys.imageio.plugins.jpeg.Application.read(Application.java:72)
	at com.twelvemonkeys.imageio.plugins.jpeg.Segment.read(Segment.java:94)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.initHeader(JPEGImageReader.java:691)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:754)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:334)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)

```
If i use the original java ImageIO (remove **_imageio-jpeg-3.3.2.jar_** from the classpath), the image loads and displays properly.

See the attached JPEG sample file that causes this error!

![roza](https://cloud.githubusercontent.com/assets/3630283/23162985/45ca9a7c-f839-11e6-8df4-cec63c86d85c.jpg)

**Comment by gregkotsaftis** [comment]
![roza](https://cloud.githubusercontent.com/assets/3630283/23162151/82ee259e-f835-11e6-8d07-a30868e2a1b1.jpg)

**Comment by haraldk** [comment]
Hi,

You can tell the authors of your scanner (software) that they create broken JFIFs. ;-)

No, seriously, they do. According to the spec, the APP0/JFIF segment should contain:

 * (...skipped...) 
 * Xthumbnail (1 byte) Thumbnail horizontal pixel count
 * Ythumbnail (1 byte) Thumbnail vertical pixel count
 * (RGB)n (3n bytes) Packed (24-bit) RGB values for the thumbnail pixels, n = Xthumbnail * Ythumbnail

As you see, the thumbnail is always 3 bytes, packed, RGB, regardless of the compressed JPEG data. However, your JFIF sample contains grayscale data in the thumbnail (which might make sense as the JPEG data is grayscale, but still incorrect according to the spec)... 

I've never come across such files before, but I guess adding support for it should be fairly easy.


Best regards,

-- 
Harald K

**Comment by gregkotsaftis** [comment]
Well, I guess you are right, but all these _d@mn_ images seems to load and display properly in all other _d@mn_ software, except mine! Since it's hard to support my case, I have removed **_imageio-jpeg-3.3.2.jar_** until further notice...

To quote a Greek movie:
> Everybody in this town f@cks, except to me!

**Comment by haraldk** [comment]
For a quick-fix, you can change line 114 in `com.twelvemonkeys.imageio.plugins.jpeg.JFIF` to:

````java
                getBytes(buffer, Math.min(buffer.remaining(), x * y * 3)),
````
and build a local patched version.

This will fix the problem so that the image will be displayed. 

If you're feeling adventurous, you can also change `com.twelvemonkeys.imageio.plugins.jpeg.ThumbnailReader` and replace the `readRawThumbnail` method with the following;

````java
    static protected BufferedImage readRawThumbnail(final byte[] thumbnail, final int size, final int offset, int w, int h) {
        DataBufferByte buffer = new DataBufferByte(thumbnail, size, offset);
        WritableRaster raster;
        ColorModel cm;

        if (thumbnail.length == w * h) {
            raster = Raster.createInterleavedRaster(buffer, w, h, w, 1, new int[]{ 0 }, null);
            cm = new ComponentColorModel(ColorSpace.getInstance(ColorSpace.CS_GRAY), false, false, Transparency.OPAQUE, DataBuffer.TYPE_BYTE);
        }
        else {
            raster = Raster.createInterleavedRaster(buffer, w, h, w * 3, 3, new int[]{ 0, 1, 2 }, null);
            cm = new ComponentColorModel(ColorSpace.getInstance(ColorSpace.CS_sRGB), false, false, Transparency.OPAQUE, DataBuffer.TYPE_BYTE);
        }

        return new BufferedImage(cm, raster, cm.isAlphaPremultiplied(), null);
    }
````

That should also fix thumbnail reading.

I'll have an official patch soon, but I'm a little occupied for the next days, so it won't happen this week.


-- 
Harald K

**Comment by gregkotsaftis** [comment]
Thanks for your quick reply and fix!
Since the original imageio jpeg handler seems to work (for now), I think I will let it be and wait for the official release. Unless other jpeg images fail to load (due to sun's bugs), and I will be forced to be _adventurous_ and try your solution as a quick fix...

**Comment by haraldk** [comment]
Fixed in latest master.
