### ISSUE TITLE
Indefinite loop while reading corrupt JPEG

### ISSUE THREAD

**Issue by Nadahar** [haraldk/TwelveMonkeys#329]
Hi Harald.

I know reading corrupt files and solving related problems is boring and not very interesting, but since this one hangs the thread it might be worth looking into. Tests have been performed on my code using some Google test suite, and it ends up hanging the application because the thread doing the reading goes into an indefinite loop while holding locks ending up blocking almost everything.

I've been able to track it down to an endless loop in ```com.sun.imageio.plugins.jpeg.JPEGImageReader.hasNextImage()```. The loop is this:
```java
        boolean foundFF = false;
        for (int byteval = iis.read();
             byteval != -1;
             byteval = iis.read()) {

            if (foundFF == true) {
                if (byteval == JPEG.SOI) {
                    iis.reset();
                    if (debug) {
                        System.out.println("true");
                    }
                    return true;
                }
            }
            foundFF = (byteval == 0xff) ? true : false;
        }
```

From what I can tell, the only ways to break the loop is either by an ```Exception``` being thrown, ```-1``` being returned from the ```ImageInputStream``` or finding the ```SOE```. I know that this code isn't yours, but it seems that the reason for the endless loop is found in ```com.twelvemonkeys.imageio.plugins.jpeg.JPEGSegmentImageInputStream.repositionAsNecessary()``` which swallows the ```EOFException```. The code comments says that an ```EOFException``` will be thrown or ```-1``` will be returned by the subsequent read, but this clearly isn't the case.

I'm not familiar enough with this code to understand why the ```EOFException``` is ignored in the first place, and thus not able to produce a fix.

The test suite has thousands of images, and only 8 JPEGs end up in a hung thread, so it's not a very frequent problem. Still it would be nice to avoid it.

The corrupt/invalid JPEGs are very small (as they have very little actual content), so I'm attaching them all:

![id_005573 sync_jpeg_turbo src_004235](https://cloud.githubusercontent.com/assets/12900583/23625107/513f29d0-02a8-11e7-9756-6035edb96e79.jpg)
![id_000448 src_000000 op_havoc rep_32 cov](https://cloud.githubusercontent.com/assets/12900583/23625109/5145e95a-02a8-11e7-8372-4787a7307ab8.jpg)
![id_001917 src_001912 op_havoc rep_8](https://cloud.githubusercontent.com/assets/12900583/23625108/51432b02-02a8-11e7-9203-b42b1c43c0c3.jpg)
![id_001918 src_001917 op_havoc rep_8](https://cloud.githubusercontent.com/assets/12900583/23625110/514b20dc-02a8-11e7-92c6-d4fed7b4ebb1.jpg)
![id_003682 sync_jpeg_turbo src_001907](https://cloud.githubusercontent.com/assets/12900583/23625111/514c48ea-02a8-11e7-8789-bb75321f404f.jpg)
![id_003723 sync_jpeg_turbo src_001917](https://cloud.githubusercontent.com/assets/12900583/23625112/514e4122-02a8-11e7-8c03-0830d60cd585.jpg)
![id_003809 sync_jpeg_turbo src_001918](https://cloud.githubusercontent.com/assets/12900583/23625113/515e763c-02a8-11e7-85fb-573b41201f05.jpg)
![id_004235 src_003897 op_havoc rep_16](https://cloud.githubusercontent.com/assets/12900583/23625114/516c2778-02a8-11e7-9d50-e916ce831200.jpg)

**Comment by haraldk** [comment]
Hi Nadar,

Thanks for the report, thorough research and sample files! 

While it's definitively more fun to implement new features, I think fixing bugs like this is at least as important. :-)

I'll look into it as soon as possible!


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Hi again,

Can you show me the code that you use to reproduce this issue? 

Using the latest code (3.4-SNAPSHOT from master), I seem to get `java.lang.NegativeArraySizeException` for all the test images (which is not good, as the exception should be an `IOException` subtype), except "id_000448 src_000000 op_havoc rep_32 cov" which isn't recognized as JPEG, and "id_003682 sync_jpeg_turbo src_001907" that first logs a warning ("Truncated File - Missing EOI marker") and then throws a  `javax.imageio.IIOException` ("Image format error"). The last two are both good I think. 

But no infinite loops so far...


Best regards,

-- 
Harald K

**Comment by Nadahar** [comment]
I'll try to give an as accurate description of my test case (that produced the infinite loop) as possible. First of all, I was using ```MemoryCacheImageInputStream``` as the source I sent in (maybe that doesn't return ```-1``` when the disk-cached one does?). I'm using the ```3.3.2``` version as it's the latest I can find a Maven central.

I just reproduced it now, and the exact file where this happend now was ```src_001912,op_havoc,rep_8.jpg``` (but when I tested yesterday I think it was ```id_000448,src_000000,op_havoc,rep_32,+cov.jpg```). 

The calling code is a bit strange I guess, but it's this:
```java
try (ImageInputStream stream = createImageInputStream(inputStream)) {
    Iterator<?> iter = ImageIO.getImageReaders(stream);
    if (!iter.hasNext()) {
        throw new UnknownFormatException("Unable to find a suitable image reader");
    }

    ImageReader reader = (ImageReader) iter.next();
    try {
        int width = -1;
        int height = -1;
        ImageFormat format = ImageFormat.toImageFormat(reader.getFormatName().toUpperCase(Locale.ROOT));
        if (format == null) {
            throw new UnknownFormatException("Unable to determine image format");
        }

        ColorModel colorModel = null;
        try {
            reader.setInput(stream, true, true);
            Iterator<ImageTypeSpecifier> iterator = reader.getImageTypes(0);
            if (iterator.hasNext()) {
                colorModel = iterator.next().getColorModel();
            }
            width = reader.getWidth(0);
            height = reader.getHeight(0);
        } catch (RuntimeException e) {
            throw new ImageIORuntimeException("Error reading image information: " + e.getMessage(), e);
        }

        boolean imageIOSupport;
        if (format == ImageFormat.TIFF) {
            // ImageIO thinks that it can read some "TIFF like" RAW formats,
            // but fails when it actually tries, so we have to test it.
            try {
                reader.read(0, reader.getDefaultReadParam()); //TODO: (Nad) Any better way to do this?
                imageIOSupport = true;
            } catch (Exception e) {
                // Catch anything here, we simply want to test if it fails.
                imageIOSupport = false;
            }
        } else {
            imageIOSupport = true;
        }

        ImageInfo imageInfo = ImageInfo.create(
            width,
            height,
            format,
            size,
            colorModel,
            metadata,
            applyExifOrientation,
            imageIOSupport
        );
        return imageInfo;
    } finally {
        reader.dispose();
    }
}
```

The above doesn't actually read images, it's part of "parsing" - that is, trying to determine their format and other metadata about the image that we cache so that we know what to do with it if we're asked to deliver it later (UMS is a media server, serving media files to "clients" upon request).

When it comes to throwing ```RuntimeException```s there's quite a lot of that in ```ImageIO``` both from Sun's code and your plugins. I agree that it's not ideal, but I've kinda accepted that there's no way to get completely rid of it (as there's nothing anyone can do with Sun's code) so I just as well deal with it. As a result I wrap any call to ```ImageIO``` in a try/catch as you can see in the code above, rethrowing it as ```ImageIORuntimeException``` which IS a (checked) ```IOException``` subclass.

**Comment by haraldk** [comment]
Excellent!

I can reproduce the issue now. Seems your code reaches some less common code path that I don't currently have a test for. Need to look more into it, but at least I see the problem now. 

Also, if you have examples of `RuntimeException`s thrown from my plugins, I'd like to see them if you have the time. They are really programming errors/lack of input validation in most cases. I do understand that you want to keep your code the way it is though, it's completely reasonable.

PS: I think your reader disposal is just fine. The iterator returned by `ImageIO.getImageReaders(..)` is lazy, but will create a new `ImageReader` instance for each `next()` invocation. Native/internal resources might be allocated already in the constructor.

PPS: Most "Camera RAW" formats are Exif derivates. And Exif is again a derivate of the TIFF format (TIFF is basically just a container format designed for raster data). In other words, they actually *are* TIFF files. Thus, it's very hard for `ImageIO` plugins and other software to distinguish them from "normal" TIFF files. I actually started working on CR2, NEF and DNG support for `ImageIO` some time ago, but didn't have the time to finish it. You might have a look at it in the [camera-raw](https://github.com/haraldk/TwelveMonkeys/tree/camera-raw) branch. Hope to be able to pick it up one day.

A faster (if not better) way of testing for `ImageIO` compatibility is to read just a tiny area of the image, like:
````java
ImageReadParam param = reader.getDefaultReadParam();
param.setSourceRegion(new Rectangle(1, 1));
reader.read(0, param);
````


-- 
Harald K

**Comment by Nadahar** [comment]
@haraldk I have a pretty good insight in TIFF/Exif/RAW after working with images for the last couple of months, so I know why it is like it is. The complete lack of standards and structure amongst the camera manufactureres makes trial and error the only viable option as I see it. The code comment isn't criticism, but an explanation of why things are done as they are. 

We use other methods, like DCRaw to decode images that ```ImageIO``` can't handle - but ImageIO is the "primary" image decoder and thus it's convenient to cache whether an image can be decoded by ```ImageIO``` or need "special treatment". 

Trying to read just a little piece of the image is perfect, I just didn't know how to do it. Thank you 👍 

Regarding disposal of ```ImageReaders``` that actually means that if you iterate through several you'll have to dispose of them all? What about those reads you never touch (if you just accept the first one)? Will they linger and tie up resources? It's a bit hard for me to understand exactly how the "reader factory" design meant for this to be handled. We do this with thousands of images, so I don't want any "memory"/"resource" leaks as it quickly adds up. Do I want to always iterate through them as dispose of those I don't use?

I have a huge log file where a lot of ```RuntimeError```s from ImageIO is logged. I don't have the source images used to produce it though, but I can probably get them. I have seen these thrown on numerous occations which is why I made the "rethrow as ```IOException" solution, but I don't remember exactly under which circumstances, which is why referring to this recent log file is the easiest. 

It's probably cleaner to create a separate issue for the ```RuntimeException```s? I can do that and try to remove duplicates from the log file (although I don't know how easy that is). Many of these are probably caused by the same lack of validation.

**Comment by haraldk** [comment]
Re: Disposal: It's complicated. ;-) The iterator is created "lazily", in that it contains only an iterator over `ImageReaderSpi` instances. These are "lightweight" service providers that are created during plugin registration.  When you invoke `hasNext()` each provider is asked in turn if it can decode the given input, until one accepts (its `canDecodeInput()` returns `true`). When `next()` is invoked, however, the provider that accepted creates a full `ImageReader` instance. So, you should dispose the ones you invoked `next()` for, but not iterate more than you need. If that all made sense. ;-)

Fine print: If you don't `dispose()` the `finalize()` method will do it for you when the object is garbage collected, although you never know when (if at all) it happens, so it's safer to just do it when you know you are done. 

Re: Exceptions: If you find the time, yes, please file as one or more separate issues. It's always easier to reproduce and fix if you have the source files. I have to reject bugs I can't reproduce. 

-- 
Harald K

**Comment by haraldk** [comment]
Okay...

So I think I finally found the issue and fixed it locally, but I need some time to clean it up. 

The main reason it's never been discovered before, is I usually use `reader.setInput(stream)`, while you use `reader.setInput(stream, true, true)`. The latest boolean specifies "ignore metadata". A possible quick fix for you until I fix the issue, is to pass `false` here instead, as this will make the `getImageTypes(0)` method fail on metadata initialization before the endless loop has a chance to happen...

The problem is, as you correctly indicated, caused by ignoring the `EOFException` and not handling it accordingly in the `JPEGSegmentImageInputStream.read()` method. A new problem arises when I fix this, however, as the `com.sun...JPEGImageReader` starts to crash with `RuntimeException`s at random places. So I need to work around those as well. :-/

I'll let you know when I have a proper fix ready.

-- 
Harald K

**Comment by Nadahar** [comment]
@haraldk Thanks for the construction explanation, even though I had been lucky in this method, I found another one where an ```Exception``` in the right place would fail to dispose of the reader. 

I guess it's good that the GC will handle it, but my goal is to free up as much as possible without waiting for the GC.

You'd think that they could have included this in the ```ImageIO``` documentation, it's important to get these things right and it isn't always very easy to guess how to do it. Maybe they did and I just didn't find it, but this should have been documented in an easily accessible location like the Javadocs for ```getImageReaders()```. 

The only thing I've got left to do on my "refactor anything image related" PR is to reduce the memory footprint, so I'm very focused on this right now. Reading just one pixel of the image when testing if ```ImageIO``` can read an image was just what I needed, but I still have to come up with a better solution to handle source images (```InputStream```, byte array, ```ImageInputStream``` etc.) Because the GC is so slow to act, I need to avoid reading things into memory in the first place if possible, but I also need to be able to read the sources multiple times (not all sources are on disk, they can be network streams or even pipes). I suspect that the biggest sinner is ```BufferedImage``` though, but it doesn't seem that there's much I can do about that.

I'm digressing, what I meant to say is that I appreciate the hints/help on reducing memory consumption.

**Comment by haraldk** [comment]
Sorry for the delay on this! Having a quite tight schedule at the moment, but things will hopefully be better soon. 

Hoping to have a dig at some of the bugs then. I'll let you know when I have a bug fix release ready.

-- 
Harald K

**Comment by haraldk** [comment]
1 year+.. Your definition of soon may differ.. ;-)

Not forgotten though.  

-- 
Harald K

**Comment by Nadahar** [comment]
@haraldk I on the other hand, have forgotten all about this issue :wink:

**Comment by haraldk** [comment]
Should be good now. 😀

-- 
Harald K
