### ISSUE TITLE
Image created for a large PSD file is empty

### ISSUE THREAD

**Issue by srbhatna** [haraldk/TwelveMonkeys#333]
PSDImageReader#read is resulting in 0KB image (samplefile.jpg) created for the large PSD file (chDisabBinaryOn.psd). Below is the code snippet used -
````java
      File file = new File("C:/Users/srbhatna/Desktop/apple/chDisabBinaryOn.psd");
        InputStream is = null;

        try {
            is = new FileInputStream(file);
            ImageReader reader = (new PSDImageReaderSpi()).createReaderInstance();
            ImageInputStream stream = ImageIO.createImageInputStream(is);
            reader.setInput(stream);

            BufferedImage image = null;
            ImageReadParam param = new ImageReadParam();
            image = reader.read(0, param);

            File f = new File("C:\\Users\\srbhatna\\Desktop\\apple\\samplefile.jpg");
            if (f.createNewFile()) {
                System.out.println("Created");
            } else {
                System.out.println("Exists");
            }
            ImageIO.write(image, "jpg", f);
        }
        catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
````

Is there a known PSD size limit while reading it through twelvemonkeys or is it a bug?
Let me know in case you need the psd file - chDisabBinaryOn.psd

**Comment by haraldk** [comment]
Hi srbhatna,

You assume it's the `PSDImageReader`, but I think it's more likely that the `JPEGImageWriter` is the culprit here. In any case, I do need the PSD file you used to reproduce the problem. Please ZIP and attach it, or share it on a file sharing service and link it here.

-- 
Harald K

**Comment by srbhatna** [comment]
Hi @haraldk ,

Thanks for your prompt response. Here's the link to the zipped file - https://www.dropbox.com/s/l4yktmqdc6p1gmg/sample.zip?dl=0

Thanks,
Srijan

**Comment by haraldk** [comment]
Hmmm..

Dropbox keeps telling me "There was an error downloading your file.", not sure what's the issue there. 

-- 
Harald K

**Comment by srbhatna** [comment]
Well, that's strange. I'm somehow able to download using the same. Anyway, here's another link -  https://drive.google.com/file/d/0B-w42epvAE8zdXJocWk0OHZHTk0/view?usp=sharing

Thanks,
Srijan

**Comment by haraldk** [comment]
Thanks,

Dropbox link works fine now, seems to have been a temporary issue...

Anyway, your image reads fine using the `PSDImageReader` as I expected. 

The problem you are facing, is that it is has 32 bits per sample (that is, 96 bits per pixel for RGB!), and the `JPEGImageWriter` probably can't cope with that. The fix is to create a temporary `BufferedImage` using normal `TYPE_3BYTE_BGR` or `TYPE_INT_RGB`, and paint the PSD image onto that, before saving the temporary image through the `JPEGImageWriter`. Keep in mind that you are going to need quite a bit of memory though, as the image is 13500 x 12000 pixels, and in 96 bits per sample, that means ~1.8 GB contiguous memory is needed for the original + ~460 MB for the temp image...


-- 
Harald K

**Comment by srbhatna** [comment]
Thanks @haraldk for your suggestions.

Would something like the following make sense before writing through JPEGImageWriter? 
`BufferedImage tmpImage = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_INT_RGB);
int[] rgbArray = image.getRGB(0, 0, image.getWidth(), image.getHeight(), null, 0, image.getWidth());
tmpImage.setRGB(0, 0, image.getWidth(), image.getHeight(), rgbArray, 0, image.getWidth());
image = tmpImage;`

**Comment by haraldk** [comment]
I believe the following is faster, but otherwise, yes:

    BufferedImage  tmpImage = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_INT_RGB);
    Graphics2D g = tmpImage.createGraphics();
    try {
        g.drawImage(image, 0, 0, null);
    }
    finally {
        g.dispose();
    } 
    image = tmpImage;

-- 
Harald K
