### ISSUE TITLE
Better rendering of corrupted JPEGs

### ISSUE THREAD

**Issue by lfcnassif** [haraldk/TwelveMonkeys#339]
The attached jpgs are partially corrupted, most have part of its data overwritten by unrelated data, others are early terminated. ImageMagick, GraphicsMagick and Windows can partially render these files. It would be awesome if TwelveMonkeys could render part of these files too.
[corrupted-jpg.zip](https://github.com/haraldk/TwelveMonkeys/files/911679/corrupted-jpg.zip)

**Comment by haraldk** [comment]
Hi lfcnassif,

Partial rendering of corrupted JPEGs is already supported. The normal flow is to throw an `IOException` in such cases, and that can't be easily changed, as this is the expected API behavior.

But by providing a destination image to the `JPEGImageReader` through the `ImageReadParam`, it will read as much as possible into the this image, before it throws an exception. 

Try the code below (works for all but one of your test files, I think there's a small issue in my segment parsing, I'll fix):

````java
    public static void main(String[] args) throws IOException {
        File file = new File(args[0]);

        try (ImageInputStream input = ImageIO.createImageInputStream(file)) {
            ImageReader reader = ImageIO.getImageReaders(input).next();

            try {
                reader.setInput(input);

                ImageReadParam param = reader.getDefaultReadParam();
                BufferedImage image = reader.getImageTypes(0).next().createBufferedImage(reader.getWidth(0), reader.getHeight(0));
                param.setDestination(image);

                try {
                    reader.read(0, param); // Will return image
                } catch (IOException e) {
                    e.printStackTrace();
                }

                // image now contains as much of the decoded image as possible, even if an exception occured

                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        JFrame frame = new JFrame(file.getName());
                        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                        frame.add(new JScrollPane(new JLabel(new ImageIcon(image))));
                        frame.pack();
                        frame.setVisible(true);
                    }
                });

            }
            finally {
                reader.dispose();
            }
        }
````

Best regards,

-- 
Harald K

**Comment by lfcnassif** [comment]
Hi Harald, thanks for the ultra fast reply!

I thought partial rendering should be done by default based on readme.md:

> Issues warnings instead of throwing exceptions in cases of corrupted or non-conformant data where ever the image data can still be read in a reasonable way<quote>

I Will try your code as soon as I come back to my computer.

Thanks,
Luis Nassif

**Comment by haraldk** [comment]
Hi again Luis,

Yes, I agree that passage might be a bit unclear in this case. The kind of corruption and non-conformance I'm talking about here, is mostly auxiliary data, like ICC profiles, Exif data, JFIF thumbnails etc. Here the images will decode fine, but colors might be a bit off, or metadata or thumbnails may be missing.

In your case, parts of the main JPEG stream is missing (truncated) or tables/markers necessary for decoding is missing. I don't consider this possible to "read in a reasonable way", even though parts of the image can be decoded. ;-)

Hope that clarifies the behavior!


Best regards,

-- 
Harald K

**Comment by lfcnassif** [comment]
Hi Harald,

Thank you for the explanation! With param.setDestination(image) I can read a lot of partial corrupted jpgs! Awesome!

But I tested the same approach with the default jdk jpeg reader (without twelve monkeys), and I could render a bit more partial jpgs. They are attached for your library improvement, if you have time.
[partial-jpgs-fail.zip](https://github.com/haraldk/TwelveMonkeys/files/914440/partial-jpgs-fail.zip)

Thank you very much for your tips and time!
Luis

**Comment by haraldk** [comment]
Thanks!

I'm aware of a few leniency issues in the segment parsing, as mentioned. I hope to have them fixed soon, either as a pure bugfix release or with some small new features. Might use some of your files as test samples. :-)

-- 
Harald K

**Comment by haraldk** [comment]
I believe this was fixed a couple of releases ago...
