### ISSUE TITLE
CMMException when parsing jpeg

### ISSUE THREAD

**Issue by rtimpe** [haraldk/TwelveMonkeys#34]
Hi Harald,

I've been using TwelveMonkeys successfully, but I found an image that causes problems (attached and linked):

http://25.media.tumblr.com/77f31c36ea8f46ad1f41d6c6f02c60a8/tumblr_n0ccizPvsK1smx7x5o5_1280.jpg

![tumblr_n0ccizpvsk1smx7x5o5_1280](https://f.cloud.github.com/assets/1720246/2083446/a2b0cd6e-8e02-11e3-9773-119d1f0996b8.jpg)

When I try to read in that image, I get the following exception:

```
java.awt.color.CMMException: General CMM error517
    at sun.java2d.cmm.kcms.CMM.checkStatus(CMM.java:180)
    at sun.java2d.cmm.kcms.CMM.createTransform(CMM.java:134)
    at java.awt.image.ColorConvertOp.filter(ColorConvertOp.java:540)
    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readImageAsRasterAndReplaceColorProfile(Unknown Source)
    at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
    at javax.imageio.ImageIO.read(ImageIO.java:1448)
    at javax.imageio.ImageIO.read(ImageIO.java:1308)
...
```

This may be related to this java bug:
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6444360

And here's another image I found that causes the same problem, in case that helps:
http://lh6.ggpht.com/_zhJGGuLhHrQ/Ro6SIyBE_TI/AAAAAAAAAA4/PWx6LzckCSs/Flower+-+GalleryPlayer.jpg

**Comment by lauerc** [comment]
The current release 3.3.2 doesn't seem to contain this patch and crashes with the same exception.

Is there a twelvemonkey release which applied this patch?

**Comment by haraldk** [comment]
@lauerc The current release may be old, but not *that old*.... The patch is in the 3.3.2 release. But as the exception isn't really a TwelveMonkeys bug, but rather a ICC profile or ColorManagment issue, we might have to work around it in more places. 

Please *create a new issue*, include the relevant stack trace, and attach an image that can reproduce the problem. If the problem can't be reproduced through a trivial `ImageIO.read(...)`, you also want to include the source code needed to reproduce. 

PS: If you have the time, please get the latest master from GitHub, build locally, and test with that version. There will be a 3.4 release *really soon*


Best regards,

-- 
Harald K
