### ISSUE TITLE
Problem generating a BufferedImage directly from DICOM file containing JPEG Lossless image

### ISSUE THREAD

**Issue by msfanous** [haraldk/TwelveMonkeys#344]
I am trying to create a BufferedImage from a DICOM (DCM) file containing JPEG Lossless data (transfer syntax: 1.2.840.10008.1.2.4.57).  I believe #182 added support for this.

After including the Twelve Monkeys JPEG Plugin, I expected the following to work.
`BufferedImage img = ImageIO.read(dcmFile);
`

However, I still received  a codec error and soon realized that the Twelve Monkeys JPEG Reader was not being loaded.

I then tried to force my application to use the Twelve Monkeys JPEG Reader like this:
```
ImageInputStream iis = ImageIO.createImageInputStream(dcmFile);
Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("JPEG");
if (readers.hasNext()) {
  ImageReader reader = readers.next();
  reader.setInput(iis, true);
  BufferedImage img = reader.read(0);
}
```

However, that triggered the following exception.
```
ImageIO ImageReader for JPEG failed
javax.imageio.IIOException: No SOF segment in stream
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:762)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:334)
	at javax.imageio.ImageReader.read(ImageReader.java:939
```

I feel like there is something simple that I might be missing, and I would appreciate any guidance.  Do I need to somehow extract the JPEG data from DICOM file prior to attempting the conversion to a BufferedImage?  The test data posted by @HermannKroll in #234 is just the JPEG data that was somehow extracted from a DICOM file.   Is extracting the JPEG data in that manner necessary?  If so, would anyone be able to point me in the right direction on how to go about doing that?

Thanks for any help!

**Comment by haraldk** [comment]
Hi,

First of all, thanks for reporting this as a separate issue, helping us keep the issue database tidy! :-)

The JPEG lossless support added to the `JPEGImageReader` in #182 is just that, _JPEG lossless support_. It does not add DICOM format support. Neither do we currently have a "DICOMImageReader" (although such plugins exists from other libraries). 

So, yes, if you want to use the TwelveMonkeys JPEG plugin to decode the image, you need to extract or locate the JPEG substream within the DICOM file (sorry if I use non-standard terms, I'm not too familiar with DICOM).

Best regards,

-- 
Harald K

**Comment by msfanous** [comment]
Thanks for the quick response @haraldk.  I did manage to figure this out.  Here's how in case anyone else has a similar need:

DCM4CHE has a DICOM Image reader.  However, it fails when the image included in the DICOM is of type JPEG Lossless.

The trick is to configure the DCM4CHE DICOM Image Reader to delegate to the Twelve Monkeys JPEG Image Reader as it tries to process the JPEG Lossless data.

First, configure DCM4CHE to use the ImageIO Service Registry by setting a System Property.
```
Properties props = System.getProperties();
props.setProperty("dcm4che.useImageIOServiceRegistry", "true");
```

Next, configure the DCM4CHE's ImageReaderFactory to map the JPEG Lossless Transfer Syntax UIDs to the Twelve Monkeys JPEGImageReader class.

```
ImageReaderParam jpegImageReaderParam = new ImageReaderParam("jpeg", JPEGImageReader.class.getName(), null);
ImageReaderFactory.getDefault().put("1.2.840.10008.1.2.4.57", jpegImageReaderParam);
ImageReaderFactory.getDefault().put("1.2.840.10008.1.2.4.70", jpegImageReaderParam);
```

That's really all there was to it!  The following code now successfully reads the imagery in my DCM file.
`BufferedImage img = ImageIO.read(dcmFile);`

Just include the DCM4CHE and TwelveMonkeys libraries in your project and follow the steps above to have them work together.  This worked for me with the 3.3.7 version of the DCM4CHE libraries and the 3.3.2 version of the TwelveMonkeys libraries.

**Comment by haraldk** [comment]
Excellent!

Thanks for reporting back with a very detailed and easy to follow solution! If you allow, I might add this to the readme, in case others have the same problem. 

Thanks,

-- 
Harald K

**Comment by msfanous** [comment]
No problem!  Add it where ever you like if you think it will be useful.

**Comment by alancoler** [comment]
> `BufferedImage img = ImageIO.read(dcmFile);`

When I run this after applying suggested code, it uses the dcm4che DicomImageReader instead of the 12M JPEGImageReader. I'm not sure why.

**Comment by alancoler** [comment]
After using suggested code changes above, ImageIO.read() appears to be using dcm4che DicomImageReader instead of 12M JPEGImageReader
java.lang.ArrayIndexOutOfBoundsException: 599808
	at org.dcm4che3.image.ByteLookupTable.lookup(ByteLookupTable.java:44)
	at org.dcm4che3.image.LookupTable.lookup(LookupTable.java:134)
	at org.dcm4che3.image.LookupTable.lookup(LookupTable.java:89)
	at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.applyLUTs(DicomImageReader.java:471)
	at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.read(DicomImageReader.java:353)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)

**Comment by haraldk** [comment]
@alancoler 
I'm sorry I can't help you much here...  I haven't tested @msfanous solution above, but it seems to have worked for him. But as far as I understand, it's used just in a few very specific cases (ie. to handle JPEG Lossless). I'm not sure it applies to your file.

Anyway, if for some reason DCM4CHE can't be configured to delegate to the TwelveMonkeys JPEGImageReader, there's nothing we can do about that (no TwelveMonkeys code is involved, according to your stack trace). You might get some better answers if you ask the people at https://dcm4che.org/, so I suggest starting there.  :-)


Best regards,

-- 
Harald K

**Comment by rich-coe** [comment]
@alancoler There is a LUT in your dicom image.
For every pixel value, the result pixel is found by a lookup in the LUT.
I would check to make sure the data is decompressed by the decompressor before being processed by the LUT. 
dcm4che is complaining that pixel value 0x92700 is not found in the LUT.

**Comment by sean-astraia** [comment]
@haraldk Firstly, thanks for a great lib!!! Saved my life! ;)

@msfanous Thanks for the handy solution!!! Still works in dcm4che version 5.31.2

And, just to put it out there, there's at least user of the dcm4che lib who is having real problems, and would without the help of this lib be really stuck. They, for some reason, while apparently having support for these lossless codecs, bundle it in modules of a separate application - weasis - the version of which is not available on maven. I don't yet understand how they expect anyone to be able to use it.

So, in case you guys have nothing to do - some more explicit dcm4che support would likely make a lot of us happy. 
But for now,  this solution already gets my quite far. Thanks both!!
