### ISSUE TITLE
Runtime control if TwelveMonkeys is used

### ISSUE THREAD

**Issue by simonsteiner1984** [haraldk/TwelveMonkeys#348]
At runtime we want to be able to choose if TwelveMonkeys is used or Sun classes.

Since ImageIO API is called in many libraries we dont want to modify them all, can we control the order so TwelveMonkeys appears after Sun classes when you call ImageIO.getImageReaders() type APIs.

We are currently doing this by modifying TwelveMonkeys JPEGImageReaderSpi, not sure if same can be achieved for TIFF also? 

```
--- a/imageio/imageio-jpeg/src/main/java/com/twelvemonkeys/imageio/plugins/jpeg/JPEGImageReaderSpi.java
+++ b/imageio/imageio-jpeg/src/main/java/com/twelvemonkeys/imageio/plugins/jpeg/JPEGImageReaderSpi.java
@@ -103,7 +103,7 @@ public class JPEGImageReaderSpi extends ImageReaderSpiBase {
 
         if (delegateProvider != null) {
             // Order before com.sun provider, to aid ImageIO in selecting our reader
-            registry.setOrdering((Class<ImageReaderSpi>) category, this, delegateProvider);
+            registry.setOrdering((Class<ImageReaderSpi>) category, delegateProvider, this);
```

**Comment by haraldk** [comment]
Hi Simon,

Technically, yes, you could do that. I would recommend adding this in your own code though, rather than modifying the Spi classes. You can can modify the registry order from anywhere you want.

I'm not sure why you want to do this though, as this will in most cases have the same effect as not installing the TwelveMonkeys plugins in the first place. Is there a specific use case that you want to support? Can you describe it in more detail, to help me understand it? :-)


Best regards,

-- 
Harald K

**Comment by simonsteiner1984** [comment]
Do you know how to do this for TIFF?

Use case is we want to test using Sun classes since that is what is what is in use for our customers, in some cases the images won't work so we enable TwelveMonkeys for certain images when required.

**Comment by haraldk** [comment]
Sure,

It works the same way for any service provider. 

See [this StackOverflow answer](http://stackoverflow.com/a/38198991/1428606) for code and details.
Just replace the GeoSolutions provider with the TwelveMonkeys one (`com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReaderSpi`), and make sure you order the `com.sun...` provider first.  


Best regards,

-- 
Harald K

**Comment by simonsteiner1984** [comment]
Thank you, the link says:
lookupProviderByName(registry, "com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader");
should be:
lookupProviderByName(registry, "com.sun.media.imageioimpl.plugins.tiff.TIFFImageReaderSpi");

**Comment by haraldk** [comment]
Ooops.. 

Good catch! Fixed it.

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now. Feel free to reopen if you have further questions regarding this issue.

-- 
Harald K
