### ISSUE TITLE
JPEG plugin not installed and used at run-time after maven built

### ISSUE THREAD

**Issue by leobr29** [haraldk/TwelveMonkeys#352]
Hi,

I import your librarie in a web application with maven : 

```
<dependency>
        <groupId>com.twelvemonkeys.imageio</groupId>
        <artifactId>imageio-jpeg</artifactId>
        <version>3.3.2</version>
</dependency>
```

When I execute my project in Eclipse, all work fine. I can see that the plugin seems to be install thanks to your documentation trick code : 

```
Code :
Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("JPEG");
while (readers.hasNext()) {
    System.out.println("reader: " + readers.next());
}

Response :
reader: com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader@4bed5ebf
reader: com.sun.imageio.plugins.jpeg.JPEGImageReader@45da7525
```

When I build a my web application with maven, the plugin is not install and I dont understand why because imageio-core-3.3.2.jar, imageio-jpeg-3.3.2.jar and imageio-metadata-3.3.2.jar appears in the lib repertory of the WAR. Here is the response of your documentation trick code : 

`reader: com.sun.imageio.plugins.jpeg.JPEGImageReader@2a28f67a`

Do you have ever seen that kind of problem ? 

Best regards,
Leo.

**Comment by haraldk** [comment]
Hi Leo,

Did you also read [Deploying the plugins in a web app](https://github.com/haraldk/TwelveMonkeys#deploying-the-plugins-in-a-web-app)? Are you using the context listener?


Best regards,

-- 
Harald K

**Comment by leobr29** [comment]
Next time I will take more time to read your doc.

Thanks !

**Comment by haraldk** [comment]
Feel free to suggest improvements to the documentation as well, it may not be perfectly structured... ;-)

-- 
Harald K
