### ISSUE TITLE
Issue when running ImageIO in Wildfly...

### ISSUE THREAD

**Issue by adanecito** [haraldk/TwelveMonkeys#357]
Hi,
I am seeing the following exception when trying to call ImageIO in Wildfly using 1.8.0_91-b14

Caused by: java.util.ServiceConfigurationError: javax.imageio.spi.ImageReaderSpi: Provider com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderSpi not found

Any idea how to resolve?

Thanks!

**Comment by adanecito** [comment]
This is running on Windows if that helps.
Thanks!

**Comment by pcorless** [comment]
I've seen something similar with using other imageIO plugins and tomcat.  I best guess is that the plugins don't work automagically with a custom class loader.    The following code might help as a work around.

static {
    IIORegistry registry = IIORegistry.getDefaultInstance();
    registry.registerServiceProvider(new com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderSpi());
}

**Comment by adanecito** [comment]
Ok I am getting the error message when compiling that the com.twelvemonkeys.imageio.plugins.jpeg package does not exist.
Any ideas what to do?

-Tony

**Comment by haraldk** [comment]
Have you read https://github.com/haraldk/TwelveMonkeys/blob/master/README.md#deploying-the-plugins-in-a-web-app ?

There known issues deploying ImageIO plugins as part of a web app in general.  Currently the best known option is to use the context listener. 

Best regards,

-- 
Harald K

**Comment by adanecito** [comment]
Yes. But I am concerned I am missing something when I read that. I am not loading any jars from my war. Is there some jars I need rather than relying on the jre/jdk to supply them? Is the jpeg class an plugin that does not exist normally in the jre/jdk?

Thanks haraldk

**Comment by adanecito** [comment]
Ok I tried haraldk your suggestion and I get the error message:
java.lang.ClassNotFoundException: com.twelvemonkeys.servlet.image.IIOProviderContextListener 

This leads back to my previous comment about imageio and the jre. What jars do I need to put in my war and where can I get them?

**Comment by adanecito** [comment]
ok I downloaded your source used maven but no jars created.

**Comment by adanecito** [comment]
Ok I tried adding the servlet created via maven to my wildfly module and on startup of the server I get the following error related to the servlet:
Failed to define class com.twelvemonkeys.servlet.image.IIOProviderContextListener in Module

Why am I getting this error? If we fix it will I get another?

**Comment by adanecito** [comment]
Ok copyint the servlet to the main lib got past the first problem now I have another:
 javax.imageio.spi.ImageWriterSpi: Provider com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriterSpi not found

So where is the jar with the plugins? From the maven build hard to find what it is.

**Comment by adanecito** [comment]
Ok I added your core and jpeg jars and now error messages mentioning dependency's for other libraries. Like scriptfreetlv and others. So more critical to know what is needed to run your libraries.

**Comment by adanecito** [comment]
Thanks everyone but I have decided not to use ImageIO since there seem to be too many issues with it on the Server side. Not your fault just the way classloaders are and with java 9 around the corner seems too risky to use anything using classloaders. Best of luck.

**Comment by haraldk** [comment]
Hi again,

Sorry for the brief replies, but I don't have access to my computer right now. 

Everything needed to either compile or use the library is explicitly defined in the Maven POMs. There are no other dependencies. 

For normal web apps, all that is needed is to place the jars in the standard WEB-INF/lib folder and add the context listener to your web.xml. I've used this myself in several projects, and many others are doing the same. Nothing risky about it.

The fact that classloaders are used to separate web apps in a container is part of Java EE, and has nothing to do with ImageIO or my library. I think you are confusing concepts here...

Finally, the dependencies you are mentioning are not related to my library, so I can't really say much useful about them. 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Closing the issue now, seems from the SO thread you finally got it working.

As mentioned, sorry about the brief replies, as I have been on holidays, only being able to reply via my phone.

-- 
Harald K

**Comment by richard-nielsen** [comment]
Any chance you can post a link to the SO thread please? I'm having a similar issue.

**Comment by haraldk** [comment]
@richard-nielsen It's been a while but I believe it's [this thread](https://stackoverflow.com/q/44786890/1428606). Not much details there though. 

-- 
Harald K
