### ISSUE TITLE
Reading and Writing a JPEG with EXIF data

### ISSUE THREAD

**Issue by ravikiranj** [haraldk/TwelveMonkeys#359]
Hi there,
    I'm trying to read a JPEG image (CMYK/RGB color space) that contains EXIF data and write it to a different folder retaining the original EXIF data. When I tried using the jar, I found that the output image is missing the EXIF data, can you help me as to how I can write it along with embedded EXIF data? I tried googling and looking at stackoverflow links but couldn't find a concrete solution.

```java
public class ReadAndWriteJPEGWithExif
{
    public static void main(String[] args) throws IOException
    {
        // has exif data
        Path p = Paths.get("images/exif/Landscape_1.jpg");

        BufferedImage bi = ImageIO.read(p.toFile());

        // output read file to another file
        ImageIO.write(bi, "jpg", Paths.get("images/exif/Landscape_1_tw_converted.jpg").toFile());     
     }
}
```

```bash
[rjanardhana@rjd exif (master)]# identify -format "%[EXIF:*]" Landscape_1.jpg
exif:Orientation=1
exif:ResolutionUnit=2
exif:XResolution=72/1
exif:YCbCrPositioning=1
exif:YResolution=72/1
         
[rjanardhana@rjd exif (master)]# identify -format "%[EXIF:*]" Landscape_1_tw_converted.jpg
```

**Comment by haraldk** [comment]
Hi Ravikiran,

Sorry about the late reply, I've been away on summer holidays.

If you just want to copy a JPEG file, you should use the normal classes in `java.io/nio`, like `Files.copy(from, to, ...)`. This will leave all EXIF and other image metadata untouched. This is also much faster than the code in your sample, as it just copies all bytes as-is, no need to decode and encode the JPEG image data.

If, however, you need to change the image in any way, and still retain the EXIF metadata, you need to use `ImageReader.readAll(...)` method, and the corresponding `ImageWriter.write(...)`, passing along the original metadata. Note that you need to manually update the EXIF metadata, if you change the dimensions of the image, as there's no automatic support for EXIF in the JPEG plugin (neither the JRE or TwelveMonkeys version).

You can use the classes in `com.twelvemonkeys.imageio.metadata.tiff` to modify EXIF metadata, if you like.


Best regards,

-- 
Harald K

**Comment by ravikiranj** [comment]
@haraldk Thank you very much for the response! I'll give ImageReader.readAll and ImageWriter.write with original metadata a shot since I need to change the image slightly.

**Comment by ravikiranj** [comment]
@haraldk I tried your method and the fix worked for RGB colorspace. However, when I tried doing the same for a JPEG image in CMYK colorspace, I noticed "Metadata components != number of destination bands" in the JPEGImageWriter.

I also came across https://github.com/haraldk/TwelveMonkeys/issues/4 which seems to fit my current usecase.

```java
// Set output stream and WriteParam
imageWriter.setOutput(imageOutputStream);
JPEGImageWriteParam imageWriteParam = (JPEGImageWriteParam) imageWriter.getDefaultWriteParam();
// JPEG Image Write can fail due to "Missing Huffman code table entry" if it's not embedded, hence ask the ImageWriter to compute it explicitly
imageWriteParam.setOptimizeHuffmanTables(true);

// The image already contains metadata, hence streamMetaData parameter is null
imageWriter.write(null, imageWithMetaData, imageWriteParam);
imageBytes = byteArrayOutputStream.toByteArray();
```

The exception is throw at `imageWriter.write` and I chased it down to http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/com/sun/imageio/plugins/jpeg/JPEGImageWriter.java#1347. Thank you for your help so far! Appreciate it!

**Comment by ravikiranj** [comment]
I noticed that you mentioned a possible solution in the #4 

> For the second issue I might have to do some work on the JPEGImageWriter as well, to handle writing of the metadata. The problem is that the image is converted from CMYK to RGB by default, but the metadata still contains SOF, SOS, Adobe DCT, ICC profile etc for CMYK data... I was hoping the writer would just see that these values were no longer correct, thus ignoring them.

>It IS possible to read CMYK images as CMYK (without conversion), you could try that as a workaround (using ImageReader.getImageTypes and ImageReadParam.setDestination/setDestinationType).

Unfortunately, this fix doesn't work for me since the output image needs to be transformed to RGB colorspace.

**Comment by haraldk** [comment]
If you convert from CMYK/YCCK to RGB/YCbCr (or in other words change the number of channels/bands from 4 to 3)  you also need to account for that in the metadata. It's not handled automatically yet, but it may be so in the future. 

I *think* you can just delete the relevant nodes from the tree (SOF, SOS, Adobe DCT and ICC profile, possibly the DHT/DQT tables as well), and the writer *should* generate these as needed, matching the new image data. 

JPEG writing is delegated to the `com.sun...JPEGImageWriter` so don't remember all the details of how things are handled, you may have to dig a little in the JDK code. :-)


Best regards,

-- 
Harald K

**Comment by ravikiranj** [comment]
Thank you for the input! Marking this ticket as CLOSED for now.
