### ISSUE TITLE
Add JPEG-LOSSLESS and jpeg-lossless to names array in JPEGProviderInfo

### ISSUE THREAD

**Issue by thoughtslinger** [haraldk/TwelveMonkeys#360]
The names 'jpeg-lossless' and 'JPEG-LOSSLESS' are not included in the names array in JPEGProviderInfo. These names are used by JAI to identify jpeg lossless readers and writers. Some packages explicitly look for these names. Please add these for JAI compatibility.

**Comment by haraldk** [comment]
Implemented in latest master.
