### ISSUE TITLE
Segmentation fault in libm.so caused by twelvemonkeys.imageio call

### ISSUE THREAD

**Issue by sleeply4cat** [haraldk/TwelveMonkeys#366]
This happens spontaneously. Unfortunately, I can not provide any additional information.

[crash.zip](https://github.com/haraldk/TwelveMonkeys/files/1169333/crash.zip)

**Comment by haraldk** [comment]
Hi,

As the TwelveMonkeys ImageIO plugins are all just plain Java, it does not make any direct JNI calls. So I doubt I can do much about it... 

From the crash logs, it seems like a JVM crash, and this MUST be directed at Oracle or the OpenJDK community. 


Best regards,

-- 
Harald K
