### ISSUE TITLE
TwelveMonkeys & JAI with JDK 1.6

### ISSUE THREAD

**Issue by BelenFlux** [haraldk/TwelveMonkeys#377]
Hi, i'm trying ti write a TIFF image with TwelveMonkeys, but i can't use the TIFFwriter.

So i found Harald's answer in this post: https://stackoverflow.com/questions/25385966/reading-tiff-file-using-jai
And i'm still trying to find wich ImageIO jar/s or maven deps add to my project.
Any help? please!

**Comment by haraldk** [comment]
Hi,

Are you trying to use JAI (as in the SO question) or Twelvemonkeys? In the latter case, Java 7 is required. There are Java 5/6 backports available, but these are not maintained by us.

If you are using Java 7 and Maven, adding the following dependency to your pom.xml is all that should be needed:

    <dependency>
         <groupId>com.twelvemonkeys.imageio</groupId>
         <artifactId>imageio-tiff</artifactId>
         <version>3.3.2</version>
     </dependency>


Best regards,

-- 
Harald K

**Comment by BelenFlux** [comment]
**Hi Harald!
My client is an old and big organization, and it doesn't want to change it's java version.
We must develop with Java 6, and i'm trying to use TwelveMonkeys to transform images to TIFF and compress them to CCITT group 4.

Following this: https://github.com/haraldk/TwelveMonkeys#old-version-30x
i added these to my pom:**
```
<!-- https://mvnrepository.com/artifact/com.twelvemonkeys.imageio/imageio-core -->
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-core</artifactId>
			<version>3.0.2</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.twelvemonkeys.imageio/imageio-tiff -->
		<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-tiff</artifactId>
			<version>3.0.2</version>
		</dependency>
```
And i tried this:
```
Iterator<ImageReader> tifReaders = ImageIO.getImageReadersByFormatName("TIF");
		while (tifReaders.hasNext()) {
		    System.out.println("IMAGE reader: " + tifReaders.next());
		}

		Iterator<ImageReader> tiffReaders = ImageIO.getImageReadersByFormatName("TIFF");
		while (tiffReaders.hasNext()) {
		    System.out.println("IMAGE reader: " + tiffReaders.next());
		}

		Iterator<ImageReader> jpegReaders = ImageIO.getImageReadersByFormatName("JPEG");
		while (jpegReaders.hasNext()) {
		    System.out.println("IMAGE reader: " + jpegReaders.next());
		}

		Iterator<ImageReader> bmpReaders = ImageIO.getImageReadersByFormatName("BMP");
		while (bmpReaders.hasNext()) {
		    System.out.println("IMAGE reader: " + bmpReaders.next());
		}
		
		final Iterator<ImageWriter> bmpWriters = ImageIO.getImageWritersByFormatName("BMP");
		while (bmpWriters.hasNext()) {
		    System.out.println("IMAGE writer: " + bmpWriters.next());
		}
		final Iterator<ImageWriter> tifWriters = ImageIO.getImageWritersByFormatName("TIF");
		while (tifWriters.hasNext()) {
		    System.out.println("IMAGE writer: " + tifWriters.next());
		}
		
		final Iterator<ImageWriter> tiffWriters = ImageIO.getImageWritersByFormatName("TIFF");
		while (tiffWriters.hasNext()) {
		    System.out.println("IMAGE writer: " + tiffWriters.next());
		}
		final Iterator<ImageWriter> jpegWriters = ImageIO.getImageWritersByFormatName("JPEG");
		while (jpegWriters.hasNext()) {
		    System.out.println("IMAGE writer: " + jpegWriters.next());
		}
		System.out.println("------------------------");
	
String names[] = ImageIO.getReaderFormatNames();
	    for (int i = 0; i < names.length; ++i) {
	      System.out.println("reader " + names[i]);
	    }

	    names = ImageIO.getWriterFormatNames();
	    for (int i = 0; i < names.length; ++i) {
	      System.out.println("writer " + names[i]);
	    }
	    System.out.println("------------------------");
```
**Obtaining this output:**
IMAGE reader: com.sun.imageio.plugins.jpeg.JPEGImageReader@5eaa780b
IMAGE reader: com.sun.imageio.plugins.bmp.BMPImageReader@3f766af0
IMAGE writer: com.sun.imageio.plugins.bmp.BMPImageWriter@3d5b5376
IMAGE writer: com.sun.imageio.plugins.jpeg.JPEGImageWriter@6fbdd27a
------------------------
reader jpg
reader BMP
reader bmp
reader JPG
reader jpeg
reader wbmp
reader png
reader PNG
reader JPEG
reader WBMP
reader GIF
reader gif
writer BMP
writer bmp
writer jpg
writer JPG
writer wbmp
writer jpeg
writer png
writer PNG
writer JPEG
writer WBMP
writer GIF
writer gif
------------------------

Thank you,

--
Belén

**Comment by haraldk** [comment]
Ok,

How do you run your application? How is it packaged and deployed?

You do need to have all the required JARs on the class path, when you *run* your application., for the plugin to register itself. Depending on how your application is packaged and run, the way to set this up varies. 

But the JARs needed in your case are (from the [Manual dependency example](https://github.com/haraldk/TwelveMonkeys/#manual-dependency-example) in the readme): 

```
twelvemonkeys-common-lang-3.0.2.jar
twelvemonkeys-common-io-3.0.2.jar
twelvemonkeys-common-image-3.0.2.jar
twelvemonkeys-imageio-core-3.0.2.jar
twelvemonkeys-imageio-metadata-3.0.2.jar
twelvemonkeys-imageio-tiff-3.0.2.jar

```

Note that the old version is no longer updated with new features or bug fixes.

If you package your application as a web app, you also need to read [Deploying the plugins in a web app](https://github.com/haraldk/TwelveMonkeys/#deploying-the-plugins-in-a-web-app).



-- 
Harald K

**Comment by BelenFlux** [comment]
It's a backend app, i receive images sent in Base64 through a POST.
We have a customised (by the client) Tomcatv6, JDK 1.6, Maven 2, and i have checked jars before:
![libs](https://user-images.githubusercontent.com/29309902/30216106-4b8e4eea-9488-11e7-8dfd-a25924f9bbd7.png)
![libs2](https://user-images.githubusercontent.com/29309902/30216141-612ea272-9488-11e7-994f-633f10a5d82c.png)

--
Belén

**Comment by BelenFlux** [comment]
This is happening with the helper i'm trying to create:
![twelvemonks](https://user-images.githubusercontent.com/29309902/30217447-8c3908c8-948c-11e7-80b4-a25f53264e15.png)

**Comment by haraldk** [comment]
Sorry,

I just remembered that TIFF write support wasn't added until 3.1.x version of the library. Unfortunately. 

This means, you need to either use JAI or look for one of the back port forked projects (or create a back port yourself). Here's one: https://github.com/Topdanmark/TwelveMonkeys/commit/a2a1d85d3bdaf3579cc2d9869dea7d5c516560d6

This code is completely unsupported by me though. 

-- 
Harald K

**Comment by BelenFlux** [comment]
Yes!
That's exactly what you are saying in StackOverflow (the link is in my first comment right here), that we should add JAI.

So, to use JAI, do you have any idea of wich ImageIO jar/s or maven deps add to my project?

**Comment by haraldk** [comment]
Sorry,

While I try to be nice and help out, this is the issue tracker for the TwelveMonkeys ImageIO project. This is not general discussion forum or free help site. For that, I recommend using StackOverflow.

JAI and JAI ImageIO is a separate (competing) library owned by Oracle. You can probably find everything you need on their site. There's also an open source fork on GitHub. 

PS: You should still read [Deploying the plugins in a web app](https://github.com/haraldk/TwelveMonkeys/#deploying-the-plugins-in-a-web-app), as the same problem applies to JAI ImageIO as well, if you choose to deploy ImageIO plugins as part of a web app.


Good luck!

-- 
Harald K

**Comment by BelenFlux** [comment]
Oh! i wasn't aware about it is a competing library, sorry.

Thanks a lot for all your answers!

--
Belén.
