### ISSUE TITLE
Colorspace changes on write?

### ISSUE THREAD

**Issue by ksclarke** [haraldk/TwelveMonkeys#382]
I may be misunderstanding how it's supposed to work, but I'm reading in a TIFF image with an sRGB colorspace and, when I write it out as a JPEG, it's coming out with the colors wrong. If I use Imagemagick's `identify` on the JPEG image, it says that it's using CMYK.

Here is the code:

```
package test;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Iterator;

import javax.imageio.IIOImage;
import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.imageio.ImageWriter;
import javax.imageio.stream.ImageInputStream;

public class Test {

    public static void main(final String[] args) throws IOException {
        final ImageInputStream input = ImageIO.createImageInputStream(new File("test-format.tif"));
        final Iterator<ImageReader> readers = ImageIO.getImageReaders(input);
        final BufferedImage image;

        ImageReader reader = null;

        if (readers.hasNext()) {
            reader = readers.next();
            reader.setInput(input);
            image = reader.read(0);

            System.out.println("Reading with " + reader.getOriginatingProvider().getPluginClassName());

            System.out.print(" TIFF ");
            System.out.println(image.getColorModel().getColorSpace().isCS_sRGB() ? "is sRGB" : "isn't sRGB");

            final Iterator<ImageWriter> writers = ImageIO.getImageWritersByMIMEType("image/jpeg");

            if (writers.hasNext()) {
                final ImageWriter writer = writers.next();

                System.out.println("Writing with " + writer.getOriginatingProvider().getPluginClassName());

                // Isn't this supposed to write using the color space of the input image?
                writer.setOutput(ImageIO.createImageOutputStream(new FileOutputStream("test-out.jpg")));
                writer.write(null, new IIOImage(image, null, null), null);
            }
        }

        if (reader == null) {
            System.err.println("Error: no appropriate reader");
        }

    }

}
```

The test image is available from: https://s3.amazonaws.com/ksclarke-test/test-format.tif

Identify reports it as: `test-format.tif TIFF 1000x1000 1000x1000+0+0 8-bit sRGB 4MB 0.000u 0:00.000`

Output from identify: `test-out.jpg JPEG 1000x1000 1000x1000+0+0 8-bit CMYK 58.4KB 0.000u 0:00.000`

Am I misunderstanding how the writing is supposed to work or is this an issue? Thanks.

My test script output:

```
Reading with com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader
 TIFF is sRGB
Writing with com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter
```

**Comment by haraldk** [comment]
Hi Kevin,

The underlying issue here is likely that JPEG doesn't have well defined way of specifying channel colors. I think your TIFF is RGBA (with alpha channel), and the Java JPEGImageWriter writes this as an RGBA (or YCCA) JPEG (even if there are no transparent pixels). 

But when most applications see a JPEG with 4 channels, it is assumed to be CMYK. 

The easiest solution is just to remove the alpha channel before writing the JPEG.  See for example [this StackOverflow answer](https://stackoverflow.com/a/36057374/1428606).


Best regards,

-- 
Harald K

**Comment by ksclarke** [comment]
Hi Harold,

It was sRGB when I read it back in, but I read in another ticket (#281) that CMYK images are converted into sRGB as they're read in by the library by default so I assumed that was why.

The TIFF source does have an alpha channel. So the fact that the JPEGImageWriter is writing this as a RGBA is causing the colors to be off? I can remove the alpha channel as you suggest before writing the JPEG. Thanks!

Kevin

**Comment by ksclarke** [comment]
Hmm, setting the alpha to white like in the stackoverflow answer doesn't seem to have fixed the incorrect colors in the output JPEG.

**Comment by haraldk** [comment]
Hi Kevin,

Happy to hear it worked out! 

And yes, the important part is not to replace the transparent parts with a color (that's optional), but to change to a `BufferedImage` type without alpha channel altogether, like `TYPE_3BYTE_BGR` or `TYPE_INT_RGB`. 

Sorry about the somewhat rushed answer and slow follow-up. I was just about to go on vacation and have been away for a couple of days. 


-- 
Harald K

**Comment by ksclarke** [comment]
No problem. Thanks again for pointing me in the right direction!
