### ISSUE TITLE
Resolution issue when reading Apple ICNS files

### ISSUE THREAD

**Issue by Ringwid** [haraldk/TwelveMonkeys#385]
I want to get the icon in Apple ICNS that has the highest resolution.

In some cases, TwelveMonkeys handled perfectly.
<img width="374" alt="untitled" src="https://user-images.githubusercontent.com/19713691/32064741-5009ac8a-baad-11e7-983c-2fecba2d9b9f.png">
However, the image read is sometimes in a low resolution.
<img width="453" alt="untitled 2" src="https://user-images.githubusercontent.com/19713691/32064807-80bc1d22-baad-11e7-9058-5515385c7144.png">

I could not find a clear pattern of on which type of ICNS the problem occurs.

**Comment by haraldk** [comment]
Hi Ringwid,

The pattern is actually quite straight forward. The ICNS files contains multiple icons in multiple sizes. The `ICNSImageReader` simply reads them in the order they are found in the file. This means that if you use `ImageIO.read(...)` to read your icon, you will always end up with the first icon the file (in whatever resolution it has).

I did consider implementing an algorithm to look up the "best" icon and return that as the first icon. However, I realized there's no one size fits all solution to do this, as what is "best" depends on the use case.

So, if you want to load the highest resolution image, you need to implement such an algorithm.  It should be fairly simple. Start by obtaining the `ImageReader`:

````java
File icnsFile ...; // or InputStream
ImageInputStream stream = ImageIO.createImageInputStream(icnsFile);
ImageReader reader = ImageIO.getImageReaders(stream).next(); // In real code, test hasNext() first
````

Then loop over the images, to find the highest resolution:

````java
int best = -1;
int bestSize = 0;

int numImages = reader.getNumImages(true);

for (int i = 0; i < numImages; i++) {
    int w = reader.getWidth(i); // Most icon resources are square, but not all
    int h = reader.getHeight(i);
    int size = w * h;

    if (size > bestSize) {
        best = i;
        bestSize = size;
    }
}
````

Finally read that image:

````java
BufferedImage bestIcon = reader.read(best, null);
````

Some notes: 

* An ICNS file may contain multiple icons of the same size, but in various bit depths. To test for this, use the `reader.getRawImageType(i)` to figure out which one is "better". 
* Larger isn't always better (you might want to specify a threshold size, and get the smallest icon larger than the threshold size instead). 
* Unless you have a JPEG 2000 plugin installed, icon resources compressed using this format will not be decoded properly, you may want to choose a different one.


Hope that helps,

-- 
Harald K

**Comment by Ringwid** [comment]
Thank you @haraldk for spending your time providing such a detailed solution to this specific problem!
I was thinking maybe you should create a link in the README to this issue in case of others also looking for this problem.

**Comment by haraldk** [comment]
I might consider adding it to the readme, or create a more in-depth tutorial at some point.

Happy coding! 😉

-- 
Harald K
