### ISSUE TITLE
NPE while reading TIFF image(s)

### ISSUE THREAD

**Issue by xlthor** [haraldk/TwelveMonkeys#391]
With certain TIFF files I encounter a strange behaviour:

```
BufferedImage img = null;
try
{
	if ( is != null && fos != null )
	{
		ImageInputStream iis = ImageIO.createImageInputStream(is);

		if ( iis != null )
		{
			dumpIioReaders(iis);

			img = ImageIO.read(iis);

			if ( img != null )
			{
				LOGGER.info(" Image: " + img.toString());
				ImageIO.write(img, "png", fos);
				converted = true;
			}
			else
				LOGGER.info(" Image IS NULL ??");
		}
		else
			LOGGER.info(">>>> Image Input Stream is null ??");
	}
}
catch ( Exception e )
{
	LOGGER.error("An error occured: " + e.getMessage(), e);
	LOGGER.error( Arrays.toString(Thread.currentThread().getStackTrace()).replaceAll(",", "\n"));
	return converted;
}
```
The '`dumpIioReaders`' method correctly spit's out "`tiff`" for the opened stream, although I get a "NPE" w/o any stack trace info:

```
05.11.2017 23:33:13.106 *INFO* [ WEBCACHE] [sling-threadpool-2296c9cc] com.corp.webcache.core.asset.services.ConverterServiceImpl  found image readers: tiff
05.11.2017 23:33:13.108 *ERROR* [ WEBCACHE] [sling-threadpool-2296c9cc] com.corp.webcache.core.asset.services.ConverterServiceImpl An error occured: null
java.lang.NullPointerException: null
05.11.2017 23:33:13.109 *ERROR* [ WEBCACHE] [sling-threadpool-2296c9cc] com.corp.webcache.core.asset.services.ConverterServiceImpl 
```
which is the line with the stacktrace itself.

The particular TIFF is this one:
http://www.fileformat.info/format/tiff/sample/1f37bbd5603048178487ec88b1a6425b/download

Other tiffs are working, is this particular format not supported or what can be the cause.

Any help appreciated, Axel

**Comment by haraldk** [comment]
Hi Axel,

That file is already included in my set of test samples, so if it wasn't supported the build would fail. I also have no problem reading it in a separate test here.

It's a pretty standard TIFF file, using LZW compression and predictor, stored in strips. Nothing exotic about it.

As there's no stack trace associated with the exception, it's also hard to say just what causes it. So I suggest you pull out the debugger, and step through the code to see exactly what happens, and where the NPE occurs. 

-- 
Harald K

**Comment by xlthor** [comment]
Hi Harald,

actually, we solved that problem. It hasn't todo anything with twelvemonkeys, so srry for bothering you!

We are running twelvemonkeys within an OSGI container (apache felix) and use Aries SPI fly to integrate the SPI plugins into imagio. Unfortunately, the downloadable jar for Aries SPI fly was obviously compiled on a JAVA < 1.6 and had JSR/RET issues. Re-compiling with JAVA 8 fixed this.

Thank you for your quick respones and sorry for bothering you,
Axel

**Comment by haraldk** [comment]
No problem! 

Glad to hear you solved it!

-- 
Harald K
