### ISSUE TITLE
Update Batik for imageio-batik to 1.9.1

### ISSUE THREAD

**Issue by TsundereBug** [haraldk/TwelveMonkeys#392]
So that I don't get a NoClassDefFoundError whenever I try to use ImageIO

**Comment by haraldk** [comment]
Hi Anthony,

I'm not sure I understand the problem... What version of the library are you running, and what version of Batik do you use at runtime?

Why do you think that updating the dependencies to 1.9.1 would be required? 

The current dependencies are 1.8, because that is what the library is built and tested against. I will probably update to 1.9.x at some point, but most likely not before 4.0. 

-- 
Harald K

**Comment by TsundereBug** [comment]
I'm using Batik 1.9.1 and TwelveMonkeys ImageIO Batik 3.3.2. When trying to run a test to print out some results that use BufferedImages of SVGs or when trying to scan for plugins in ImageIO I get a NoClassDefFoundError. I can upload my build.sbt later :)

**Comment by haraldk** [comment]
Ah, okay, I see.

Well, as mentioned, TwelveMonkeys ImageIO 3.3.x only supports Batik 1.8. Any specific reasons why you don't want to use that version? Anyway, 1.9 and 1.9.1 seems to work fine as well for me. 

Can you include the stack trace of the `NoClassDefFoundError` you see?

-- 
Harald K

**Comment by TsundereBug** [comment]
Setting my project SDK to Java 9 fixes this issue. Very odd :thinking:

**Comment by haraldk** [comment]
Very odd indeed.

Most likely there's something else going on. Bad Java install, missing dependencies etc. I see you don't include` com.twelvemonkeys.common/common-io` and `com.twelvemonkeys.common/common-image` which are required. There's also missing Batik dependencies, compared to what is declared in the `com.twelvemonkeys.imageio/imageio-batik` POM.

I don't have any problems running Batik or the SVG ImageIO plugin using Java 7, 8 or 9, and Batik 1.8, 1.9 or 1.9.1. Normal Java/Maven build.

But I'm no Scala/SBT expert, so I can't really help much there. Usually though, there should be a `ClassNotFoundException` (or other exception from the `ImageIO` class initialization) somewhere *before* the `NoClassDefFoundError` occurs. But it may be caught and "swallowed" somewhere on the way...


-- 
Harald K

**Comment by TsundereBug** [comment]
@haraldk You shouldn't have to supply all dependencies if they're in the `compile` (default) scope of a dependency.

`batik-transcoder` uses a lot of these dependencies and I don't know where i get my `common-io` and `common-image` from.
