### ISSUE TITLE
ArrayIndexOutOfBoundsException when drawing float greyscale TIFF

### ISSUE THREAD

**Issue by converge20t** [haraldk/TwelveMonkeys#394]
First, I'd like to thank you on this excellent image library, as it has been very beneficial in adding TIFF support to our application.

Previously using version 3.3.2, I was unable to to read in greyscale TIFF images using this code:

`BufferedImage tiffImage = ImageIO.read(new File("greyscale_image.tif"));`

I would get this exception: _IllegalArgumentException: Bad value for bits!_

After downloading and compiling the latest sources, the above code now completes without exception. However, if I try to do anything with the BufferedImage afterwards, I get an _ArrayIndexOutOfBoundsException_. The code below produces this exception:

```
Graphics2D g2 = (Graphics2D) g.create();
g2.drawImage(tiffImage, 0, 0, this);
```

I created a work-around by manually creating a new BufferedImage and using setRGB() to copy the read-in image. However, I have to catch the _ArrayIndexOutOfBoundsException_ as image.getRGB() also produces the same exception whenever it encounters a black pixel. This work-around works, although the image appears to be inverted (black/white to white/black) once it's drawn on the screen. Here is that code:

```
BufferedImage convertedImage = new BufferedImage(tiffImage.getWidth(), tiffImage.getHeight(), BufferedImage.TYPE_INT_RGB);
for (int y = 0; y < tiffImage.getHeight(); y++) {
	for (int x = 0; x < tiffImage.getWidth(); x++) {
		try {
			int color = tiffImage.getRGB(x, y); // may create exception
			convertedImage.setRGB(x, y, color);
		} catch (ArrayIndexOutOfBoundsException e) {
		}
		
	}
}
```

Attached is an example image that exhibits this issue.
[greyscale_image.zip](https://github.com/haraldk/TwelveMonkeys/files/1474986/greyscale_image.zip)

**Comment by haraldk** [comment]
@converge20t Thanks!

Your image seems to read and display fine here. But I think perhaps there's a bug in the latest master that clamps values > 1 to 1, but does not clamp values < 0 to 0.. This seems to work in most cases, but creates an exception in some, which I don't have test coverage for... I'll try to push a fix for this ASAP!

About the inversion... The TIFF in question lacks the required `PhotometricInterpretation` tag (as per the TIFF 6.0 spec) . This means that there's no way to know for sure how the data is to be interpreted... The only thing a reader can do, is to fail gracefully, or make a (educated) guess. You'll get a warning about this, if you add a warning listener to the reader. We use a fallback that is pretty much the same as the JDK9/JAI ImageIO TIFFImageReader for compatibility, and unfortunately it isn't what you expect in this case (you get `BlackIsZero`). 
(I also see that the normalization of float values isn't implemented for `WhiteIsZero`, so setting it won't help... I'll fix).


Best regards,

-- 
Harald K

**Comment by converge20t** [comment]
Thank you for the quick response and the information about the TIFF in question. The image was submitted to us by a user, which was originally created by a scientific instrument they are using. Because of this, we have to deal with the image "as is", since we have no control over this instrument and how it generates TIFF images.

The inversion is not a big problem, as our software already has the option of inverting the image before the user analyzes it.

**Comment by haraldk** [comment]
Should work now, in latest master.
