### ISSUE TITLE
TIFFImageWriter: Work around stream position issue in FileCacheImageOutputStream causing garbled output for multipage TIFF files

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#401]
See discussion from #334, [bug found by James Dudley](https://github.com/haraldk/TwelveMonkeys/issues/334#issuecomment-353616311). 

Filing as separate issue for better tracking/release notes.

**Comment by tiagoquaini** [comment]
Hi Harald,

First of all, thanks on all the effort you've put into TwelveMonkeys so far!

I am working on a project in which we have a PDF to a multipage TIFF conversion, and we are using TwelveMonkeys to achieve this. However, we are facing the issue described in #334.

I tested our code using the current TwelveMonkey's current master branch and it is working as expected. My question is: do you think the next release to the maven repository will happen in the near future? Or is there any other workaround we could apply until the next release is made?

Thanks!
Tiago

**Comment by haraldk** [comment]
@tiagoquaini 

Thanks! I have a few more issues I'd like to close before making the next release. 

In retrospect, I should have made a bug fix release right away, after fixing some of the more critical bugs. But unfortunately, as nobody pays me to do this work, it all happens on my spare time, and spare time is a very limited resource.

It will happen as soon as I am able to fix [the last known issues](https://github.com/haraldk/TwelveMonkeys/milestone/6) though. I just can' make any promises on a specific date.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
@tiagoquaini  Release is finally out. :-)

**Comment by tiagoquaini** [comment]
@haraldk thanks Harald! Appreciate the hard effort you have put into this!

Best,
Tiago
