### ISSUE TITLE
Help needed - Convert imagemagick commends

### ISSUE THREAD

**Issue by subbagudipalli** [haraldk/TwelveMonkeys#415]
@haraldk 
Is it possible to convert below imagemagick commands? if so, could you please share the stub code

convert image_1.tif  -background white -alpha off -flatten -format jpg (to convert tif to jpg with white background color,  alpha channel off and flatten all layers)
 
 convert step1.jpg -background white -gravity center -extent "11331"x"11331" step2.jpg (to extent the image)

**Comment by haraldk** [comment]
Hi,

Yes, I'm confident it's possible to do that (using Java)! 

Read the TIFF using ImageIO (and our TIFF plugin), create a new `BufferedImage`, of the correct size, fill it with white, then place the original image in the center, and finally write it all out as JPEG using ImageIO. 

If you would like me to implement the above solution as a paid service for you, please contact me at my private email, and we can work out the details. Or, if you just need help to implement some of the steps, StackOverflow is a great place to ask!


Best regards,

-- 
Harald K

**Comment by subbagudipalli** [comment]
Thank you very much for your suggestions :) :)
