### ISSUE TITLE
PSD File rendered incorrectly

### ISSUE THREAD

**Issue by vsarya** [haraldk/TwelveMonkeys#422]
Wrong image is generated for the the following PSD 
https://drive.google.com/file/d/1wTcFAz6zok3NMzQ1TFsTb5KqJOQbgcbi/view?usp=sharing

Rendered Image(incorrect) - 
![incorrect](https://user-images.githubusercontent.com/11541786/38803602-5a75205c-418d-11e8-94f8-7428281ce70b.jpeg)

Expected - 
![correct](https://user-images.githubusercontent.com/11541786/38803607-604e83f6-418d-11e8-90a7-c47619ef7aa1.jpg)

**Comment by haraldk** [comment]
Hi Vishal,

Are you using the latest master? If not, what version are you using?

For me, it looks good, the image looks exactly like the expected.


-- 
Harald K

**Comment by haraldk** [comment]
I see. 

Well, the bug is fixed, pending release.

-- 
Harald K
