### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by joshi1976** [haraldk/TwelveMonkeys#427]
edited: 
I downloaded jar files. 

My basic requirement is I need to convert PNG<->JPEG<->TIFF image formats.I believe with the help of this project I can do it right? also where can I find code to convert all these 3 formats?

Thank you in advanced!

**Comment by haraldk** [comment]
Hi Joshi,

Precompiled JARs can be found on the [project home page](https://github.com/haraldk/TwelveMonkeys#links-to-prebuilt-binaries). 

There's no specific documentation on this kind of conversion, as it is covered by the ImageIO API (which is part of Java). The TwelveMonkeys ImageIO library mainly provides plugins for various formats, like JPEG and TIFF. For general documetation, see for example [tha Java2D tutorial "Working with images"](https://docs.oracle.com/javase/tutorial/2d/images/index.html) and [the The Java Image I/O API guide](https://docs.oracle.com/javase/8/docs/technotes/guides/imageio/spec/imageio_guideTOC.fm.html). There's also an example [on the project home page](https://github.com/haraldk/TwelveMonkeys#advanced-usage), showing more advanced usage.

The simplest possible conversion would be something like (where `format` is a "format name", like "JPEG", "PNG" or "TIFF"):

    public void convert(File input, File output, String format) throws IOException {
        BufferedImage image = ImageIO.read(input);
        if (image == null || !ImageIO.write(image, format, output)) {
            throw new IIOException("Could not convert " + input + " to " + format + " format.");
        }
    }

The somewhat naive implementation above, will work in many cases. But it won't handle things like metadata (do you want to keep copyright, artist/photographer, keywords, GPS location etc.?), thumbnails, multiple images in a single file (supported by TIFF, but not JPEG or PNG) or handle image data issues (like JPEG doesn't have a standard way of storing transparency and can't store indexed or color mapped images, PNG has no specified way of storing CMYK data or floating point data, while TIFF can store image data in pretty much any way you can think of, etc). Here you need to find a subset of the features you need/want, and implement accordingly.


Best regards,

-- 
Harald K
