### ISSUE TITLE
Can't read this image

### ISSUE THREAD

**Issue by vitalyster** [haraldk/TwelveMonkeys#441]
![](https://i.imgur.com/w3FnBZV.jpg)

Anyone except Java even with this library says it is correct JPEG

**Comment by makc** [comment]
+1 I have same problem

**Comment by vitalyster** [comment]
Sorry, my bad, the real issue is `URLConnection.guessContentTypeFromStream` return `null` for this image, so this is not the issue of this project

**Comment by haraldk** [comment]
Oh, okay, I see. 

Well, the "problem" is this is a "bare" JPEG, without either APP0/JFIF or APP1/Exif marker (or any other APPn marker, really). That's why the (very simple) algorithm in `URLConnection.guessContentTypeFromStream` don't recognise it. Still a valid JPEG stream though. 

-- 
Harald K
