### ISSUE TITLE
How to add entry to metadata

### ISSUE THREAD

**Issue by nanthony21** [haraldk/TwelveMonkeys#444]
I would like to add an image description to the file that I am saving. Based on what I saw in #412 I figured something like this is what I would want. However, as far as I can tell, the `createTiffFieldNode` method doesn't exist. What is the proper way to add a node to the metadata?

```
IIOMetadata  meta = writer.getDefaultImageMetadata(ImageTypeSpecifier.createFromBufferedImageType(bim.getType()), param);
IIOMetadataNode tree = (IIOMetadataNode) meta.getAsTree(meta.getMetadataFormatNames()[0]);
IIOMetadataNode ifdNode = tree.getFirstChild();
createTiffFieldNode(ifdNode, TIFF.TAG_IMAGE_DESCRIPTION, "MyDescription");
```

**Comment by haraldk** [comment]
Hi Nick,

I believe he copied the code from the `TIFFImageMetadataTest`. In that case, the method looks like this:

````java
    static void createTIFFFieldNode(final IIOMetadataNode parentIFDNode, int tag, short type, Object value) {
        IIOMetadataNode fieldNode = new IIOMetadataNode("TIFFField");
        parentIFDNode.appendChild(fieldNode);

        fieldNode.setAttribute("number", String.valueOf(tag));

        switch (type) {
            case TIFF.TYPE_ASCII:
                createTIFFFieldContainerNode(fieldNode, "Ascii", value);
                break;
            case TIFF.TYPE_BYTE:
                createTIFFFieldContainerNode(fieldNode, "Byte", value);
                break;
            case TIFF.TYPE_SHORT:
                createTIFFFieldContainerNode(fieldNode, "Short", value);
                break;
            case TIFF.TYPE_RATIONAL:
                createTIFFFieldContainerNode(fieldNode, "Rational", value);
                break;
            default:
                throw new IllegalArgumentException("Unsupported type: " + type);
        }
    }

    static void createTIFFFieldContainerNode(final IIOMetadataNode fieldNode, final String type, final Object value) {
        IIOMetadataNode containerNode = new IIOMetadataNode("TIFF" + type + "s");
        fieldNode.appendChild(containerNode);

        IIOMetadataNode valueNode = new IIOMetadataNode("TIFF" + type);
        valueNode.setAttribute("value", String.valueOf(value));
        containerNode.appendChild(valueNode);
    }
````

Feel free to adapt and change to suit your needs. 

There's no strict "proper" way to add nodes, you can do it however you like, what matters is that it conforms to the spec/DTD found [here](https://docs.oracle.com/javase/9/docs/api/javax/imageio/metadata/doc-files/tiff_metadata.html).

Just keep in mind that #412 is still open, so only a very limited set of fields may be set (for now).


Best regards,

-- 
Harald K

**Comment by nanthony21** [comment]
Thanks for the help. There was one minor issue in the code above. The "number" attribute needs to be set before appending fieldNode to the parentIFDNode. After making that change I am able to add an image description.

I'm surprised that there isn't a straightforward method of IIOMetadata that takes care of this.
