### ISSUE TITLE
PSD file rendered incorrectly

### ISSUE THREAD

**Issue by vsarya** [haraldk/TwelveMonkeys#450]
Following PSD file is not rendered correctly by TwelveMonkeys : 

PSD file - https://drive.google.com/open?id=1LSgvNX-mGNAB1c0dru5Cysa10SnLPZBy 

Correct Preview -  ![correct](https://user-images.githubusercontent.com/11541786/47008065-3072f400-d157-11e8-8b4d-e45dca0079f0.jpeg)
Incorrect preview - ![incorrect](https://user-images.githubusercontent.com/11541786/47008066-3072f400-d157-11e8-8373-487734e78c7f.jpeg)

**Comment by haraldk** [comment]
Hi Vishal,

I believe this issue is fixed in the 3.4 (3.4.1) release. Please upgrade your dependencies and try again. 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now.

Let me know if you still have problems (using 3.4.1 or later).

-- 
Harald K

**Comment by haraldk** [comment]
@vsarya 

What do you mean by "standalone setup"? There are (in most cases) no dependencies on anything apart from the JDK from the TwelveMonkeys ImageIO plugins. 

But as they are indeed plugins, they are obviously tied in to the ImageIO API and the Java2D classes. You can not use it without Java2D (ie. Android). Other than that, you can be as standalone as you like. 

-- 
Harald K
