### ISSUE TITLE
TIFF with PHOTOMETRIC_WHITE_IS_ZERO and ICC Profile is inverted

### ISSUE THREAD

**Issue by Schmidor** [haraldk/TwelveMonkeys#455]
The TIFF uses CCITT Compression with PHOTOMETRIC_WHITE_IS_ZERO and a ICC profile.
Since the changes in  https://github.com/haraldk/TwelveMonkeys/commit/dd914444c9f526afc1f85cca3edb0fc13479e53e#diff-6b756dc8ec79c1721a23075308fae210 it is displayed inverted.
I'm not sure whether we must invert the data as before the changes or whether 
other readers are just ignoring the color profile.

[00002426622018.zip](https://github.com/haraldk/TwelveMonkeys/files/2604268/00002426622018.zip)

**Comment by haraldk** [comment]
Thanks Oliver,

I'll look into it! Very possible that the change caused it, as it takes the color profile into account in the first `if` and not the second... :-/

Though, I really wonder what kind of software/hardware would need a color profile to display discrete black/white samples..? :-P
Perhaps just ignoring the profile would be good enough for this case. 


Best regards,

-- 
Harald K

**Comment by Schmidor** [comment]
Hi Harald,

fortunately our evildoer has written himself to the software-tag: A PDF library, probably used as a converter.
I suppose the profile is just wrong and it wasn't noticed in the older version, as after data inversion it matched to the profile.

Best regards,
Oliver

**Comment by haraldk** [comment]
Just realised I committed the warning as part of another fix...
