### ISSUE TITLE
javax.imageio.IIOException: "Bogus marker length" when reading malformed JPEG image

### ISSUE THREAD

**Issue by davidekholm** [haraldk/TwelveMonkeys#462]
This image produces a javax.imageio.IIOException: Bogus marker length" error when being read:
http://www.ddkonline.com/Gallery/2018_06_07_08_June/20180609_165051.jpg

**Comment by haraldk** [comment]
Hi David,

I believe this is another one of those Samsung panoramic "JPEG"s, see #428.

-- 
Harald K

**Comment by davidekholm** [comment]
Ok. Thanks.
/DE
