### ISSUE TITLE
Tests that don't test any TwelveMonkey's code (that don't compile in the latest java versions)?

### ISSUE THREAD

**Issue by jimfcarroll** [haraldk/TwelveMonkeys#464]
java.util.Collection.toArray is now overloaded with another single parameter `toArray` method (I think since Java 8) and it's now ambiguous to call:

```
        collection.toArray(null);
```

like you do here: https://github.com/haraldk/TwelveMonkeys/blob/master/common/common-lang/src/test/java/com/twelvemonkeys/util/CollectionAbstractTest.java#L1139

The bigger question, however, is why do you have 1000's of lines of test code to test builtin java runtime classes?

**Comment by haraldk** [comment]
Hi Jim,

This is not thousands of lines of code to test Java library classes. It's abstract tests for testing my own implementations of `Collection`, `List` `Set` etc. But it may be that this is currently dead code, and doesn't really do anything as of now. Feel free to dig into that, and propose a PR! 

The project uses `source`/`target` 1.7 (as in the Maven POMs), and I don't have any plans to support *building* with `source`/`target` 1.8 especially. But if we can get rid of the code, that's only good I guess. The current version should be 100% compatible and support being built JDK 8 and run on a Java 8 runtime though.

The next major release will support (and probably require) Java 11. I am at the same time working on restructuring the modules and getting rid of lots of unused classes like the one you mentioned. Unfortunately, things take time...


Best regards,

-- 
Harald K

**Comment by jimfcarroll** [comment]
Thanks. I just loaded your pom file with the source and target set to 1.7 but with a JRE 11 and got that single error. I took a quick look and it appeared that all of the tests in that test class were against java.util.* classes but now I see I was wrong and most are testing your `CollectionUtils`. I have a PR I'll submit momentarily.
