### ISSUE TITLE
Unable to load JPG images due to "Unsupported JPEG process: SOF type 0xcb"

### ISSUE THREAD

**Issue by sgoeschl** [haraldk/TwelveMonkeys#47]
Before starting the bug report - you also save my day :-)

For a few images I get the error message

> Unsupported JPEG process: SOF type 0xcb

```
[ERROR] [2014.03.26 09:53:49]  Loading the image failed  : /iad/styria/prod/htdocs/uploads/20140301_123857_2363439246058001517.jpg [Environment: Host: "www.willhaben.at" Action: "swfuploadimage" Action Class name: "null" Sequence #: "135192664" Referer: "null" URL: "/swfuploadimage" RemoteIP: "212.152.181.235" User-Agent: "Shockwave Flash" jsessionid=3AD5B5AC
CAC4F054C1F1EEA4FE891D51&email=eidi@live.at]  at no.finntech.base.modules.scale.ScaleJavaOnly.createImageFromImageFile(ScaleJavaOnly.java:282)
javax.imageio.IIOException: Unsupported JPEG process: SOF type 0xcb
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImage(Native Method)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1231)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1034)
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
        at javax.imageio.ImageIO.read(ImageIO.java:1448)
        at javax.imageio.ImageIO.read(ImageIO.java:1308)
```

Not an expert but 
- it might stem from an unsupported compression type "Lossless (sequential arith)" 
- it might not stem at all from your library 

I attached the offending image

Cheers,

Siegfried Goeschl

![test-image-broken-01](https://f.cloud.github.com/assets/204576/2527674/8b903904-b507-11e3-8498-fb7e845aa88c.jpg)

**Comment by gouessej** [comment]
Hi

Sven Gothel wrote a JPEG decoder, he ported it from Javascript, you can find it in JOGL:
https://github.com/sgothel/jogl/blob/master/src/jogl/classes/jogamp/opengl/util/jpeg/JPEGDecoder.java
https://github.com/sgothel/jogl/blob/master/src/jogl/classes/com/jogamp/opengl/util/texture/spi/JPEGImage.java

**Comment by KoenDG** [comment]
I see this old issue is still open. Just going to mention that with the code from this issue: https://github.com/haraldk/TwelveMonkeys/issues/197

The exception is logged and the image is processed properly.

**Comment by haraldk** [comment]
@KoenDG Thanks for looking into this and taking the time to test! 😀

Perhaps we should add the code from #197 to the documentation on the home page?


Best regards,

-- 
Harald K

**Comment by KoenDG** [comment]
> 
> 
> @KoenDG Thanks for looking into this and taking the time to test! 😀
> 
> Perhaps we should add the code from #197 to the documentation on the home page?
> 
> Best regards,
> 
> --
> Harald K

Sounds like a good idea. Though I'm not super familiar with the code and the internals of image processing. I'm going to assume this is good for all formats, save perhaps SVG or others that more heavily rely on "extra syntax" if that makes sense?
