### ISSUE TITLE
Difficulty creating a standalone executable JAR, containing all dependencies and automatic resource discovery. 

### ISSUE THREAD

**Issue by mattanaw** [haraldk/TwelveMonkeys#470]
I'm working on a simple java project that includes use of the PSD plugin. Following the instructions, I can execute correctly in IntelliJ and Eclipse, with the following JARs in the classpath:

src/main/resources/common-io-3.4.jar
src/main/resources/common-lang-3.4.jar
src/main/resources/common-image-3.4.jar
src/main/resources/imageio-core-3.4.jar
src/main/resources/imageio-metadata-3.4.jar
src/main/resources/imageio-psd-3.4.jar

However, when attempting to build an executable JAR, I'm having difficulty making sure these JARs are discovered.

Following this stackoverflow thread, I opted for the maven shade plugin (Since Eclipse and intelliJ are unable to include these resources correctly within the JAR, despite proper execution in the workspace):

https://stackoverflow.com/questions/32633759/twelvemonkeys-3-1-1-3-1-2-not-working-with-maven-dependency-plugin

I was wondering, if it would be possible, to include a sample use of the maven shade plugin, that would both include all the proper dependencies in the jar, and have the correct settings for discovery of the resources. Since this appears to be a repeat question, it may be worthwhile to provide a sample pom.xml entry, that will correspond to the recommendation to use the maven shade plugin.

Right now, I have the JAR with the dependencies inside it, but I rely on ManifestTransformer to write classpath entries, that for some reason only point to my src/main/resources directory, outside the JAR, and not inside it. I'm under the impression that the classpath entries may not be necessary if I'm using the shade plugin, but I'm not quite sure how to configure it correctly from the apache documentation (this documentation seems incomplete).

Many thanks for any assistance you can provide, and thank you for putting together this very useful library.

**Comment by haraldk** [comment]
Hi,

If I understand your problem correctly, you really should *only* use the transformer linked in the StackOverflow answer, the [ServicesResourceTransformer](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer). There's a sample configuration there. You should not need a ManifestTransformer, but I may be wrong. 

Regarding documentation, I might add it at some point. However, there are so many ways to include the library into an application, and each is specific to the way the application is deployed or the tool used for bundling. 


-- 
Harald K
