### ISSUE TITLE
Indexed TIFF with alpha from EPS loads incorrectly

### ISSUE THREAD

**Issue by cgscolin** [haraldk/TwelveMonkeys#473]
Hi,

I'm attempting to load a TIFF image that is the embedded preview from an Encapsulated PostScript file with version 3.4.1 of your plugin however it does not seem to be loading correctly. The TIFF is indexed and has alpha transparency. I've attached a ZIP containing the original TIFF data and a PNG file generated by ImageIO.write().

Thanks

[TIFF Sample.zip](https://github.com/haraldk/TwelveMonkeys/files/2829542/TIFF.Sample.zip)

**Comment by haraldk** [comment]
Hi Colin,

Your TIFF preview has a color map (indexed color model) and extra samples that are *not* transparency according to TIFF spec (ie. `ExtraSamples` tag is 0 or "unspecified"). This configuration is currently not supported, and as the extra samples are interleaved with the indexed values, the output becomes trashed. If `ExtraSamples` was either 1 or 2 ("associated" or "unassociated" alpha), it would have worked.

I see that Preview on Mac at least does treat this as transparency, but I don't think it's correct. If I treat the unspecified extra samples as alpha, it looks the same as in Preview. I'll look into it!


Best regards,

-- 
Harald K

**Comment by cgscolin** [comment]
Interesting! For what it's worth the EPS in question was created by CorelDRAW and a number of image programs are able to read it correctly (IrfanView and GIMP for example). Perhaps this particular broken TIFF format is something that an ancient graphics program produced and instead of fixing said program everyone just accepted the broken files haha.

Anyway, thanks for looking into it!

**Comment by haraldk** [comment]
Thanks,

To be clear, I don't think this particular TIFF is broken, it's my reader that is at fault here. :-)
It's just a quite odd combination of indexed color and unspecified extra samples, that I have never come across before. 

On Windows it's displayed on a white background, which I think is more correct than the MacOS Preview app. Out of curiosity, what does it look like in IrfanView or GIMP?


Best regards,

-- 
Harald K

**Comment by cgscolin** [comment]
I just double checked and GIMP loads the image with the alpha channel applied but IrfanView loads the image without applying the alpha channel however it is available in the channel list. I also just loaded it in Photoshop and Photoshop loads the alpha as a separate channel which is not applied by default.

That said, just to elaborate a bit, my use case here is a piece of printing layout software that loads EPS files and uses the embedded TIFF previews to visually represent said files and sometimes they have transparencies such as these. The old Sun JAI ImageIO supports the alpha channel but would load them as greyscale for some mysterious reason so I was excited to discover your project loaded them in color despite the whole not handling the alpha channel thing :)
