### ISSUE TITLE
Exception creating TIFF multi-images larger than 2 GB

### ISSUE THREAD

**Issue by davidOua** [haraldk/TwelveMonkeys#475]
Hi,
I have an exception when a TIFF file in writing get to 2 GB. Bearing, it seems to me that the standard tiff allows to have files of 4 GB maximum.

I do not know if it's important, but I'm trying to create a multi-image file.

I used the 3.4.1 version and I had the problem with previous versions.

Thanks in advance.

DO

````
java.lang.UnsupportedOperationException: Method guessType not implemented for type class java.lang.Long
     at com.twelvemonkeys.imageio.metadata.tiff.TIFFEntry.guessType(TIFFEntry.java:389)
     at com.twelvemonkeys.imageio.metadata.tiff.TIFFEntry.<init>(TIFFEntry.java:64)
     at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter.writePage(TIFFImageWriter.java:372)
     at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter.writeToSequence(TIFFImageWriter.java:950)
````

**Comment by haraldk** [comment]
Hi David,

I'm not familiar with 2Go, what it is or what it does. 

Anyway, can you please update the issue with the code to reproduce the issue, and any input files needed?

It may be that the file you are trying to write is becoming too large for a TIFF. It may also be a bug that limits the current implementation to write a 2 GB file.


Best regards, 

-- 
Harald K

**Comment by ankon** [comment]
"Go" seems to be a common way to specify file sizes in French: https://fr.wikipedia.org/wiki/Octet#Multiples_normalis%C3%A9s ... :)

**Comment by haraldk** [comment]
Thanks @ankon,

Feeling stupid now. Even though I learned something new... 😉

.k

**Comment by haraldk** [comment]
Ok,

I think I have found the culprit. 

The `TIFFImageWriter` contains the lines:

````java
    entries.put(TIFF.TAG_STRIP_OFFSETS, new TIFFEntry(TIFF.TAG_STRIP_OFFSETS, stripOffset));
    entries.put(TIFF.TAG_STRIP_BYTE_COUNTS, new TIFFEntry(TIFF.TAG_STRIP_BYTE_COUNTS, stripByteCount));
````
This will write the strip offsets and byte counts, mapping the Java `long` to suitable a TIFF type, which is TIFF LONG (unsigned 32 bit). But only if the value is less than `Integer.MAX_VALUE`.  Otherwise it gives up.... The code in `guessType` which maps these types, is a bit naive. However, there's really no need to guess here, as these values should always be written as TIFF LONGs. So, we can instead use:

````java
    entries.put(TIFF.TAG_STRIP_OFFSETS, new TIFFEntry(TIFF.TAG_STRIP_OFFSETS, TIFF.TYPE_LONG, stripOffset));
    entries.put(TIFF.TAG_STRIP_BYTE_COUNTS, new TIFFEntry(TIFF.TAG_STRIP_BYTE_COUNTS, TIFF.TYPE_LONG, stripByteCount));
````

...and have instant 4 GB support. :-)


-- 
Harald K

**Comment by davidOua** [comment]
Hi Harald,

I just tested your solution ... And it works perfectly !! (a file larger than 3 GB (3Go in french ;-))

Thank you very much and good day !

DO
