### ISSUE TITLE
Incompatibility with Batik / FOP / <fo:instream-foreign-object> ???

### ISSUE THREAD

**Issue by s0m3body** [haraldk/TwelveMonkeys#476]
I have a project using FOP / Batik / ImageIO libraries. Yesterday I updated to latest available versions _(FOP 2.3, Batik 1.11, ImageIO 3.4.1)_, and run into an issue.

Exception:

[exception.txt](https://github.com/haraldk/TwelveMonkeys/files/2876381/exception.txt)

My *.fo file contains <fo:instream-foreign-object> with an embedded SVG image.

The issue is caused by the fact, that ImageInfo object which gets created during parsing of *.fo file,  <fo:instream-foreign-object> tag, has URI set to null.

This ImageInfo object is created by FOP, but only when TwelweMonkey's ImageIO library is used. It is created by org.apache.fop.render.intermediate.AbstractIFPainter class:

    protected void drawImageUsingDocument(final Document doc,
            final Rectangle rect) {
        final ImageManager manager = getFopFactory().getImageManager();
        ImageInfo info = null;
        try {
            info = manager.preloadImage(null, new DOMSource(doc));

This fails later on in FOP's InternalResourceResolver, which contains code:

    public Resource getResource(String stringUri) throws IOException, URISyntaxException {
        if (stringUri.startsWith("data:")) {
            return new Resource(resolveDataURI(stringUri));
        }
        return getResource(cleanURI(stringUri));
    }

Obviously, stringUri being null, NPE is the outcome.

Why I am posting this also in TwelveMonkey is the fact, that if I remove imageio/imageio-batik-3.4.1.jar from the classpath, so ImageIO is not used by Batik / FOP, it uses xmlgraphics-commons instead, and everything works.

To me it looks like TwelveMonkey's ImageIO is not compatible with recent FOP / Batik / <fo:instream-foreign-object>...

Any idea why?

**Comment by haraldk** [comment]
Hi,

I have looked into this a little bit. I don't use FOP myself, so I'm only scratching the surface here, but the only thing I can think of, is that the *dependencies* of TwelveMonkeys ImageIO and FOP (i.e. the version of Batik or XML Graphics Commons) are incompatible. 

The supported version of Batik (the one declared in the `imageio-batik` POM) is 1.9. The supported version XML Graphics Commons is 2.2. These were the most recent version available at the time of 3.4 release I think. I don't see any reason why it shouldn't work with a more recent version, but I don't have the time or resources to test. Feel free to do so, and optionally provide a PR with the updated versions and any needed code changes. :-)

Other than that, there's nothing in the stack trace or otherwise that indicates any TwelveMonkeys code is directly involved here, so it's hard to see any way I can fix it...


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
See also: https://issues.apache.org/jira/browse/FOP-2842?jql=project%20%3D%20FOP

**Comment by s0m3body** [comment]
Yes, I wrote that one :-).

Anyway, in the meantime I found a workaround (for my particular use case), even though I still cannot say where's the problem.

In general, FOP, since version 2.x, has a problem working with relative / missing URIs. Already the fact, that FOP creates ImageInfo object with uri=null seems quite inconsistent to me, as its own InternalResourceResolve throws NPE for such URI - and it is being called for it!

The fact, that not even relative URIs are supported is especially painful if the application is deployed as JAR file.

Anyway as to my workaround - I disabled ImageIO's manifest to prevent it from registering with FOP. This way I can still use ImageIO where I need it, but I have no conflict with FOP. I actually had to disable xmlgraphics commons' manifest as well. This leaves straight Batik for SVG, and it works for SVGs emebdded in *.fo through an instream tag.

My guess is, that there are several ways how FOP handles images, and not all image libraries support all of them. So the fact that I cannot use instream-embedded SVGs via ImageIO in FOP is either a bug in FOP, or simply a missing support for some new (2.x) FOP mechanism how the images are handled (in ImageIO).

As I do not feel I can contribute to a resolution any further, I am closing the issue for now.

**Comment by s0m3body** [comment]
I closed on github with comment.

Thanks for your help!

Regards,

Martin

**Comment by haraldk** [comment]
Ok, 

Thanks for reporting back!

I understood the FOP issue was created by you, I just like to keep it here, for reference, in case someone else would read this issue. :-)

I'm a little curious to what 

> I disabled ImageIO's manifest to prevent it from registering with FOP

means, though..? Would you like to elaborate on that a bit, in case it helps me or other users in the future? What JAR's manifest did you change, and what changes did you make? :-)


Best regards,

-- 
Harald K

**Comment by s0m3body** [comment]
My fault, I meant META-INF - I stripped it completely from xmlgraphics-commons-2.3.jar and imageio-batik-3.4.1.jar. I.e. I only have classfiles in my classpath which I can use explicitly where I need. Of course, I have no idea what else is broken now - but apparently nothing which my application would rely on.

I *believe*, that this causes FOP not knowing anything about these libraries, or at least some of their components.

Whatever remains there (Batik?) to handle instream-embedded SVGs does the right job :-).

**Comment by haraldk** [comment]
I see..

Well, if you don't read SVGs using ImageIO, there's really no need to include `imageio-batik` on class path at all. Without the `META-INF/services` entries, it won't do much anyway, unless you manually instantiate and use the classes there. Maybe removing this JAR is all it takes to fix the issue?

I see that `xmlgraphics-commons-2.3.jar` (I use 2.2, but they contain the same entries) contains a lot of services too, probably used internally by Apache SVG  stuff, but I don't know what it does. 

Anyway, glad you found a solution! :-)


-- 
Harald K
