### ISSUE TITLE
JFIF woes

### ISSUE THREAD

**Issue by scousegit** [haraldk/TwelveMonkeys#480]
Maybe I am doing something wrong but here goes...
Have the plugins installed. All working fine except for JFIF.

Registered like so:
private static final IIORegistry registry = IIORegistry.getDefaultInstance();
registry.registerServiceProvider(new com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReaderSpi());
registry.registerServiceProvider(new com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderSpi()); 

The image files themselves are what is causing my problems. The files are named "foo.TIF" but they are actually JFIF formarted files. They have been incorrectly named. They should be "foo.JFIF".

IIORegistry fails them as it think sthey are TIF files and TIFFImageReader tries to pick them up as expected since they end in ".TIF"

Renaming them to ".JFIF" and even JPEGImageReade fails to pick them up. If I rename to ".JPG" the plugins work fine but this is not what I want to do. Ideally, I want to pick the file up by parsing its contents and figuring out how to read it rather than its file name extension.

Anyway, I note JPEGProviderInfo does "NOT" include strings for "JFIF". So I suspect this is why I am having problems.

I tried to extend JPEGProviderInfo but it's final so I defined my own class:

final class JFIFProviderInfo extends ReaderWriterProviderInfo {
    JFIFProviderInfo() {
        super(
               JFIFProviderInfo.class,
                new String[] {"JFIF", "jfif"},
                new String[] {"jfif"},
                new String[] {"image/jfif"},
                "com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader",
                new String[] {"com.jft.media.image.imageReaders.JFIFReader.JFIFImageReaderSpi"},
                // ONLY INTERESTED IN THE READER
                null,
                null,
                false, null, null, null, null,
                true, null, null, null, null
        );
    }
}

I tried to implement a JFIFImageReaderSpi using JPEGImageReader but it is protected.

So my luck has run out.

Mac Mojave, Java 1.8.0_151. I don't use maven.

**Comment by haraldk** [comment]
Hi,

It seems you are doing way more work than required... If you have the needed JARs (see the "Manual dependency example" in `README.md`) on class path, all you need to do is `ImageIO.read(file)`, or perhaps something a little more advanced. However, you should not need to be bothered with manually registering plugins, or creating your own SPIs.  

ImageIO `ImageReader` implementations are normally *not* chosen based on file extension, instead they are chosen based on inspecting the contents of the input. If you use `ImageIO.read(file)` the reader is chosen this way. If you know the content of the file, you may explicitly ask for a reader based on format name, mime-type or extension ("suffix"), but this is normally not needed. 

If you need to interact with the `ImageReader`, the recommended way of doing that is:

    try (ImageInputStream input = ImageIO.createImageInputStream(file)) {
        Iterator<ImageReader> readers = ImageIO.getImageReaders(input);
        if (!readers.hasNext()) {
            System.err.println("No reader for " + file); // You probably want to handle this better...
            System.exit(1);
        }

        ImageReader reader = readers.next();
        BufferedImage image = reader.read(
    }

Finally, JFIF is one of the most common file formats often referred to simply as "JPEG" (which is a compression scheme, not really a file format). Another common format is Exif, and others exists too. But in any case, the `JPEGImageReader` should be able to both recognise the format and decode the image. 

It would help if you could provide the code you use to actually read the image, if anything more advanced than `ImageIO.read(file)`. I may also need to see a sample file, if there 


Best regards,

-- 
Harald K

**Comment by scousegit** [comment]
Hi Harald,
Many thanks for your quick response.
Thanks to your suggestions, I have rewritten my code to include your suggestions. And all works great!
Basically, I didn’t fully understand how ImageIO works. I presumed I had to individually register Spi’s for specific formats that java doesn't support.

However, I have come across another problem. This one I think is a bug.
I have a few test “TIF” files. I have attached one that exhibits the problem.
The file is “BIG-ENDIEN” but the header starts with “4949 2A00…….”
It fails in TIFFReader.read() because it starts with “II” and the code sets the the byte order for LITTLE-ENDIEN.
    public Directory read(final ImageInputStream input) throws IOException {
        Validate.notNull(input, "input");

        byte[] bom = new byte[2];
        input.readFully(bom);

        if (bom[0] == 'I' && bom[1] == 'I') {
            input.setByteOrder(ByteOrder.LITTLE_ENDIAN); <<<<<<<<<<<<<<<<<<<
        }
        else if (bom[0] == 'M' && bom[1] == 'M') {
            input.setByteOrder(ByteOrder.BIG_ENDIAN);
        }
        else {
            throw new IIOException(String.format("Invalid TIFF byte order mark '%s', expected: 'II' or 'MM'", StringUtil.decode(bom, 0, bom.length, "ASCII")));
        }

I have hex-dumped a bunch of TIF test files I have and it seems to me that the 1st two bytes should not be depended on despite the spec saying otherwise.
I read the TIF6 spec and it is clear that “II” is LE and “MM is “BE” but then it also states that bytes 2 & 3 is “always” 42 and as you reference in your code
it is in fact sometimes 43, which is not mentioned in the spec at all. However, of the 60 TIF files I have mixed BE and LE, bytes 2 & 3 do always depict
correctly the byte order. If byte 2 is zero then byte 3 is 42 or 43 and it is always LE. Alternatively if byte 2 is 42 or 43 then byte 3 is always zero thus its BE.
But I have seen the bytes 0 & 1 to be II and MM mixed between them incorrectly according to the spec.

I look forward to hearing from you and many thanks for your support
Cheers
Berny

**Comment by haraldk** [comment]
Okay,

Glad it helped!

For the TIFF endianness issue, I'm not really sure if that should be handled... The bytes you are referring to (`II` or `MM`), are the byte order of the TIFF, and there's really no ambiguity about it in the spec as I can see. The values are chosen to match the byte order of popular processors, Intel-processors being little-endian (`II`) and Motorola processors traditionally being big-endian (`MM`). If the writer didn't write these correctly, a lot of software will not treat the files as TIFF (or complain about bad byte order).

That said, I'm very interested to have a sample or two of such a file! Curious about which software or version wrote those...

Perhaps you could just write a small utility that detects files with this problem, and rewrite the byte order correctly? 

The version 43 you see in the code, is to properly handle BigTIFF files. BigTIFF is a proposed (and now de facto) specification for TIFF files larger than the 4 GB limit imposed by the 32 bit offsets in normal TIFF files. As the BigTIFF proposal is more recent than the TIFF 6 specification, it's not mentioned there. You can read more about it in [The BigTIFF File Format](https://www.awaresystems.be/imaging/tiff/bigtiff.html) or [BigTIFF Design](http://www.simplesystems.org/libtiff/bigtiffdesign.html).


Best regards,

-- 
Harald K

**Comment by scousegit** [comment]
Hi harald 
I sent some files to yu but the email bounced as content too big. Sheesh only about 5mb. Anyway I'll pop them on my Dropbox and send yu a link.
Cheers
Berny

**Comment by haraldk** [comment]
@scousegit Perhaps you can just attach the images to the issue tracker? But yes, sending a Dropbox link will work as well.

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now. Will reopen, if I get the files to investigate.
