### ISSUE TITLE
"javax.imageio.IIOException: No SOF segment in stream" for a JPEG image

### ISSUE THREAD

**Issue by rigeborod** [haraldk/TwelveMonkeys#481]
Here's a sample jpg image:
![example](https://user-images.githubusercontent.com/11740579/55168783-85924780-5184-11e9-8c69-e1c2dc9e788c.jpg)

Probably it's related to #407. And it's not a png, like in #278.

**Comment by haraldk** [comment]
Thanks for reporting!

Your sample file is... interesting. Do you know what software that created it? Or the origin of the file? 

It contains an unknown JPEG marker `FF9E` (not `FFE9`). I'm not sure what it is... It does not display correctly in Chrome, on either MacOS or Windows, neither does it display in standard Windows tools. It does display in Safari and MacOS preview though... 

It seems a little like this file is artificially crafted, perhaps to test JPEG software, but that's just a guess. 


Best regards,

-- 
Harald K

**Comment by rigeborod** [comment]
@haraldk I don't think this file was artificially crafted. Company I'm working for is developing a b2b solution, that involves our clients to upload their images to display in the app. This particular image contains jeans' texture. Also when I open it in a text editor, it contains this: "Canon EOS 5D Mark IIIАЖ-'АЖ-'Adobe Photoshop CC 2015.5 (Macintosh)2016:10:06 18:55:38". So I assume this jpg was originally produced by Canon EOS 5D and then edited in the Adobe Photoshop CC 2015.5. I don't know of any other alterations to the file and cannot think of any reason for it.

**Comment by OlafGreve** [comment]
The same exception is thrown by loading one of the following TIF-Documents in the archive:  
[KyoceraM2635dn.zip](https://github.com/haraldk/TwelveMonkeys/files/3030044/KyoceraM2635dn.zip)

These Documents are produced by the Kyocera M2635dn multi function printer, when scanning into a network folder. They aren't handcrafted ;-)

Best regards from Kiel
Olaf G

**Comment by haraldk** [comment]
Thanks @OlafGreve,

I don't see the same exception with any of the files you mentioned though, they all read fine using the latest master. I think this is not related. 

-- 
Harald K

**Comment by haraldk** [comment]
@rigeborod It is just a hunch I got, after manually inspecting the file. I have no hard evidence of the file being crafted. However, I do find that (perfectly well formed, but unknown) `0xFF9E` marker very strange. It does seem to contain multiple SOSs (also well formed) and compressed data. It's this marker segment that breaks the `JPEGImageReader` in this specific case (because it encounters the SOS markers inside the unknown tag before the "real" SOF and SOS markers). 

I haven't found any documentation on this `0xFF9E` marker, even through extensive googling, so I'm a little reluctant to add support for it... 


-- 
Harald K

**Comment by rigeborod** [comment]
@haraldk what if one particular jpeg implementation (in PS CC 2015.5 for Mac) there's a typo in the code: FF9E instead of FFE9. Will it repair the jpg it is changed back from FF9E to FFE9? Also I will fetch some other files with the same error for you to confirm they have the same error.

**Comment by rigeborod** [comment]
Checked logs again. Looks like it is the only file I have with this exact problem.

**Comment by OlafGreve** [comment]
@haraldk 
> I don't see the same exception with any of the files you mentioned though, they all read fine using the latest master. None of those files contains unknown marker segments in the embedded JPEG streams. I think this is not related.

You're right. Our problem was using the tiff reader from com.github.jaiimageio in combination with your jpeg reader. After switching to the right tiff reader (TwelveMonkeys) everything is working fine.

Thanks!

Olaf G

**Comment by haraldk** [comment]
> Checked logs again. Looks like it is the only file I have with this exact problem.

Thanks for reporting back!

I really don't think it's worth adding special handling for reading a single image that we don't really know the source of. If you need to read this file, you can strip out the `0xFF9E` segment, and it will work fine. 

If this problem starts occurring more frequent (ie. a known bug in Adobe Photoshop CC or similar), we might add a workaround for it at some point.

I plan to close this issue for now.


Best regards,

-- 
Harald K
