### ISSUE TITLE
ArrayIndexOutOfBoundsException in getEmbeddedICCProfile

### ISSUE THREAD

**Issue by akultomar17** [haraldk/TwelveMonkeys#488]
```
Exception java.lang.ArrayIndexOutOfBoundsException: 14 occurred with cause: null

and stack trace: 
com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader(JPEGImageReader.java:646) intFromBigEndian
com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader(JPEGImageReader.java:959) getEmbeddedICCProfile
com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader(JPEGImageReader.java:332) read
javax.imageio.ImageIO(ImageIO.java:1448) read
javax.imageio.ImageIO(ImageIO.java:1308) read
```

**Comment by akultomar17** [comment]
I'm trying to read this image: https://drive.google.com/file/d/1QRPVD_16VOEA3_6J359bXfbOYi6AZJKI/view?usp=sharing

**Comment by haraldk** [comment]
Thanks for reporting!

The JPEG contains a bogus `APP2/ICC_PROFILE` segment, that contains no ICC profile... But I agree, the reader should just ignore it and read the image regardless.

I've created a fix, but I need to write a test case and clean it up. Hope to push it soon.


Best regards,

-- 
Harald K

**Comment by akultomar17** [comment]
@haraldk thanks for the quick resolution. Please let me know when you push the fix.

**Comment by haraldk** [comment]
Sorry about the delay. Fix is pushed now.

-- 
Harald K
