### ISSUE TITLE
Support reading PSD layer font types

### ISSUE THREAD

**Issue by harvies** [haraldk/TwelveMonkeys#491]

**Comment by haraldk** [comment]
Hi @harvies,

The `PSDImageReader` currently supports reading bitmap layer data. 
It does not read extra layer data, like effects, fonts etc, even if the *format* supports storing such information.


-- 
Harald K

**Comment by harvies** [comment]
Thank you, there is currently this demand, can you give me some help, for example, how to achieve it?

**Comment by haraldk** [comment]
Okay,

Depends on what you mean by "achieve it".. 

If you plan on implementing this yourself, please make yourself familiar with the source code for the `PSDImageReader` and `PSDMetadata`, and have a look at the [Photoshop file format specification](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/). Everything you need should be documented there. 

If you want me or anyone else to implement this feature for you, it's possible to arrange that too. Please contact me using my private email and we can discuss the details.


Best regards,

-- 
Harald K

**Comment by harvies** [comment]
Thank you.

**Comment by harvies** [comment]
What's your email address?

**Comment by haraldk** [comment]
Hi @harvies,

I get this question a lot, so I figured I'll just update my [Profile Page](https://github.com/haraldk). You'll find it there. :-)

Best regards,

-- 
Harald K
