### ISSUE TITLE
ArrayIndexOutOfBoundsException in TIFFImageReader#readStripTileData

### ISSUE THREAD

**Issue by viqueen** [haraldk/TwelveMonkeys#493]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 217 out of bounds for byte[216]
	at java.base/java.lang.System.arraycopy(Native Method)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readStripTileData(TIFFImageReader.java:1874)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1095)
```

**Comment by haraldk** [comment]
Hi Hasnae,

Thanks for reporting!

What version of the library did you use? And can you please share the TIFF file that caused the exception?


Best regards,

-- 
Harald K

**Comment by viqueen** [comment]
Oops sorry for not providing the full context, I was wrapping my head around the code for a bit.
Also Github is not supporting TIFF files because such is life.

We are using version 3.4.1 , and just now upgraded to 3.4.2 which displays the same error , and so does master snapshot

Yes we are setting a custom sampling period (without it I am not hitting the bug btw)
We determine it as follow

```
final ImageReadParam param = imageReader.getDefaultReadParam();
            final int samplingPeriod = resolve(imageReader.getWidth(0), imageReader.getHeight(0));
            param.setSourceSubsampling(samplingPeriod, samplingPeriod, 0, 0);
            final BufferedImage scaledImage = imageReader.read(0, param);
```

```
// this is fake java
resolve(imageWidth, imageHeight) {
dimensions = {
       if (maxHeight > imageHeight && maxWidth > imageWidth) {
            return (imageWidth, imageHeight);
        } else {
            double thumbRatio = (double)maxWidth / (double)maxHeight;
            double imageRatio = (double)imageWidth / (double)imageHeight;
            return thumbRatio < imageRatio 
? (maxWidth, (int)Math.max(1.0D, (double)maxWidth / imageRatio)) 
: ((int)Math.max(1.0D, (double)maxHeight * imageRatio), maxHeight);
        }
}
return (int) Math.round((imageWidth / (double) dimensions.getWidth()));
}
```

**Comment by viqueen** [comment]
Using the following file http://www.fileformat.info/format/tiff/sample/592c6ebdafc349a2b03d40be86fd6484/download

with the settings : maxWidth=300 , maxHeight=300

**Comment by haraldk** [comment]
Excellent, thanks!

That should be all I need. I'll look into it!

PS: GitHub's file support is a little lame, you can either zip things up, or just rename the file to a supported extension... But linking is fine too. 

-- 
Harald K

**Comment by viqueen** [comment]
Some more info , we started seeing the bug after upgrading from 3.0 to 3.4.1

**Comment by haraldk** [comment]
Sorry,

Got swamped in workshops and meetings all day yesterday... 

But the quick assessment is, it seems you have run into #289:

> There are also issues left with subsampling sub-component (ie. 1, 2, 4 bits/pixel, packed ushort 565/4444 etc) types in the TIFFImageReader.

This is an old bug, which has had low priority, as there hasn't been much need (subsampling "packed" pixels isn't that useful and is more complicated to implement)... 

But I'll look into it. 


-- 
Harald K

**Comment by viqueen** [comment]
Thanks for the update ! and no worries , I can totally relate !

**Comment by haraldk** [comment]
Hi Hasnae,

Finally found some time to implement this yesterday, but I need som time to clean it up, add test cases etc. Will push it soon.

PS: Hope to see you at JavaZone next month. ;-)

-- 
Harald K

**Comment by viqueen** [comment]
Fantastisk !
Jeg vil være på Javazone, vi ses !

**Comment by haraldk** [comment]
Fixed in latest master.
