### ISSUE TITLE
TwelveMonkeys plugins not being found

### ISSUE THREAD

**Issue by richard-nielsen** [haraldk/TwelveMonkeys#494]
After upgrading our TwelveMonkeys ImageIO plugins to 3.4.1 version, I can no longer use them.
I have resorted to progressively more aggressive attempts to get them to load.
```java
public static void scanForPlugins() {
    printJpegPlugins("Initally");
    ImageIO.scanForPlugins();
    printJpegPlugins("After scanForPlugins");
    javax.imageio.spi.IIORegistry.getDefaultInstance().registerServiceProvider(new com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderSpi());
    printJpegPlugins("After registerServiceProvider");
}
    
private static void printJpegPlugins(final String blurb) {
    for(Iterator<ImageReader> iterator = ImageIO.getImageReadersByFormatName("JPEG"); iterator.hasNext();) {
        ImageReaderSpi provider = iterator.next().getOriginatingProvider();
        LOG.info(blurb + "\t" + provider.getVersion() + "\t" + provider.getVendorName() + "\t" + provider.getDescription(Locale.ENGLISH));
           
    }
}
```
This merely result in the following log output
```
INFO Initally       0.5     Oracle Corporation      Standard JPEG Image Reader
INFO After scanForPlugins   0.5     Oracle Corporation      Standard JPEG Image Reader
INFO After registerServiceProvider  0.5     Oracle Corporation      Standard JPEG Image Reader
```
 I expect the following output
```
INFO 3.4.1/0.5        TwelveMonkeys/Oracle Corporation        Standard JPEG Image Reader
```
I would imagine that the scope for things to go wrong between registerServiceProvider and getImageReadersByFormatName should be fairly small. 

Do you have any idea why it's failing to provide the registered twelvemonkeys JPEG image reader?

**Comment by haraldk** [comment]
Hi Richard,

That's odd. 

Are you running this as a standalone application, a web application or something else? What JRE platform/version are you on? 

I tried wrapping your code in a simple `public static void main` and running it as a standalone application, and it printed:

```
Initally        3.4.1/0.5 TwelveMonkeys/Oracle Corporation        Standard JPEG Image Reader
Initally        0.5     Oracle Corporation      Standard JPEG Image Reader
After scanForPlugins    3.4.1/0.5 TwelveMonkeys/Oracle Corporation        Standard JPEG Image Reader
After scanForPlugins    0.5     Oracle Corporation      Standard JPEG Image Reader
After registerServiceProvider   3.4.1/0.5 TwelveMonkeys/Oracle Corporation        Standard JPEG Image Reader
After registerServiceProvider   0.5     Oracle Corporation      Standard JPEG Image Reader

```

Which is what I would expect.

(Using Oracle JRE 1.8.0_171 or OpenJDK 11.0.1, both on Windows)


-- 
Harald K

**Comment by haraldk** [comment]
Have you made any progress with this?

-- 
Harald K

**Comment by richard-nielsen** [comment]
Yes. Sorry for the delay.

Java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
.
The system is running in  JBoss AS 7.1.1.Final "Brontes"

The problem seems to be classloader related. The classloader for com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi is the root classloader and this means that the IIOUtil.lookupProviderByName performed as part of the twelvemonkeys JPEGImageReaderSpi.onRegistration() returns null (as the "delegate"). The ultimate cause is that Class.forName throws an exception if you don't pass null as the classLoader in this case.

If I obtain the sun JPEGImageReaderSpi and use reflection to set is as the "delegateProvider" on the twelvemonkeys JPEGImageReaderSpi then I can successfully add the altered JPEGImageReaderSpi to the IIORegistry.

Unfortunately altering objects using reflection in this fashion is not an acceptable workaround.
I'm preparing some code which showcases the problem.

**Comment by richard-nielsen** [comment]
We appear to have solved the problem - although I will do more comprehensive checks on Monday.
We added <path name="com/sun/imageio/plugins/jpeg"/> to the boss/modules/sun/jdk/main/module.xml file. This exposes the com.sun.imageio.plugins.jpeg package to all applications running in the container.
Would you consider making a change to IOUtils.lookupProviderByName to better avoid this problem? It's odd (and probably not great) that the sun JPEG plugin is listed in the IIORegistry but IOUtils.lookupProviderByName can't find it under certain circumstances. If you are still interested then I will try to reproduce this circumstance in a test case for you in my own time.

**Comment by haraldk** [comment]
Thanks for digging deeper into this!

If you can provide me with a test case (and perhaps even a proposed fix) that would be very useful! Unfortunately, setting up a full JBoss instance, debugging and replicating issues like these are extremely time consuming, and I don't really have the resources to do so. Any help here is appreciated.

Normally, the way class loaders and class resolution in Java work, is the class loader delegate to its parent loader first (all the way up) to find the requested class, and if not the current class loader tries to resolve it itself. But the JBoss class loader doesn't do this, and unfortunately, this is a common problem with application servers, as they try to isolate the container's own libraries, from your application's. 

I think your current solution is perhaps the best (just exposing the package to all applications), as this is the "normal" case. 

Trying to enforce the root class loader is in my mind not a good idea (even though it will work for your case), as you can use the `lookupProviderByName` method to look up other services that are not found by the root loader (i.e loaded by application class loaders).


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Closing this for now.

Assuming others with the same problem can use the solution/workaround found:

> [Add] `<path name="com/sun/imageio/plugins/jpeg"/>` to the `boss/modules/sun/jdk/main/module.xml` file. This exposes the `com.sun.imageio.plugins.jpeg` package to all applications running in the container.

Unfortunately, I don't see a better solution to this issue at the moment.

-- 
Harald K
