### ISSUE TITLE
The link to 3.4.2 under "Latest" only shows 19 of the 3.4.2 .jars

### ISSUE THREAD

**Issue by richard-nielsen** [haraldk/TwelveMonkeys#496]
The following link to https://search.maven.org/search?q=g:com.twelvemonkeys.imageio%20AND%20v:3.4.2 which shows as "3.4.2"in the "Latest" section on the homepage misses out the common dependencies common-lang-3.4.2.jar, common-io-3.4.2.jar and common-image-3.4.2.jar

The list at the bottom of the homepage seems to omit imageio-pdf-3.4.2.jar, imageio-pict-3.4.2.jar and imageio-reference-3.4.2.jar which can be found using the above link.

**Comment by haraldk** [comment]
For me it lists "1 - 20 of 20" (which is all there should be).

The common dependencies has group id `com.twelvemonkeys.common` for now (I'll remove these for 4.0).

The imageio-reference is not useful for anything but testing, and imageio-pdf is just a placeholder for now. But imageio-pict should be included, that's an omission.


-- 
Harald K

**Comment by haraldk** [comment]
Closing for now, feel free to comment/reopen if you still think there are issues or have ideas on how to improve the links section on the page.
