### ISSUE TITLE
jp2 conversion output 0KB

### ISSUE THREAD

**Issue by sarankup** [haraldk/TwelveMonkeys#498]
Hi, This is really awesome to ImageIO drawback. 

At present few of my images are in ".jp2" format. Please advise how to convert them to jpg format.

**Comment by haraldk** [comment]
Hi,

.jp2 file extension usually indicates that the file is in JPEG 2000 format. This format is not supported by this library (as you can see in the readme, there’s no claim that we support it). 

To convert your files, a JPEG 2000 capable plugin is needed. 

Best regards,

— 
Harald K

**Comment by mokun** [comment]
Will you by any chance consider adding jp2 support in future ? Thanks !

**Comment by haraldk** [comment]
Still assuming we are talking about JPEG 2000 format, I had a working fork of the JJ2000 code (the original Java reference implementation) as an ImageIO plugin. However, the code has a non-standard license that I don't understand, and  I have not been able to get in touch with the original authors for a clarification, despite trying for several years... So, it was never released. 

Creating a JPEG 2000 plugin from scratch is of course always a possibility, but it will require either some kind of financing/sponsorship or contribution of working code (I don't have the capacity to develop it in my spare time). Is this something you/your company would be interested in?
