### ISSUE TITLE
No writer found for TGA

### ISSUE THREAD

**Issue by lbalazscs** [haraldk/TwelveMonkeys#499]
I am using the imageio-tga dependency (version 3.4.2)  from Maven. I was able to read tga files, but not to write them. No file is created and ImageIO.write returns false. Here's what I tried (it works if I change the format from "tga" to "png"):

```java
import javax.imageio.ImageIO;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class WriteTest {
    public static void main(String[] args) throws IOException {
        BufferedImage img = createTestImage();

        String format = "tga";

        File file = new File("C:\\Users\\Laci\\Desktop\\out." + format);

        System.out.println("WriteTest::main: writing to " + file);
        boolean writerFound = ImageIO.write(img, format, file);
        System.out.println("WriteTest::main: writerFound = " + writerFound);
    }

    private static BufferedImage createTestImage() {
        BufferedImage img = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = img.createGraphics();
        g2.setColor(Color.RED);
        g2.fillOval(25, 25, 50, 50);
        g2.dispose();
        return img;
    }
}
```

**Comment by haraldk** [comment]
Hi Làszlò,

TGA write support is in the master repo, but not yet released. It will most likely be part of 3.5. 

If you need TGA write support you need to build your own version of the master branch. 

-- 
Harald K

**Comment by lbalazscs** [comment]
Hi Harald,

The github version works fine, but using locally built jars is not an option for me, as I want easily and also automatically (travis) reproducible builds. So I'll wait for a Maven release. 

László
