### ISSUE TITLE
Cannot compile project, tests jar missing from sonar nexus

### ISSUE THREAD

**Issue by KoenDG** [haraldk/TwelveMonkeys#504]
Not sure where else to go with this.

> **Could not resolve dependencies for project com.twelvemonkeys.common:common-io:jar:3.5-SNAPSHOT: Could not find artifact com.twelvemonkeys.common:common-lang:jar:tests:3.5-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)**

How should this be solved?

**Comment by haraldk** [comment]
Hi Koen,

It looks like you are trying to build common/common-io 3.5 from sources without building common/common-lang first. 

The message

 >  Could not find artifact [...]  in sonatype-nexus-snapshots

isn't really that helpful here, as I don't push snapshots to Maven central and 3.5 isn't released yet. 

The easy fix is probably to just do

    mvn clean package 

from the root module to build everything (or `mvn clean install` if you want to be able to build sub modules directly later).


Best regards,

-- 
Harald K

**Comment by KoenDG** [comment]
Yes, package and install does the trick.

Had to skip tests, a test in the JPEG suite seems to fail. But other than that, I can now compile the code and create a project for it in Intellij.

Thanks!
