### ISSUE TITLE
ICOImageWriter not included in released imageio-bmp module 

### ISSUE THREAD

**Issue by lpellegr** [haraldk/TwelveMonkeys#506]
I am a new user of TwelveMonkeys library. While looking at the project readme it is mentioned that ICO write is supported and is included in module `imageio-bmp`. Unfortunately, after adding the following dependencies:

> implementation 'com.twelvemonkeys.imageio:imageio-bmp:3.4.2'
> implementation 'com.twelvemonkeys.imageio:imageio-core:3.4.2'

listing the supported writer format with `ImageIO.getWriterFormatNames()` returns:

> ImageIO.getWriterFormatNames()

No, ICO format included!  

As a consequence, I started looking at the source code. There is indeed a class _ICOImageWriter_ and it's SPI implementation in the current master:

https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-bmp/src/main/java/com/twelvemonkeys/imageio/plugins/bmp/ICOImageWriter.java

Unfortunately, the maven JARs do not include the ICO writer related files for a reason that is still obscured to me. It seems affecting all `imageio-bmp` 3.X versions. Is it a bug? or ICO write is no longer supported?

**Comment by haraldk** [comment]
ICO writing has been experimental, and is only in master for now. It will be released as part of 3.5 some time soon.

Best regards,

--
Harald K

**Comment by haraldk** [comment]
Closing for now, as this will be resolved in the next release.

-- 
Harald K
