### ISSUE TITLE
Can't find the artifacts on Maven Central nor JCenter

### ISSUE THREAD

**Issue by rocboronat** [haraldk/TwelveMonkeys#508]
It seems that Gradle (who works on Maven, by the way) can't find the artifacts on Maven Central nor JCenter.

This is how I declare my dependencies:

```
compile 'com.twelvemonkeys.imageio:imageio-jpeg:3.4.2'
compile 'com.twelvemonkeys.imageio:imageio-png:3.4.2'
compile 'com.twelvemonkeys.imageio:imageio-bmp:3.4.2'
```

But this is what Gradle prints:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.twelvemonkeys.imageio:imageio-png:3.4.2.
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/twelvemonkeys/imageio/imageio-png/3.4.2/imageio-png-3.4.2.pom
         https://repo.maven.apache.org/maven2/com/twelvemonkeys/imageio/imageio-png/3.4.2/imageio-png-3.4.2.jar
         https://jcenter.bintray.com/com/twelvemonkeys/imageio/imageio-png/3.4.2/imageio-png-3.4.2.pom
         https://jcenter.bintray.com/com/twelvemonkeys/imageio/imageio-png/3.4.2/imageio-png-3.4.2.jar
     Required by:
         project :
```

**Comment by haraldk** [comment]
Hi Roc,

The problem is the following dependency in your Gradle project:

> compile 'com.twelvemonkeys.imageio:imageio-png:3.4.2'

There is no TwelveMonkeys PNG plugin (for now, at least). :-)

The PNG format is fully supported by the JDK/JRE as standard. I haven't had a need to create a separate plugin. Do you have any specific problem reading PNG files?


Best regards,

-- 
Harald K

**Comment by rocboronat** [comment]
Hahahaha! Sorry! Thanks for the feedback!

And yes, I'm having some issues with PNG files... Sometimes, they throw `Illegal band size: should be 0 < size <= 8` and others, `Bogus input colorspace`. I'm documenting the experience here: https://github.com/Fewlaps/slim-jpg/blob/1a107333a1aaae81dcaac202456e684ddfeb8376/src/test/java/BuggyPicturesTest.java

**Comment by rocboronat** [comment]
After using your library, `JFIF APP0 must be first marker after SOI` doesn't happen 🎉
