### ISSUE TITLE
PNG Version + Byte Buffer version

### ISSUE THREAD

**Issue by darkyellow** [haraldk/TwelveMonkeys#51]
Hi

I like your project and I intend on using it in my java 3D game engine which is in its early stages, I was wondering if you were going to produce your own version of the PNG loader? I have my own version and speed wise it is 3-4 times faster than the ImageIO reader that comes with Java 

Also do you have any intension of creating a ByteBuffer version of your readers? Ie it loads directly in to a byte buffer and and skips the ImageIO API? This would be for people wanting to load images directly in to a 3D renderer, this might increase speed dramatically.

Thanks

Peter

**Comment by haraldk** [comment]
Implemented `int getCompatibleBufferedImageType(BufferedImage)` in cf323dbc51fffe0a22dd8082b17c7e641d950a7e.

Probably too late, but did so anyway. :-)
