### ISSUE TITLE
Unsupported JPEG process: SOF type 0xc3 for some JPEG file

### ISSUE THREAD

**Issue by leoleozhu** [haraldk/TwelveMonkeys#512]
Thank you very much for your project. It saved me a lot of time in processing images in different formats.

Recently some users' JPEG files are not successfully read. But when I remove the dependency of TwelveMonkeys, the "sun" jpeg reader successfully read those images.

I guess it's a metadata issue since I get a warning `Invalid EXIF text encoding for UserComment` from the output of `exiftool`. Well, some other JPEG file also have that warning, but can be processed on my Macintosh.

I have created a repo which contains a test case for this problem. 
https://github.com/leoleozhu/twelvemonkeys-issues

[The Problem Image](https://github.com/leoleozhu/twelvemonkeys-issues/raw/master/src/test/resources/images/3.jpg)

The output 
```
==== Reading images/1.jpg with class com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader ====
==== Reading images/2.jpg with class com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader ====
==== Reading images/3.jpg with class com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader ====
Error:Unsupported JPEG process: SOF type 0xc3
==== Reading images/4.jpg with class com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader ====
==== Reading images/5.jpg with class com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader ====
==== Reading images/1.jpg with class com.sun.imageio.plugins.jpeg.JPEGImageReader ====
==== Reading images/2.jpg with class com.sun.imageio.plugins.jpeg.JPEGImageReader ====
==== Reading images/3.jpg with class com.sun.imageio.plugins.jpeg.JPEGImageReader ====
==== Reading images/4.jpg with class com.sun.imageio.plugins.jpeg.JPEGImageReader ====
==== Reading images/5.jpg with class com.sun.imageio.plugins.jpeg.JPEGImageReader ====
```

Could you please have a look?

Thanks

**Comment by haraldk** [comment]
Hi Leo,

Did a quick test, and here the TwelveMonkeys and standard plugins could not read 1, 2, and 3, but both displayed 4 and 5...

Using your code, the `com.sun` reader did read all, but the TwelveMonkeys reader choked on image 3, as you say. 

The main difference is that my original code uses `getNumImages(true)` to determine number of images in the file, and tries to decode all of them, in addition to meta data. So it seems that the order of method calls will make a difference.

I'll see if I can make some sense of it... From the initial debugging, it seems that your JPEGs are corrupted somehow, but not more than that they are still decodable.

PS: I doubt the `Invalid EXIF text encoding for UserComment` message is directly linked to this problem.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
I have a feeling this is related to #428 and others.

-- 
Harald K

**Comment by leoleozhu** [comment]
Hi Haraldk,

Thank you for effort on this. 
Yes, my pictures are also taken by Samsung 😳.

I will try your read with fallback solution for now.

--
Leo

**Comment by KoenDG** [comment]
With the code example from this issue: https://github.com/haraldk/TwelveMonkeys/issues/197

The error was caught and the image was processed normally.
