### ISSUE TITLE
Trouble with an "In the Wild" tiff file.

### ISSUE THREAD

**Issue by PhotoKevin** [haraldk/TwelveMonkeys#513]
I'm working on converting some TIF files that were made in the late 90s.  They seem to use CCITT G4 but won't process with anything I've found yet (Image Magick, LibTiff, various viewers).  Your code comes closest and I'm hoping I can work with you to see about  getting things to read.  I'm attaching a small example.

Thanks,
Kevin

[BadImage1.zip](https://github.com/haraldk/TwelveMonkeys/files/4020715/BadImage1.zip)

**Comment by haraldk** [comment]
Hi Kevin,

I'll look into it!

However, if LibTIFF or ImageMagick does not process these images, I'm not sure if it's worth adding support for these images (if they are indeed readable at all)... Anyway, I'll give it a try! :-)


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
The attached image looks kind of like a bad fax transmission...

I'm not sure if it's possible to get back the information that should have been in the missing lines. 

Do you have that software (Cimage Corporation, Imagenation VME) so that you can see if the original software can read it? And do you have more examples that are broken in the same way?


-- 
Harald K

**Comment by PhotoKevin** [comment]
I have the original software (Family Archive Viewer) and it reads them fine.  The background is that this company used to sell CDs with scans of genealogy books.  They no longer support the software that reads them so I'd like to pull out the data I paid for.  I suspect there are many others in the same boat.  The software doesn't have any export option.

I have maybe a thousand of these files.  A dozen or so look fine. The vast majority have this glitch but a few have an error of "Unknown code in Huffman RLE stream"
 
Here's one of the next page.
[BadTiff2.zip](https://github.com/haraldk/TwelveMonkeys/files/4027259/BadTiff2.zip)

Thanks so much for looking into this.

**Comment by haraldk** [comment]
Hi,

I haven't had time to prioritize this, sorry. If anyone's up to the task, I'll gladly accept a PR with a fix for this! But until then, I'll close this issue. 

Best regards,

-- 
Harald K
