### ISSUE TITLE
TIFF: Invalid StripByteCounts when writing large resolution files (9800x8000)

### ISSUE THREAD

**Issue by jmleziva** [haraldk/TwelveMonkeys#514]
Hello, when writing a high resolution tiff file the stripByteCounts appears to be corrupt. An approx 300 mb output file has a single image strip with the byte count of: 4071696385 which is larger than the file itself. 

However when working with lower (more common) resolutions the meta for the image strips is created properly. 

I'm not for sure if I am missing a step or if it is a bug with the library.

This code creates the file with the incorrect meta data:
```
// Input high resolution 48 bit depth
final InputStream inStream = getClass().getClassLoader().getResourceAsStream("9800x8000_resolution_48bit_depth.tif");
final BufferedImage originalImage = ImageIO.read(inStream);
final int width = originalImage.getWidth();
final int height = originalImage.getHeight();

// Modify image (8 bit per channel, ARGB)
final BufferedImage modifiedImage = new BufferedImage(width, height, TYPE_INT_ARGB);
final Graphics2D g = modifiedImage.createGraphics();
g.drawImage(originalImage, 0, 0, width, height, null);
g.dispose();

// Write modified file 
final File convertedTempFile = File.createTempFile("converted_test_image_", ".tiff");
ImageIO.write(modifiedImage, "tiff", convertedTempFile);
```

Attaching zipped image: [9800x8000_resolution_48bit_depth.zip](https://github.com/haraldk/TwelveMonkeys/files/4060292/9800x8000_resolution_48bit_depth.zip)

I've tested and reproduced the issue with the following versions: 3.4.1, 3.4.2, 3.4.3

Thanks in advance,
-Jesse

**Comment by haraldk** [comment]
Hi Jesse,

Thanks for reporting!

It seems you are right.. Unfortunately there's an integer overflow in the computation of the byte count for uncompressed images, on [line 318 of `TIFFImageWriter`](https://github.com/haraldk/TwelveMonkeys/blob/7a9523690c26c2d4e5c13c761f9bbb67ab1dfc6f/imageio/imageio-tiff/src/main/java/com/twelvemonkeys/imageio/plugins/tiff/TIFFImageWriter.java#L318).

You could probably work around the issue by writing compressed (see [example code in readme](https://github.com/haraldk/TwelveMonkeys#advanced-usage) for more details), as the sizes are then computed by looking at the actual bytes written. 

I'll fix this one right away. You may have to wait a little for the new release, but if you can live with a patched version until, feel free to build from source.


Best regards,

-- 
Harald K
