### ISSUE TITLE
TIFFImageMetadata.setFromTree(...) fails on TIFF.TAG_BITS_PER_SAMPLE

### ISSUE THREAD

**Issue by Schmidor** [haraldk/TwelveMonkeys#520]
We're modifying some metadata tags in the tree and merge the changes back via setFromTree.
When the base image uses simple color data it works, but on grayscale or monochrome image types it fails on merging the tree node containing TIFF.TAG_BITS_PER_SAMPLE.
I'm suspecting the latest metadata changes in 3.5, as this is a newer problem not happening in an older 3.5 snapshot i'm using.

```
java.lang.NumberFormatException: For input string: "[S@5cc7c2a6"

	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:658)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageMetadata.getValue(TIFFImageMetadata.java:1252)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageMetadata.toEntry(TIFFImageMetadata.java:1170)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageMetadata.toIFD(TIFFImageMetadata.java:1152)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageMetadata.mergeNativeTree(TIFFImageMetadata.java:1134)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageMetadata.mergeEntries(TIFFImageMetadata.java:953)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageMetadata.setFromTree(TIFFImageMetadata.java:922)
```

```
    @Test
    public void testMergeTree() throws IOException{
        BufferedImage image;
        try(InputStream inputStream = getClass().getResourceAsStream("/tiff/ccitt_tolessrows.tif")){
            image = ImageIO.read(inputStream);
        }

        ImageWriter writer = createImageWriter();
        ImageWriteParam writeParam = writer.getDefaultWriteParam();
        writeParam.setCompressionMode( ImageWriteParam.MODE_EXPLICIT );
        writeParam.setCompressionType("CCITT T.6");

        IIOMetadata metadata = writer.getDefaultImageMetadata( new ImageTypeSpecifier( image ), writeParam );

        IIOMetadataNode tiffTree = ( IIOMetadataNode )metadata.getAsTree( metadata.getNativeMetadataFormatName() );
        metadata.setFromTree( metadata.getNativeMetadataFormatName(), tiffTree );
    }
```

**Comment by haraldk** [comment]
Interesting... 

The input string looks like a `toString` on a String array... Odd that it works for color (which has multiple values), but not for single value?

But anyway, I think your suspicion is correct. I did quite a few changes to the metadata handling, to allow passing a lot more fields through the metadata (from the original)... Might have missed some corner cases that also lacked tests..

Will look into it!


Thanks,

-- 
Harald K

**Comment by haraldk** [comment]
Okay, scratched my head for a while trying to figure out why it worked before, because I use pretty much the same code for setting the `BitsPerSample` value.. 

Turns out the difference is that in 3.5 the value is now present in the metadata returned from `getDefaultImageMetadata`, while in 3.4 and before it was only present in the written file... So, `setFromTree` or `mergeTree` will now handle a lot more values than before.

I'll fix...


-- 
Harald K

**Comment by haraldk** [comment]
I believe that's it.

Fixed in latest master.

-- 
Harald K
