### ISSUE TITLE
Problems writing single-page TIFF

### ISSUE THREAD

**Issue by BenMcLean** [haraldk/TwelveMonkeys#521]
I'm trying to make TIFF 6.0 Group 4 compressed, Little Endian (Intel) byte order single page TIFF images with TwelveMonkeys.

In the TIFF format, the next four bytes after the IFD (where the tags go) are supposed to be zeroes if there is no next page. TwelveMonkeys is putting bytes there which aren't zeroes. The results will work in some TIFF reading software and not in others, depending on how they implement their single-page or multi-page detection. Some software will assume that if those bytes aren't zero, this must be a multi-page TIFF which can cause problems if it isn't a multi-page TIFF.

TwelveMonkeys should please fix this to make those bytes zeroes in single-page TIFFs. Thanks.

**Comment by Schmidor** [comment]
Can you give us a sample code how you are writing those TIFFs and a sample file?

If've checked the TIFFWriter from latest master and the closing IFD pointer is written correctly as zeroes.

**Comment by haraldk** [comment]
Hi Thanks for reporting,

In addition to sample code/file, can you please state the version of the TwelveMonkeys TIFF plugin you use and the Java version it runs on? 

I'm also quite confident the TIFFs output from the latest versions are good, but there may be corner cases...


Best regards,

-- 
Harald K

**Comment by BenMcLean** [comment]
I'm seeing this in twelvemonkeys imageio-tiff 3.4.2

Will hopefully be able to post some code to reproduce the issue soon.

**Comment by haraldk** [comment]
Hi again,

Thanks for responding! I am investigating...

Are you able to disclose what software does recognize the next IFD pointers as non-zero?

I think I may have found an issue in that sometimes the TIFF writer does not write the pointers at word boundaries, and according to the spec they should... This is actually quite a nasty bug... Most software seems to cope though, but we should of course not write such files.

If this is indeed the problem, some software might read the values one byte off, if they enforce word alignment of IFD pointers...


-- 
Harald K

**Comment by BenMcLean** [comment]
If that was the case then it would explain both the behavior I'm seeing, the fact that most software reads the files just fine anyway and the fact that so far, I can't seem to reliably reproduce the issue in unit tests.

**Comment by BenMcLean** [comment]
Ah yes, I got a unit test made which looks like that's it. Start of IFD is not on a word boundary. Can you fix? :)

**Comment by BenMcLean** [comment]
Wait ...

Maybe I'm not great with the math, but what I'm seeing on most single page TIFF images from around the Internet and in single page TIFF images produced by GIMP is that the value 256 (four bytes, being zero, zero, one, zero) is in the spot where I would expect four zeroes to be to indicate no next page. But this isn't the case with a select few single page TIFF images: I have found a few that have four zeroes as expected out there. Any idea what I might be missing?

**Comment by haraldk** [comment]
@BenMcLean Without seeing any of the TIFF files in question, it's hard to say. If you attach one or more such files, we could probably give some more details...

Also, if you managed to create a reliable test to reproduce your issue, are you able to share it? It would help a lot in assuring we actually fix the issue experience.

Best regards,

-- 
Harald K

**Comment by BenMcLean** [comment]
Turns out I was doing the math wrong. Ignore what I said about that 256 value.

I've been working on trying to come up with a good test to reproduce the issue but it's tricky because so far, I haven't managed to find an image I can actually share which triggers the bug. Still investigating.

Here is some Java code I wrote to parse out the offset for the second page:
```java
public static int page2Offset(byte[] tiff) {
    final int ifd = (int) bytes2UInt(tiff[4], tiff[5], tiff[6], tiff[7]);
    return ifd + 2 + (int) bytes2UInt(tiff[ifd], tiff[ifd + 1]) * 12;
}

public static long bytes2UInt(byte... bytes) {
    return (bytes.length > 3 ? byteAsULong(bytes[3]) << 24 : 0) |
            (bytes.length > 2 ? byteAsULong(bytes[2]) << 16 : 0) |
            (bytes.length > 1 ? byteAsULong(bytes[1]) << 8 : 0) |
            (bytes.length > 0 ? byteAsULong(bytes[0]) : 0);
}

public static long byteAsULong(byte b) {
    return ((long) b) & 0x00000000000000FFL;
}
```
Where `tiff` is a byte array of TwelveMonkeys output, I parsed out the value in that spot like this:
```java
final int page2 = page2Offset(tiff);
return bytes2UInt(tiff[page2], tiff[page2 + 1], tiff[page2 + 2], tiff[page2 + 3]);
```
The value at that offset from TwelveMonkeys output of a single-page TIFF is always 0 like it should be. However, the actual offset seems to end up being even or odd more or less at random, and it would need to always be even to be on a 16-bit word boundary as the TIFF spec demands, I believe.

I'm never quite sure I'm doing this sort of thing correctly in Java due to its irritating lack of unsigned data types. Still investigating. I hope to have a good test to reproduce the issue soon.

**Comment by haraldk** [comment]
Closing for now, no feedback for years.
