### ISSUE TITLE
Write TGA with RLE compression.

### ISSUE THREAD

**Issue by nuklx** [haraldk/TwelveMonkeys#532]
Hi,
I can not set the compression for the TGA writer. Writing without compression works.

This works:
```java
ImageIO.write(bufferedImage, “TGA”, outputFile);
```

This does not work:
```java
final ImageWriter writer = ImageIO.getImageWritersByFormatName("TGA").next();
writer.setOutput(ImageIO.createImageOutputStream(outputFile));
final ImageWriteParam writeParam = writer.getDefaultWriteParam();
writeParam.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
writeParam.setCompressionType("RLE");
writer.write(null, new IIOImage(bufferedImage, null, null), writeParam);
```

It throws this exception:
```java
java.lang.UnsupportedOperationException: Compression not supported.
	at javax.imageio.ImageWriteParam.setCompressionMode(ImageWriteParam.java:914)
```

It seems the TGAImageWriteParam class does not set `canWriteCompression = true` ?

**Comment by haraldk** [comment]
Hi @nuklx,

That's correct. It works exactly as intended, compression is not supported and the exception is correct. 😀

I understand you would like it to write using RLE compression though. To do that you would need to set `canWriteCompression = true` AND also add support for it in the `TGAImageWriter` (through an `RLEEncoder`, analogous to the `RLEDecoder` in the same package).

Let me know if this is something you need, maybe we can work out the details.


Best regards,

-- 
Harald K
