### ISSUE TITLE
Add Extra Sample to Tiff Image

### ISSUE THREAD

**Issue by AKMANSoft** [haraldk/TwelveMonkeys#539]
Hi I have two tiff images, one without extra sample another image same width and height and has only extra sample in it, I want to add the extra sample image to first image. I don't know much about Tiff images, and you are expert in that field, your guideness will be helpful. 

Below link is the example. 

[Working with TIFF Extra Channels](https://www.graphicsmill.com/docs/gm/working-with-tiff-extra-channels.htm)

Thank you

**Comment by haraldk** [comment]
Hi,

There's no special functionality in the TIFFImageReader/Writer to merge images into one. Instead, use the reader to read the two images, use standard Java2D to merge them, and then write the TIFF (with alpha channel) using the writer. 

Typically, you create a new image with `BufferedImage.TYPE_INT_ARGB` or `TYPE_4BYTE_ABGR` and then draw the first image into the new image, then copy the second image into the alpha raster. If you have trouble doing this, I suggest you ask a question on StackOverflow or similar, as this is not directly related to the library.

I'm assuming you want to use the extra channel for alpha. If not, the writer should support that too, but you have to create a custom `BufferedImage` with extra samples that are not alpha.

Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now. 

-- 
Harald K
