### ISSUE TITLE
JPEG image identified as RGB instead of CMYK

### ISSUE THREAD

**Issue by rmuller** [haraldk/TwelveMonkeys#545]
After reading this [SO answer](https://stackoverflow.com/a/50852137/868941) i assume TM supports the detection of color space model fr JPEG images conform spec.

However, [this image](http://test.infomas.eu/images/Vitocell_100-W_00019.jpg) returns RGB using

```
int type = bufferedImage.getColorModel().getColorSpace();
```

However, ImageMagick 6.9.7-4 reports 

```
identify -verbose Vitocell_100-W_00019.jpg | grep Colorspace
Colorspace: CMYK
```

So does exiftool 10.80:

```
exiftool Vitocell_100-W_00019.jpg | grep "Color Space Data"
Color Space Data                : CMYK
```

So maybe this is a bug?

Using openjdk version "11.0.7" 2020-04-14 LTS; OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)

**Comment by haraldk** [comment]
Hi Ronald,

No, I don’t think so. You are comparing the color space of the decoded BufferedImage (which in our case is converted to RGB by default), with what is in the JPEG file. If the color space is detected incorrectly, the colors will look all weird. To look at the color space in the file, have a look at the image metadata. 
If you want the BufferedImage in CMYK color, that’s possible using the correct destination type in the ImageReadParam. 

Best regards,

— 
Harald K

**Comment by rmuller** [comment]
Ah, got it ("which in our case is converted to RGB by default"). 

> have a look at the image metadata

Can you give me a hint what the best approach is, using TM?

**Comment by rmuller** [comment]
> have a look at the image metadata

I now use the following code, which returns a valid ImageTypeSpecifier (including color space) for all images i tested, **except** the one i original reported. That one returns `null`. So I assume there is something wrong here.

```` java
ImageInputStream iis = ImageIO.createImageInputStream(is);
ImageReader r = getImageReaders(iis).next();
r.setInput(iis, true);
r.addIIOReadWarningListener((source, warning) -> LOG.warn(warning));
ImageTypeSpecifier rawType = r.getRawImageType(0);
if (rawType == null) {
     System.out.println("No ImageTypeSpecifier!");
 } else {
      System.out.println("Color Space type: " + rawType.getColorModel().getColorSpace().getType());    
 }
 r.dispose();
 iis.close();
````

**Comment by haraldk** [comment]
The "raw" image type is useful in many cases, unfortunately the `JPEGImageReader` (the com.sun... one) do return `null` for any color space that does not have a standard Java representation (like YCbCr, YCCK, etc). I've just kept this convention, and do the same ting. This might have changed in more recent versions of Java 9-10-11-ish, so I might reconsider at some time. But at the moment, this behaviour is intentional. 😀

Use `r.getImageMetadata(0)` instead, use the "standard" metadata format (`"javax_imageio_1.0"`), and get the `"Chroma"` node and its `"ColorSpaceType"` sub node. It should have a `"name"` attribute giving you the correct color space. 


Best regards,

-- 
Harald K

**Comment by rmuller** [comment]
All clear now. And indeed, this works! BTW I use JDK11 and behavior is still as you described :(

In this thread you gave me a lot of (excellent) info that I cannot find anywhere. Is this indeed not documented? Or do i miss something?

**Comment by haraldk** [comment]
Glad it works! 😀

I think the change I referred to is [JDK-8143562](https://bugs.openjdk.java.net/browse/JDK-8143562). The `ImageReader.getRawImageType` API doc is also slightly changed, to include the following:

> "If there is no close match then a type which preserves the most information from the image should be returned."

So, the standard JPEG plugin should return non-null from Java 9. Mine may still return null... 

Is it documented? Probably. Easy to find? Definitively not.. As this is not TM specific behaviour, I haven't bothered documenting it, other than in code or test cases. 

Feel free to submit a PR to the readme.md, describing this, or a fix to return sRGB. 😉 

-- 
Harald K

**Comment by rmuller** [comment]
Thanks, even more clear now!

Thank you very much for all this information.
Before pushing a PR, I need to invest more time in this subject / API. Maybe my notes can be a starting point for a FAQ.
