### ISSUE TITLE
"imageio-batik:3.5" in Gradle didn't load Batik dependencies

### ISSUE THREAD

**Issue by ksilz** [haraldk/TwelveMonkeys#548]
I'm using Gradle 6.5 on OpenJ9 Java 11 for a Spring Boot project. I added `implementation 'com.twelvemonkeys.imageio:imageio-batik:3.5'` in my Gradle file. That did **not** load the Batik dependencies. Instead, I had to add them manually:

````
implementation 'org.apache.xmlgraphics:batik-rasterizer-ext:1.13'
implementation 'org.apache.xmlgraphics:batik-rasterizer-ext:1.13'
implementation 'org.apache.xmlgraphics:batik-anim:1.13'
implementation 'org.apache.xmlgraphics:batik-svggen:1.13'
implementation 'org.apache.xmlgraphics:batik-transcoder:1.13'
implementation 'org.apache.xmlgraphics:xmlgraphics-commons:2.2'
````

I noticed that [the POM](https://search.maven.org/remotecontent?filepath=com/twelvemonkeys/imageio/imageio-batik/3.5/imageio-batik-3.5.pom) references a `${batik.version}`. Do I need to set that somewhere in my Gradle file?

**Comment by haraldk** [comment]
Hi Karsten,

I'm not using Gradle myself, so I'm probably not the best person to answer here, but... 

The `batik.version` variable is defined in my batik plugin's Maven POM, you should not need to set that. It's just there to make it easier for me when upgrading version. It's however a good idea to use the same version, as earlier/later versions may not work  properly (ie. I haven't tested).

I would guess the "issue" is that the batik dependencies in my Maven POM is defined as `<scope>provided</scope>`, to avoid excessive transitive dependencies. This means that the batik JARs are assumed to be available at runtime, provided by 3rd party (ie. you), so I think you are actually doing the right thing adding these in your Gradle file. There might be smarter ways, but as said, I'm no Gradle expert. 😀


Best regards,

-- 
Harald K

**Comment by ksilz** [comment]
Fair enough. I now know that I need to provide this myself.
