### ISSUE TITLE
EOFException for tiff file

### ISSUE THREAD

**Issue by igorlauxen** [haraldk/TwelveMonkeys#549]
I'm trying to process the TIFF file in attach but I receive the following exception: ```java.io.EOFException: Unexpected end of PackBits stream```

The first page gets added to the List<BufferedImage>, but the second page fails with the exception above.

I saw that this error already happened in the past and it was fixed, so I moved from version 3.3.2 to the 3.5 but the issue still happens.

I'm only able to reproduce with this file, if I test against a tiff file with more pages but less content in each of them, the read works normally.

Could you please give me a hand to find out the root cause?
[Untitled.tiff.zip](https://github.com/haraldk/TwelveMonkeys/files/4897040/Untitled.tiff.zip)

let me know if you require more information.

Thanks!
Igor

**Comment by haraldk** [comment]
Hi Igor,

I tried reading your file using both 3.5 and the latest master branch, and both could read your file (all 3 pages) just fine.

I am not able to reproduce your exception. If you want me to look into this, I need you to provide either a standalone program (a single class with a main method) or a failing JUnit test case that shows this behaviour.


Best regards,

-- 
Harald K

**Comment by igorlauxen** [comment]
Hi Harald,

We were able to reproduce this issue in our unit tests as well, but the issue would only appear in the intelliJ or in the Jenkins (what a luck day). If running the project in the mvn command in the cmd, it would work.

We upgraded to the version 3.6 and we were not able to reproduce it anymore!

Thanks for your support!
Igor
