### ISSUE TITLE
Slight color distortion

### ISSUE THREAD

**Issue by TLN2** [haraldk/TwelveMonkeys#551]
Hi,

to start with, I'm amazed about TwelveMonkeys. Awesome job, thanks for sharing all this work with everyone!

**The bug I found:**
I have a file that won't parse or save as intended when using TwelveMonkeys. (Java also doesn't handle it as intended). The bug is that colors between original and saved by TwelveMonkeys are slightly different when displaying the image in Internet browsers (confirmed the bug in Google Chrome and Mozilla Firefox as well as Windows Photo Viewer).

Unfortunately there's a copyright on that file, so I can't share it with everyone here (but I'd be willing to send it to you by mail if wanted). Also, I haven't found a way how to scale down the image (current size is about 5000x1800 pixels) without either already running into or "losing" the bug.

**The following is the demonstration code that I'm using:**

Maven:
```
<dependency>
	<groupId>com.twelvemonkeys.imageio</groupId>
	<artifactId>imageio-jpeg</artifactId>
	<version>3.6</version>
</dependency>
```

Java:
```java
public static void main(String[] args) throws Exception
{
	final File sourceFile=new File(PATH, "dancer.jpg");
	ImageInputStream input=ImageIO.createImageInputStream(sourceFile);
	Iterator<ImageReader> readers=ImageIO.getImageReaders(input);
	System.out.println(readers);
	while (readers.hasNext())
	{
		ImageReader curReader=readers.next();
		input=ImageIO.createImageInputStream(sourceFile);
		System.out.println(curReader);
		curReader.setInput(input);
		BufferedImage sourceBufferedImage=curReader.read(0);

		File destinationFile=new File(PATH, "dancer-"+curReader.getClass().getName()+".jpg");

		try (OutputStream fos=new FileOutputStream(destinationFile))
		{
			ImageIO.write(sourceBufferedImage, "jpg", fos);
		}
	}
}
```

**It prints something like the following:**
javax.imageio.ImageIO$ImageReaderIterator@617c74e5
com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader@61a485d2
com.sun.imageio.plugins.jpeg.JPEGImageReader@86be70a

**It creates two pictures:**
dancer-com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.jpg
dancer-com.sun.imageio.plugins.jpeg.JPEGImageReader.jpg

**To give you a first impression of the problem,** I'm attaching a preview file:
![imageio](https://user-images.githubusercontent.com/14839030/87232928-385ed700-c3c3-11ea-9082-b6ddfa06b935.png)
What you see here is the following:
On the left you see two small samples (small parts of the image) what the original file (dancer.jpg) looks like in Chrome, Firefox, and Windows Photo Viewer.
On the right you see two small samples what files saved by above Java code look like. Both JPEGImageReaders mentioned above seem to give the same result.
Differences seem minor in this sample file, but I promise: This is an optical illusion. If you switch between both pictures in reality, you clearly see that the version saved by ImageIO is darker, less impressive. The sunset has lost part of its power.
Pay attention to the shades of red at the right side of the upper sample, for instance: They're much more vibrant in the original than in the TwelveMonkeys version.

I'm not an expert with color profiles and the like, so I can't pinpoint where the problem is here. Either way, if I just save the file that I read without any modifications, I'd expect that what TwelveMonkeys saves looks the same in major browsers and other image viewing software. Since this is not the case (beyond JPEG artifact phenomena), I'm assuming it's a bug.

To set things in perspective: This bug is not a huge issue for me as long as it appears only with this file, since I can work around it by re-saving the original in an image editing software. I just thought: If you spend so much time developing this tool and offering it for free, the least I can be expected to do is report this to make you aware. I highly appreciate your work. :)

Thanks.

**Comment by TLN2** [comment]
After a few days of contemplating about it I'm starting to suspect something else:
My image editing software reports The original picture is reported to have an ICC profile named "Adobe RGB (1998)" embedded by my image editing software. It seems the color space in that profile is "bigger" than sRGB and my monitors are able to display that color space completely. So when reducing the image to sRGB as a natural consequence some colors get more dull, less vivid. It seems this is what's happening. And it seems when I took the screenshots above, it also reduced everything to sRGB in the process, that's why the difference I'm talking about is not or only barely visible.

Now, if that's so, the question is: Why does opening and saving the image through TwelveMonkeys reduce it to sRGB and how can that be avoided?
I'd share the original picture with your for inspecting the problem. Thanks.

**Comment by haraldk** [comment]
Hi,

Thanks! I’m currently on summer holiday, so not able to look into your issue right away. But will do as soon as possible. 

It’s possible to keep the AdobeRGB profile, but we convert to sRGB as it’s faster for display and many standard imaging operations. 

You need to use ImageReader.getTypes to find a type containing the AdobeRGB profile, then use ImageReadParam.setDestinationType and pass the param to the read methods. You’ll find some examples on StackOverflow or so, but it should be fairly straightforward. 


Best regards,

— 
Harald K

**Comment by haraldk** [comment]
@TLN2 Did you figure out how to open/edit/save your JPEG while preserving the AdobeRGB profile? 

As I said, it should be possible, but as most things Java2D assumes sRGB (`java.awt.Color` has a fixed sRGB color space, the `BufferedImage.getRGB/setRGB` works with sRGB pixel values etc). it's more convenient for mose use cases to convert to sRGB as the default behaviour.  :-)


-- 
Harald K

**Comment by haraldk** [comment]
Closing for now.
