### ISSUE TITLE
Usage in HCL Domino JVM?

### ISSUE THREAD

**Issue by tyrex1975** [haraldk/TwelveMonkeys#552]
Hi there - a little embarrassed to ask for help, but am trying to incorporate TwelveMonkeys into my Java-based image thumbnailer but extensive reading and Googling isn't helping.

The code itself uses a bunch of javax.imageio.* dependencies to resize an incoming image and usually works without issue.

However, more recently I have been trying to retain EXIF information which leads to the occasional runtime error, and it was this post which led me here.
[https://stackoverflow.com/questions/57558484/reading-jpg-metadata-with-javax-imageio-sometimes-throw-jfif-app0-must-be-first](https://stackoverflow.com/questions/57558484/reading-jpg-metadata-with-javax-imageio-sometimes-throw-jfif-app0-must-be-first)

I'm using IBM/HCL Domino 10.0.1 (JVM 1.8) with an Eclipse-based IDE for my Java agent. I've downloaded and included the following JARS into my project:

```
twelvemonkeys-common-lang-3.6.jar
twelvemonkeys-common-io-3.6.jar
twelvemonkeys-common-image-3.6.jar
twelvemonkeys-imageio-core-3.6.jar
twelvemonkeys-imageio-metadata-3.6.jar
twelvemonkeys-imageio-jpeg-3.6.jar
twelvemonkeys-imageio-tiff-3.6.jar
```

[Screenshot of project showing JARS used](https://web.teletrack.biz/teletrack/testclient.nsf/Annotation%202020-07-13%20144925.png?OpenFileResource)

I'm using the 'Installing' section advice from the README, but unfortunately the verification code recommended shows the following message at runtime, which I guess means my project is not picking up the TwelveMonkeys code.

`
13/07/2020 13:16:16   HTTP JVM: reader: com.sun.imageio.plugins.jpeg.JPEGImageReader@64c4bcc0
`

I realise this is highly niche, so not expecting an answer, but was wondering if there was any experience here?

Thank you in advance.

**Comment by haraldk** [comment]
Hi,

Don’t be embarrassed! 😀

I’m currently on summer holiday, so not able to help much.. 

And this is not an environment I’m familiar with... But the HTTP logging output kind of hints at a servlet container or similar... If so, did you read about deploying the plugins in a web app?

Also, just to rule out this being a JVM/JRE issue, try writing a standalone program with a simple main method, printing the registered readers. 


Best regards,

— 
Harald K

**Comment by tyrex1975** [comment]
Thank you Harald, and apologies for interrupting your holiday.

The "HTTP JVM" logging line in my original post is the full printout of registered readers, so definitely not seeing TwelveMonkeys.

I had read the "Deploying the plugins in a web app" documentation without much joy, but decided to read it again and suddenly realised I could give the final recommendation a try.

> Another safe option, is to place the JAR files in the application server's shared or common lib folder.

In Domino, it is not just a case of adding the JARs to the root folder, you also have to modify some INI settings too (and bounce the server).

From HCL Domino help: [Adding java files to the Domino classpath](https://help.hcltechsw.com/dom_designer/9.0.1/user/wpd_programming_ui_java_classpath.html)

These are the settings I added
```
JavaUserClassesExt=common-image,common-io,common-lang,imageio-core,imageio-jpeg,imageio-metadata,imageio-tiff
common-image=C:\notes\data\domino\java\twelvemonkeys\common-image-3.6.jar
common-io=C:\notes\data\domino\java\twelvemonkeys\common-io-3.6.jar
common-lang=C:\notes\data\domino\java\twelvemonkeys\common-lang-3.6.jar
imageio-core=C:\notes\data\domino\java\twelvemonkeys\imageio-core-3.6.jar
imageio-jpeg=C:\notes\data\domino\java\twelvemonkeys\imageio-jpeg-3.6.jar
imageio-metadata=C:\notes\data\domino\java\twelvemonkeys\imageio-metadata-3.6.jar
imageio-tiff=C:\notes\data\domino\java\twelvemonkeys\imageio-tiff-3.6.jar
```

The good news is this has worked! Now let's see if I can get the EXIF retention code to work...

Thank you very much again :-)

**Comment by haraldk** [comment]
Glad you made it work!

Closing this issue for now.

-- 
Harald K
