### ISSUE TITLE
Compressing CMYK images is including cmyk profile embeded

### ISSUE THREAD

**Issue by nizanth** [haraldk/TwelveMonkeys#569]
I am working on a use case where i wanted to compress the image. Unfortunately this is a CMYK profile image and i would like the output to be cmyk with generic profile.

```java
ImageReader reader = readers.next();
imageTypeSpecifier =getImageType(ColorSpace.TYPE_CMYK,reader); // get CMYK type from the reader and sets specifier
image = reader.read(0, param);
ImageWriteParam param = writer.getDefaultWriteParam();
param.setDestinationType(imageTypeSpecifier);
param.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
param.setCompressionQuality(0.5f);  // Change the quality value you prefer
writer.write(new IIOImage(image, null, null));
```

Is there any way i can remove the embeded profile from the final stored image?

**Comment by haraldk** [comment]
Hi,

Writing CMYK JPEGs without an ICC profile is not recommended, as there's no "standard" profile for CMYK like the sRGB profile is for RGB. 

However, if you REALLY wanted to you could create a non-ICC color space implementation (have a look at `com.twelvemonkeys.imageio.color.CMYKColorSpace`, but you don't really need any implementation at all, other than the type and number of components), and create a new `ImageTypeSpecifier` with the same sample model, but new color model. Something like (code from a test case I just created):

```java
imageTypeSpecifier = getImageType(ColorSpace.TYPE_CMYK, reader); // get CMYK type from the reader and sets specifier
readParam.setDestinationType(imageTypeSpecifier);
IIOImage image = reader.readAll(0, readParam); // Could also use normal read(..) I guess, if you don't want the other meta data

// Create non-ICC CMYK color space
ColorSpace fakeCS = mock(ColorSpace.class);  // Could also use new ColorSpace(ColorSpace.TYPE_CMYK, 4) {...}
when(fakeCS.getType()).thenReturn(ColorSpace.TYPE_CMYK);
when(fakeCS.getNumComponents()).thenReturn(4);

// Get rid of the color model/ICC profile
ImageWriteParam writeParam = writer.getDefaultWriteParam();
writeParam.setDestinationType(new ImageTypeSpecifier(new ComponentColorModel(fakeCS, false, false, Transparency.OPAQUE, DataBuffer.TYPE_BYTE), image.getRenderedImage().getSampleModel()));
writer.write(null, image, writeParam);
```


Best regards,

-- 
Harald K

**Comment by nizanth** [comment]
Thank You Harald for your help. This worked.
