### ISSUE TITLE
Reconfigure Maven release process without org.sonatype.oss:oss-parent:9

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#575]
`org.sonatype.oss:oss-parent:9` is deprecated:

> In the past all the plugin configuration and other setup was managed by a Maven parent POM with the latest coordinates of `org.sonatype.oss:oss-parent:9`. This project leaked SCM, URL and other details and its usage is discouraged. Maintenance of the project has stopped and it no longer works with latest tooling such as Maven versions or Java versions. If desired, please manage your own organization-level POM in a similar manner.

See https://central.sonatype.org/pages/apache-maven.html for details.

**Comment by gotson** [comment]
I would be happy to contribute a PR, since i just contributed a [similar one](https://github.com/xerial/sqlite-jdbc/pull/678) on another project, but looking at your POM i couldn't find how you are currently signing releases. I don't see any release profile either that would trigger the signing.

**Comment by haraldk** [comment]
@gotson That would be awesome! 👍🏻 

I don't have automatic releases from CI right now, but that would be a great bonus! 

I believe everything that has to do with releasing and signing is in the `org.sonatype.oss:oss-parent` POM:

```xml
    ...
    <build>
        ...
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>2.1</version>
                    <configuration>
                        <mavenExecutorId>forked-path</mavenExecutorId>
                        <useReleaseProfile>false</useReleaseProfile>
                        <arguments>${arguments} -Psonatype-oss-release</arguments>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    ...

    <profiles>
        <profile>
            <id>sonatype-oss-release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>2.1.2</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>2.7</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>1.1</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
    ...
```

PS: There's also a PR for moving the CI from Travis to GH Actions. I don't expect you to finish that, but just keep It in mind. 😀 


Thank you,

-- 
Harald K

**Comment by gotson** [comment]
Indeed the parent POM contains the signing plugin. I can propose a PR that would perform automatic pushes to OSSRH, which would be done on snapshots repository for `*-SNAPSHOT` versions, and to Maven Central for proper versions. You could keep doing the commits to set the version before a release, and the CI would do the deployment.



> PS: There's also a PR for moving the CI from Travis to GH Actions. I don't expect you to finish that, but just keep It in mind. 😀

I was looking at that also 🙃
