### ISSUE TITLE
Greyscale JPG: Scaled image gets brighter

### ISSUE THREAD

**Issue by FlorianKirmaier** [haraldk/TwelveMonkeys#576]
Hello,

After reading, rescaling, and writing a JPG, the brightness gets changed.
If the rescaling is skipped, the brightness is correct.

This is one of our test-images: https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Broadway_tower_grayscale.jpg/256px-Broadway_tower_grayscale.jpg
(The other we cannot share)

This only seems to happen with the color-model grey.
<img width="740" alt="Screenshot 2020-11-27 at 16 36 43" src="https://user-images.githubusercontent.com/6547435/100464937-bf8cbd00-30ce-11eb-832f-34b88569cfa5.png">

Interestingly, it also happens when Image.getScaledInstance is used.

```
    public static void main(String ... args) throws Exception {
        Iterator<ImageReader> readers = ImageIO.getImageReaders(ImageIO.createImageInputStream(new FileInputStream(new java.io.File("/Users/x1fkirma/test2/original.jpg"))));
        int i = 0;
        while(readers.hasNext()) {
            i += 1;
            ImageReader reader = readers.next();
            System.out.println("Reader: " + reader);
            reader.setInput(ImageIO.createImageInputStream(new FileInputStream(new java.io.File("/Users/x1fkirma/test2/tower.jpg"))));
            BufferedImage input = reader.read(0);

            //twelvemonkey
            BufferedImage result = com.twelvemonkeys.image.ImageUtil.createScaled(input, 875, 583, Image.SCALE_DEFAULT);

            //java.awt.rescale
            //java.awt.Image img = input.getScaledInstance(875, 583, java.awt.Image.SCALE_SMOOTH);
            //BufferedImage result = new BufferedImage(875, 583, input.getType());
            //Graphics2D g2 = result.createGraphics();
            //g2.drawImage(img, 0, 0, null);
            //g2.dispose();


            javax.imageio.ImageIO.write(result, "jpg", new java.io.File("/Users/x1fkirma/test2/scaled_" + i + ".jpg"));
        }
        
    }
```

**Comment by haraldk** [comment]
Hi Florian,

Thanks for your report!

The `ImageUtil.createScaled` method was something I created for internal use ages ago, that does a lot of odd things... So I don't think you should use that... 😉 

Does the same thing happen if you use `ResampleOp` directly?

Anyway I believe this is a known bug in the Java2D libraries, either [5051418](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=5051418) or one of the related bugs. 


Best regards,

-- 
Harald K

**Comment by FlorianKirmaier** [comment]
What should be used instead of ImageUtil.createScaled?
I've tested ResampleOp, and it behaves exactly the same.
```
BufferedImage result = new BufferedImage(875, 583, input.getType());
new ResampleOp(875, 583).filter(input, result);
```
I'm using JDK11 when testing this.
The bug report you've mentioned claims to be fixed with Java9, so theoretical it must be another bug.

**Comment by haraldk** [comment]
The bug is just resolved, not fixed, unfortunately:

> Implementing this  would suddenly change how regular grayscale images draw impacting user functionality so closing this as not to fix.

Anyway, I wrote my own little program, and I don't experience any changes in brightness here (there might be some very small ones due to the resampling, but the curves look very similar to the original). 

```java
public class GrayscaleTest {
    public static void main(String[] args) throws IOException {
        BufferedImage image = ImageIO.read(new File(args[0]));
        System.out.println("image = " + image);

        BufferedImage result = new ResampleOp(875, 583).filter(image, new BufferedImage(875, 583, image.getType()));
        System.out.println("result = " + result);

        if (!ImageIO.write(result, "JPEG", new File("test.jpg"))) {
            System.err.println("Woot: Can't write JPEG: " + result);
        }
    }
}
```

Also, using `null` for the result parameter to `filter` gives the exact same result.

```java
BufferedImage result = new ResampleOp(875, 583).filter(image, null);
```

Here's what I got:

![Broadway_tower_grayscale_resampled_j11](https://user-images.githubusercontent.com/110299/100588072-add72f80-32f1-11eb-866d-ee07bfe2626c.jpg)

--
Harald K

**Comment by FlorianKirmaier** [comment]
You are right, it's my fault. It works properly with ResampleOp. Sorry for the confusion.
I was properly confused because the image already looked "light greyish".
I assume ResampleOp is the method which is also recommended to rescale an image?

**Comment by haraldk** [comment]
Yes, 

I think using `ResampleOp` is better. 😀 

PS: I see that the original input image has an sRGB ICC color profile (which is a little odd for gray data, but I think it's a gray response curve that matches sRGB gamma). The result image does not contain a profile. This means that software that uses color profiles *may* display these images differently. But I think the most common behavior is to treat absence of a profile as sRGB, so they should be the same.


-- 
Harald K

**Comment by FlorianKirmaier** [comment]
@haraldk 
I've looked more into the topic and noticed the behavior depends on the performance hints.
I've found the following cases:
ImageUtil:
```
ImageUtil.createScaled(input, 875, 583, Image.SCALE_DEFAULT); // wrong
ImageUtil.createScaled(input, 875, 583, Image.SCALE_FAST); // correct
```

ResampleOp with the following RenderingHints, and filter is called with the second argument as null:
```
// No settings // correct
map.put(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR); // correct
map.put(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BICUBIC);  // wrong
map.put(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BILINEAR); // wrong
```

ResampleOp seems to work in all cases when the second argument for filter is a pre created BufferedImage, created like the following:
```
BufferedImage result = new BufferedImage(875, 583, input.getType());
```

**Comment by haraldk** [comment]
Yes, this is expected. 

As `ImageUtil.createScaled` (does a lot of odd things and then) delegates to `ImageUtil.createResampled` which in turn delegates to `ResampleOp.filter`. 

The mapping from `Image.SCALE_*` to `ResampleOp.FILTER_*` is as follows:

* `Image.SCALE_FAST` =>  `ResampleOp.FILTER_POINT`
* `Image.SCALE_DEFAULT` =>  `ResampleOp.FILTER_QUADRATIC`

The mapping from ´RendereingHints` to `ResampleOp.FILTER_*` is slightly more complicated, but:

* `RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR` =>  `ResampleOp.FILTER_POINT`
* `RenderingHints.VALUE_INTERPOLATION_BILINEAR` =>  `ResampleOp.FILTER_TRIANGLE`
* `RenderingHints.VALUE_INTERPOLATION_BICUBIC` =>  `ResampleOp.FILTER_QUADRATIC`

There's also specific hints for `ResampleOp` that maps directly to the `ResampleOp.FILTER_*` variants.

In any case, all of the mentioned cases should end up delegating back to `AffineTransformOp`, as it contains the fastest operations (native code, possibly hardware assisted) for these filters. And I'm afraid that's where you run into the mentioned Java bug. For more info, see the source code.

If you instead use the constructor that only takes the dimension parameters (as in my sample), the default filter is currently `FILTER_LACZOS`. Also, pretty much any other filter than point, triangle or quadratic (as in your code) will force a "pure" Java conversion, and should not run into the bug.

If you feel adventurous, you could try removing the delegation to `AffineTransformOp` from `ResampleOp`, and see if that works better for your cases. 


Best regards,

-- 
Harald K
