### ISSUE TITLE
Subsampled reading of some TGA files throws exception

### ISSUE THREAD

**Issue by lbalazscs** [haraldk/TwelveMonkeys#577]
I am using the latest maven version of imageio-tga (3.6.1)
I originally found the issue with the shuttle image that can be found at https://people.math.sc.edu/Burkardt/data/tga/tga.html
Normal reading works fine, the problem is only with the subsampled reading.
Since then I realized that the bug exists even with files written by Twelve Monkeys, see the following code. Perhaps it only depends on the image size?
The following code should reproduce the issue. If the formatName is changed to "png" (so that Java's own PNG reader is used), then it works fine.

```java
import javax.imageio.ImageIO;
import javax.imageio.ImageReadParam;
import javax.imageio.ImageReader;
import javax.imageio.stream.ImageInputStream;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;

public class ReadTGAWithSubsampling {
    public static void main(String[] args) throws IOException {
        String formatName = "tga";

        // create a 640*480 TGA image
        File testFile = new File("test." + formatName);
        BufferedImage testImg = new BufferedImage(640, 480, BufferedImage.TYPE_INT_ARGB);
        ImageIO.write(testImg, formatName, testFile);

        // now read it back with subsampling
        try (ImageInputStream input = ImageIO.createImageInputStream(testFile)) {
            Iterator<ImageReader> readers = ImageIO.getImageReaders(input);

            if (!readers.hasNext()) {
                throw new IllegalArgumentException("No reader for: " + testFile);
            }

            ImageReader reader = readers.next();
            try {
                reader.setInput(input);
                ImageReadParam param = reader.getDefaultReadParam();
                param.setSourceSubsampling(4, 4, 0, 0);
                BufferedImage image = reader.read(0, param);
            }
            finally {
                reader.dispose();
            }
        }
    }
}
```

The exception is:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	at java.desktop/sun.awt.image.ByteInterleavedRaster.setDataElements(ByteInterleavedRaster.java:572)
	at com.twelvemonkeys.imageio.plugins.tga.TGAImageReader.readRowByte(TGAImageReader.java:254)
	at com.twelvemonkeys.imageio.plugins.tga.TGAImageReader.read(TGAImageReader.java:196)

**Comment by haraldk** [comment]
Thanks,

I will look into this as soon as possible! 

-- 
Harald K

**Comment by haraldk** [comment]
Okay,

Turned out to be a bug in the subsampled reading of top/down TGA images (it worked for bottom/up). Good report with test case, thanks!

Plus I fixed some other minor issues with metadata and palette BGR -> RGB conversion while I was at it. 😉

-- 
Harald K
