### ISSUE TITLE
Broken Display of TIFF with CCITT Group 3 Fax Encoding

### ISSUE THREAD

**Issue by GuidoRahn** [haraldk/TwelveMonkeys#579]
We recently updated our application to Java 11. It is a JavaFx application in which Images in various image formats / compressions can be displayed.

There were some problems with the display of images and images in PDF documents (displayed via PDFBox). By updating to the latest available version of the twelvemonkey library 3.6.1, one of our customers encountered a new problem with certain Tiff image files with 'CCITT Group 3 Fax Encoding'.
These Tiff image files are displayed distorted and cut off.

If we go back to our previous used version 3.4.1, the Tiff image files are displayed correctly.

Attached is a sample-Application, which shows how we display images in our application and which also includes an imagefile in the resources-directory. The Image is loaded on Click on the 'Load Image'-Button.
[FaxViewer.zip](https://github.com/haraldk/TwelveMonkeys/files/5733780/FaxViewer.zip)

**Comment by haraldk** [comment]
Hi Guido,

Thanks for reporting! 

I'm unfortunately not able to look at the source code for your JavaFX application. But `resources/sample/Fax.tiff` seems to be show the problem, and I can see the problem right away.

We introduced a way to discover a different set TIFF files that had the encoding set incorrectly, that looks at the CCITT stream to discover the presence of leading EOLs, and if not found, reverts to RLE encoding. Unfortunately, your file is in Group 3/T.4 format, but is still missing the EOLs... So it's decoded "incorrectly". 

These kinds of problems typically occurs with CCITT streams extracted from PDF files and put into TIFF containers without properly re-encoding. So if possible, have a look at the software that created the file, and see if something can be done. But we'll look into it!


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
@Schmidor I'm kind of hoping you have clever fix for this! 😉 Any input is appreciated though. Is leading EOLs required by the spec for G3/T.4?

**Comment by haraldk** [comment]
Okay,

I think actually the check is still good, we just need to test a few more bytes for the EOL code. Changing from 20 to 32 seems to be enough. @Schmidor Can this be done smarter? 

I have a fix soon. 

-- 
Harald K

**Comment by Schmidor** [comment]
@haraldk 
I believe the case for the detection here was, that the leading EOL was missing, but there were EOLs between the lines. Searching a few more bytes shouldn't be a problem. If simply increasing the data helps, it just seems the first line is just longer.

If there are really no EOLs I would assume this is G4/T.6, as this and the missing full-line-RLE Mode are the only difference to G3. But then increasing the array would not work.

The missing first EOL still truncates the first line of the image, as the reader always starts at the first EOL. If we want to change this behaviour, we would have to check if at least the mode-flag is present, or if there is directly either V-data or RLE-data for this line.

@GuidoRahn 
PDFBox uses afaik an (older) version of our CCITT decoder directly for rendering, not via the TM Jars. So I assume you extract the images via PDFBox and your issue occurs, when you try to render the exported TIFFs. Am I right?

**Comment by GuidoRahn** [comment]
The use of PDFBox consists in displaying the PDF pages for a preview. For this purpose, the individual pages of the PDF document are converted into BufferedImages using PDFRenderer::renderImageWithDPI and then further converted into JavaFX ImageViews.
To what extent PDFBox works together with Twelvemonkey is not known to me, but earlier investigations had shown the interaction of PDFBox and twelvemonkeys with lead to display problems of images. The problems could be solved.
In the current case, however, there was no problem with using PDFBox with twelvemonkeys. Sorry if I got it wrong, I just wanted to mention the use of PDF-Box in case it might have an impact here; that was also the case with the earlier problem.
The TIFF document provided in the example application was generated by a FAX-application at one of our users. Which software is used and how the TIFF document is created is unknown.

@haraldk Do you have plans for the next release which contains the fix? Or is the fix not yet complete as the comment from @Schmidor sounds like?

**Comment by haraldk** [comment]
@Schmidor Thanks for your great input! I think the current fix is good enough, but perhaps we should calculate the worst case line length based on the image width, instead of a fixed length? 

We should probably look into the truncation at some point... But this is a border case, so I don't think it's worth spending a lot of time on.

@GuidoRahn I believe the current fix is good, and will include it in the next release. I'm hoping to create a bugfix release soon. If you want a fixed date, that can be arranged too but it will no longer be free of charge. 😀 


Best regards,

-- 
Harald K

**Comment by GuidoRahn** [comment]
@haraldk 
Today I integrated the new version 3.6.2 with the correction. Unfortunately the pictures are not displayed correctly yet.
The entire picture is displayed, but its display height is compressed.
You can reproduce it again with the test application provided at the beginning. For comparison, you can switch between versions 3.6.1 and 3.6.2 in the gradle file.

**Comment by Schmidor** [comment]
@GuidoRahn Your TIFF has asymmetric DPI (204/98). TwelveMonkeys is not rescaling such things.
You need to read TIFF.TAG_X_RESOLUTION and  TIFF.TAG_Y_RESOLUTION to scale it accordingly.

**Comment by haraldk** [comment]
> Unfortunately the pictures are not displayed correctly yet. The entire picture is displayed, but its display height is compressed.

We just *read* the pixels as they are in the file. How you display them is up to you. 😀 

The DPI for TIFF is available in the meta data. 


Leaving this as closed. 

-- 
Harald K
