### ISSUE TITLE
IndexOutOfBoundsException in ImageReader.getImageMetadata(0)

### ISSUE THREAD

**Issue by garretwilson** [haraldk/TwelveMonkeys#587]
As you know from my ongoing saga in #586 I want to scale an image, modify metadata, and write the image to a file using Java Image I/O.

For the time being for certain images I have updated the code to maintain the existing metadata. I just need to do this:

```java
IIOMetadata imageMetadata = imageReader.getImageMetadata(0);
IIOImage iioImage = new IIOImage(newImage, null, imageMetadata);
```

Unbelievably it works well, and Java Image I/O seems to keep all the Exif, IPTC and XMP metadata!

Note that I am assuming that the image I am processing is the first image, image `0`. (This might not work on a JPEG image with no image metadata, but truly that is the last of my worries at the moment.)

Because of this approach I don't even need to use Twelve Monkeys, so had taken it out altogether. I wanted to check one last thing, so I added back Twelve Monkeys 3.6.2 _without changing any of my code_, and I get this:

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readSegments(JPEGImageReader.java:842)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.initHeader(JPEGImageReader.java:693)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.initHeader(JPEGImageReader.java:727)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1229)
```

I have no idea why Twelve Monkeys thinks that there are no images when calling `ImageReader.getImageMetadata(0)`. It was working earlier when I was ignoring metadata altogether (and adding the last `true` argument in `ImageReader.setInput(imageInputStream, true, true)`).

As I mentioned this works fine with pure Java Image I/O; it's only when I add Twelve Monkeys as a dependency that this breaks.

Because I wound up not needing Twelve Monkeys at the moment (and I have to deal with breaking bugs in Apache Commons Imaging such as [IMAGING-281](https://issues.apache.org/jira/browse/IMAGING-281); and in metadata-extractor such as https://github.com/drewnoakes/metadata-extractor/issues/270 ) unfortunately I don't time to investigate this further. Sorry. I hope you understand.

**Comment by haraldk** [comment]
Hi Garret,

Thanks for reporting!

For normal* JPEGs, using `reader.getImageMetadata(0)` should always be safe. If there's an image, there's also meta data. 

However, I'm afraid I can't reproduce the issue you see in any of the test files I use. You'll also find that there are tests that cover similar code to what you have posted. But I am *very* interested to see your full code (or better, a test case) that showcases this exception, as I'm sure it happens for you. I just don't understand how... 

*) The only kind of files where this *should* fail with the exception you see, is a tables-only file (a file containing DHT and DQT segments to initialize the reader for subsequent reading of JPEGs without tables. These are typically not used in normal file interchange, so I agree. Don't worry. 


Best regards,

-- 
Harald K

**Comment by garretwilson** [comment]
> However, I'm afraid I can't reproduce the issue you see in any of the test files I use. You'll also find that there are tests that cover similar code to what you have posted. But I am very interested to see your full code (or better, a test case) that showcases this exception, as I'm sure it happens for you. I just don't understand how...

@haraldk a good checkpoint of the code in question can be found in the [Guise Bitbucket repository](https://bitbucket.org/globalmentor/guise/) in commit [`5525b5acc7aecfd1bba32824f1279cf28d0319dc`](https://bitbucket.org/globalmentor/guise/commits/5525b5acc7aecfd1bba32824f1279cf28d0319dc). The code you want to look at in the `guise-mummy` subproject is `io.guise.mummy.mummify.image.DefaultImageMummifier`. The two methods that process the image are `mummifyFile(…)` and `processImage()`. You'll find the processing logic simple and fully commented.

Unfortunately this project depends on the snapshot versions of a couple of other dependency projects, so you can't just go to the command line and build this with Maven _unless_ you first download those projects as well and do a `mvn install` on them. And unfortunately there are quite a few of them. You can see which ones they are when you try to do a `mvn install` on this project. The other projects are available publicly on Bitbucket as well (and will be available here on GitHub once the new versions are released).

Nevertheless the code in question should be using pure Java Image I/O. The other dependencies relate to other parts of the application. (If you can't reproduce this you may need the original image as well, but as I mentioned I don't have time to put together a full turnkey test case at the moment, especially since I'm not even using Twelve Monkeys so far.)

**Comment by haraldk** [comment]
Okay,

I looked at the source code, downloaded all test files in the commit, and created the following test, trying to mimic the code from `DefaultImageMummifier`, reading all three files, with and without `ignoreMetadata` flag set:

```java
    @Test
    public void testReadGarretsFiles() throws IOException {
        List<TestData> testData = Arrays.asList(
                new TestData(getClassLoaderResource("/jpeg/gate-turret-reduced-xmp.jpg"), new Dimension(972, 648)),
                new TestData(getClassLoaderResource("/jpeg/gate-turret-reduced-exif.jpg"), new Dimension(972, 648)),
                new TestData(getClassLoaderResource("/jpeg/gate-turret-reduced-exif-iptc.jpg"), new Dimension(972, 648)));

        JPEGImageReader reader = createReader();
        ImageReadParam param = reader.getDefaultReadParam();

        try {
            for (TestData test : testData) {
                try (ImageInputStream stream = test.getInputStream()) {
                    reader.setInput(stream, true, false);

                    BufferedImage image = reader.read(0, param);

                    assertNotNull(image);
                    assertEquals(test.getDimension(0).width, image.getWidth());
                    assertEquals(test.getDimension(0).height, image.getHeight());
                }
            }

            for (TestData test : testData) {
                try (ImageInputStream stream = test.getInputStream()) {
                    reader.setInput(stream, true, true);

                    BufferedImage image = reader.read(0, param);

                    assertNotNull(image);
                    assertEquals(test.getDimension(0).width, image.getWidth());
                    assertEquals(test.getDimension(0).height, image.getHeight());
                }
            }
        }
        finally {
            reader.dispose();
        }
    }
```

"Unfortunately" it passes for all six cases, so I'm still unable to reproduce... 

Perhaps the issue is caused by a specific file? If so, can you please attach or link it here? 


Best regards,

-- 
Harald K

**Comment by garretwilson** [comment]
Good morning! It wasn't one of the committed test files. It was a large, multimegabyte source image that was being scaled as part of real-life application for my photography site. Some day maybe I can go look for the image. I would want to say I hope I can find the time, but I don't know how realistic that is or when it would be.

**Comment by haraldk** [comment]
That would be nice! 

I'll follow up when I receive a test file. I don't necessarily need *the original* file, just *a file* that showcases the above exception. 😀 

-- 
Harald K

**Comment by garretwilson** [comment]
@haraldk I sent you the original image via email. I'd rather not post it on GitHub. (It's nothing secret, just a large, full-size version of one of my photography works. I prefer to distribute only the scaled versions, which is part of why I'm going to all the trouble to scale them to begin with.)

Yesterday I generated an entire set of photos with a milestone version of my static site generation with image scaling project. It worked just fine. To reproduce this problem, I merely added the following as a dependency as per your project instructions:

```java
    <dependency>
        <groupId>com.twelvemonkeys.imageio</groupId>
        <artifactId>imageio-jpeg</artifactId>
        <version>3.6.2</version>
    </dependency>
```

Boom, it broke:

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readSegments(JPEGImageReader.java:842)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.initHeader(JPEGImageReader.java:693)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.initHeader(JPEGImageReader.java:727)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1229)
	at io.guise.mummy.mummify.image.DefaultImageMummifier.processImage(DefaultImageMummifier.java:249)
	at io.guise.mummy.mummify.image.DefaultImageMummifier.mummifyFile(DefaultImageMummifier.java:125)
	at io.guise.mummy.mummify.AbstractFileMummifier.mummify(AbstractFileMummifier.java:204)
	at io.guise.mummy.mummify.collection.DirectoryMummifier.mummify(DirectoryMummifier.java:366)
	at io.guise.mummy.mummify.collection.DirectoryMummifier.mummify(DirectoryMummifier.java:366)
	at io.guise.mummy.GuiseMummy.mummify(GuiseMummy.java:314)
	at io.guise.cli.GuiseCli.mummify(GuiseCli.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1872)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
	at picocli.CommandLine.execute(CommandLine.java:1978)
	at com.globalmentor.application.BaseCliApplication.execute(BaseCliApplication.java:213)
	at com.globalmentor.application.AbstractApplication.start(AbstractApplication.java:118)
	at com.globalmentor.application.Application.start(Application.java:133)
	at io.guise.cli.GuiseCli.main(GuiseCli.java:88)
```

This is with commit [`5525b5acc7aecfd1bba32824f1279cf28d0319dc`](https://bitbucket.org/globalmentor/guise/commits/5525b5acc7aecfd1bba32824f1279cf28d0319dc) as indicated above.

**Comment by haraldk** [comment]
Thanks! 

Much appreciated! 

I just realized that your code is different than the test case, in that it is the `getImageMetadata` method that fails. I added it to my test case. Unfortunately, I *still* cannot reproduce. 😕 

-- 
Harald K

**Comment by garretwilson** [comment]
FWIW I'm not running a particular test case, but actually building my site. The only differences as far as this is concerned should be the image parameters. I'm using:

* `mummy.image.scaleMaxLength` = `1920`
* `mummy.image.compressionQuality` = `0.7`

You can see in the image processing code where these are used. I think the code uses the defined defaults, and those should generate the errors, but you can substitute in these values above just to make sure.

**Comment by haraldk** [comment]
Hmmm... 

I do spot a problem in your code though. If this is the cause, you owe me a beer! 😉 

DefaultImageMummifier.java:

[`193`](https://bitbucket.org/globalmentor/guise/src/5525b5acc7aecfd1bba32824f1279cf28d0319dc/mummy/src/main/java/io/guise/mummy/mummify/image/DefaultImageMummifier.java#lines-193)`
 			imageReader.dispose(); //tell the image reader we don't need it any more
`
And then 

[`249`](https://bitbucket.org/globalmentor/guise/src/5525b5acc7aecfd1bba32824f1279cf28d0319dc/mummy/src/main/java/io/guise/mummy/mummify/image/DefaultImageMummifier.java#lines-249)`			final IIOMetadata imageMetadata = keepMetadata ? imageReader.getImageMetadata(imageIndex) : null; //get any metadata associated with the image if we have been asked to keep it
`

You cannot use the `imageReader` *after* it's disposed! 

This *should* however cause `java.lang.IllegalStateException: Attempting to use reader after dispose()` (and it does in my tests), but somehow we run into a different code path. 

And your code should fail regardless of using TwelveMonkeys or the default JPEG plugin.

Confused...


-- 
Harald K

**Comment by garretwilson** [comment]
> You cannot use the `imageReader` _after` it's disposed!

Ah, the original code was written about 15 years ago when I was discarding all metadata. I didn't think to revisit this part recently when I started including the metadata.

Just looking at the docs, it's not clear to me whether these "resources" that the image is keeping in memory is the metadata or the image data or all data or if the API even defines that. Perhaps the Java implementation maintains the metadata, but the Twelve Monkeys implementation decides that `dispose()` means that it should throw everything away, even the metadata.

This is a great clue! (And I already owed you a beer or several. 😉 ) This afternoon I'll test it by moving the `dispose()` somewhere else, or at least getting the metadata first.

A couple of questions:

* Do you think I can get away with `getImageWriter(imageReader)` even after calling `imageReader.dispose()`?
* If I grab `imageReader.getImageMetadata(imageIndex)` before calling `imageReader.dispose()`, do you think I can still use it later to pass to `new IIOImage(…)`? (Basically I'm trying to reduce memory by disposing the original image reader as soon as possible.)

**Comment by garretwilson** [comment]
@haraldk if we solve this problem, that means Twelve Monkeys might be an option for my project after all. The scaling is working fine using plain Java as pert the code you're seeing, and if I write metadata I'll be (for the moment) writing it using another library.

So do you have a page that tells me succinctly what benefit Twelve Monkeys would bring over plain Java just to scale an image like the code we're discussing?

**Comment by haraldk** [comment]
> * Do you think I can get away with getImageWriter(imageReader) even after calling imageReader.dispose()?

Well, the API docs for `ImageReader.dispose()` says:

> [...] The result of calling any other method (other than `finalize`) subsequent to a call to this method is undefined. [...]

So it doesn't have to be `IllegalStateException`. It could work (actually it will, given the current implementation). But I wouldn't count on it staying like that forever. 😉

> * If I grab imageReader.getImageMetadata(imageIndex) before calling imageReader.dispose(), do you think I can still use it later to pass to new IIOImage(…)? (Basically I'm trying to reduce memory by disposing the original image reader as soon as possible.)

Yes, I think that should be safe. 

> So do you have a page that tells me succinctly what benefit Twelve Monkeys would bring over plain Java just to scale an image like the code we're discussing?

No, not really. If you have only nice, compliant JFIFs as input, the standard JPEG reader might even be faster. The TwelveMonkeys plugin just supports a lot more non-standard (but common) JPEG variations.
 
If you're interested in high quality scaling, the `ResampleOp` may produce better results than `Image.getScaledInstance` (with `Lanczos` filter for example). But it does have known bugs, so unless you're in the need, maybe stick with what you have... 

-- 
Harald K

**Comment by garretwilson** [comment]
I have excellent news!

> I do spot a problem in your code though. … You cannot use the `imageReader` _after_ it's disposed!

Indeed, that was the problem! Thank you so much! Even though it wasn't causing me any problems at the moment (as I wasn't using Twelve Monkeys), it's very good to have the code more robust and to remove a blatant error.

Here is what the code looks like now. I've restructured the code a bit to prevent this sort of problem the future:

```java
final ImageInputStream imageInputStream = createImageInputStream(inputStream); //this stream will not be closed in this method, as it wraps a stream provided by the caller
if(imageInputStream == null) {
  throw new IOException("No suitable image input stream service provider found.");
}
final BufferedImage oldImage; //read the first of the images
final IIOMetadata oldImageMetadata;
final ImageWriter imageWriter; //get the writer while the reader is still valid
{ //use the reader in a separate block to keep it from being accidentally used after it is disposed
  final ImageReader imageReader = findNext(getImageReaders(imageInputStream)) //use the first available image reader
      .orElseThrow(() -> new IOException("No service provider image reader available."));
  try {
    final ImageReadParam imageReadParam = imageReader.getDefaultReadParam();
    imageReader.setInput(imageInputStream, true, !keepMetadata); //tell the image reader to read from the image input stream, ignoring metadata if we shouldn't keep metadata
    oldImage = imageReader.read(imageIndex, imageReadParam); //tell the image reader to read the image
    oldImageMetadata = keepMetadata ? imageReader.getImageMetadata(imageIndex) : null; //get any metadata associated with the image if we have been asked to keep it
    imageWriter = getImageWriter(imageReader); //get an image writer that corresponds to the reader
  } finally {
    imageReader.dispose(); //tell the image reader we don't need it any more
  }
}
```

> If this is the cause, you owe me a beer!

I now owe you several! Seriously, after the pandemic if I'm in the area I might just buy you one personally.

I'll mark this ticket as closed. Feel free to add an "invalid" label or whatever to the bug report.
