### ISSUE TITLE
javax.imageio.IIOException: Missing TIFF tag JPEGQTables

### ISSUE THREAD

**Issue by gabrielbieules** [haraldk/TwelveMonkeys#590]
Hi,

We go issues with some TIFF images. I attached an example (example.zip). We get the exception below when trying to read it:

Caused by: javax.imageio.IIOException: Missing TIFF tag JPEGQTables
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getValueAsLongArray(TIFFImageReader.java:2369) ~[imageio-tiff-3.6.2.jar:3.6.2]
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1402) ~[imageio-tiff-3.6.2.jar:3.6.2]

It appears that this TIFF file is identified as an "Old-style JPEG compressed TIFF". But then it can't find a JPEGQTables (519).

From the debugger, the directory **currentIFD** seems to contain:

0 = {TIFFEntry@24253} "256/ImageWidth: 5184 (SHORT)"
1 = {TIFFEntry@24254} "257/ImageHeight: 3456 (SHORT)"
2 = {TIFFEntry@24255} "258/BitsPerSample: [8, 8, 8] (SHORT)"
3 = {TIFFEntry@24256} "259/Compression: 6 (SHORT)"
4 = {TIFFEntry@24257} "271/Make: Canon (ASCII)"
5 = {TIFFEntry@24258} "272/Model: Canon EOS 7D (ASCII)"
6 = {TIFFEntry@24259} "273/StripOffsets: 67732 (LONG)"
7 = {TIFFEntry@24260} "274/Orientation: 8 (SHORT)"
8 = {TIFFEntry@24261} "279/StripByteCounts: 1124880 (LONG)"
9 = {TIFFEntry@24262} "282/XResolution: 72 (RATIONAL)"
10 = {TIFFEntry@24263} "283/YResolution: 72 (RATIONAL)"
11 = {TIFFEntry@24264} "296/ResolutionUnit: 2 (SHORT)"
12 = {TIFFEntry@24265} "306/DateTime: 2016:09:26 21:05:56 (ASCII)"
13 = {TIFFEntry@24266} "315/Artist:  (ASCII)"
14 = {TIFFEntry@24267} "700/XMP: [60, 63, 120, 112 ... 119, 39, 63, 62] (8192) (BYTE)"
15 = {TIFFEntry@24268} "33432/Copyright:  (ASCII)"
16 = {TIFFEntry@24269} "34665/EXIF: IFD[33434/ExposureTime: 1/1000 (RATIONAL), 33437/FNUmber: 9/2 (RATIONAL), 34850/ExposureProgram: 3 (SHORT), 34855/ISOSpeedRatings: 100 (SHORT), 34864: 2 (SHORT), 34866: 100 (LONG), 36864/ExifVersion: [48, 50, 51, 48] (UNDEFINED), 36867/DateTimeOriginal: 2016:09:26 21:05:56 (ASCII), 36868/DateTimeDigitized: 2016:09:26 21:05:56 (ASCII), 37121/ComponentsConfiguration: [1, 2, 3, 0] (UNDEFINED), 37377/ShutterSpeedValue: 10 (SRATIONAL), 37378/ApertureValue: 35/8 (RATIONAL), 37380/ExposureBiasValue: -1/3 (SRATIONAL), 37383/MeteringMode: 5 (SHORT), 37385/Flash: 16 (SHORT), 37386/FocalLength: 10 (RATIONAL), 37500/MakerNote: [41, 0, 1, 0 ... -40, 3, 0, 0] (45494) (UNDEFINED), 37510/UserComment: [0, 0, 0, 0 ... 0, 0, 0, 0] (264) (UNDEFINED), 37520: 78 (ASCII), 37521: 78 (ASCII), 37522: 78 (ASCII), 40960/FlashpixVersion: [48, 49, 48, 48] (UNDEFINED), 40961/ColorSpace: 1 (SHORT), 40962/PixelXDimension: 5184 (SHORT), 40963/PixelYDimension: 3456 (SHORT), 40965/Interoperability: IFD[1: R98"
17 = {TIFFEntry@24270} "34853/GPS: IFD[0: [2, 3, 0, 0] (BYTE)] (LONG)"

[example.zip](https://github.com/haraldk/TwelveMonkeys/files/5985415/example.zip)

Thank you

**Comment by haraldk** [comment]
Hi Gabriel,

This file is a Canon RAW (.CR2) file. While it uses the TIFF container format and looks very much like a TIFF, it's not really a valid TIFF file. It is missing a lot of required tags for normal TIFF readers to process it.

There is some work done to support this format [here](https://github.com/haraldk/TwelveMonkeys/tree/camera-raw) but it's not a priority right now...


Best regards,

-- 
Harald K

**Comment by gabrielbieules** [comment]
Thank you @haraldk for your quick feedback.
We will have a look at the other branch in progress.

Kind regards
