### ISSUE TITLE
JPEG loading speed is slower than IrfanView

### ISSUE THREAD

**Issue by AKMANSoft** [haraldk/TwelveMonkeys#596]
Hi I'm Loading a JPEG image and resize it, it is taking around 6 sec for me to load that image, below is the link of the image. 

https://www.dropbox.com/s/uoc6amdwpkbabyk/Slow%20Image%20Loading.jpg?dl=1

If I use Irfan Viewer or other window application it load instantly.

**Comment by haraldk** [comment]
Hi Syed,

Your JPEG file uses progressive encoding. IrfanView can probably display the image while reading the progressive passes, while your Java code most likely decodes all the passes before displaying. So I think you are comparing apples and oranges here. 

You can do the same in Java by creating the destination image up front, and read into it while refreshing your display for each progressive pass. 

See `ImageReadParam.setDestination` for setting the destination, and the `IIOReadUpdateListener` interface for listening to progressive updates. 

That said, IrfanView *is* probably faster still. Our `JPEGImageReader` delegates actual JPEG *decoding* to the `JPEGImageReader` of the JDK, which is a packaged versjon of IJG libJPG. LibJPGTurbo or other optimized versions of libJPEG may be faster. If the performance is something that is important to you, you can help by suggesting improvements, donating or sponsor specific development for improving performance. 


Best regards,

-- 
Harald K

**Comment by AKMANSoft** [comment]
Hi Thank you for reply, I don’t know how this works

you can help by suggesting improvements, donating or sponsor specific development for improving performance.

**Comment by haraldk** [comment]
This library is open source software. You can take the code, use it for whatever you like, and make any improvements you need. And then, if you want to, you can share those improvements with the community, by contributing the improvements back to the library.

Or, if you/your company don't have the time or knowledge to make such improvements yourself, you could hire someone to do it for you. I'm open for taking on such tasks, if you are interested you can contact me directly. 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Closing, as it's not really clear what sort of improvements would be needed to consider this issue "fixed". 

-- 
Harald K
