### ISSUE TITLE
ImageIO.createImageOutputStream returns null

### ISSUE THREAD

**Issue by nanthony21** [haraldk/TwelveMonkeys#597]
I am using the TwelveMonkey TIFF plugin to save TIFF files to a network share that is connected as NFS.

On one computer that I use (Windows 7) this appears to work flawlessly. However on another computer (Windows 10) I get an occasional issue where `ImageIO.createImageOutputStream` returns null.

Here is a snippet of the problematic code:
```
        File directory = new File(this.savePath);
        if (!directory.exists()) { directory.mkdirs(); }
        File file = Paths.get(this.savePath, fullFileName).toFile(); 
        try (ImageOutputStream outStream = ImageIO.createImageOutputStream(file)) {
            writer.setOutput(outStream);
            writer.prepareWriteSequence(null); //null means we will use the default streamMetadata.
        ...
```

It seems that for roughly 1 out of 3 runs of this code the outputStream gets returned as `null`. This then correctly causes an exception to be thrown at `writer.setOutput(outStream`.

How can I figure out why the plugin is failing to create an outputStream?

**Comment by haraldk** [comment]
Hi Nick,

This is most likely a JDK issue, as TwelveMonkeys don't provide any `ImageOutputStream` implementations... I would use a debugger to find out exactly what happens (and hopefully why!). There are a couple of reasons this may happen, the most likely reason for the `null` is `com.sun.imageio.spi.FileImageOutputStreamSpi`, which contains the following code (Java 1.8 version, I think later releases are basically unchanged):

````java
            try {
                return new FileImageOutputStream((File)output);
            } catch (Exception e) {
                e.printStackTrace();
                return null;
            }
````

If so, you should also see the stack trace somewhere, but of course the exception swallowing is not ideal...

See also [JDK-5034864: remove spurious printStackTrace() calls in ImageIO classes](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=5034864), which is still open.


-- 
Harald K

**Comment by haraldk** [comment]
PS: One possible workaround, would be to replace the JDK provider (the Spi class only) with a custom implementation that instead does something like:

````java
            try {
                return new FileImageOutputStream((File)output);
            } catch (Exception e) {
                if (e instanceof IOException) {
                    throw (IOException) e;
                }
                throw new IOException(e);
            }
````

Should be quite straight forward to implement. May even be something that the library could include in the future, if you're up for creating a PR. 😀 

-- 
Harald K

**Comment by nanthony21** [comment]
Thanks @haraldk , I'll see if I can dig into what is going on in `com.sun.imageio.spi.FileImageOutputStreamSpi`.

When looking at the output in the debugger I didn't see any stack traces coming up which makes me think that the `null` I was getting may actually come directly from `ImageIO.createImageOutputStream`:

```
        while (iter.hasNext()) {
            ImageOutputStreamSpi spi = (ImageOutputStreamSpi)iter.next();
            if (spi.getOutputClass().isInstance(output)) {
                try {
                    return spi.createOutputStreamInstance(output,
                                                          usecache,
                                                          getCacheDirectory());
                } catch (IOException e) {
                    throw new IIOException("Can't create cache file!", e);
                }
            }
        }

        return null;
```

**Comment by haraldk** [comment]
Well.. I doubt it, as that should happen only if there is no registered Spi for `File` (or something completely broken in the registry, which is a separate branch)... But in those cases, I believe the `null` result should be consistent. 

In any case, stepping through in the debugger will tell you for sure. 😀 

-- 
Harald K

**Comment by nanthony21** [comment]
So, in todays testing I did in fact see a stack trace printed out and you were right about the cause.

Here is the stack trace:

```
java.io.FileNotFoundException: Z:\Nick\test2\Cell2\PWS\pws.tif (The system cannot find the path specified)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at javax.imageio.stream.FileImageOutputStream.<init>(FileImageOutputStream.java:69)
	at com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(FileImageOutputStreamSpi.java:55)
	at javax.imageio.ImageIO.createImageOutputStream(ImageIO.java:419)
```

I noticed that this only happens when there isn't a break point that results in a pause between creating the `File` and calling `createImageOutputStream` so it's probably something to do with timing.

I'll have to do some more reading about `RandomAccessFile`, hopefully I can make the program briefly pause until the `File` is read to be passed in to `createImageOutputStream`.

Since this is clearly not related to TwelveMonkeys I'll go ahead and close this. Thanks for the help!
