### ISSUE TITLE
com.twelvemonkeys.util.TimeoutMap#containsKey returns true for expired items 

### ISSUE THREAD

**Issue by apu84** [haraldk/TwelveMonkeys#600]
```
import com.twelvemonkeys.util.TimeoutMap;

import java.util.Map;

public class TimeOutMapTest {
  public static void main(final String[] args) {
    Map<String, String> timeoutMap = new TimeoutMap<>(2000);
    boolean containsBefore = timeoutMap.containsKey("xyz");
    timeoutMap.put("xyz", "xyz");
    try {
      Thread.sleep(3000); // Let the item expire
    }
    catch (InterruptedException e) {
      e.printStackTrace();
    }
    boolean containsAfter = timeoutMap.containsKey("xyz");
    System.out.println("containsKey before expiry: " + containsBefore);
    System.out.println("containsKey after expiry: " + containsAfter);
    System.out.println("value after expiry: " + timeoutMap.get("xyz"));
  }
}
```

Outputs as
```
containsKey before expiry: false
containsKey after expiry: true
value after expiry: null
```
containsKey method should return false after the expiry period.
Somehow the first containsKey method invocation is messing up this process. If I omit the first containsKey invocation code outputs as expected.

Tested with **MacOS 11.2.3** 
Java: **openjdk 11.0.10 2021-01-19**
**com.twelvemonkeys.common:common-lang:3.3.2**  

I have tested this behaviour persist in the latest release as well

**Comment by haraldk** [comment]
Hi Apu,

Thanks for reporting and providing test code! Interestingly, there was a bug that is triggered when you invoke `containsKey` when the map is empty... After that, no entry will expire again (before sometime far into the future), unless you set the expiry time again. 😕 

Just curious, does this bug cause other bugs in the library, or are you using the map directly in a separate project? This map is likely to be removed in the future, as part of a bigger clean-up job for the next major release. Just so you are aware. 


Best regards,

-- 
Harald K

**Comment by apu84** [comment]
Thanks Harald, for the quick response.

I found this bug in one of our product, which is using TimeoutMap directly. Use case, we are checking if the map already contains the key before putting an item. And that's where it is started to behave abnormally.

Thanks for heads up. I believe we need to come up with alternate solution for this.

**Comment by apu84** [comment]
Harald, is there any eta when we can have a patch with this fix?

**Comment by haraldk** [comment]
You're in luck, as I'm working on last pieces of the 3.7 release these days. Hope to have it done by the end of the week/early next week. But I don't have an exact ETA. 

If you need a fix now, you need to build from sources. Or I could make one for you if you (your company/product) would like to become a sponsor of the project. 


Best regards,

-- 
Harald K
