### ISSUE TITLE
3.7 Image-jpeg release: "Old JPEG compression not supported"

### ISSUE THREAD

**Issue by adjonkep** [haraldk/TwelveMonkeys#603]
Hello and Thank you for the amazing work!
My real issue is a derivative of #584, but I see that you have put a fix for it in 3.7. However upon building the source and adding all the dependencies in the classpath, the plugin doesn't seem to be detected. This is specific to 3.7 because , I get a "No sof segment in stream" with 3.6.4. Any insight would be appreciated.

Thanks

**Comment by haraldk** [comment]
Thanks!

I'm afraid I need some more details to go on... What is your JDK version? Plugins in use? Code to reproduce? Sample image? Stack trace? You also mention "building the source", does this mean you built TwelveMonkeys from source, rather than the official release?

The message "Old JPEG compression not supported" is likely from a TIFF plugin, but not ours. Did you expect the TwelveMonkeys TIFF plugin to be used, or just use the TwelveMonkeys JPEG plugin with a third-party TIFF plugin? 

The only thing I can see that would cause the plugins to not get detected, is if the new automatic module name causes problems, but I would still be surprised. 

Anyway, provide the details I ask for, and I'll look into it! 😀 


Best regards,

-- 
Harald K

**Comment by adjonkep** [comment]
Thanks for responding so promptly!

 

So here are the details of my setup!

Im trying to process some tif files with the old JPEG compression.

I am using java 1.8 and I am alternating between the JAI imageio 1.1 and its community fork (JAI-imageio-core 1.4) for the TiffReader. The reason I am using their TiffReader instead of the TwelveMonkeys, is because I don't want to rewrite a bunch of legacy code I inherited. So I am adding the TwelveMonkeys JPEG plugin with all the dependencies in the classpath (common-lang, common-io... you know them all and thank you!!)

 

The problem is when I try to read the file

[sampleTif.zip](https://github.com/haraldk/TwelveMonkeys/files/6371066/sampleTif.zip)

with the code:

 

    ImageInputStream inputStream = ImageIO.createImageInputStream(new FileInputStream(inputFile));

    Iterator<?> imageReaderIter = ImageIO.getImageReaders(inputStream);

    ImageReader reader = (ImageReader)imageReaderIter.next();

    reader.setInput(inputStream);

    String formatName = reader.getFormatName();

 

    int numImages = reader.getNumImages(true);

 

    ImageData[] imageDataArray = new ImageData[numImages];

 

    for (int i = 0; i < numImages; ++i) {

      ImageDataImpl imageData = new ImageDataImpl();

 

      imageData.setImage(reader.read(i));

      imageData.setImageMetadata(reader.getImageMetadata(i));

      imageData.setPageIndex(i);

 

      imageDataArray[i] = imageData;

    }

 

using imageio-jpeg-3.6.4, I get the following error:

Caused by: javax.imageio.IIOException: No SOF segment in stream

               at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:861)

               at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:312)

               at com.github.jaiimageio.impl.plugins.tiff.TIFFOldJPEGDecompressor.decodeRaw(TIFFOldJPEGDecompressor.java:651)

               at com.github.jaiimageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2583)

               at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:1144)

               at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1414)

               at javax.imageio.ImageReader.read(ImageReader.java:939)

 

So I followed the issues about the No start of frame and I saw that it may be related to the Indianess in the interaction between the ImageReader (JAI and TM); and there is a possible fix in the release 3.7.

 

As soon as you made it official, I did a downloaded it and did a mvn package to build and replace all the dependencies with the 3.7 ones. Unfortunately I got a:

 

Caused by: javax.imageio.IIOException: Old JPEG compression not supported!

               at com.github.jaiimageio.impl.plugins.tiff.TIFFImageWriter.setupMetadata(TIFFImageWriter.java:897)

               at com.github.jaiimageio.impl.plugins.tiff.TIFFImageWriter.write(TIFFImageWriter.java:2570)

               at com.github.jaiimageio.impl.plugins.tiff.TIFFImageWriter.insert(TIFFImageWriter.java:2869)

               at com.github.jaiimageio.impl.plugins.tiff.TIFFImageWriter.writeInsert(TIFFImageWriter.java:2828)

               at com.github.jaiimageio.impl.plugins.tiff.TIFFImageWriter.writeToSequence(TIFFImageWriter.java:2720)

 

The write to sequence is related to a later part of the code but it completely skips the Reader of earlier; As if the spi wasn't seeing the new plugin. For reference, I get the same error when I don't use any plugins at all.

 

Sorry for the lengthy comment and thanks in advance.

 

Adrien

**Comment by haraldk** [comment]
Okay,

That explains a few things. 😀 

The #584 and #433 issues are both related to *reading* using a combination of either JAI, the community fork or the JEP 262 (JDK 9+) `TIFFImageReader` and the TwelveMonkeys `JPEGImageReader`. As you don't get this exception now (and I tested your sample image, and it works fine) I believe this is as it should.

The exception you get when trying to *write* an old-style JPEG-in-TIFF using the JAI `TIFFImageWriter` is completely unrelated to anything TwelveMonkeys (as can be seen for the stack trace). You simply can't write TIFFs with compression 6 (except for EXIF thumbnails, but that's a special case) using the JAI plugin. We have the behavior in our writer and most others too, as this part of the spec is deprecated. This is something you have to fix in your own code, most likely you want to write using compression 7 ("new-style" JPEG), unless this is in fact an EXIF thumbnail. 

>  For reference, I get the same error when I don't use any plugins at all.

That's odd... As there is no TIFF plugin installed by default in JDK 1.8. Perhaps you have an old installation of JAI on your computer? 

Anyway, I'm closing this for now as it doesn't seem to be TwelveMonkeys related. 

PS: There is simple test code in the README on the project front page, to see if the JPEG plugin is installed, if you believe there is an issue registering the plugin. 


-- 
Harald K
