### ISSUE TITLE
wbmp files have black area after reading

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#606]
Happens with 3.7.0 but not with 3.6.4. The pom.xml has imageio-jpeg. Using windows 10 and oracle jdk8 almost latest.
```
    @Test
    public void wbmpTest() throws IOException
    {
        BufferedImage bw = new BufferedImage(500, 500, BufferedImage.TYPE_BYTE_BINARY);
        Graphics2D g = (Graphics2D) bw.getGraphics();
        g.setBackground(Color.white);
        g.fillRect(0, 0, bw.getWidth(), bw.getHeight());
        g.dispose();
        boolean b = ImageIO.write(bw, "wbmp", new File("target","test2.wbmp"));
        Assert.assertTrue(b);
        BufferedImage bim2 = ImageIO.read(new File("target","test2.wbmp"));
        b = ImageIO.write(bim2, "wbmp", new File("target","test3.wbmp"));
        Assert.assertTrue(b);
        for (int x = 0; x < bim2.getWidth(); ++x)
        {
            for (int y = 0; y < bim2.getHeight(); ++y)
            {
                Assert.assertEquals("Difference at " + x + "," + y, bim2.getRGB(x, y), bw.getRGB(x, y));
            }
        }
    }

```

Original file is white, second file is black and white.

**Comment by haraldk** [comment]
Odd... 

TwelveMonkeys ImageIO does not have a WBMP plugin... 

Does that mean somehow the WBMP (which has a very weak magic signature), is recognized (and read without exceptions) using a different format reader? Technically possible, but very odd. I'll look into it. 


-- 
Harald K

**Comment by THausherr** [comment]
this code

```
        ImageInputStream iis = ImageIO.createImageInputStream(new File("target","test2.wbmp"));
        System.out.println("Stream: " + iis);
```
3.6.4:
Stream: javax.imageio.stream.FileImageInputStream@17c68925


3.7.0:
Stream: com.twelvemonkeys.imageio.stream.BufferedFileImageInputStream@edf4efb

**Comment by THausherr** [comment]
Changing
`BufferedImage bim2 = ImageIO.read(new File("target/test2.wbmp"));`
to
`BufferedImage bim2 = ImageIO.read(new MemoryCacheImageInputStream(new FileInputStream("target/test2.wbmp")));`

makes the test succeed.

**Comment by haraldk** [comment]
Thanks @THausherr ! 

I had forgot, but I made some optimized streams available in 3.7.0. They make quite a difference for the speed of the WebP plugin among others. 

But that  makes sense. I'll debug and see what might cause this!

-- 
Harald K

**Comment by haraldk** [comment]
Hmmm..

It does seem like there is a bug in `com.sun.imageio.plugins.wbmp.WBMPImageReader`, they use `read`:

```java
    iis.read(((DataBufferByte)tile.getDataBuffer()).getData(),
                     0, height*sm.getScanlineStride());
```

Where they should have used `readFully`, like this:

```java
    iis.readFully(((DataBufferByte)tile.getDataBuffer()).getData(),
                     0, height*sm.getScanlineStride());
```

Obviously, this bug is masked by the behavior of the old `FileImageInputStream`, `MemoryCacheImageInputStream` and others...

It's possible to work around it, but how important is WBMP in 2021? 😛 


-- 
Harald K

**Comment by THausherr** [comment]
Yeah, it's not really important except for archivists and it's not in your code. I never use the format, I found it while building PDFBox (which has wbmp for unit tests) in a modified version (that uses twelvemonkeys).
You can close this if you want. Do you want to create an issue in https://github.com/jai-imageio/jai-imageio-core/ or should I?

**Comment by haraldk** [comment]
I made a relatively simple fix that does not seem to affect performance, so I think I'll go with that.  I have seen similar bugs in the JDK before, so better be on the safe side.

Feel free to file an issue with jai-imageio, but I think its more important to file one with OpenJDK, as the WBMP plugin is bundled as standard. 

-- 
Harald K

**Comment by THausherr** [comment]
internal review ID : 9070094

**Comment by haraldk** [comment]
@THausherr Did you file an OpenJDK bug?

**Comment by THausherr** [comment]
No, it was on the oracle bug submission.

**Comment by THausherr** [comment]
https://bugs.openjdk.java.net/browse/JDK-8266435

**Comment by haraldk** [comment]
Thanks @THausherr for registering all those bug reports and creating a good test case! 👍🏻

**Comment by THausherr** [comment]
They fixed it for jdk18.
