### ISSUE TITLE
Support for TIFF compression types 3 and 4 (CCITT Group 3/4 Fax encoding)

### ISSUE THREAD

**Issue by hmashlah** [haraldk/TwelveMonkeys#61]
I am trying to read the following image https://www.dropbox.com/s/zpjfppfjcz0emb8/image.tiff?dl=0
The imageio plugins are loaded and I can read other tiff images, but when I try reading this specific one ImageIO.read(new FileInputStream("image path")) returns null

**Comment by dhartford** [comment]
I am very interested in this, and although a side-request, a 'best usage' of Twelvemonkeys for taking a TIFF, split out some pages, and create a new TIFF with those selected pages (something we did with the old JAI library).  Reference thread around this common challenge: http://stackoverflow.com/questions/17770071/splitting-a-multipage-tiff-image-into-individual-images-java

**Comment by sylvainmouquet** [comment]
+1 CCITT 4

**Comment by haraldk** [comment]
Hi guys,

I'd really like to implement it, it's on the list but didn't make it to 3.1. If anyone has some spare time to implement the T4 and T6 decompression algorithms, I'd be very happy to integrate that (bilevel reading is already fully done). :-)

Otherwise, stay tuned. 

-- 
Harald K

**Comment by THausherr** [comment]
Maybe a possible idea for the Google Summer of Code? Github has been accepted as organization. It is still a lot of work mentoring the student (in my case: 5-10 hours a week), but less than coding it yourself :-)

**Comment by haraldk** [comment]
@THausherr That is an interesting idea! Not sure I have 5-10 hours/week available, though. And if I had, I might as well just do it myself. :-) But will definitively consider it!

-- 
Harald K

**Comment by Schmidor** [comment]
I'm currently trying to implement Group 3 / 4 decoding. As soon as i'm satisfied with the results i will make a pull request. However, i'm currently having problems with determining the correct reference row changing elements in Group 4 images.

**Comment by rlauck** [comment]
Is there any hope for a pure Java implementation of Group 4 en/decoding performing on par with JAI native libs?

**Comment by haraldk** [comment]
@Schmidor This is great news! I was planning to have a stab at this some time soon, but if you can make it work, that leaves me with more time for JPEG-Lossless. :-)

Let me know if I can help in any way (feel free to contact me by direct email)! I'd need to read up on the specs, and possibly need to see some code to be able to help with the exact problem you are referring to... But at least good to see that someone is working on this!


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
@rlauck Not sure. But I also don't see why not. :-) 

In any case, if you need the native performance (and don't have a problem installing native libs and JNI stuff), using either JAI or even creating a separate plugin backed by LibTIFF shouldn't be a problem. The goal of this project is to have everything written in Java, for easy deployment and predictable behaviour.

-- 
Harald K

**Comment by Schmidor** [comment]
I think i've got it, just a wrong start index in 2d encoding.

One thing left is wheter the decoder should know about PhotometricInterpretation and output accordingly or whether it always should output WhiteIsZero and the Tiff Reader should invert it at a later stage.
Currently it always outputs BlackIsZero  and the reader inverts it if the Tag is set to WhiteIsZero, so WhiteIsZero images are currently displayed inverted :)

**Comment by haraldk** [comment]
Cool! 

I'll have a look (I'm currently on holiday, so it may take some time).

The idea so far has been to keep the `PhotometricInterpretation` out of the decoding parts, to avoid having to implement this for every possible combination of compression, predictor, interpretation, bits, etc., etc. I like to keep it that way, if you don't mind. :-)

Otherwise, this looks like a very valuable addition to the TIFF reader! 

Thanks, 

-- 
Harald K

**Comment by haraldk** [comment]
Fixed via #148. 

Thanks @Schmidor !

-- 
Harald K
