### ISSUE TITLE
is ImageIO.getImageReadersByFormatName("jpeg-ls") supported with the jpeg plugin? 

### ISSUE THREAD

**Issue by juanbill** [haraldk/TwelveMonkeys#610]
Hi, 

I noticed 

ImageIO.getImageReadersByFormatName("jpeg-lossless") is supported but wondering if 

ImageIO.getImageReadersByFormatName("jpeg-ls")

like this link suggests https://github.com/haraldk/TwelveMonkeys/issues/361

if "jpeg-ls" is supported, what needs to be added gradle to work. 
the following is what I have added

    implementation group: 'com.twelvemonkeys.imageio', name: 'imageio-core', version: '3.7.0'
    implementation group: 'com.twelvemonkeys.imageio', name: 'imageio-jpeg', version: '3.7.0'
    implementation group: 'com.twelvemonkeys.imageio', name: 'imageio-metadata', version: '3.7.0'

Thanking you guys in advance
J.

**Comment by haraldk** [comment]
Hi @juanbill,

There's no support in the library for JPEG-LS at the moment (JPEG-LS is based on a completely different algorithm than normal JPEG or JPEG-LOSSLESS).  

Best regards,

-- 
Harald K
