### ISSUE TITLE
Certain Webp files are not read

### ISSUE THREAD

**Issue by KalhariL** [haraldk/TwelveMonkeys#611]
[0m.webp.zip](https://github.com/haraldk/TwelveMonkeys/files/6697915/0m.webp.zip)

The attached webp file is not read and throws the following exception. (With imageio-webp-3.7.0.jar)

```
javax.imageio.IIOException: Corrupt WebP stream, colorCacheBits < 1 || > 11: 0
        at 
      com.twelvemonkeys.imageio.plugins.webp.lossless.VP8LDecoder.readVP8Lossless(VP8LDecoder.java:79)
        at 
      com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.readVP8Lossless(WebPImageReader.java:432)
        at 
      com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.read(WebPImageReader.java:323)
        at 

```

**Comment by haraldk** [comment]
As [documented](https://github.com/haraldk/TwelveMonkeys/wiki/WebP-Plugin), WebP lossless (VP8L) is currently not supported by the plugin. Using `ImageIO.read(new File("0m.webp"))` should return `null`, and not throw an exception in this case.

If WebP lossless is something you would like, you can contribute to the project or use the sponsorship badge on the project front page. 😀 

Best regards,

-- 
Harald K
