### ISSUE TITLE
Can not load transparent lossy WebP texture

### ISSUE THREAD

**Issue by Ali-RS** [haraldk/TwelveMonkeys#613]
Hi

**Describe the bug**
I can not load the transparent WebP texture **lossy** converted from PNG. (tried both with Gimp and an online PNG to WebP converter)

`BufferedImage image = ImageIO.read(new File("path to webp file"));`

returned image is null.

It works fine for non transparent files converted from JPG.

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.7.0

Using this Gradle snippet:

`api group: 'com.twelvemonkeys.imageio', name: 'imageio-webp', version: '3.7.0'`

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 

```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

```

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

Linux Mint 20.1
Gimp 2.10.18

**To Reproduce**

1. Use below code to load webp file

`BufferedImage image = ImageIO.read(new File("path to webp file"));`

2. Download the sample image file from here

[textures.zip](https://github.com/haraldk/TwelveMonkeys/files/6797374/textures.zip)
(includes the original Png file and the WebP file converted using Gimp)

3. Run the code with the sample file
4. The returned BufferedImage image is null and no error is logged.

**Expected behavior**
Should properly log what is going wrong with image file.

Regards

**Comment by haraldk** [comment]
Hi Ali-RS,

As mentioned on the [WebP Wiki](https://github.com/haraldk/TwelveMonkeys/wiki/WebP-Plugin), only lossy WebP in the "simple format" is currently supported. Transparency (always lossless in WebP) and extended format is not supported yet. 

There is nothing wrong with the image, it is simply not supported yet. According to [`ImageIO.read()` API doc](https://docs.oracle.com/javase/7/docs/api/javax/imageio/ImageIO.html#read(java.io.File)): 

>  If no registered `ImageReader` claims to be able to read the resulting stream, `null` is returned.

Thus, there is nothing going wrong, and nothing to log (or exceptions to be thrown). 

Most of the support for extended format is there. It's possibly to force the WebP plugin to read your file, and decode the lossy part. But it still won't decode the transparency, so may not be very useful other than for debugging/development:

````java
try (ImageInputStream input = ImageIO.createImageInputStream(file)) {
    ImageReader reader = ImageIO.getImageReadersByFormatName("WEBP").next();

    try {
        reader.setInput(input);

        BufferedImage image = reader.read(0, null);
    }
    finally {
        reader.dispose();
    }
}
````

Hope that explains things!


-- 
Harald K

**Comment by Ali-RS** [comment]
That explains why. I was thinking transparency is lossy as well.

Thanks, @haraldk.

**Comment by Ali-RS** [comment]
Hi @haraldk

Is alpha support availble in the master branch? Can we expect it for the incomming release?

Regards

**Comment by haraldk** [comment]
No, alpha support is not planned for any release at the moment.

I just created #629 to track this feature request. 

-- 
Harald K
