### ISSUE TITLE
Dependency convergence error - xmlgraphics-commons:jar

### ISSUE THREAD

**Issue by rbri** [haraldk/TwelveMonkeys#616]
**Description**

Hi and thanks for this great project.

During some analysis i found this Dependency convergence error.

08:18:59 [WARNING] 
08:18:59 Dependency convergence error for org.apache.xmlgraphics:xmlgraphics-commons:jar:2.6:test paths to dependency are:
08:18:59 +-net.sourceforge.htmlunit:htmlunit:jar:2.53.0-SNAPSHOT
08:18:59   +-com.twelvemonkeys.imageio:imageio-batik:jar:3.7.0:test
08:18:59     +-org.apache.xmlgraphics:batik-extension:jar:1.14:test
08:18:59       +-org.apache.xmlgraphics:batik-css:jar:1.14:test
08:18:59         +-org.apache.xmlgraphics:xmlgraphics-commons:jar:2.6:test
08:18:59 and
08:18:59 +-net.sourceforge.htmlunit:htmlunit:jar:2.53.0-SNAPSHOT
08:18:59   +-com.twelvemonkeys.imageio:imageio-batik:jar:3.7.0:test
08:18:59     +-org.apache.xmlgraphics:xmlgraphics-commons:jar:2.2:test
08:18:59 and
08:18:59 +-net.sourceforge.htmlunit:htmlunit:jar:2.53.0-SNAPSHOT
08:18:59   +-org.apache.xmlgraphics:batik-transcoder:jar:1.14:test
08:18:59     +-org.apache.xmlgraphics:batik-awt-util:jar:1.14:test
08:18:59       +-org.apache.xmlgraphics:xmlgraphics-commons:jar:2.6:test
08:18:59 and
08:18:59 +-net.sourceforge.htmlunit:htmlunit:jar:2.53.0-SNAPSHOT
08:18:59   +-org.apache.xmlgraphics:batik-transcoder:jar:1.14:test
08:18:59     +-org.apache.xmlgraphics:batik-bridge:jar:1.14:test
08:18:59       +-org.apache.xmlgraphics:xmlgraphics-commons:jar:2.6:test

**Reason**
* ImageIO uses a hard coded dependeny to xmlgraphics-commons 2.2
* ImageIO uses xmlgraphics:batik-transcoder:jar:1.14 that in the end points to xmlgraphics-commons:jar:2.6

**Version information**
3.7.0

Hope the info is sufficient - if not please drop me a note.

Thanks again
    Ronald

**Comment by haraldk** [comment]
Hi Roland,

Thanks for reporting! 

I can't remember exactly why I have the `xmlgraphics-commons 2.2` dependency in there, but I vaguely remember that there was some internal version conflict in the Batik dependencies, or a Batik dependency pointing to some non-released version of `xmlgraphics-common`. So I ended up declaring the specific version. 

Anyway, it seems now (using Batik 1.14) that both pinning it to 2.6, or just leaving it out altogether works fine... 

What do you think would be the best option?


Regards,

-- 
Harald K

**Comment by rbri** [comment]
From my point of view i think you can to drop the explicit dependency from image-io.

**Comment by rbri** [comment]
Thanks for the great support
