### ISSUE TITLE
WebP Color Discrepancy

### ISSUE THREAD

**Issue by garthhenning** [haraldk/TwelveMonkeys#619]
**Describe the bug**
Map tiles loaded by Java using the TwelveMonkeys WEBP ImageIO reader have inconsistent colors. The file is converted from a PNG file which is all "ocean" pixels with sRGB values of (112, 173, 215). The WEBP codec returns different values, which vary slightly based on whether there are other non-"ocean" pixels in the map tile. The most common codec color for the loaded WEBP is an sRGB of (111, 165, 202). 

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.

It happens in both the 3.7.1 version and the 3.8-SNAPSHOT version (which includes the fix to #609)

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 

openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

MacOS 11.5.1 x86_64, run from Netbeans 12.4 directly as an executable application.

**To Reproduce**

This WEBP file loads correctly in web browsers but the colors are off in Java:
https://www.runningreality.org/lib/map/tiles/8/136/97.webp

The file is converted from this PNG file:
https://www.runningreality.org/lib/map/tiles/8/136/97.png

The conversion was done using the command:
cwebp -m 6 -q 85 -mt -af -progress -sharp_yuv

**Expected behavior**
Expect the WEBP to load with the exact color values as the PNG.

**Comment by haraldk** [comment]
Garth,

Thanks for reporting! And also for testing the unreleased 3.8-SNASHOT code! 👍🏻 

I had some trouble confirming your results. When I download the PNG from the second link above, Safari downloads the same WEBP file as the first link... Probably some server magic trying to serve WebP if the browser supports it? Had to use `curl` to get the actual PNG. 

Also, my MacOS 11.5.2 Preview/Digital Color meter displays the sRGB values as (114, 174, 213) on my external Dell screen, but as (115, 174, 213) on my laptop screen. These are slightly different than your values. The WebP and the PNG values are consistent though. 

For the Java version, the PNG is (114, 174, 213) on Dell, (96, 175, 217) on laptop. WebP is (113, 166, 200) on Dell and (97, 167, 204) on laptop. Something very odd is going on with the sRGB values on the laptop screen there... 

Anyway... I agree that the colors are at least inconsistent between the WebP and the PNG in Java and they should be the same. I'll look into it! 


Best regards,

-- 
Halald K

**Comment by haraldk** [comment]
PS: If you have the time to dig further into this, it would also help a lot! 😀 

-- 
Harald K

**Comment by garthhenning** [comment]
It is definitely hard to sort out the various color profiles influencing the pixels. Between our tests, it seems to imply that different monitor profiles affect the pixels, but independent of PNG or WEBP. But Safari/Chrome/Firefox/Preview all still show identical pixels across PNG and WEBP but Java shows some discrepancies.

I see it most repeatably on those blue map tiles, since the blue values are off more than the green and the red are nearly spot on. Still, it shows up on all map tiles. What gets weird is that the Java-loaded tiles each have slightly different WEBP blue values from each other.... when it all other apps they have identical blue values to each other and to the PNG.

I've been trying different Java color profiles, but nothing affects it at all. If any code variation gives any clue, I'll post it. This implies to me that the issue is in the codec upstream of when the color model comes into play.

My next try is to vary the Java version from 14.0.2 and see if 11 or 15 or 16 changes anything. I was really hoping your fix to #609 would fix it, but it didn't. Maybe some of the Java color model fixes in 15 or 16 might fix it. Fingers crossed.

The cwebp utility also seems to have problems with red values, and I've varied the encoding parameters. Using -sharp_yuv was supposed to be something that improved color consistency between the source image and WEBP image created by cwebp. It might be that it is writing out the color model in a not-fully-compliant way that other apps' libwebp code is tolerantly interpreting.

**Comment by haraldk** [comment]
Hmmm..

If you look into `com.twelvemonkeys.imageio.plugins.webp.vp8.VP8Frame#copyBlock` method, you'll notice I use the same YCbCr -> RGB conversion as I used for JPEG. This yields correct results for JPEG, but perhaps not the same as the native WebP codec uses... Perhaps something to look into.

I don't find any exact specification on the conversion either, other than:

> ### What color spaces does the WebP format support?
>
> Consistent with the VP8 bitstream, lossy WebP works exclusively with an 8-bit Y'CbCr 4:2:0 (often called YUV420) image format. Please refer to Section 2, "Format Overview" of RFC 6386, VP8 Data Format and Decoding Guide for more detail.

(https://developers.google.com/speed/webp/faq#what_color_spaces_does_the_webp_format_support) 

But this isn't very informative, as these are just encodings, and doesn't really say anything about color profiles... Or anything about the exact YCbCr encoding used. 


-- 
Harald K

**Comment by haraldk** [comment]
Okay, okay... 

So, after some more googling and looking into the libwebp source, it seems WebP uses [standard ITU-R rec. 601](https://en.wikipedia.org/wiki/YCbCr#ITU-R_BT.601_conversion) Y'CbCr -> RGB conversion, while [JPEG uses a slightly modified version of rec. 601](https://en.wikipedia.org/wiki/YCbCr#JPEG_conversion). This is likely what causes the discrepancy.

Using the standard conversion, I get values very similar (they are sometimes off by one 😕) that of a PNG. 

I'll try to create a fix, using this knowledge some time soon. 😀

Good find!


-- 
Harald K

**Comment by garthhenning** [comment]
That does indeed seem like it fits all of the symptoms exactly. I can imagine that there are some circumstances where some of the integer rounding might produce a value that is off by 1 between PNG and WEBP, so that might not even technically be a bug. 

I really appreciate that you are queuing up this fix. Your work to bring a solid implementation of the WEBP format to Java is of enormous benefit to the community. Thank you.

**Comment by haraldk** [comment]
Closing this for now, awaiting the release. 

Feel free to reopen or file a new issue, if you are able to send me a few sample files for comparison.
 

-- 
Harald K
