### ISSUE TITLE
Read Jpg：throw No SOF segment in stream

### ISSUE THREAD

**Issue by jlutt** [haraldk/TwelveMonkeys#620]
Sorry my poor English!

Read the file,the file is jpg file and header is ffd8，but throw exception
```
Exception in thread "main" javax.imageio.IIOException: No SOF segment in stream
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:886)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:293)
	at TestImage.main(TestImage.java:41)
```

```
         File srcFileJPG = new File("D:\\1.jpg");
        try (ImageInputStream input = ImageIO.createImageInputStream(srcFileJPG)) {
            // Get the reader
            Iterator<ImageReader> readers = ImageIO.getImageReaders(input);

            if (!readers.hasNext()) {
                throw new IllegalArgumentException("No reader for: " );
            }

            ImageReader reader = readers.next();
            reader.setInput(input);
            System.out.println(reader.getClass().getName());

            ImageReadParam param = reader.getDefaultReadParam();
            BufferedImage image = reader.read(0, param);
            Thumbnails.of(image).scale(0.7).outputQuality(0.5).outputFormat("jpg").toFile("D:\\1_thumb.jpg");
        }
```

![1](https://user-images.githubusercontent.com/11289075/130211826-5077ef69-f1b9-40c3-b993-3bcf68f18eed.jpg)

**Comment by haraldk** [comment]
Hi @jlutt,

Your sample image seems to read just fine for me, using the latest version of the library. If you are using a different version, I suggest upgrading to the 3.7.0 version. Not sure what Java version you are on, but works fine for me using 1.8, 11 and 15. 

Can't see anything unormal about the file either. 

Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
I'm closing this as not reproducible for now. 

But feel free to re-open, if you have the time to add the relevant details necessary to exactly reproduce the situation. 

Best regards,

-- 
Harald K
