### ISSUE TITLE
Wrong color on Linux enviroment

### ISSUE THREAD

**Issue by alachina** [haraldk/TwelveMonkeys#622]
We are using your library calling java code from within java ETL enviroment (Talend Studio Integration) and we are able to correctly open an image with Space color CMYM, resize it, crop margin, and save it. From an Windows enviroment no problem are faced. Run code in Server side (Centos 7.5) result a writed image with wrong color

**Version information**
1. 3.7

2. Local windows (working correctly):
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

Remote server  (bug present):
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

3. 
**To Reproduce**
1. use imageIO lib to read file original file attached
2. use imageIO lib to write buffer Image created 

**Expected behavior**
same image (transformed from jpg with CMYK Space color to RGB)

**Example code**
File f = new File(imagePath);
BufferedImage source;
source = ImageIO.read(f);
ImageIO.write(source , "jpg", f);

**Sample file(s)**
I attach origina image file and a zip contaning a test package.
To test simply run
java -cp .;* ImgResize original_image.jpg

**Comment by alachina** [comment]
[test_java.zip](https://github.com/haraldk/TwelveMonkeys/files/7082981/test_java.zip)

**Comment by haraldk** [comment]
@alachina 

As the code works on Windows (and also on my MacOS machines) it's unlikely that this is a bug in the library. I used the example code you provided above to verify, as the sample project is way to complex for a bug report. It also seems to use other libraries for CMYK conversion. 

Unfortunately, I'm also unable to reproduce the issue as I don't have access to any CentOS or other Linux environment. 

If you send me the output image from the CentOS environment (created from the attached input), I might give you some input on what is wrong. Other than that, I think you will have to attach a debugger to the Java process on the CentOS environment and look into why things behave differently. Perhaps that will inspire you to make a PR with a fix? 😀 

PS: The included image is a normal YCbCr encoded RGB JPEG, it does not use a CMYK color space. Was this intentional? 


Best regards,

-- 
Harald K

**Comment by alachina** [comment]
Hi Harald, perhaps this is a problem on Standard ImageIO llibs.
I attach Original file, and Original just opened with IO read and then IO
Write, on Linux and then On Windows.

Sample code:

File f = new File(imagePath);
BufferedImage source = ImageIO.read(f);
boolean ok = writeImage(source, imagePath);

Yer for me is ok that the destination file is an RGB, we don't need CMYK
image, that seems to create a lot of problems for us...

Thanks
Alessandro Lachina ***@***.***>

*Sistemi Informativi*


spa
Via Olanda, 2
35127 Padova
Tel.0498692214 - Fax.0498692200
www.alisupermercati.it


Il giorno mar 31 ago 2021 alle ore 16:32 Harald Kuhr <
***@***.***> ha scritto:

**Comment by haraldk** [comment]
Hi again,

I'm sorry, but the above does not make much sense to me... 

1. There is only one file included in the zip, named `original_image.jpg`, and it is NOT a CMYK file. I don't see how that can be used to recreate the situation initially explained, which seemed to involve CMYK *input*.
2.  There are no attachments in the latest message (GitHub doesn't support email attachments, if that was the case. You need to upload them using the web UI). 
3. What is the `writeImage()` method in the latest code sample? I would assume it was just `ImageIO.write(...)` but that would make the sample identical to the one in the original request..? 


-- 
Harald K

**Comment by alachina** [comment]
Sorry now I've attached file directly from web UI.
[file.zip](https://github.com/haraldk/TwelveMonkeys/files/7088864/file.zip)

Yes writeImage is simply ImageIO write, I've do some test specifing additional parameter with ImageWrite but nothing change.

public static boolean writeImage(BufferedImage bi, String imagePath){
		try {
			//Metodo classico con imp di default, da problemi di colore con CMYK
			File f = new File(imagePath);
			ImageIO.write(bi, "jpg", f);
			//Test con parametri aggiuntivi
			/*
			Iterator iter = ImageIO.getImageWritersByFormatName("jpeg");
			ImageWriter writer = (ImageWriter)iter.next();
			// instantiate an ImageWriteParam object with default compression options
			ImageWriteParam iwp = writer.getDefaultWriteParam();
			iwp.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
			iwp.setCompressionQuality(1);   // an integer between 0 and 1
			// 1 specifies minimum compression and maximum quality

			File file = new File(imagePath);
			FileImageOutputStream output = new FileImageOutputStream(file);
			writer.setOutput(output);
			IIOImage image = new IIOImage(bi, null, null);
			writer.write(null, image, iwp);
			writer.dispose();
			*/
			
			return true;
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return false;
		}

	}

**Comment by haraldk** [comment]
Thanks,

Okay, now it makes sense! 😀 

The original (`original_image.jpg` from `file.zip`) is in CMYK color space, but *does not contain an ICC profile* (you will get a warning about this, if you attach a warning listener to the `ImageReader` before reading). This means that the colors are converted to RGB using either:

- a fallback "Generic CMYK" profile *if one is found on the host system*
- or just a fast linear conversion as a fall back if no profile is found

The linear conversion usually creates very vibrant and "clean" colors, but looks unnatural for most photographic images like yours. 

So, what likely happens is that on the Windows computer, the profile is found and used (default is `C:/Windows/System32/spool/drivers/color/RSWOP.icm` for Windows) but on the Linux computer, no profile is found and the fallback algorithm is found.

To fix, you can place a properties-file on class path, named `com/twelvemonkeys/imageio/color/icc_profiles.properties`:

    GENERIC_CMYK=<path to CMYK profile>
    #ADOBE_RGB_1998=<path to AdobeRGB1998 profile>

(An open source equivalent of AdobeRGB1998 profile is bundled with the library, so you probably won't need it, but I have not yet found an open source CMYK profile that is a) good enough and b) has reasonable file size). 

You can download free ICC profiles from Adobe, ICC consortium and more. 

I will try to update the readme/Wiki to make this more straight-forward in the future!


Best regards,

-- 
Harald K

**Comment by alachina** [comment]
Talend Support give me possibility to add file to class path, I've test again if in this way is corretly applied a Profile but nothing change.
So how to check if it correctly searching ICC profile specified in .properties?
Or if  .properties is not readed.
![test](https://user-images.githubusercontent.com/9430250/131671383-1c40c266-ebcc-4ca5-8f7c-a596a0b00bee.jpg)
[icc_profiles.properties.txt](https://github.com/haraldk/TwelveMonkeys/files/7091014/icc_profiles.properties.txt)

**Comment by haraldk** [comment]
The file itself looks good. Did you also create the correct folder structure? It needs to be exactly as I specified above. It may also be placed inside a JAR with the same structure. 

You should get some information on the console during startup/first conversion, by setting the system property `com.twelvemonkeys.imageio.color.debug` to `true` (ie. passing `-Dcom.twelvemonkeys.imageio.color.debug=true` to the `java` command).

You should see something like: 

    User ICC profiles: {GENERIC_CMYK=<your path>, ...}
    System ICC profiles : {...}

And either:

    Loading profile from: <your path>

or

    Using fallback profile


Best regards,

-- 
Harald K

**Comment by alachina** [comment]
Great! using a jar with exact correct path and import as module in Talend, ICC Profile it's correctly loaded and now conversion respect color also from Linux server!
Thank a lot

ICC ProfileCleaner instance: com.twelvemonkeys.imageio.color.LCMSSanitizerStrategy
User ICC profiles: {ADOBE_RGB_1998=/home/talenduser/jobserverdata/iccProfiles/RGB/AdobeRGB1998.icc, GENERIC_CMYK=/home/talenduser/jobserverdata/iccProfiles/CMYK/CoatedFOGRA27.icc}
System ICC profiles : {}
Loading profile from: /home/talenduser/jobserverdata/iccProfiles/CMYK/CoatedFOGRA27.icc
Building YCC conversion table

**Comment by haraldk** [comment]
Output looks all good! 



-- 
Harald K
