### ISSUE TITLE
TGA 4BYTE_BGRX image fails to transform. Possible cause in custom bandoffsets for 32-bit depth of image

### ISSUE THREAD

**Issue by KoenDG** [haraldk/TwelveMonkeys#623]
**Describe the bug**
Filtering certain TGA images results in an exception:

```
java.awt.image.ImagingOpException: Unable to transform src image
```

Explanation below with code example.

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
`3.7.0`, the TGA plugin.

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 

```
$ java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment Corretto-8.275.01.1 (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM Corretto-8.275.01.1 (build 25.275-b01, mixed mode)
```

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

A jar with some GC flags, cannot share full details.

**To Reproduce**

1. Compile the below sample code
2. Use the provided sample image
3. Run the code with the sample file

I don't know for sure why this happens, though I suspect it has to do with this: https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-tga/src/main/java/com/twelvemonkeys/imageio/plugins/tga/TGAImageReader.java#L141

If the bitdepth is 32, a TGAImageReader will return an `ImageTypeSpecifier` with bandOffsets: `new int[] {2, 1, 0, 3}`

This, combined with how BufferedImage behaves, I suspect is the root cause of the issue. But I can't be sure.

**Expected behavior**
The file gets filtered without error

**Example code**
```
File orig = new File(...); // Absolute path to file
ImageInputStream input = ImageIO.createImageInputStream(orig); // javax.imageio.ImageIO
Iterator<ImageReader> readers = ImageIO.getImageReaders(input);
ImageReader reader = readers.next();
reader.setInput(input);

ImageReadParam param = reader.getDefaultReadParam();
 // This is where the bandOffset gets set to what it is.
BufferedImage originalImage = reader.getImageTypes(0).next().createBufferedImage(reader.getWidth(0), reader.getHeight(0));
param.setDestination(originalImage);

try {
    originalImage = reader.read(0, param); // Don't really need the return value here, as it will always be same value as "image"
} catch (javax.imageio.IIOException e) {
    // See: https://github.com/haraldk/TwelveMonkeys/issues/197
    // Ignore this exception or display a warning or similar, for exceptions happening during decoding
    logger.warn(e.getMessage(), e);
}

int width = 240; // Known for this image
int height = 164; // Known for this image

AffineTransform transform = new AffineTransform();
AffineTransformOp op = new AffineTransformOp(transform, AffineTransformOp.TYPE_NEAREST_NEIGHBOR);
BufferedImage resultImage = op.createCompatibleDestImage(originalImage, (originalImage.getType() == BufferedImage.TYPE_BYTE_GRAY) ? originalImage.getColorModel() : null);
Graphics2D g = resultImage.createGraphics();
g.setBackground(Color.WHITE);
g.clearRect(0, 0, resultImage.getWidth(), resultImage.getHeight());
resultImage = op.filter(originalImage, resultImage); // The exception happens here
```

When creating the bufferedimage, it will pass here: https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/classes/java/awt/image/BufferedImage.java#L785-L801

The condition:

```
offs[0] == numBands-1 &&
offs[1] == numBands-2 &&
offs[2] == numBands-3
```

Will fail, as there are 4 bands. 4 minus 1 is 3, but the first item of `2,1,0,3` isn't `3`. At this point the code has no alternative and the BufferedImage ends up with `imageType` `TYPE_CUSTOM`.

The code ends up here: https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/classes/java/awt/image/AffineTransformOp.java#L284

And inside that method goes here: https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/classes/sun/awt/image/ImagingLib.java#L254

`transformBI` is a native method, I can't find details on how it works.

The condition fails and `retBI` never gets assigned. It is returned as `null`. Which causes the exception.

**Sample file(s)**
This file from this repo can cause it: https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-tga/src/test/resources/tga/XING_T32.TGA

**Stack trace**
```
java.awt.image.ImagingOpException: Unable to transform src image
        at java.awt.image.AffineTransformOp.filter(AffineTransformOp.java:285)
        // Own code
```

Sorry if this is a lot. I spent quite some time debugging it and am not even sure of what I saw anymore.

**Comment by haraldk** [comment]
Hi Koen,

I can reproduce your results. And I agree that is really annoying. However, I'm not sure if I buy the premise; that feeding the result of library A into library B, and if library B fails with a meaningless exception, that indicates a bug in library A... Did you file a bug report to OpenJDK? 😉

The fact is that these 32 bit TGA files really have a layout of BGRA or BGRx internally (the last 8 bits are either alpha or just ignored), and this is reflected in the band offsets `{2, 1, 0, 3}`. There's nothing wrong or incorrect with a `BufferedImage` being `TYPE_CUSTOM`. One could perhaps argue that using `TYPE_INT_BGR` would be more natural for for the non-alpha case. But, there is no `TYPE_INT_BGRA`, so we would have to byte-swap these to get `TYPE_INT_ARGB`, or create another `TYPE_CUSTOM` BGRA layout. In either case this will make the reader more complex. I guess it's a valid feature request though...

Until then, you can easily work around this issue in client code by creating a new `BufferedImage` of the desired type, and paint the original into it, before passing it to the `AffineTransformOp`. 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
>  ~~One could perhaps argue that using `TYPE_INT_BGR` would be more natural for for the non-alpha case. But, there is no `TYPE_INT_BGRA`, so we would have to byte-swap these to get `TYPE_INT_ARGB`, or create another `TYPE_CUSTOM` BGRA layout. In either case this will make the reader more complex.~~ 

As TGA is using little endian byte order, the pixel layout will be byte swapped to `TYPE_INT_RGB/TYPE_INT_RGBA` automatically, making this easier than I initially thought. I think we can make this work!

I still think `AffineTransformOp/ImagingLib` is broken though. 😉 

-- 
Harald K

**Comment by KoenDG** [comment]
Nice to hear. I'll try this out, hopefully tomorrow. Not sure what you mean by `creating a new BufferedImage of the desired type, and paint the original into it` but I'm hopeful that's an easy find on google.

**Comment by haraldk** [comment]
That's basically:


```java
BufferedImage original;
int type = BuffferedImage.TYPE_INT_ARGB; // Or whatever you like

// Create a buffered image
BufferedImage image = new BufferedImage(original.getWidth(), original.getHeight(), type);

// Draw the image onto the buffer
Graphics2D g = image.createGraphics();
try {
    g.setComposite(AlphaComposite.Src);
    g.drawImage(original, 0, 0, null);
}
finally {
    g.dispose();
}
```

-- 
Harald K

**Comment by KoenDG** [comment]
Thanks, but I just realized I'd need to do some parsing to actually determine the BufferedImage imageType I'd want, in all possible cases.

I'll leave it at this for now.

Thanks for your help.

**Comment by haraldk** [comment]
@KoenDG 

I submitted a fix for this issue (and same issue in SGI and PCX/DCX formats), along with some other minor improvements. I believe that will fix this issue for you, but please test and report back if it doesn't. 😀 

Thanks a log for your report, excellent PR and feedback! 


Best regards,

-- 
Harald K

**Comment by KoenDG** [comment]
Fix confirmed. I added a quick unit test using the code I put up there, and ran it once on master, once on an older git commit. Most recent code runs fine, older code gives the expected error.
