### ISSUE TITLE
TIFFImageMetadata outputs rationals without denominator, incompatible with JAI

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#628]
See [Strange exception when trying to save TIFF with DPI](https://stackoverflow.com/q/69220990/1428606) (StackOverflow question) for details.

The reason is that `Rational.toString()` outputs "200" instead of "200/1" when denominator is 1, and the JAI `TIFFImageMetadata` implementation expects the '/' separator to always be there...

**Comment by DP486** [comment]
When this fix gets released and with which version?

**Comment by haraldk** [comment]
@DP486 I might release a 3.7.1 bug fix release with this and some other minor issues. Otherwise it will be in 3.8.0 for sure.
It will be released as soon as I find the time.  

PS: Please consider becoming a sponsor, if you'd like regular releases. 😀 

.k

**Comment by DP486** [comment]
@haraldk: Thank you
