### ISSUE TITLE
read jpg image but too much red

### ISSUE THREAD

**Issue by dream0411** [haraldk/TwelveMonkeys#630]
Hi, thank you for this great software!

I found this problem recently. Read some jpg file but it looks like too much red. 

no problem env:    jdk8 + macos/centos6 + jdk jpeg
problem env:   jdk8 + centos6 + TwelveMonkey jpeg 3.7.0

I'm sure CentOS 6 don't have system icc file, and tried #622 with CoatedFOGRA27.icc but nothing changed.

reading in this code:

BufferedImage img = ImageIO.read(new URL(srcImage));

original file:
![ok_face](https://user-images.githubusercontent.com/1435705/134904287-d438563f-7f2e-4ca7-a26d-eef6dfe80812.jpg)

read in IDEA:
![image](https://user-images.githubusercontent.com/1435705/134905602-e053cdf2-9c53-4b95-b9a4-e23b2c076433.png)

I checked CoatedFOGRA27.icc file likes this:
1、write this code somewhere and debug it:
ColorSpace colorSpace = ColorSpaces.getColorSpace(ColorSpaces.CS_GENERIC_CMYK);
2、check variable in method loadProfiles() of com/twelvemonkeys/imageio/color/ColorSpaces.java
![image](https://user-images.githubusercontent.com/1435705/134907796-da55cfa8-6e23-4525-8c1e-50d23adeb064.png)

Any suggestion is welcome, thanks!

**Comment by haraldk** [comment]
Hi @dream0411 

I'm not sure I follow... Your "original file" is a normal YCbCr encoded (RGB) JFIF. But `CoatedFOGRA27.icc` is a CMYK ICC profile and not used for RGB data. So I don't think the ICC profile is relevant at all. 

The image is also displayed correctly on my computers, using any version of Java, with or without the TwelveMonkeys ImageIO JPEG plugin. 

Are you absolutely sure that the original file is exactly the same as you use in your code? Also, I would need to to see the code you use to produce the result you see in IntellIJ, if you want me to look further into this.

-- 
Harald K

**Comment by dream0411** [comment]
Thanks for reply!

The “original file" can be replace with this image url, it's bigger and used to repeat problem.
http://p0.meituan.net/movie/4ddd3e5806f20678c0ef12b3581dd51e925954.jpg

The problem is only for linux, my mac computer works correctly.

I tried this again and got the same problem, here's the steps.

1. Build a demo project, here is the source and packed jar. 

import imageio-jpeg in pom.xml, and source file looks like this:
public class Main {

    public static void main(String[] args) throws IOException {
        String srcImage = "http://p0.meituan.net/movie/4ddd3e5806f20678c0ef12b3581dd51e925954.jpg";
        BufferedImage img = ImageIO.read(new URL(srcImage));

        ImageIO.write(img, "JPEG", new File("out.jpg"));// 输出到文件流
        System.out.println("generated file out.jpg");
    }
}

source project:
[red-jpeg.zip](https://github.com/haraldk/TwelveMonkeys/files/7240727/red-jpeg.zip)

packed jar:
(please rename it to .jar instead of .zip, github doesn't support upload jar)
[red-jpeg-1.0-SNAPSHOT-jar-with-dependencies.zip](https://github.com/haraldk/TwelveMonkeys/files/7240683/red-jpeg-1.0-SNAPSHOT-jar-with-dependencies.zip)

2. upload this jar to remote linux machine(centos 6), and execute cmd:
java -jar red-jpeg-1.0-SNAPSHOT-jar-with-dependencies.jar

this cmd generated a out.jpg, download it and found a much more red image.

this is the image file, and it's already in the project zip:
![out](https://user-images.githubusercontent.com/1435705/135017027-0503a8a4-7744-4471-a143-251bf8e27e40.jpg)

I debug with jdb in linux machine, BufferedImage variable show likes this, may be a bit help:

main[1] print img
 img = "BufferedImage@57e1b0c: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@4232c52b transparency = 1 has alpha = false isAlphaPre = false ByteInterleavedRaster: width = 1400 height = 755 #numDataElements 3 dataOff[0] = 2"

Thanks for help.

**Comment by haraldk** [comment]
Hi again, @dream0411 

I still can't see anything special about your original image, that would cause the "weird" colors (the effect you see in `out.jpg`, is YCbCr encoded data that is not correctly converted to RGB). For me it works fine both with and without the TwelveMonkeys JPEG plugin, in any of the Java versions I have installed. But I don't have a CentOS/Linux environment available for testing, so I'm not able to exactly reproduce your results there.

However, you could try running your Java application on CentOS with the system property ` -Dcom.twelvemonkeys.imageio.plugins.jpeg.debug=true`, and send me the output (std out). This should print something like:

````
segments: [<segments of your file...>]
Start seeking for image <...>
Reading using <...>
````

PS: Please don't send prebuilt JARs, as I need to see the source code anyway, to know what I'm running. 😀 


Best regards,

-- 
Harald K

**Comment by dream0411** [comment]
Hi, @haraldk 

the debug output is:

segments: [APP0/JFIF v1.01 72x72 dpi (no thumbnail), DQT[], DQT[], SOF0[ffc0, precision: 8, lines: 755, samples/line: 1400, components: [id: 1, sub: 1/1, sel: 0, id: 2, sub: 1/1, sel: 1, id: 3, sub: 1/1, sel: 1]], DHT[id: 0, class: 0], DHT[id: 0, class: 1], DHT[id: 1, class: 0], DHT[id: 1, class: 1], SOS[spectralSelStart: 0, spectralSelEnd: 63, approxHigh: 0, approxLow: 0, components: [scanCompSel: 1, acTabSel: 0, dcTabSel: 0, scanCompSel: 2, acTabSel: 1, dcTabSel: 1, scanCompSel: 3, acTabSel: 1, dcTabSel: 1]]]
Read metadata in 14 ms
Reading using delegate

I found something different else in the com/sun/imageio/plugins/jpeg/JPEGImageReader.java.

the colorSpaceCode of JPEGImageReader in linux is 2
the colorSpaceCode of JPEGImageReader in macos is 3

Is it because the different jdk8 version or machine? I will tried to replace jdk8 verison in macos later(not very easy to find same version jdk).

// java version in centos:
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

// java version in macos:
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

I'm really happy for your help, thank you.

**Comment by haraldk** [comment]
> the debug output is:

Looks exactly as expected. 👍🏻 

> the colorSpaceCode of JPEGImageReader in linux is 2
> the colorSpaceCode of JPEGImageReader in macos is 3

This is indeed the problem... `2` means RGB, `3` means YCbCr. `3` is the correct value for the input image. 

There is a method `com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader#delegateCSTypeMismatch` which should detect the situations where the JDK plugin choses the wrong color space, and we need to apply special handling. We might have to add more cases here, if the CentOS implementation is different... Perhaps you could step through the debugger, and see where that method fails?

Is the CentOS JDK an Oracle JDK, or a different JDK? I can't see from the Java version output...

But you initially wrote that you didn't have this problem without the TwelveMonkeys plugin on CentOS? That's a bit odd... But perhaps there is a "reverse" issue in the writer, so it ends up writing the correct thing even if the reader is wrong? You could try writing a different format, like PNG, and see if you still get correct color?

I'm afraid I can't help as much I'd like without a Linux environment... But we might be able to work out something together. 

-- 
Harald K

**Comment by dream0411** [comment]
Hi, I found the problem java version.

I tried jre1.8.0_45 on mac computer and got the same wrong color image. 

Looks like that jre1.8.0_45 + TwelveMonkeys JPEG plugin makes this problem, because this jre version doesn't produce uncorrect image it self.

If you want this jdk version, it's here:
https://www.oracle.com/cn/java/technologies/javase/javase8-archive-downloads.html#license-lightbox

By the way, I tried to write a png file and still got red color image. 😄

I think, is it possible to change my code to make everything right? Because I can't change the jre version in linux machines but still want to keep TwelveMonkeys JPEG plugin for processing CMYK jpeg images 😅

**Comment by dream0411** [comment]
TIP:

Oracle jdk website show wrong jdk version url, if you click jdk-8u45 download button, it will give you 8u92.

I tried to change the source html of the download button to 8u45 and downloaded a correct jdk version. Like this:
![image](https://user-images.githubusercontent.com/1435705/135067739-a0c7778c-00b7-43dc-ba5d-40fb8b95e9be.png)

😅

**Comment by haraldk** [comment]
> Hi, I found the problem java version.
> I tried jre1.8.0_45 on mac computer and got the same wrong color image.

Good catch! 😀

> I think, is it possible to change my code to make everything right? Because I can't change the jre version in linux machines but still want to keep TwelveMonkeys JPEG plugin for processing CMYK jpeg images 😅

I'm not saying it's impossible. But I can tell you with 100% certainty that upgrading the JRE will be a much easier task than working around this issue. And I say that with several years of experience trying to work around such issues... The bug is likely in native code.

If upgrading to a later JRE will fix the issue, that is for sure the way to go. The current Java 1.8 JRE is 8u301 (a 100+ revisions later), so upgrading is long overdue anyway.

If you want to try to work around, I suggest making a patch for the `com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader#delegateCSTypeMismatch` method and build your own version that works with this specific JDK. Or submit PR with a fix for this issue that doesn't affect other versions of the JDK. But I really recommend upgrading! 😀 


Best regards,

-- 
Harald K

**Comment by dream0411** [comment]
Hi, I will try to work around other solutions for processing jpeg images.

Thank you so much, having a nice day 😊
