### ISSUE TITLE
The attached WebP image is not working

### ISSUE THREAD

**Issue by Horcrux7** [haraldk/TwelveMonkeys#632]
The attached WebP image was not parsed with version 3.7.0. It look like it was not detected as WebP image. Because other WebP images can be parsed this must be related to the image. The browsers can show the image. This means it is valid.

I use the follow code:
```
ImageInputStream stream = ...
ImageIO.getImageReaders( stream ).hasNext();

```
Attached as zip because Github does not accept WebP files.
[giphy_1.webp.zip](https://github.com/haraldk/TwelveMonkeys/files/7284189/giphy_1.webp.zip)

**Comment by haraldk** [comment]
Not at my laptop right now, but keep in mind that our WebP plugin only supports lossy, non- transparent data at the moment. If your file is lossless, or has alpha channel, we don’t claim to be able to read it. 

— 
Harald K

**Comment by haraldk** [comment]
Hi,

Your attached file is in the WebP extended format (`VP8X`), and contains animation (`ANIM` and `ANMF`) chunks, which are not yet supported. 

If this is a feature you would like to see in the future, you should consider becoming a sponsor.

-- 
Harald K
