### ISSUE TITLE
is there any plugin for reading .ai(adobe illustrator) files

### ISSUE THREAD

**Issue by ThreefLi** [haraldk/TwelveMonkeys#634]
i have tried using all the plugins in my projects, but still got 'No suitable ImageReader found for source data'

**Comment by haraldk** [comment]
Hi @ThreefLi ,

All [supported formats are listed on the homepage](https://github.com/haraldk/TwelveMonkeys#file-formats-supported). 

So, no. There's no plugin for Illustrator files. 

With a few exceptions, we mostly support raster formats as that's what `ImageIO` is for. `.ai` is a vector format (it's basically PostScript). But it could be possible to either extract an embedded preview (if one exists), or make a rendering to a `BufferedImage` like we do for PICT or SVG. I don't have any plans to add this for the moment.

-- 
Harald K
