### ISSUE TITLE
Writing multi resolution ICNS file

### ISSUE THREAD

**Issue by lanthale** [haraldk/TwelveMonkeys#644]
I am under way to write an icon creator for ICNS and ICO. 

Both formats are valid only if inside of the file a multi-resolution image is there.
But how can I create such a file with twelve-monkey ?

**Comment by haraldk** [comment]
You can write multi-image files using the standard `ImageWriter` API methods, `prepareWriteSequence`, `writeToSequence` and `endWriteSequence`. 

For complete examples on writing both ICO and ICNS, see the `main` method of the respective writers ([ICNS](https://github.com/haraldk/TwelveMonkeys/blob/511a29beb91a8fffd89287b0ae62820b43770afe/imageio/imageio-icns/src/main/java/com/twelvemonkeys/imageio/plugins/icns/ICNSImageWriter.java#L221) and [ICO](https://github.com/haraldk/TwelveMonkeys/blob/511a29beb91a8fffd89287b0ae62820b43770afe/imageio/imageio-bmp/src/main/java/com/twelvemonkeys/imageio/plugins/bmp/ICOImageWriter.java#L277)). 

Note that for ICNS, only certain specific sizes are allowed by the format. 

Hope that helps! If you encounter any issues, let me know! 

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now. Feel free to reopen if you have further questions.
