### ISSUE TITLE
WEBP images created with GIMP not readable

### ISSUE THREAD

**Issue by BigMichi1** [haraldk/TwelveMonkeys#646]
**Describe the bug**
WEBP images created with GIMP are not readable. I tried lossy and lossless output format when saving them, both are not readable. When I check the general functionality with downloaded images from the internet it works. So something must be different or causing an issue in the images created by GIMP

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.8.0

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 

    openjdk version "15.0.2" 2021-01-19
    OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
    OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.
    it is a standalone program (packed by maven) containing only the dependency on `com.twelvemonkeys.imageio:imageio-webp:3.8.0`

GIMP version: 2.10.28

**To Reproduce**

1. Compile the below sample code
2. Download the sample image files
3. Run the code with the sample files
4. last to results are `null` (these two files have been generated with GIMP, the `example.webp` file is downloaded from internet to verify that it works in general

1. use GIMP with the attached BMP file and export it as a webp image (lossless and lossy)
2. run sample program again

**Expected behavior**
be able to read webp images created by GIMP

**Example code**
```java
package com.example.demo;

import javax.imageio.ImageIO;

public class Demo1Application {

    public static void main(String[] args) {
        try {
            final var example = ImageIO.read(Demo1Application.class.getClassLoader().getResourceAsStream("example.webp"));
            System.out.println("example = " + example);
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            final var loosy = ImageIO.read(Demo1Application.class.getClassLoader().getResourceAsStream("test_pattern_gimp_loosy.webp"));
            System.out.println("loosy = " + loosy);
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            final var looseless = ImageIO.read(Demo1Application.class.getClassLoader().getResourceAsStream("test_pattern_gimp_looseless.webp"));
            System.out.println("looseless = " + looseless);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
```

**Sample file(s)**
webp image from internet do verify that it works generally
[example.zip](https://github.com/haraldk/TwelveMonkeys/files/7710913/example.zip)
files created by GIMP in webp format
[looseless.zip](https://github.com/haraldk/TwelveMonkeys/files/7710914/looseless.zip)
[loosy.zip](https://github.com/haraldk/TwelveMonkeys/files/7710915/loosy.zip)
Original use to create the webp files with GIMP
[test_patter.zip](https://github.com/haraldk/TwelveMonkeys/files/7710919/test_patter.zip)

**Stak trace**
no stacktrace shown, just read return `null`

**Screenshots**
-

**Additional context**
-

**Comment by haraldk** [comment]
Hi Michael,

Thanks for reporting! 

However, as [mentioned](https://github.com/haraldk/TwelveMonkeys/wiki/WebP-Plugin), we only have

> support for lossy WebP, using VP8 encoding and simple format

at the moment. So the lossless file can't be read, as expected.

GIMP seems to write files in "extended format", even for simple lossy encoding without alpha. Perhaps there is a setting to make GIMP output "simple format" files? In any case, our WebP reader will actually read such files just fine, if you "force" it. The Spi just doesn't claim to read the extended format (as we don't support lossless and alpha yet). You can try it out like this:

````java
try (ImageInputStream input = ImageIO.createImageInputStream(file)) {
    ImageReader reader = ImageIO.getImageReadersByFormatName("WEBP").next(); // Will fail if the plugin isn't installed
    reader.setInput(input);
    BufferedImage image = reader.read(0);
    System.out.println("image: " + image);
    // ..and probably show it... 😀 
}
````

In the future, this will of course change.  But as for now, the behavior you see is expected.

**Comment by haraldk** [comment]
I pushed a small change that will make the lossy files from GIMP work using `ImageIO.read()`.

**Comment by haraldk** [comment]
Should now work with the 3.8.1 release.
