### ISSUE TITLE
Force TGA files to be saved with an alpha channel to allow 32bpp format

### ISSUE THREAD

**Issue by PlayerHOI** [haraldk/TwelveMonkeys#649]
**Is your feature request related to a problem? Please describe.**
Hi, thank you for this amazing tool.

I have a need to save converted image files to a TGA format in 32bpp and the only outcome I currently get is 24bpp (bits per pixel). These are used for a game engine that flips the files upside down if they are not in 32bpp as well as producing plenty of errors in said game engine so just flipping them again to look ok is not a valid solution.

**Describe the solution you'd like**
It would be great if there was a way to force the ImageIO.write method to add an alpha channel for a file outputted in TGA format. Maybe by including a specific tag, for example:
```
if (!ImageIO.write(output, "**TGA-32**", outputImage)) {
}
```

**Describe alternatives you've considered**
Nothing I could find really...

**Additional context**
Add any other context or screenshots about the feature request here, like links to specifications or sample files.

**Comment by haraldk** [comment]
Hi,

The `TGAImageWriter` already fully supports writing TGA 32 bit. It will write in a format that best matches the image your pass in. If your images does not contain alpha, all you need to do, is convert your images to a 32 bit image type, like `TYPE_4BYTE_BGRA` or `TYPE_INT_ARGB`:

```java
BufferedImage original;
BufferedImage copy = new BufferedImage(original.getWidth(), original.getHeight(), BufferedImage.TYPE_INT_ARGB);

Graphics2D g = copy.createGraphics();
try {
    g.setComposite(AlphaComposite.Src);
    g.drawImage(original, 0, 0, null);
}
finally {
    g.dispose();
}
```

Hope that helps!
