### ISSUE TITLE
Unsupported SamplesPerPixel/BitsPerSample combination for RGB TIFF (expected 3/8, 4/8, 3/16 or 4/16): 4/2048

### ISSUE THREAD

**Issue by sunishkumar** [haraldk/TwelveMonkeys#654]
I am getting the following exception while trying to read a tiff file.

Unsupported SamplesPerPixel/BitsPerSample combination for RGB TIFF (expected 3/8, 4/8, 3/16 or 4/16): 4/2048

**Comment by haraldk** [comment]
Yes, 2048 bits per pixel is definitively not supported. What data type would you use to hold such a value?

Do you think this is an error? If so, I need to see the file.

**Comment by sunishkumar** [comment]
[Sample.zip](https://github.com/haraldk/TwelveMonkeys/files/7862603/Sample.zip)

I am trying to read this file. I don't know what is  2048 bits per sample meant for this image. I am able to view the image using other image viewers. Will you please help me in identifying what is the issue and how to resolve it.

Thank you.

**Comment by haraldk** [comment]
What version of Java and TwelveMonkeys are you using? 

What does your code look like? Can you reproduce this in a small standalone application or JUnit test? 

I don't have any problems reading this file using TwelveMonkeys 3.8.1 on any of my installed Java versions. There is no error or mention of `2048` bits per sample (as in your exception message) anywhere as far as I can see...

**Comment by sunishkumar** [comment]
You are correct. It was due to presence of some other image-io plugin in class path.
Thank you
