### ISSUE TITLE
Some TGA files are not parsed

### ISSUE THREAD

**Issue by kirill-782** [haraldk/TwelveMonkeys#658]
The following code returns NULL when parsing the following files

`BufferedImage img = ImageIO.read(new File("..."));`

[images.zip](https://github.com/haraldk/TwelveMonkeys/files/7891914/images.zip)

**Comment by haraldk** [comment]
Hi @kirill-782,

Thanks for reporting! 

The problem with TGA files, is that they don't contain a "magic" value in the header, so they are hard to detect reliably... 

Both files in your collection are TGA files in RGB mode, one RLE compressed, one uncompressed. They don't contain color maps, but they both state that they contain color maps of depth 24... Which is not recommended (instead the field should be left as 0 in this case). The reader currently only recognizes the recommended value.

But it is relatively easy to fix. I'll add one of the images to the test suite to verify, along with the fix some time soon.

**Comment by kirill-782** [comment]
@haraldk, Thank you for the quick response.

I think I found another problematic file. There is already IIOException

`
javax.imageio.IIOException: TGA Extension Area size less than 495: 0
	at com.twelvemonkeys.imageio.plugins.tga.TGAExtensions.read(TGAExtensions.java:78)
	at com.twelvemonkeys.imageio.plugins.tga.TGAImageReader.readHeader(TGAImageReader.java:414)
	at com.twelvemonkeys.imageio.plugins.tga.TGAImageReader.getRawImageType(TGAImageReader.java:117)
	at com.twelvemonkeys.imageio.plugins.tga.TGAImageReader.getImageTypes(TGAImageReader.java:96)
	at com.twelvemonkeys.imageio.plugins.tga.TGAImageReader.read(TGAImageReader.java:169)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315)
`

[image.zip](https://github.com/haraldk/TwelveMonkeys/files/7892457/image.zip)

**Comment by haraldk** [comment]
Okay,

This new file has a different problem, it contains an offset to an "extension area", and have the size field of the extension area set to 0. The spec says that the offset should be 0 in this case, and no extension area should be present. 

Again, it's an easy fix, and doesn't affect the image data, so we might as well allow it.

**Comment by haraldk** [comment]
Both issues are addressed in the latest SNAPSHOT build if you like to try it out.
