### ISSUE TITLE
TIFF support reading 4 bits per sample RGB data

### ISSUE THREAD

**Issue by Schmidor** [haraldk/TwelveMonkeys#666]
Currently only 8 or 16 bits per sample RGB data is supported.

This is a LZW compressed TIFF with interleaved 3 samples / 4 bits per sample RGB data.
[print.zip](https://github.com/haraldk/TwelveMonkeys/files/8124324/print.zip)

**Comment by haraldk** [comment]
We do actually support any multiple of 2, > 8 bits (up to 32 bits), so it should be fairly simple to also add support for multiples of 2, < 8 bits...

**Comment by haraldk** [comment]
> It should be fairly simple to also add support

...at least that's what I thought the other day. Seems it's a little more work than I initially hoped, as the bit padding doesn't work correctly for 2/4 bit samples and multiple samples per pixel. But still doable and a good addition.

**Comment by Schmidor** [comment]
I tried using a PackedSampleModel with DataType "short" and activating bit padding but gave up, when I couldn't figure out the problem and thought im totally wrong.

So the BitPaddingStream currently is padding per sample and we need padding per pixel, when a PackedSampleModel is used. Is that correct?

**Comment by haraldk** [comment]
Funny, I tried something similar, but chose to use a `ComponentColorModel` and tried to pad each component to 8 bits... Unfortunately, there seems to be a "bug" in `BitPaddingStream` that makes this impossible... I'll try your approach too, as it makes sense to use packed samples. 

> So the BitPaddingStream currently is padding per sample and we need padding per pixel, when a PackedSampleModel is used. Is that correct? 

Yes, I think so. We could probably "fake" it by saying that the 3 RGB 4 bit samples are actually just a single 12 bit sample though, and get it padded to 16 bit...

**Comment by haraldk** [comment]
Yup, think I got it now. 

Kind of hackish, and possibly not byte order safe, but it works for both the LibTIFF `flower-rgb-contig-0*.tif` samples and your `print.tif`. 😀

**Comment by haraldk** [comment]
Try it out, if you have more sample files! 😀
