### ISSUE TITLE
Support for Animated WebP

### ISSUE THREAD

**Issue by ftk789** [haraldk/TwelveMonkeys#673]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for Animated WebP files

**Describe alternatives you've considered**
Nothing

**Additional context**
Thank you <3

**Comment by haraldk** [comment]
> **Is your feature request related to a problem? Please describe.**
> No

You don't have a use case for animated WebP, you just like support for it, is that the case? 😉 

Actually, the `WebPImageReader` in the master branch should already support animated WebP. You can try out the prebuilt [snapshot release](https://oss.sonatype.org/content/repositories/snapshots/com/twelvemonkeys/) if you like. 

The ImageIO API isn't great for working with animation though, you need to read frame by frame and handle the animation yourself. But at least the reader should report the correct number of frames (`getNumImages(true)`) and decode each frame in VP8 format.

**Comment by ftk789** [comment]
Well i want to use it and make it embed some links to support WebP for Java, If that makes any sense.

**Comment by haraldk** [comment]
Sorry, no I didn't get that... 😛 

But in any case, give the current implementation a try, and let me know how that worked. 😀

**Comment by ftk789** [comment]
It works, But the loseless un-transparent is an issue , No transparency at all sadly

**Comment by haraldk** [comment]
Yes, that is expected, see  #629. 

Feel free to contribute working code or support/sponsor the project, if you like to help out fixing that! 😀
