### ISSUE TITLE
RGBA TIFF with 4 bits per channel has channels mixed up

### ISSUE THREAD

**Issue by bernhardf-ro** [haraldk/TwelveMonkeys#681]
The attached TIFF is RGBA with 4 bits per channel. The order of channels seems to get mixed up during reading, including using one of the color channels as alpha.

An included PNG shows the result ("transparent"). The other PNGs are the same but with different background colors or patterns to highlight the incorrect alpha.

Please see [attachment](https://github.com/haraldk/TwelveMonkeys/files/8805354/rgba-4444.zip) and [expected colors](https://cdn.pixabay.com/photo/2016/10/22/20/52/balloon-1761634__340.jpg).

**Comment by haraldk** [comment]
Thanks for reporting!

This seems to be an issue with how we read ARGB 4444 as USHORT / 16 bit entities and byte order... I'll fix.

**Comment by haraldk** [comment]
Thanks for the sample files! Should be fixed now in master.

**Comment by bernhardf-ro** [comment]
Tried master in our integration and can confirm the fix.
