### ISSUE TITLE
Lab TIFFs with alpha cause exceptions (with partial solution)

### ISSUE THREAD

**Issue by bernhardf-ro** [haraldk/TwelveMonkeys#682]
The attached TIFFs use Lab colors and one extra sample for unassociated alpha.
Both cause exceptions in TIFFImageReader.normalizeColor() in line 2251 or 2335 for 8 and 16 bits per channel respectively.
In both cases changing the step of the surrounding for-loop (line 2243 and 2327 respectively) from 3 to 4 fixes the issue.
So I assume the step of the for-loops in that method must include the extras samples of the image being read.
Please see the [attachment](https://github.com/haraldk/TwelveMonkeys/files/8805394/lab-a.zip).
https://github.com/haraldk/TwelveMonkeys/blob/b7d865f2cfb648d6acf9cd93d27bfe2c1d069933/imageio/imageio-tiff/src/main/java/com/twelvemonkeys/imageio/plugins/tiff/TIFFImageReader.java#L2243-L2251
https://github.com/haraldk/TwelveMonkeys/blob/b7d865f2cfb648d6acf9cd93d27bfe2c1d069933/imageio/imageio-tiff/src/main/java/com/twelvemonkeys/imageio/plugins/tiff/TIFFImageReader.java#L2327-L2335

**Comment by haraldk** [comment]
Thanks! I'll look into it!

**Comment by haraldk** [comment]
Thanks for the sampel files and investigation! Should be fixed now in master.

**Comment by bernhardf-ro** [comment]
Tried master in our integration and can confirm the fix.
