### ISSUE TITLE
SVG ImageReader returns wrong scaled images with height/width set and `setSourceRenderSize` used

### ISSUE THREAD

**Issue by fmeiser** [haraldk/TwelveMonkeys#684]
**Describe the bug**

Rendering with `setSourceRenderSize` of an SVG image with height and width set causes the corresponding output image to show an incorrect section.

See `circle.svg` and `wrong_scale.jpg` for details.

Reason for this seems to be the change by #522 , because thereby the default dimensions of an image are set with given width and height of SVG root. 

The code 
```
        else if (size != null) {
            // Allow non-uniform scaling
            hints.put(ImageTranscoder.KEY_AOI, new Rectangle(origSize));
        }
```
from `SVGImageReader` takes the `origSize` as AOI but `origSize` contains the dimensions from width and height.
Before the changes made by #522 , the `origSize` contained the view box, which I think would be correct.

For `correct_scale.jpg` the `origSize` was set to the view box dimensions in debugging mode so that a correct image was created.

**Version information**

Used version 3.8.2, since 3.6

**To Reproduce**

Render `circle.svg` with 

```
svgParam.setSourceRenderSize(new Dimension(400,400));
``` 

'circle.svg'
![circle](https://user-images.githubusercontent.com/11080382/171917258-a8e6dcae-3449-44d9-b3e8-0eda6167b563.svg)

`wrong_scale.svg`
![wrong_scale](https://user-images.githubusercontent.com/11080382/171917394-aca74260-5a0b-46ba-8da8-ada5c78533af.jpg)

`correct_scale.svg`
![correct_scale](https://user-images.githubusercontent.com/11080382/171917349-2ebcc65f-f460-4666-a158-7b5a8549464d.jpg)

**Comment by haraldk** [comment]
Should be fixed now in latest snapshot.
