### ISSUE TITLE
same project mac is success,but linux and win is fail

### ISSUE THREAD

**Issue by InTheBloodHorse** [haraldk/TwelveMonkeys#686]
so sad

**Comment by InTheBloodHorse** [comment]
I want tools to solve the method "ImageIO.read(new URL(url))" The picture will be red. MVN has added dependency. The test function on MAC is normal. Linux and win are useless. Please help me!

**Comment by haraldk** [comment]
Sorry you're sad, 

But with this level of information I can only give very generic help:

1. For general questions about standard JDK ImageIO, it's better to ask on StackOverflow than here. But still, be specific and make sure you include necessary and relevant information like the value of your URL, what format do you try to read and stack trace or other symptoms of the problem.
2. If you believe that this is a problem with the TwelveMonkeys library, in addition to the above, specify the Java version, the library version, and what plugin you use.
3. If you read images from HTTP(S) or other non-local URL, I suggest you first download them to a local file and read from there. While reading directly from a non-local resource will work in theory, you have very little control over headers, response and how things are downloaded.
