### ISSUE TITLE
WebP: Reading from InputStream with unknown length does not decode (produces black image)

### ISSUE THREAD

**Issue by gjrjf** [haraldk/TwelveMonkeys#692]
**Version information**
3.8.2

** The *exact* output of `java --version` (or `java -version` for older Java releases). 
openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment Corretto-11.0.3.7.1 (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.3.7.1 (build 11.0.3+7-LTS, mixed mode)

**Describe the bug**

First of all, thank you for creating a very useful library.

My problem is:

https://github.com/haraldk/TwelveMonkeys/issues/672#issue-1204081521
Similar to the problem above. (only for webp )

In my case, I want to immediately save the image uploaded by the client.
It's not reading a file, it's saving a byte[] or InputStream as an image file.

Because in my case I am using Spring framework,

From org.springframework.web.multipart.MultipartFile.
For example

`BufferedImage image = ImageIO.read(multipartFile.getInputStream());`

However, the result is that a black image is extracted.

https://github.com/haraldk/TwelveMonkeys/issues/672#issue-1204081521
Seeing the above case, I temporarily solved it like this:

// Once uploaded, save the image as a file to disk.
`FileCopyUtils.copy(multipartFile.getBytes(), file);`

// Read back the file saved to disk. for image processing
`BufferedImage image = ImageIO.read(file);`

// Process the image and save it again.

This works fine, but it's an unnecessary process.
It will take more time.

BufferedImage image = ImageIO.read(multipartFile.getInputStream());

Is there any way to solve the above at once?

thank you!

**Comment by hprange** [comment]
Hey @haraldk! I'm having the same issue reported by gjrjf. I see you fixed it on Apr 22nd (https://github.com/haraldk/TwelveMonkeys/commit/9fe87fe10d692c5b9142e0c8f00f4118c07fc49e). However, the latest TwelveMonkeys release is from Feb 22nd. Are you planning to release a new version of TweveMonkeys any time soon? Can I help somehow? I'm very interested in this fix.

**Comment by haraldk** [comment]
Hi,

I'm currently on summer holiday with my family, but I'll try to make a new release when I'm back in the office.

-- 
Harald K

**Comment by gjrjf** [comment]
Thank you very much.
Have a nice summer holiday.

**Comment by Matt-MX** [comment]
I'd like to add to this, when decoding an animated WebP image, it mostly works but produces some rather strange results.
frames are either read incorrectly or have an incorrect size.
https://cdn.discordapp.com/attachments/1002313233471913985/1005877018484818050/animated-3.png
https://cdn.discordapp.com/attachments/1002313233471913985/1005876297056137286/unknown.png

**Comment by haraldk** [comment]
@Matt-MX I don't think that is related to the issue here. It might be a different issue, an effect of the fact that we don't (yet) support lossless data needed for transparency, or not an issue at all (animation frame data may be just a subregion of the first frame, if it only replaces part of the frame, this is consistent with how a GIF animation is decoded).

**Comment by haraldk** [comment]
@gjrjf Regarding the issue reported, this was indeed fixed as mentioned by @hprange, and should work using the snapshot releases. I'll try to make a full release soon.

**Comment by gjrjf** [comment]
@haraldk 
That's cool.
thank you!

**Comment by haraldk** [comment]
Closing as duplicate.
