### ISSUE TITLE
No image reader for some webp images

### ISSUE THREAD

**Issue by sghpjuikit** [haraldk/TwelveMonkeys#695]
**Describe the bug**
No image reader for some webp images. Maybe they are unsupported?

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.8.3

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
```
IBM Semeru Runtime Open Edition 17.0.3.0 (build 17.0.3+7)
Eclipse OpenJ9 VM 17.0.3.0 (build openj9-0.32.0, JRE 17 Windows 10 amd64-64-Bit Compressed References 20220422_155 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - dc07fd49b92 based on jdk-17.0.3+7)
```

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Win10

4. Gradle dependencies (all imageio dependencies):
```
         implementation("com.drewnoakes", "metadata-extractor", "2.18.0")
         fun imageIO(name: String) = implementation("com.twelvemonkeys.imageio", "imageio-$name", "3.8.3")
         imageIO("batik")
         imageIO("bmp")
         imageIO("clippath")
         imageIO("core")
         imageIO("hdr")
         imageIO("icns")
         imageIO("iff")
         imageIO("jpeg")
         imageIO("metadata")
         imageIO("pcx")
         imageIO("pdf")
         imageIO("pict")
         imageIO("pnm")
         imageIO("psd")
         imageIO("reference")
         imageIO("sgi")
         imageIO("tga")
         imageIO("thumbsdb")
         imageIO("tiff")
         imageIO("webp")
```

**To Reproduce**
```kotlin
val stream = ImageIO.createImageInputStream(File("path to file"))
val reader = ImageIO.getImageReaders(stream).asSequence().first() // throws exception, sequence is empty
```

**Expected behavior**
At least 1 ImageReader available.

**Sample file(s)**
The problem is not in the file extension. Using `http://www.detectfiletype.com/detect-file-type` for the example file produces
```
File Type: RIFF (little-endian) data, Web/P image (Lepton 3.x), scale 22439-26858, spot sensor temperature -0.000000, color scheme 2, minimum point enabled, maximum point enabled, calibration: offset 182531631487665091641344.000000, slope 77920946189811760608417463402496.000000 (Lepton 2.x), scale 11820-4235, spot sensor temperature -304598018687058958721167281283399680.000000, color scheme 141, calibration: offset -603874.187500, slope 49309304049631232.000000
- data
MIME Type: image/webp;
Suggested file extension(s): webp
```

**Comment by sghpjuikit** [comment]
Test file to reproduce the issue
[dvgi7z75o5x61.zip](https://github.com/haraldk/TwelveMonkeys/files/9387317/dvgi7z75o5x61.zip)

**Comment by haraldk** [comment]
Hi,

This is a known issue. Your WebP file is in WebP Lossless format, and we only support lossy VP8 encoding at the moment. There is specific code in the `WebPImageReaderSpi` that rejects this kind of files, even if they are in WebP/RIFF format. 

-- 
Harald K

**Comment by sghpjuikit** [comment]
Ok, thx for the info.

**Comment by sghpjuikit** [comment]
Just for anyone wondering, support for lossless webp has been implemented.

**Comment by haraldk** [comment]
True, and it will be released soon. Hope to do it today/during the weekend.

**Comment by sghpjuikit** [comment]
Tested and works, with some performance issues, see https://github.com/haraldk/TwelveMonkeys/issues/687#issuecomment-1279897454
