### ISSUE TITLE
batik docs: recommend v1.15?

### ISSUE THREAD

**Issue by pjfanning** [haraldk/TwelveMonkeys#700]
Thanks for maintaining the project. Batik 1.15 fixes some security issues. Would it be possible to recommend that version as a minimum? 

https://www.cvedetails.com/vulnerability-list/vendor_id-45/product_id-4834/Apache-Batik.html

**Comment by haraldk** [comment]
Hi PJ,

I agree. However, recommending a specific version of a third-party library will always be a moving target, and I don't have the time to monitor and validate the security of each release.

The front page contains a security notice on Batik, and links to [https://xmlgraphics.apache.org/security.html](The Apache™ XML Graphics Project - Security). Perhaps we should remove the version number here, and instead state something like "make sure you use an updated and secure version"?

**Comment by pjfanning** [comment]
I'm happy with that. I agree that maintaining version numbers in docs is a pain.

**Comment by pjfanning** [comment]
I'm happy with that. I agree that maintaining version numbers in docs is a pain.

**Comment by haraldk** [comment]
Fixed in 29dca0f124ca2c5dff400d806163af51e36d5193 😀
