### ISSUE TITLE
Facing IIOInvalidTreeException: Xdensity attribute out of range

### ISSUE THREAD

**Issue by MoonStruckHorrors** [haraldk/TwelveMonkeys#701]
I'm trying to write an JPEG image with metadata using imageio-jpeg. It works for most of the scenarios but is failing for one particular case with this error:

````
javax.imageio.metadata.IIOInvalidTreeException: Xdensity attribute out of range
at com.sun.imageio.plugins.jpeg.MarkerSegment.getAttributeValue(MarkerSegment.java:164)
at com.sun.imageio.plugins.jpeg.JFIFMarkerSegment.updateFromNativeNode(JFIFMarkerSegment.java:266)
at com.sun.imageio.plugins.jpeg.JFIFMarkerSegment.<init>(JFIFMarkerSegment.java:151)
at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromNativeTree(JPEGMetadata.java:2203)
at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromTree(JPEGMetadata.java:2168)
at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:168)
````

This is the write method I'm using:

`writer.write(null, new IIOImage(resizedImage, null, metadata), param);`

where `param` is

````
ImageWriteParam param = writer.getDefaultWriteParam();
if (param instanceof JPEGImageWriteParam) {
            ((JPEGImageWriteParam) param).setOptimizeHuffmanTables(true);
}
````

`metadata` is read from the source image like this

````
imageMetadata = imageReader.getImageMetadata(0);
````

Now, I don't have the image which is causing this but trying to figure out how I can go about avoiding this.

Doesn't yield much results in search. Except an old issue (#4) which doesn't seem relevant.

**Comment by haraldk** [comment]
Thanks for reporting!

The x and y density fields of the JFIF segment should be in the range [1 ... 65535] (unsigned short). If the values are read from an existing image, my guess would be the value is 0 (the only possible value that doesn't fit in that range). 

A quick fix would be to force the values into that range. Depending on the unit field, good defaults could be 1 for unit 0 ("aspect only"), 72 for unit 1 (DPI) or equivalent for unit 2 (Dots per cm).

Would be interesting to see a sample image that cause this bug, along with a failing test case. Also, if you like, feel free to provide a PR that fixes this. I think the best place is to modify/correct the metadata in the writer (`JPEGImageWriter` and issue a warning that the invalid metadata was discarded.

**Comment by MoonStruckHorrors** [comment]
Thanks for the response. Unfortunately I don't have a sample image to reproduce this error, so not sure what's the actual value of Xdensity in the metadata. I'll see if I can find something and create a PR.

**Comment by haraldk** [comment]
Closing for now. But please reopen if you find a sample image, so we can investigate if there is something smart we can do!😀
