### ISSUE TITLE
NullPointerException while reading an WebP animated image

### ISSUE THREAD

**Issue by XspeedPL** [haraldk/TwelveMonkeys#702]
**Describe the bug**
NullPointerException while trying to read an otherwise browser-viewable WebP animated image frame

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.9.0-20220929.130202-41

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
openjdk version "17.0.4.1" 2022-08-12 LTS
OpenJDK Runtime Environment Zulu17.36+17-CA (build 17.0.4.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu17.36+17-CA (build 17.0.4.1+1-LTS, mixed mode, sharing)

3. Extra information about OS version, server version, standalone program or web application Windows 10 [Version 10.0.19044.2075]

**To Reproduce**
1. Run the below sample code
2. See error

**Expected behavior**
Image frame loaded for reading

**Example code**
```java
var source = new URI("https://cdn.7tv.app/emote/60dbea82e3e5887a4a95e1db/2x").openStream();
var in = ImageIO.createImageInputStream(source);
var reader = ImageIO.getImageReaders(in).next();
int numFrames = reader.getNumImages(true);
System.out.println("Frames: " + numFrames);

for (int frameIndex = 0; frameIndex < numFrames; ++frameIndex) {
	var img = reader.read(frameIndex);
	System.out.println("W: " + img.getWidth() + ", H: " + img.getHeight());
}
```

**Sample file(s)**
https://cdn.7tv.app/emote/60dbea82e3e5887a4a95e1db/2x

**Stack trace**
```
java.lang.NullPointerException: Cannot invoke "java.awt.image.WritableRaster.getHeight()" because "<parameter1>" is null
at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.opaqueAlpha(WebPImageReader.java:640)
at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.read(WebPImageReader.java:439)
at java.desktop/javax.imageio.ImageReader.read(ImageReader.java:938)
```

**Screenshots**

**Additional context**

**Comment by haraldk** [comment]
Thanks for reporting!

There seems to be an incorrect assumption that there is always alpha in animation frames... 
I'll fix.

**Comment by haraldk** [comment]
Fixed.
