### ISSUE TITLE
Performance of WebP Reader

### ISSUE THREAD

**Issue by sghpjuikit** [haraldk/TwelveMonkeys#704]
**Describe the bug**
Loading big lossless WebP image takes seconds.

**Version information**
```
Win10
TwelveMonkeys ImageIO library in use. For example:  3.9.0

IBM Semeru Runtime Open Edition 17.0.3.0 (build 17.0.3+7)
Eclipse OpenJ9 VM 17.0.3.0 (build openj9-0.32.0, JRE 17 Windows 10 amd64-64-Bit Compressed References 20220422_155 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - dc07fd49b92 based on jdk-17.0.3+7)
```

**To Reproduce**
Load reasonably big lossless webp image (multiple MBs).

**Expected behavior**
Shorter loading time with subsampling.

**Sample file(s)**
Attach any sample files needed to reproduce the problem. Use a ZIP-file if the format is not directly supported by GitHub.

**Stak trace**
n/a

**Screenshots**
n/a

**Details**

Using setCache(true) does make load times worse. Therefore, I'm going to only discuss loading times with setCache is false.
Using setCache(false) for 8MB losless webp:

ImageIO.createImageInputStream(FileInputStream(file).readAllBytes().inputStream()) // 1.5s (everything in memory from the start)
ImageIO.createImageInputStream(FileInputStream(file).buffered(bufferSize)) // 1.5s (bufferSize 8k vs 124k vs 1M has 0 impact)
ImageIO.createImageInputStream(FileInputStream(file)) // +-22s
ImageIO.createImageInputStream(file) // +-25s

Debugging confirms the implementations use
* class com.twelvemonkeys.imageio.plugins.webp.WebPImageReader
* class com.twelvemonkeys.imageio.stream.BufferedChannelImageInputStream

> Running the entire WebP test...

I had a try with the images in TwelveMonkeys\imageio\imageio-webp\src\test\resources\webp. They are all very small. The largest images are 100kB and those already last 500ms to load, so they show the problem already.

> I'm very surprised that ImageIO.createInputStream with File or FileInputStream displays this sort of performance...
Yeah, particularly the fact that using BufferedInputStream helps so much (see below) points to some serious problem.

> ImageIO.setCache(true) is the same as the default setting, and enables disk caching (as opposed to in-memory cache). It will always be slower. So when possible, use setCache(false) for better performance.

Alright, I will. But setting false has little effect on loading speed unless I explicitly use BufferedInputStream

> The new stream implementations does buffering internally (using fixed 8k buffer), so changing the buffer size of the InputStream is unlikely to have much effect.

Yes my tests confirm this. 8k buffer or 1MB buffer show almost no change.

> Instead, using a File or FileInputStream directly should be faster, as we then buffer only in once place.

My tests show this is VERY not true. Wrapping the FileInputStream into BufferedInputStream has tremendous benefits.
```
ImageIO.createImageInputStream(new FileInputStream(file)) // 25s
ImageIO.createImageInputStream(new BufferedInputStream(new FileInputStream(file))) // 2s
```
So there are 2 issues really, the buffering on client part should not be necessary and the speed is still unsatisfactory even then.

> seekForwardOnly and ignoreMetadata is mostly ignored in my readers, should have no impact on performance

Good to know

> The WebP compression is designed so that you need to decode everything, even if you are subsampling. It might be possible to decrease memory usage a little, but don't expect it to be much faster...

Does lossless do compression? From the size of the images I assumed this is basically a raw, like bmp.

The problem is not memory usage but loading speed. Windows explorer shows preview instantly, So do other image viewers - JpegView shows full-size image instantly.

**Comment by sghpjuikit** [comment]
For anyone interested, here are webp vs png stats by Google https://developers.google.com/speed/webp/docs/webp_lossless_alpha_study

Thinking about this, webp should really have better performance than png. But loading 5MB png file takes (very roughly) about 5 times less time with imageio

**Comment by haraldk** [comment]
Yes, we are very interested! 

However, I need your benchmark code and sample image to be able to reproduce your results. As I said, some of your results are very surprising.

PS: In the meantime, when debugging, can you also have a look at type of the `channel` member in the `BufferedChannelImageInputStream`?

**Comment by sghpjuikit** [comment]
I do not have any benchmark code, it is simply manual testing. Change code, load app, measure time. Again and again. Didnt think this would require so much detective work. I was planning on profiling this, but I need to do that on other pc, so maybe tomorrow.

I did not post image because it should not matter, its all lossless webp images, but here it is, 7-zipped due to Github file policy
[3bq5l7p8i5e91.zip](https://github.com/haraldk/TwelveMonkeys/files/9804573/3bq5l7p8i5e91.zip)

PS: reader: WebPImageReader, stream: BufferedChannelImageInputStream, byteBuffer: HeapByteBuffer, channel: MemoryCache(Channels$ReadableByteChannelImpl(BufferedInputStream)).

PPS: Hotspot JDK results in no difference in load times.

**Comment by sghpjuikit** [comment]
I did some profiling and didnt find anything suspicious. Im attaching the stats after reading the previously attached file. It can be seen what methods are called and how much time (absolute and relative) they took in the process of loading.
![Capture](https://user-images.githubusercontent.com/5527071/196552856-4bec11d1-c102-48fe-85c1-a5501dbe56b0.PNG)

I guess the slowness comes from the way the algorithm is implemented and not from the underlying streams. I still wonder how can other applications be so fast and I suspect there may be some good optimizations possible with lossless webp. But I have no idea what are the main performance concerns for image loading in Java. Id think that the algorithm should be the same as in native applications, so it should only be somewhat slower due to lack of inlineable types like struct and the like.

**Comment by haraldk** [comment]
Thanks for profiling! There are indeed optimizations to be done... 😀 

I made a trivial fix that made decoding your large WebP 50% faster. But that is still slow... 

I think the `LSBBitReader` implementation is part of the problem. And the `PredictorTransform` seems a bit suspicious according to your profile. 

I don't think we use `ResampleOp` in the WebP plugin anywhere. It probably has room for optimizations too, but I believe that to be a completely separate issue. Let's keep focus, please.

**Comment by sghpjuikit** [comment]
You already made improvements? And 50%? That's great. I do not mean to put pressure on you. Take your time.

I can do more profiling if needed. For Loom, I had to ditch OpenJ9 JVM, which allowed me to use profilers (lots of tools do not like OpenJ9).

PS: I do not mean to deal with multiple issues here, I merely posted some of my conclusions from profiling that people may find useful or interesting. In regards to Loom and synchronous code. Loom turns code into nonblocking code, so client avoids threads for waiting. This does not make the algorithm faster, but it does decrease memory. The real benefit of Loom comes when dealing with parallel processing (be it server requests or multiple images loading at once) - it does not make image loading faster on single image, but it does efficiently use the hardware which in turn improves overall speed. You are right that for this issue, virtual threads are irrelevant - but it is good to have it confirmed, which I did by explicitly testing with and without virtual threads.

**Comment by haraldk** [comment]
Okay, found a huge issue. 

It was caused by code in the `LSBBitReader` that did a forward seek by 8 bytes, followed by a single byte read, then did a backwards seek by 8 bytes (in result, advancing the stream by one byte). The problem arises when this happens across the boundary of the stream buffer, as this has the side effect of invalidating the buffer. This in turn was causing the entire 8k buffer to be read over and over... 

With the current version (3.9.2 release, building as we speak), you should see the kind of performance more in line with what I would expect, and that is that reading directly from a `File` or `FileInputStream` with no buffer should be as fast as or possibly faster than using a `BufferedInputStream` and `setCache(false)`. On my computer, your 8 MB/1728 * 4096 pixel WebP reads in just below 1 second. 

There are still some issues with the stream implementation, when seeking back and forth between the buffer boundary that can be resolved, or other parts of the WebP decoding that can be optimized. But at least, the performance is no longer completely ridiculous... 😀

**Comment by sghpjuikit** [comment]
That's exactly the kind of issue I'd expect and why I did not originally post the image.

In my understanding of streams, crossing the stream boundary as you call it is solved by using BuferredStream, which is what I did to get the 'good' performance. Which indicates to me, that all you did, was make using BufferedStream unnecessary, because the internal stream is aware of the boundaries. It is nice, because developers do not have to be concerned with buffering their streams, but on the other hand, the speed is actually the same as before. I would still recommend buffering explicitly to defend against more possible issues like you just fixed, buffer should not cause any problem. It could be argued making code more complicated is not worth it when adding a buffering has the same effect, but that's a broad brush to paint with.

I'm testing 3.9.3 right now... and the result is - 800-900ms without buffering (has no effect now). 3.9.2 800-900ms (requires buffering). 3.9.1 1500ms (requires buffering).

Sub second speed is not what I would call broken anymore. I suppose this is good enough and can be closed.

**Comment by tonyhook** [comment]
MoviesAnywhere uses webp for their posters. For example: https://images.moviesanywhere.com/726e7301e784f7c648824b39c0bc1a12/41434172-4331-4a14-b4ac-9a3c61ca8ad7.webp

`URL url = new URL(urlString);`
`HttpURLConnection con = (HttpURLConnection) url.openConnection();`
`con.setRequestMethod("GET");`
`if (con.getResponseCode() == HttpURLConnection.HTTP_OK) {`
`byte[] media = con.getInputStream().readAllBytes();`
`ByteArrayInputStream bais = new ByteArrayInputStream(media);`
`BufferedImage bi = ImageIO.read(bais); // This line costs minutes to return`
`bais.close();`
`}`

**Comment by haraldk** [comment]
@tonyhook On my computer, decoding the linked image takes less than 1 second. I think you are either using an outdated version of the library, or there's something else going on (ie. low memory, disk caching to slow disk, slow CPU). I am aware of issues in the WebP implementation that would benefit from optimizations, but not to this extent.

**Comment by tonyhook** [comment]
Thank you, I'll check those configurations.
