### ISSUE TITLE
Serializing decoded image

### ISSUE THREAD

**Issue by sghpjuikit** [haraldk/TwelveMonkeys#709]
I thought I would ask a question, since the authors of this project may know more about this. What would be a way to serialize decoded image, let's say into a file. Is there a way to get `BuferredImage`'s byte[] in some format (ideally without conversion)? The INT_ARGB stuff confuses me - does it change how the byte[] would then need to be read? I.e. does this information also need to be serialized?

The idea is to avoid decoding the image on read, i.e. cache, such as thumbnail cache. This could also be done for certain sizes so the image is the right size and again, we cut down on scaling and resizing and also improve final image quality, as well as make it possible to apply heavier processing of the image, since this is only done once.

But serializing raw bytes is not disk-friendly and may be actually counter-productive on small or slow devices.

Any thoughts? After replying, this issue can be closed.

**Comment by sghpjuikit** [comment]
Mostly answered by the author here https://stackoverflow.com/questions/32094497/serializing-an-object-that-includes-bufferedimages

**Comment by sghpjuikit** [comment]
My final solution for JavaFX Image (can be changed to support BufferedImage instead):
```Kotlin
   /** Stateless image cache [javafx.scene.image.Image] serializer that uses img binary data as cache format. Incurs no image processing cost. */
   object ImageFxObjectStreamSerializer {
      fun serialize(img: Image, file: File) {
         if (img.progress != 1.0 || img.isError) return
         file.parentFile.mkdirs()
         ObjectOutputStream(file.outputStream().buffered()).use { s ->
            s.writeDouble(img.width)
            s.writeDouble(img.height)
            s.writeUTF(img.url)
            s.writeObject(BYTE_BGRA_PRE)
            ByteBuffer.allocate(img.width.toInt()*img.height.toInt()*4).apply {
               img.pixelReader.getPixels(0, 0, img.width.toInt(), img.height.toInt(), img.pixelReader.pixelFormat.asIs(), this, img.width.toInt()*4)
               s.writeInt(capacity())
               s.write(array())
            }
         }
      }
      fun deserialize(file: File): Image {
         ObjectInputStream(file.inputStream().buffered()).use { s ->
            val w = s.readDouble()
            val h = s.readDouble()
            val url = s.readUTF()
            val pixelFormatType = s.readObject().asIs<PixelFormat.Type>()
            val pixelFormat = pixelFormatType.net { failIf(it!=BYTE_BGRA_PRE) { "Unsupported format=$it" }; PixelFormat.getByteBgraPreInstance() }
            val bufferCapacity = s.readInt()
            val buffer = ByteBuffer.wrap(s.readNBytes(bufferCapacity))
            return WritableImage(PixelBuffer(w.toInt(), h.toInt(), buffer, pixelFormat.asIs())).withUrl(url)
         }
      }
   }
}
```

* This solution incurs no processing cost and is blazing fast - it loads images instantly on SSD
* I always use BYTE_BGRA_PRE, because PixelBuffer (necessary for building WritableImage) only supports BYTE_BGRA_PRE and INT_ARGB_PRE and the latter requires IntBuffer instead of ByteBuffer, and it is awkward to use int arrays with Input/OutputStream. It is simpler to cache images into singular format anyway.
* I'm using this on virtual thread with no problems.

**Comment by haraldk** [comment]
Generally, I would say that the best way to serialize/deserialize a `BuffereImage` is storing it in a standard format (which is very easy using `ImageIO`). Chose a format that can store data uncompressed (like BMP, TGA, TIFF or PNM) that supports storing the image data you need (color space, samples/pixel, bits/pixel, pixel format, etc). 

What you are doing here, is basically inventing a new, proprietary file format, with custom serializing/deserializing. 

This may make sense in a few special cases where speed is essential, and you don't mind the extra complexity. Just make sure you hide these files from ever getting out your super-secret cache directory. 😀 

PS: Writing the width/height of raster images as double precision floating point sounds suspicious. You probably want to write integers here (...and as this requires changing the format, you probably want to add an "magic identifier" and a versioning scheme to your images, to make such changes possible...).

**Comment by sghpjuikit** [comment]
Yes this is intended as thumbnail cache. For application only. It has tremendous effect on performance. Your suggested version is what I was doing until now and it does work, particularly if you properly clip and resize the images when populating the cache, and it also makes loading thumbnails more deterministic/sequential, but reading the image instead of decoding it is, as I said, instant. The extra complexity of few lines is absolutely worth it!

I'm not inventing a new format, it is called Java serialization and its been around forever. It's just Image in Java is not Serializable, not by default, and the code above makes it so. It is completely normal to serialize Java objects for later use. It's sometimes better than using object databases, because, again, there is no decoding/parsing step - it is simply reading. This will always be the fastest solution to store Java object. In my opinion it is awesome to be able to store object in its 'raw' form so it can be read and restored later. Java serialization is undoubtedly controversial, but also amazing.

I'm writing dimensions as double because JavaFX Image uses double. It's an obvious case of bad design, but I'm Serializing the object as-is.

Yes, versioning the scheme is important as migration later gets easier. Thx for reminding me of more things to do... I also want to make this support animated images. There's a lot on my plate tbh.
