### ISSUE TITLE
Uncompressed PSD (CMYK profile) cannot be load by in-memory streams

### ISSUE THREAD

**Issue by cpt-rast** [haraldk/TwelveMonkeys#713]
**Describe the bug**
Currently, it seems like PSD files **without compression** cannot be read **from a stream**. Probably it has also to do with the CMYK format (tested on with CMYK-FOGRA39 with 16bbp, PSD without compression; see attached example).

There was a similar bug in v3.8.2 with webp.

I could track the problem down to the class PSDUtil.java, line 106:
```java
    static ImageInputStream createDecompressorStream(final ImageInputStream stream, int compression, int columns, int bitsPerSample,
        final int[] byteCounts, long compressedLength) throws IOException {
        switch (compression) {
            case PSD.COMPRESSION_NONE:
                return new SubImageInputStream(stream, stream.length()); // <--- stream.length() returns -1 although data is availabe, the stream is open and on position is set to 0
         ...
```
As a workaround, the PSD stream can be written to a temporary file and then be read without problems by ImageIO.

**Version information**
1. 
 - Broken on TwelveMonkeys ImageIO v3.9.3
 - Worked at least on v3.8.2

2.    java version:
```
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment Zulu11.50+19-CA (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.50+19-CA (build 11.0.12+7-LTS, mixed mode)
```

4. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc.  
- OS Windows 10 (10.0.19044 Build 19044)
- ImageIO is used as dependency for a JAR file that is acting as shared image conversion dependency for several applications
- Used Parts of ImageIO
  - imageio
  - imageio-jpeg
  - imageio-bmp
  - imageio-tiff
  - imageio-webp
  - imageio-psd

**To Reproduce**

1. Load the attached PSD file with an InputStream that can be reset
2. Read the stream by `BufferedImage img = ImageIO.read(stream);`
3. Get the exception: `java.lang.IllegalArgumentException: length < 0: -1`

**Expected behavior**
The stream length should be recognized as >0; In the end, an uncompressed PSD file should be readable by a in-memory stream

**Example code**
```java
  try {
	FileInputStream fi = new FileInputStream("C:\\temp\\cmyk_FOGRA39.psd");
	ByteArrayOutputStream inMemoryStream = new ByteArrayOutputStream();
	fi.transferTo(inMemoryStream);
	ByteArrayInputStream inputStream = new ByteArrayInputStream(inMemoryStream.toByteArray());
	inputStream.reset();
	BufferedImage img = ImageIO.read(inputStream); }
	catch (Exception ex) {
		System.out.println(ex); }
```

**Sample file(s)**
[cmyk_FOGRA39.zip](https://github.com/haraldk/TwelveMonkeys/files/9981178/cmyk_FOGRA39.zip)

**Stak trace**
```
java.lang.IllegalArgumentException: length < 0: -1
	at com.twelvemonkeys.lang.Validate.isTrue(Validate.java:197)
	at com.twelvemonkeys.imageio.stream.SubImageInputStream.<init>(SubImageInputStream.java:65)
	at com.twelvemonkeys.imageio.plugins.psd.PSDUtil.createDecompressorStream(PSDUtil.java:106)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.readImageData(PSDImageReader.java:470)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.read(PSDImageReader.java:429)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1363)
	at xx.xx.xxxxx.core.image.ImageLoader.loadBufferedImage(ImageLoader.java:224)
        --> business application call stack
```

Thank you very much in advance.

**Comment by haraldk** [comment]
Thanks for reporting and the detailed analysis! 

That seems like an oversight on my part, sorry.  I've added a test case for it, and fix. It's relatively simple.

**Comment by cpt-rast** [comment]
Thank you very much for the quick fix
