### ISSUE TITLE
PPM: Support writing TYPE_INT_RGB

### ISSUE THREAD

**Issue by kunalbarchha** [haraldk/TwelveMonkeys#714]
I am able to convert a PPM to PNG using the extension successfully, I would like to know if the opposite is possible. I tried but it results in error: 

````
2022-11-10 17:42:31.438 ERROR 17389 --- [  XNIO-1 task-1] com.mycompany.utilities.ImageUtilities   : Unsupported data type: 3

````

Here's more details : 

https://stackoverflow.com/questions/74388981/convert-a-png-to-ppm-using-imageio-twelvemonkey-extension

**Comment by haraldk** [comment]
As answered on SO:

The PNM plugin currently doesn't support writing input of type `TYPE_INT_*`, so you need to change your image type to `TYPE_3BYTE_BGR` (data type `3` refers to `DataBuffer.TYPE_INT`) .

I believe, however, that this is a bug. We shouldn't allow writing unsupported data in the first place. But it's probably also possible to add support for this data type. I'll leave this open while researching the best solution.

**Comment by haraldk** [comment]
Fixed in lastest master.
