### ISSUE TITLE
Transparency in the BMP image format

### ISSUE THREAD

**Issue by Skillkiller** [haraldk/TwelveMonkeys#717]
Hello,
is it possible to store a BufferedImage with transparency in the BMP image format? With 32 bits per pixel this information should be storable. I also don't need a fine gradation of transparency but only is transparent or not.

I need to save it in a directly modifiable format because the image is too large for the memory of the creating program and the program assembles the image piece by piece.

**Comment by haraldk** [comment]
Yes,  it's possible. 

Unfortunately software support for transparency in BMP is variable, but I think most "serious" software should support it. My `BMPImageReader` should support both the "real" (using `BI_ALPHABITFIELDS`) and "fake" transparency options. 

I assume you want to write your own BMP writer, then the best option is probably to write one of the more recent DIB headers, that contains alpha masks (`BI_ALPHABITFIELDS`) , and set the masks to full 8 bit range, to match a `BufferedImage.TYPE_INT_ARGB` or `TYPE_4BYTE_ABGR`. 

There's a lot of good information in the [Wikipedia article on BMP](https://en.wikipedia.org/wiki/BMP_file_format).

Other options could be to write uncompressed TGA or TIFF format. The PAM format (an evolution of PBM/PGM/PPM that also supports alpha, using `TUPLTYP RGB_ALPHA`) would also work I think.

**Comment by haraldk** [comment]
Found your [SO question](https://stackoverflow.com/q/74595077/1428606), which indicates that you want to write the BMP using the TwelveMonkeys library... We do support transparency in BMP, currently only using `TYPE_4BYTE_ABGR`. 

But then I'm afraid I don't understand the following:

> I need to save it in a directly modifiable format because the image is too large for the memory of the creating program and the program assembles the image piece by piece.

Could you elaborate on this, perhaps even show code or pseudo-code?

If you want to write a `BufferedImage` using `ImageIO`, that indicates you have enough memory to keep everything in memory (as that is what `BufferedImage` does)...

**Comment by Skillkiller** [comment]
Thank you for your reply. You are right, of course, and my question is not clear. Currently I use the [BigBufferedImage](https://github.com/MiklosPathy/BigBufferedImage/blob/master/BigBufferedImage.java) class from MiklosPathy which keeps only parts of the image in memory and swaps the remaining parts to a temporary file. Not perfect and also from the performance everything else than good but with pictures which have 36000x36000 dimensions not differently possible.

My original plan was to create a big BufferedImage empty and save it to disk. After that I wanted to replace single parts of the image with ImageIO. For this I found this [SO question](https://stackoverflow.com/questions/24011156/write-region-100x100px-to-huge-file-without-reading-the-target-jpeg).
First I wanted to save the images in PNG format but then the pixel replacement is not supported. Therefore I wanted to change to the BMP format, which apparently does not have a writer in ImageIO for Alpha.

**Comment by tmccombs** [comment]
> BMPImageReader should support both the "real" (using BI_ALPHABITFIELDS) and "fake" transparency options.

Do I (as a user of the twelvemonkeys API) need to do anything special when reading the BMP in order to get the support of "fake" transparency?

**Comment by tmccombs** [comment]
I have a bmp file (unfortunately github won't let me upload it), that has the following out put form imagemagick `identify --verbose`:

```
Image: image1.bmp
  Format: BMP3 (Microsoft Windows bitmap image (V3))
  Class: DirectClass
  Geometry: 137x86+0+0
  Units: PixelsPerCentimeter
  Colorspace: sRGB
  Type: GrayscaleAlpha
  Base type: Undefined
  Endianess: Undefined
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
    alpha: 8-bit
  Channel statistics:
    Pixels: 11782
    Red:
      min: 0  (0)
      max: 255 (1)
      mean: 67.0306 (0.262865)
      standard deviation: 107.995 (0.423508)
      kurtosis: -0.683889
      skewness: 1.1153
      entropy: 0.264371
    Green:
      min: 0  (0)
      max: 255 (1)
      mean: 67.0306 (0.262865)
      standard deviation: 107.995 (0.423508)
      kurtosis: -0.683889
      skewness: 1.1153
      entropy: 0.264371
    Blue:
      min: 0  (0)
      max: 255 (1)
      mean: 67.0306 (0.262865)
      standard deviation: 107.995 (0.423508)
      kurtosis: -0.683889
      skewness: 1.1153
      entropy: 0.264371
    Alpha:
      min: 0  (0)
      max: 255 (1)
      mean: 95.5188 (0.374584)
      standard deviation: 117.165 (0.459472)
      kurtosis: -1.61215
      skewness: 0.558641
      entropy: 0.378234
```

but  twelvemonkeys 3.9.4 doesn't seem to detect the transparency.

**Comment by tmccombs** [comment]
actually it might be better to make a separate issue for this.

**Comment by tmccombs** [comment]
After inspecting the image header, it looks like the 

size of the DIB is 40 ( BITMAPINFOHEADER), the bits per pixel is 32, and the compression method is 0 (BI_RGB). 

So it doesn't actually have any masks set, but I assume that the extra byte is meant as an alpha channel.  This image displays with a transparent background in some programs such as imagemgaick `display`, and I think visio.

**Comment by haraldk** [comment]
Hmm.. I think I added to the confusion I wrote that about "fake" transparency support... Turns out we don't support this kind of fake "alpha" any more (we did at some point, but it turned out to be confusing). 😮 However, as I mentioned in #727, all the alpha data is there, if you want to "restore" it. 

With the normal `BITMAPINFOHEADER` the only way to have transparency directly is using the `BI_BITFIELDS/BI_ALPHABITFIELDS` "compression" setting and specify masks. 

PS: @tmccombs You can usually upload any kind of file if you zip compress it first, if you think that sample is important.

**Comment by Skillkiller** [comment]
Again to the initial question from me. Thanks for your help @haraldk and also for your ideas. I had to pause the project for some time due to work but I was able to solve the problem as you said.

From my side the issue is ready to close. However, I don't want to interrupt the side conversation.
Thank you

**Comment by haraldk** [comment]
Thanks @Skillkiller!

I think we have the side conversation covered in a separate thread, so closing this.
