### ISSUE TITLE
Question: How to correctly add TwelveMonkeys to read SVG in IntelliJ plugin?

### ISSUE THREAD

**Issue by Symbolk** [haraldk/TwelveMonkeys#729]
Hi, this is a very elegant solution to extend the ImageIO, but from the README, I found it confusing how to setup this lib as a dependency in Gradle (and Maven). I searched in Maven Central and found that there exist many related libs, I read from the README but have no idea about what are the base libs and what are the format-specific plugin libs. 

Currently I add these to my build.gradle, but it seems not working since the readers returned by  `Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("SVG"); ` .hasNext() is false.

```
    implementation 'org.apache.xmlgraphics:batik-all:1.16'
    implementation 'org.apache.xmlgraphics:batik-swing:1.16'
    implementation 'com.twelvemonkeys.imageio:imageio:3.9.4'
    implementation 'com.twelvemonkeys.imageio:imageio-core:3.9.4'
    implementation 'com.twelvemonkeys.imageio:imageio-batik:3.9.4'
    implementation 'batik:batik-transcoder:1.6-1'
```

**Comment by Symbolk** [comment]
I also searched GitHub Code for example configuration, but none of them works :-(
https://github.com/search?q=implementation+%27com.twelvemonkeys.imageio%3Aimageio%3A&type=code

**Comment by haraldk** [comment]
Hi,

The Batik (SVG) plugin is a bit special, in that it's the only one of our plugins that has external dependencies. 

The required dependencies are listed in the [imageio-batik POM](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-batik/pom.xml), but I believe using the `batik-all` artifact should work as well. But I think you should do one or the other, and not mix. I'm not sure what that `batik:`-prefixed dependency is, but I believe it should not be necessary, use only the ones with `org.apache.xmlgraphics:` prefix.

(`com.twelvemonkeys.imageio:imageio:3.9.4` is just the aggregator POM. I don't think you need to depend on that at all).

However, the important part is that the dependencies are available at *run time*. How do you run your program, and what does the run time class path of your program look like?

**Comment by Symbolk** [comment]
Thanks for your response.

I am developing a plugin for IntelliJ IDEA, where I use gradle as the dependency manager and hope to load icons in svg format to display them in my `EditorCustomElementRenderer`, which allows drawing image with Graphics2D.drawImage(). This method accepts an Image object, so I want to load svgs into BufferedImage objects. That's why I need this lib.

Currently, I use the following configs in the build.gradle:

```
    implementation 'com.twelvemonkeys.imageio:imageio:3.9.4'
    implementation 'com.twelvemonkeys.imageio:imageio-batik:3.9.4'
    implementation 'org.apache.xmlgraphics:batik-all:1.16'
```

Then I refresh gradle and rebuild the project to make sure dependencies are downloaded, on the Gradle sidebar we can see:

![image](https://user-images.githubusercontent.com/14107297/213607078-58be1763-202d-4234-a4cb-8580fea421d7.png)

So I think they have been added to the runtime env. Before calling `ImageIO.read(url)`, I check whether the reader has been successfully loaded with the following code:
```java
         Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("SVG");
        while (readers.hasNext()) {
            System.out.println("reader: " + readers.next());
        }
        return ImageIO.read(url);
```

However, the `readers.hasNext()` always returns false, so the svg cannot be loaded and displayed, as expected.

**Comment by haraldk** [comment]
It seems Gradle doesn't handle the transitive dependencies correctly? Or do they show only if you expand the entries in the list? What happens if you click the `>` next to the `com.twelvemonkeys.imageio:imageio-batik:3.9.4` entry?

The dependencies you need (in addition to the ones you have) are `com.twelvemonkeys.imageio:imageio-core:3.9.4`,         `com.twelvemonkeys.common:common-lang:3.9.4` ,`com.twelvemonkeys.common:common-io:3.9.4` and `com.twelvemonkeys.common:common-image:3.9.4`, in addition to `commons-io:commons-io:2.11.0` needed by Batik.

And again, `com.twelvemonkeys.imageio:imageio:3.9.4` is just an aggregator POM, there's no code there, so it makes no sense to have an `implementation` dependency on it. 

Finally, for an IntelliJ plugin, special class loader restrictions may apply, that may cause the normal SPI based discovery and registration to not work. In that case, you need to consult the IntelliJ documentation or community to figure out how to install the plugin. I would start by creating a standalone program, and see if that works.

**Comment by Symbolk** [comment]
By expanding the dependencies, I confirm that Gradle has resolved the transitive dependencies. By creating a normal Gradle project from scratch, I confirm that with only batik-all and imageio-batik output the `reader: com.twelvemonkeys.imageio.plugins.svg.SVGImageReader@1e6d1014`.

So, I think you are right, the problem is specific to IntelliJ extension projects.

**Comment by Symbolk** [comment]
Thanks! I will have a try!

**Comment by Symbolk** [comment]
I changed my code like this:
```java
    private static BufferedImage loadIcon(String iconPath) {
        ImageReaderSpi spi = new SVGImageReaderSpi(); // Will be assigned to a field later
        ImageReader reader = spi.createReaderInstance();
        InputStream is = Renderer.class.getClassLoader().getResourceAsStream(iconPath);
        reader.setInput(ImageIO.createImageInputStream(is)); // Is this the correctly way to set the input?
        BufferedImage imag = reader.read(0);
//        ImageIO.scanForPlugins();
//        Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("SVG");
//        while (readers.hasNext()) {
//            System.out.println("reader: " + readers.next());
//        }
        return imag;
    }
```

However, it reports the same error that I saw when using Batik only: 
```
Caused by: java.lang.ClassCastException: class org.apache.xerces.jaxp.SAXParserFactoryImpl cannot be cast to class javax.xml.parsers.SAXParserFactory (org.apache.xerces.jaxp.SAXParserFactoryImpl is in unnamed module of loader com.intellij.util.lang.PathClassLoader @61f8bee4; javax.xml.parsers.SAXParserFactory is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @2ca8f5df)

```

This is apparently the issue related with Intellji SDK, since I found a related issue here: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360007860739-Pluging-development-with-Apache-Batik-class-loading-error-?page=1#community_comment_9910012220178

However, I tried to follow the solution provided in this thread, but the exception is still thrown.

**Comment by haraldk** [comment]
I see.. Well, the latest exception is an IntelliJ plugin class loading issue so you probably have to work with the IntelliJ community to get this sorted. I don't have any experience with IntelliJ plugins. The cast is normally safe, but it doesn't work, probably because you have some classes that are supposed to be the same, but are loaded by different class loaders and thus treated as different by Java.

**Comment by Symbolk** [comment]
Thanks for answering, so I will close this and ask in other places.

**Comment by YangLang116** [comment]
@Symbolk I also encountered the same problem, which can be solved through dynamic registration.  [Code](https://github.com/YangLang116/MediaFilePreviewer/blob/main/src/main/java/listener/AppLifecycleListenerImpl.java)

**Comment by Symbolk** [comment]
> @Symbolk I also encountered the same problem, which can be solved through dynamic registration. [Code](https://github.com/YangLang116/MediaFilePreviewer/blob/main/src/main/java/listener/AppLifecycleListenerImpl.java?rgh-link-date=2023-02-21T13%3A44%3A53Z)

Thanks for your suggestion, I tried it in my code, but still this error was thrown:

```
Caused by: java.lang.ClassCastException: class org.apache.xerces.jaxp.SAXParserFactoryImpl cannot be cast to class javax.xml.parsers.SAXParserFactory (org.apache.xerces.jaxp.SAXParserFactoryImpl is in unnamed module of loader com.intellij.util.lang.PathClassLoader @4b4523f8; javax.xml.parsers.SAXParserFactory is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @2cd2955a)
```

**Comment by haraldk** [comment]
Great news! 

Thanks @YangLang116 for providing a solution!
