### ISSUE TITLE
Set GitHub Permissions to read only

### ISSUE THREAD

**Issue by joycebrum** [haraldk/TwelveMonkeys#733]
**Is your feature request related to a use case or a problem you are working on? Please describe.**
Since Github Workflows are granted write-all permissions, it is considered a good practice to always use credentials that are minimally scoped, a recommendation from both the [OpenSSF Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) and the [Github](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions) itself.

**Describe the solution you'd like**

I would like to set the permissions on the workflow in a way that they are minimally scoped.

It means basically set the [top level](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) permission as `contents: read` (usually enough to most actions) or even read-all, and grant any write permission at the [job level](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idpermissions)

This way, even in the case of a compromised workflow, an attacker won't be able to do much.

**Additional context**
I'm from Google and I'm working with the OpenSSF to improve supply chain security in many open source projects.

**Comment by haraldk** [comment]
Thanks for reporting and suggesting ways to make the project more secure! 

I'll look into it and will try to implement the recommended workflow permissions. I'm using an action that needs write permissions for checks, I might look into the solution described [here](https://github.com/mikepenz/action-junit-report#pr-run-permissions).

**Comment by joycebrum** [comment]
I've seen the changes and it is great! Now the permissions are minimally scoped and the ci.yml seems to be working fine. I'll close this issue as done. 

Thanks for giving attention to this issue and I hope to be able to suggest other security improvements (also implementing them if you rather).
