### ISSUE TITLE
TIFF: Support for predictor: 3 (horizontal floating point predictor)

### ISSUE THREAD

**Issue by butlnor** [haraldk/TwelveMonkeys#740]
**Describe the bug**
Where reading a 32-bit float TIFF, like for example a TIFF file from public URL:

- https://copernicus-dem-90m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_30_N46_00_E008_00_DEM/Copernicus_DSM_COG_30_N46_00_E008_00_DEM.tif

The twelvemonkeys lib report an error:

```
Unsupported TIFF Predictor value: 3
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.createUnpredictorStream(TIFFImageReader.java:2487)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1123)
	at javax.imageio.ImageReader.read(ImageReader.java:940)
```

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.

3.9.4

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 

Any java version that I tried. Regarding the stack trace, the java version is irrelevant.

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

Windows 10

**Example code**
`ImageIO.read()`

**Comment by haraldk** [comment]
Hi!

The message `"Unsupported TIFF Predictor value: 3"` means that your file uses horizontal floating point predictor, and while this is a known, valid predictor value according to the TIFF 6.0 spec, we don't support it (it's not implemented at the moment). So, this is not a bug, but a possible new feature.

If you need this feature, perhaps you would like to contribute the code or sponsor the project to help us implement it? 😀

**Comment by butlnor** [comment]
> Hi!
> 
> The message `"Unsupported TIFF Predictor value: 3"` means that your file uses horizontal floating point predictor, and while this is a known, valid predictor value according to the TIFF 6.0 spec, we don't support it (it's not implemented at the moment). So, this is not a bug, but a possible new feature.
> 

The problem is that also no other ImageReader in Java supports these files, so I am now stuck. These files are completely legal GeoTIFF files, and GDAL, QGIS program, and IrfanViewer all open it without problems.

> If you need this feature, perhaps you would like to contribute the code or sponsor the project to help us implement it? 😀

I don't have enough time to contribute the code, otherwise I would implement this. For now, I will most likely use GDAL to manage these files.

**Comment by butlnor** [comment]
So, I want to say, GeoTIFFs are using TIFF format only as a way to package the data, but they are not really true images. They are normally used as a source data for later processing, like producing a real RGB shaded image of the terrain with a parametric sun elevation and angle, or similar.

**Comment by butlnor** [comment]
This GeoTIFF covers a portion of the Mediteranian sea, so it should contains values close to the 0:

- https://copernicus-dem-90m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_30_N39_00_E002_00_DEM/Copernicus_DSM_COG_30_N39_00_E002_00_DEM.tif

Otherwise, this GeoTIFF registry contains files for the whole world, the geographical latitude and longitude in degrees are in the file name: https://copernicus-dem-90m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_30_[N|S]<latitude_2digits>_00_[E|W]<longitude_3digits>_00_DEM/Copernicus_DSM_COG_30_[N|S]<latitude_2digits>_00_[E|W]<longitude_3digits>_00_DEM.tif

**Comment by haraldk** [comment]
Thanks! I understand. It's not really about how the images are displayed, however, I need some way to verify the values in the resulting `BufferedImage`s.

**Comment by haraldk** [comment]
I've added FP predictor in the latest snapshot. Try it out, and report back. 😀

**Comment by butlnor** [comment]
I tested, it does load the TIFF without an error, but unfortunatelly it seems I get all the values clamped into the [0...1] range, if I call `image.getRaster().getSampleFloat(x, y, 0);`

**Comment by butlnor** [comment]
I think "TIFFImageReader.clamp" must not be called for float rasters. I does clamp into 0...1 range.

**Comment by bchapuis** [comment]
Thanks a lot for you work on TwelveMonkeys. I'm evaluating several solutions to read geotiff files in [Apache Baremaps](https://github.com/apache/incubator-baremaps) and I observe the same behavior (the raster is filled with 1). Here is a minimalistic example:

```java
String urlString = String.format("https://s3.amazonaws.com/elevation-tiles-prod/geotiff/%s/%s/%s.tif", 14, 8492, 5792);
URL url = new URL(urlString);
BufferedImage tiffImage = ImageIO.read(url);
var raster = tiffImage.getRaster();
for (int x = 0; x < raster.getWidth(); x++) {
    for (int y = 0; y < raster.getHeight(); y++) {
        System.out.println(raster.getSampleFloat(y, y, 0));
    }
}
```
