### ISSUE TITLE
jdk 1.8 crash on javax.imageio.ImageWriter.processImageProgress

### ISSUE THREAD

**Issue by rgambelli** [haraldk/TwelveMonkeys#743]
**Describe the bug**
We have jdk crash when we try to generate a jpeg reading first page from a specific pdf file.

We have two pdf from which generates the crash, with one of them adopting twelvemonkey we resolved while with the other one we have the crash anyway.

Our java code using PdfBox to load the document
```java
try (PDDocument document = PDDocument.load(is)) {
                PDFRenderer pdfRenderer = new PDFRenderer(document);
                BufferedImage bim = pdfRenderer.renderImage(0);
                ImageIOUtil.writeImage(bim, thumbnail.getAbsolutePath(), 300);
                thumbnail.deleteOnExit();
                
            }
```

**Version information**
3.9.4

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)

CentOS Linux release 7.3.1611 (Core)

Attached the fatal error log of jdk:

[hs_err_pid32152.log](https://github.com/haraldk/TwelveMonkeys/files/11080341/hs_err_pid32152.log)

Hope you can help me, thanks

**Comment by haraldk** [comment]
I'm afraid there's not much I can do about this. The only thing the TwelveMonkeys JPEG writer plugin does in this case (the standard, non-CMYK case) according to the stack trace, is to to invoke `com.sun.imageio.plugins.jpeg.JPEGImageWriter.write` with the same parameters  that was passed to it... 

It seems the problem occurs when the native code of the JDK JPEG plugin calls back into its Java class to report write progress, but I'm no JNI expert so I don't see why/how this can cause this crash. SIGSEGV is usually an illegal memory access. It's more likely to be a JDK/JVM issue.

But, here's some things you could try: 

 *  Run the same code with only the JDK JPEG plugin. Does it still crash? 
 * Try a different JVM or more recent version of the same JVM. Does it still crash?
 * Try writing a different format (ie. PNG). It probably won't crash. 

Finally, you can try recreating the problem without PDFBox (ie. only `ImageIO.write(...)` with an image of the same dimensions and pixel layout). If you can do that, and it still crashes regularly, we can use that as a test case for further digging.

**Comment by rgambelli** [comment]
Thanks @haraldk 

> Run the same code with only the JDK JPEG plugin. Does it still crash?

I already did, I have arrived to twelvemonkeys looking for some better image management system than the standard one and yes even with just the jdk plugin the jvm crashes

> Try a different JVM or more recent version of the same JVM. Does it still crash?

I already did, I've upgraded to the latest jdk 1.8 version found for CentOS , but even with 1.8.0.**362**.b08-1.el7_9 the jvm crashes, in that installation I can't try with higher jdk but in my local system I've written a simple java code, using same PdfBox version and same files, but I'm on Windows, I tried either with jdk 1.8 or with jdk 11 and I have no crashes with the same attachment which brings the other jvm crashes.

> Try writing a different format (ie. PNG). It probably won't crash.

Unfortunately I can't make that change easily.

Anyway I was able to test a different installation of our product, where we are in Ubuntu, jdk 1.8.0_321 without twelvemonkeys it doesn't crashes and the image is generated.

Thanks for your reply, it seems really a JDK bug with a specific OS, bye

**Comment by haraldk** [comment]
Thanks for reporting back! 

I'll close this issue for now, and hope you'll find an environment where the JDK JPEG plugin works reliably!

We might replace the delegation code with a proper JPEG encoder/decoder written in pure Java in the future, but that's not really the plan just now.
