### ISSUE TITLE
Consider supporting probeContentType

### ISSUE THREAD

**Issue by oliviercailloux** [haraldk/TwelveMonkeys#782]
**Use case**
It would be nice to be able to use the simple and standard [`Files#probeContentType`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/Files.html#probeContentType(java.nio.file.Path)) to get the (correct) mime type of a given file.

**Solution**
Consider providing a MIME type provider that the Java Files API detects and uses.

**Alternatives**
I don’t know of an alternative, perhaps using Apache Commons IO.

**Additional context**
Using `Files.probeContentType(Path.of("JPEG image.png")` does not necessarily return the correct mime type as it seems to use the file extension rather than the file content.

**Comment by haraldk** [comment]
Hi Olivier,

That could be useful! 

It should probably be included in a separate module, and would not require dependency on any of the plugins, but just use standard ImageIO API. 

Feel free to provide a PR for this feature!

**Comment by gotson** [comment]
A good alternative is to use Apache Tika.

**Comment by haraldk** [comment]
I'm leaving this to a third party, unless someone provides a PR. 😀
