### ISSUE TITLE
Reading a deflate-compressed TIFF leaks native memory

### ISSUE THREAD

**Issue by jeffrey-easyesi** [haraldk/TwelveMonkeys#786]
**Describe the bug**
When decoding a deflate-compressed TIFF file, TwelveMonkeys uses the following construct:
`return new InflaterInputStream(stream, new Inflater(), 1024);`
This does not free the native memory used by the `Inflater` in a timely manner. `InflaterInputStream.close` only frees an Inflater implicitly created by the 1-arg constructor, not one passed in to the 2- or 3- arg constructors.  

**Version information**
TwelveMonkeys ImageIO version 3.9.4

openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)

**To Reproduce**
Run the test program below with a deflate-compressed TIFF file and watch memory use. Even if limited with -Xmx, the memory usage of the Java process will grow to several times the maximum heap size.

**Expected behavior**
The Java process should not use significantly more memory than the maximum heap size as specified with -Xmx. 

**Example code**
```java
    public static void main(String[] args) throws IOException {
        while (true) {
            ImageIO.read(new File("zipped.tif"));
        }
    }
```

**Sample file(s)**
Attach any sample files needed to reproduce the problem. Use a ZIP-file if the format is not directly supported by GitHub.
[zipped.tif.zip](https://github.com/haraldk/TwelveMonkeys/files/12009529/zipped.tif.zip)

**Comment by haraldk** [comment]
Hi Jeffrey,

Good catch! 

I think we can easily fix this

* either by just using the single argument constructor (and using the default buffer size of 512 bytes):

        return new InflaterInputStream(stream);

* or change the code something similar to (using a static inner class instead of anonymous might have better performance) :

        return new InflaterInputStream(stream, new Inflater(), 1024) {
                @Override
                public void close() throws IOException {
                    inf.end(); // Explicitly close inflater when done
                    super.close();
                }
            };

Doesn't seem to be a noticeable difference in performance, so probably just go with the first as it's easier to read.
