### ISSUE TITLE
JPEG encoded TIFF: Metadata components != number of destination bands

### ISSUE THREAD

**Issue by ben-manes** [haraldk/TwelveMonkeys#791]
I am trying to write the DPI for a multi-page TIFF that uses JPEG compression. This works nicely when I use Group4 or LZW, but here it fails with a vague error message _Metadata components != number of destination bands_. Searching around and looking at your tests for examples (e.g. [TIFFImageMetadataJAInteroperabilityTest](https://github.com/haraldk/TwelveMonkeys/blob/d4721919268851e0fd4ad302ae7e48f9715a8f7e/imageio/imageio-tiff-jai-interop/src/test/java/com/twelvemonkeys/imageio/plugins/tiff/jaiinterop/TIFFImageMetadataJAInteroperabilityTest.java#L81-L87)), I don't seem to be able to find an answer on how to achieve this. Everything else works beautifully if I don't set the metadata only on a jpeg.

There's probably a one-liner that I'm missing. Thanks!

```java
var params = writer.getDefaultWriteParam();
params.setCompressionMode(MODE_EXPLICIT);
params.setCompressionType(settings.compression());
var metadata = new TIFFImageMetadata(List.of(
    new TIFFEntry(TIFF.TAG_X_RESOLUTION, 200),
    new TIFFEntry(TIFF.TAG_Y_RESOLUTION, 200)));

writer.prepareWriteSequence(/* stream metadata */ null);
for (var image : images) {
  writer.writeToSequence(new IIOImage(image, /* thumbnails */ null, metadata), params);
}
writer.endWriteSequence();
```

**Comment by ben-manes** [comment]
and just like that I got it working 🙂 

```java
IIOMetadata metadata = new TIFFImageMetadata(List.of(
    new TIFFEntry(TIFF.TAG_X_RESOLUTION, 200),
    new TIFFEntry(TIFF.TAG_Y_RESOLUTION, 200)));
var type = ImageTypeSpecifier.createFromBufferedImageType(TYPE_INT_RGB);
metadata = writer.convertImageMetadata(metadata, type, null);
```

**Comment by ben-manes** [comment]
haha, given it was very late I immediately went to bed and I completely missed that the output came out purple 😞 

I tried some of the other color spaces without any luck. Hopefully I have some time today to dig into it, but any hints would be appreciated.

**Comment by haraldk** [comment]
Hi Ben,

I don’t have a computer nearby at the moment, sorry. I type this on my phone. 

But keep in mind that image metadata is per image/IFD in the TIFF. So you should probably create the metadata object inside the loop where you write images. Also, the type var should be created from the actual image you write (use ITS.createFromRenderedImag(image)).

**Comment by ben-manes** [comment]
thanks! I appreciate the response and please don't bother yourself when not available or it is a hassle.

I actually did that in a refactoring between meetings. I think the issue is something to do with the alpha channel or in some "transparency" mode, where I read index 0 is r=255,g=0,b=255 which is pink. If I convert the original jpg with ImageMagick, it turns from sRGB 3-channel to Grayscale 2-channel and the tiff (jpeg compressed) is perfect. This could be from downloading a sample from the CDN which would do some mozjpeg-style optimization to the jpeg. That might not happen on the source image in the pipeline and that I should download a better sample.

**Comment by ben-manes** [comment]
oh oh oh! This is actually a bug in TwelveMonkeys.

If I select the `com.sun.imageio.plugins.tiff.TIFFImageWriter` then the jpeg-encoded tiff is rendered correctly. It has a white background. The `com.twelvemonkeys.imageio.plugins.tiff.TIFFImageWriter` implementation has a pink background.

The DPI metadata did not get applied where it defaults to 78. So I would need to handle that xml nonsense, which looked very messy when I was searching yesterday.

Unfortunately it does seem that I found a bug here. Attached is a zip containing my test sample and outputs.

[images.zip](https://github.com/haraldk/TwelveMonkeys/files/12188019/images.zip)

**Comment by ben-manes** [comment]
okay, so I lied 😄 

I'm not sure exactly why, but I have it now working with both writers. I believe somewhere I must have passed in the wrong property, e.g. the write params, and caused some corrupted output. I'll stop spamming you, hopefully.

**Comment by haraldk** [comment]
No worries! 

I've been away on summer holiday, so not been able to comment. But glad you figured it out! 😀
