### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 2 with a JPEG

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#792]
**Describe the bug**
java.lang.ArrayIndexOutOfBoundsException: 2 with a JPEG

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.9.4

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 

java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Microsoft Windows [Version 10.0.19045.3208]

**To Reproduce**

1. Compile the below sample code
2. Download the sample image file
3. Run the code with the sample file

**Expected behavior**
I expected no exception

**Example code**

```
    public static void main(String[] args) throws IOException
    {
        try (ImageInputStream iis = ImageIO.createImageInputStream(new File("...")))
        {
            ImageReader imageReader = ImageIO.getImageReaders(iis).next();
            imageReader.setInput(iis);
            imageReader.getNumImages(true);
        }
    }
```

**Sample file(s)**
Sorry, it's confidential :-(
However I'm willing to test modified code.

**Stack trace**

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at com.twelvemonkeys.imageio.plugins.jpeg.HuffmanTable.read(HuffmanTable.java:152)
	at com.twelvemonkeys.imageio.plugins.jpeg.Segment.read(Segment.java:56)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.initHeader(JPEGImageReader.java:699)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:880)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getNumImages(JPEGImageReader.java:823)

**Comment by THausherr** [comment]
The tc array is declared as
`private final boolean[][] tc = new boolean[4][2];`
so this code
```
            if (c > 2) {
                throw new IIOException("Unexpected JPEG Huffman Table class (> 2): " + c);
            }
```
should be changed so that "2" is replaced with "1". I tried it and the code runs without problem, I guess the exception is swallowed.

**Comment by haraldk** [comment]
Hi Tilman,

Thanks for the report and possible fix! I'll look into it as soon as possible (been away on summer holidays, so might have some catch-up to do first...).

**Comment by haraldk** [comment]
Implemented and merged your fix now. Seems to work fine.
