### ISSUE TITLE
Read huge  jpg file ,get error: javax.imageio.IIOException: Can not read image of the size 54948 by 45620 

### ISSUE THREAD

**Issue by HeXCZ1028** [haraldk/TwelveMonkeys#793]
Hi ,
I want to read a huge size picture( jpg ,size 549748 * 45620, 832MB), [picture source](https://www.eso.org/public/images/kh9a0003p-cc-8bit/) , and I get the execption "javax.imageio.IIOException: Can not read image of the size 54948 by 45620"

I read huge size picture with suggestion mentioned in [issue 398](https://github.com/haraldk/TwelveMonkeys/issues/398) by using `param.setSourceSubsampling(...)` to downsample.

The following codes is what I do
```
ImageInputStream imageInputstream = ImageIO.createImageInputStream(inputStream);
Iterator<ImageReader> it = ImageIO.getImageReaders(imageInputstream);

ImageReader reader = it.next();
reader.setInput(imageInputstream,true);

int originWidth=reader.getWidth(0);
int originHeight=reader.getHeight(0);
System.out.println("originWidth: ".concat(Integer.toString(originWidth)));
System.out.println("originHeight: ".concat(Integer.toString(originHeight)));

long size=(long)originHeight*(long)originWidth;
BufferedImage image;
// if size is huge ,downsample 
if(size>=Integer.MAX_VALUE){
    int scaledWidth=1920;
    int stepSize=originWidth/scaledWidth;
    ImageReadParam param = reader.getDefaultReadParam();
    param.setSourceSubsampling(stepSize,stepSize,0,0);
    image = reader.read(0,param); // execption happen javax.imageio.IIOException: Can not read image of the size 54948 by 45620 
}
else{
    image = reader.read(0);
}
```

By the way I have read a tif file which is 35631*85142 and 1.16GB, it is ok

Any help is highly appreciated

Thanks

**Comment by HeXCZ1028** [comment]
Sorry to bother you

  I solved it by `implementation 'com.twelvemonkeys.imageio:imageio-jpeg:3.9.4'` in gradle .

  I read tiff file by `implementation 'com.twelvemonkeys.imageio:imageio-tiff:3.9.4'` in gradle, because tiff file type is not suported by origin ImageIO. And I do not import `com.twelvemonkeys.imageio:imageio-jpeg:3.9.4`, because Jpeg is supported by origin ImageIO and It make error.
  I guess `com.twelvemonkeys.imageio:imageio-jpeg:3.9.4'` has made some optimization for read jpeg file .
  
  When reading huge picture,I am wonder whether it is necessary to import specail plugin for specail file type? For example, import `com.twelvemonkeys.imageio:imageio-bmp:3.9.4` for BMP file type.
  
  Thanks

**Comment by haraldk** [comment]
Hi,

No worries! Glad you found a solution! 

I think there was/is a bug in the JDK code for how the maximum size is computed (in `javax.imageio.ImageReader#getDestination`), so I have a different way of computing it, taking subsampling and/or tiling into account. The JDK version only verifies against the original dimensions of the file. There might be similar issues for other formats, though I believe BMP files that large is quite rare.
