### ISSUE TITLE
Add write support for ico

### ISSUE THREAD

**Issue by pron** [haraldk/TwelveMonkeys#82]
...with the ability to write multiple icon sizes.

**Comment by gouessej** [comment]
This feature would be useful for me as I'd like to switch from Apache Commons Imaging to Twelve Monkeys ImageIO too. I'd like to use your library in Java Native Deployment Toolkit, I have to write .ico and .icns files on any platform supporting Java, not only Windows and OS X. Those icons are inserted into self-contained native application bundles, typically an .app bundle under OS X.

**Comment by Schmidor** [comment]
I don't know about icns, but there is a good little library  for reading and writing multi-layer ICOs under https://github.com/imcdonagh/image4j
It just also uses a custom API and no standard ImageIO.

**Comment by gouessej** [comment]
@Schmidor It's a good source of inspiration, thanks.

**Comment by haraldk** [comment]
We now have ICO write support.
