### ISSUE TITLE
NPE while read a PSD file

### ISSUE THREAD

**Issue by jack-131** [haraldk/TwelveMonkeys#843]
**Describe the bug**
when i read a PSD file use this code
`bufferedImage = ImageIO.read(new File(srcFile));`
it causes npe.
but not every psd will cause this exception,when i try other file ,it`s ok
**Version information**
![image](https://github.com/haraldk/TwelveMonkeys/assets/53454023/78e8cafe-3532-4095-9952-7095d2fb6829)

**Screenshots**
![image](https://github.com/haraldk/TwelveMonkeys/assets/53454023/055ac5bd-d6a6-4e77-977a-8454d1445e44)
**psd file cause error**
https://inner-bucket.s3.us-west-1.amazonaws.com/00001/3WlyxmnA/7be50b03-7c5a-4e5e-9ecc-b68b327b3598.psd

**Comment by haraldk** [comment]
Thanks for reporting! 

It seems we have incorrectly handled empty image resources section of PSDs, causing problems later when we search for the embedded color space. Do you happen to have a smaller sample file with this problem, that I can use in tests?

Anyway, fixed, hopefully released soon!

PS: For the future, please include version information and stack traces as text. 😀

**Comment by jack-131** [comment]
@haraldk Thank you for your answer. But now, is there a temporary and right way before next version to read this PSD file? I would greatly appreciate your answer.

**Comment by haraldk** [comment]
Version [3.10.0](https://github.com/haraldk/TwelveMonkeys/releases/tag/twelvemonkeys-3.10.0) with the fix for this issue was released on Friday. 

I don’t think there is a workaround to read it with the previous version.
