### ISSUE TITLE
JPEG: Preserve metadata when writing CMYK

### ISSUE THREAD

**Issue by caixiaoquan** [haraldk/TwelveMonkeys#852]
Hi Harald!
Please consider a enhancement of preserve metadata when writing CMYK.
https://stackoverflow.com/questions/77357401/why-metadata-is-ignored-when-write-a-cmyk-image?noredirect=1#comment136375922_77357401

**Comment by haraldk** [comment]
Please try out the latest 3.11.0-SNAPSHOT version, and see if that works for you. 😀

**Comment by caixiaoquan** [comment]
> Please try out the latest 3.11.0-SNAPSHOT version, and see if that works for you. 😀

OK，I will try later.Thanks!

**Comment by caixiaoquan** [comment]
Hi HaraldK! After upgrading to 3.11.0-SNAPSHOT, my difficulties were resolved. By the way, when is version 3.11.0 scheduled to be released?
