### ISSUE TITLE
The OSGi support only exports the ImageReaderSpi services and not the ImageWriterSpi services

### ISSUE THREAD

**Issue by steinarb** [haraldk/TwelveMonkeys#855]
The new OSGi support only exports the ImageReaderSpi services and not the ImageWriterSpi services

version 3.10.0

My bad! I only tested the reader in an OSGi context and did not test reading and writing outside of unit tests.

The upside is that I have a fix ready and will create a PR for it.

The fix has been tested with my oldalbum application and I have verified that I can download a JPEG that has its metadata modified.

Side note: ImageIO.getImageWriter() doesn't work in an OSGi context, because it uses ClassLoader.getSystemClassLoader() to find the class of writerSpi. I had to create a version that used the classloader of the reader instead (which requires the reader and writer to be from the same OSGi bundle (which luckily they are in this case)).

**Comment by haraldk** [comment]
Thanks for reporting, and the PR! 😀 

> Side note: ImageIO.getImageWriter() doesn't work in an OSGi context, because it uses ClassLoader.getSystemClassLoader() 

Yes, `ImageIO.getImageWriter(ImageReader)` and the corresponding `getImageReader(ImageWriter)` methods are problematic. I think I have reported a bug (or there was one already), but it doesn't seem important enough for the JDK. The usage of the System `ClassLoader` is both confusing, undocumented and unnecessary. All other methods of the `IIORegistry` that performs lookups uses the Context `ClassLoader` of the current `Thread`... 😕
