### ISSUE TITLE
Possible bug in Half.shortBitsToFloat

### ISSUE THREAD

**Issue by Daniel-Alievsky** [haraldk/TwelveMonkeys#865]
While implementing support of 16/24-bit float TIFF values in my library, based on SCIFIO, I decided to compare algorithm with support of 16-bit floats in TwelveMonkey. And I've noticed a little difference. Below is your code of Half.shortBitsToFloat function:

```
    public static float shortBitsToFloat(final short shortBits) {
        int mantissa = shortBits & 0x03ff;         // 10 bits mantissa
        int exponent = shortBits & 0x7c00;         //  5 bits exponent

        if (exponent == 0x7c00) {                   // NaN/Inf
            exponent = 0x3fc00;                     // -> NaN/Inf
        }
        else if (exponent != 0) {                   // Normalized value
            exponent += 0x1c000;                    // exp - 15 + 127

            // Smooth transition
            if (mantissa == 0 && exponent > 0x1c400) { // WHY??
                return Float.intBitsToFloat((shortBits & 0x8000) << 16 | exponent << 13 | 0x3ff);
            }
        }
        else if (mantissa != 0) {                   // && exp == 0 -> subnormal
            exponent = 0x1c400;                     // Make it normal

            do {
                mantissa <<= 1;                     // mantissa * 2
                exponent -= 0x400;                  // Decrease exp by 1
            } while ((mantissa & 0x400) == 0);      // while not normal

            mantissa &= 0x3ff;                      // Discard subnormal bit
        }                                           // else +/-0 -> +/-0

        // Combine all parts,  sign << (31 - 15), value << (23 - 10)
        return Float.intBitsToFloat((shortBits & 0x8000) << 16 | (exponent | mantissa) << 13);
    }
```
Please note the check "if (mantissa == 0 && exponent > 0x1c400)". The sense is not obvious: according IEEE standard, zero mantissa is a usual case for floating-point format. My version, reworked from analogous code from SCIFIO, is the following (for the case mantissaBits=10, exponentBits=5):

```
    private static int unpackFloatBits(int value, int mantissaBits, int exponentBits) {
        final int exponentIncrement = 127 - (pow2(exponentBits - 1) - 1);
        final int power2ExponentBitsMinus1 = pow2(exponentBits) - 1;
        final int packedBitsPerSampleMinus1 = mantissaBits + exponentBits;
        final int sign = value >> packedBitsPerSampleMinus1;
        final int power2MantissaBits = pow2(mantissaBits);
        int exponent = (value >> mantissaBits) & power2ExponentBitsMinus1;
        int mantissa = value & (power2MantissaBits - 1);

        if (exponent == 0) {
            if (mantissa != 0) {
                while ((mantissa & power2MantissaBits) == 0) {
                    mantissa <<= 1;
                    exponent--;
                }
                exponent++;
                mantissa &= power2MantissaBits - 1;
                exponent += exponentIncrement;
            }
        } else if (exponent == power2ExponentBitsMinus1) {
            exponent = 255;
        } else {
            exponent += exponentIncrement;
        }

        mantissa <<= (23 - mantissaBits);

        return (sign << 31) | (exponent << 23) | mantissa;
    }
    private static int pow2(int b) {
        return 1 << b;
    }
```
Both functions work identically, at least, on my test images, in particular in your test image imageio\imageio-tiff\src\test\resources\tiff\floatingpoint-16bit.tif  - but only **if I comment 3 lines** of your code:
```
//            if (mantissa == 0 && exponent > 0x1c400) { // WHY??
//                return Float.intBitsToFloat((shortBits & 0x8000) << 16 | exponent << 13 | 0x3ff);
//            }
```
If this check is not commented, on some pixels your function returns 0x3f8003ff (1.000122 float value) instead of 3f800000 (1.000000), returned by my code.

(Now you may find the corresponding commented printing code in my library: https://github.com/scichains/scichains-maps/blob/main/src/main/java/net/algart/matrices/tiff/TiffTools.java , unpackUnusualPrecisions function.)

It seems that my code is correct, but your version is not: you should remove check of zero mantissa. Check this please.

**Comment by haraldk** [comment]
I didn't write this specific code. Please see [this StackOverflow answer](https://stackoverflow.com/a/6162687/1428606), where the author explicitly addresses the lines you mention.

**Comment by haraldk** [comment]
Giving it some more thought... Maybe we should just change it to the more standard version, to be less confusing in edge cases like this?

16 bit floats are quite exotic and not very useful in my mind, anyway...

**Comment by Daniel-Alievsky** [comment]
Thank you for the fix!
Really, it is an exotic case, as well as 24-bit float. But it seems these bit depths could be useful if we need to store large image (100000x100000 ?) containing some result of image processing, such as gradients or Sobel filter. Such operations are usually work much better when they are performed with floating-point values. At the same time, the results are usually close to 0.0, and we **do** need good precision for values near 0.0, but not for large values like 100-200 (when the source image is represented by bytes 0..255). 16-bit float is an ideal choice for this situation.

**Comment by haraldk** [comment]
Btw.. Do you happen to have any sample TIFF files with 24 bit floats? 

Maybe I need a `ThreeQuarter` type... 😛

**Comment by Daniel-Alievsky** [comment]
I've found an example [here](https://github.com/ImageMagick/ImageMagick/issues/1842) and added it to my example set: 
https://github.com/scichains/scichains-maps/tree/main/build/java/resources/demo/images/tiff/rare_precisions
But I'm planning to move my TIFF support to another GitHub project soon, so the previous link will become invalid.
