### ISSUE TITLE
Workaround for ComponentColorModel.getRGBComponent throwing ArrayIndexOutOfBoundsException for SHORT (signed 16 bit)

### ISSUE THREAD

**Issue by haraldk** [haraldk/TwelveMonkeys#87]
When reading 16 bit TIFFs with signed integral data, the following stack trace occurs if you try to draw the image (see #85):

    java.lang.ArrayIndexOutOfBoundsException: -65536
    at java.awt.image.ComponentColorModel.getRGBComponent(ComponentColorModel.java:903)

We should try to provide a workaround for that (ComponentColorModel subclass).

**Comment by jan-tosovsky-cz** [comment]
What is the root cause for this error? Is is something in the image header (RGB is expected instead of grey), or value outside the expected range? I am getting this error on file generated using http://www.gdal.org/gdalwarp.html command. There are various options, maybe it could be tweaked/fixed on that end.

**Comment by haraldk** [comment]
Hmm.. 

From what I remember, the problem is that the `ComponentColorModel` doesn't properly handle signed values, so you'll get an `ArrayIndexOutOfBoundsException` when trying to look up the RGB value. I made a workaround/fix for 32 bit, however, the same/similar fix didn't work for 16 bit. Didn't have time to investigate further at the time, so the bug is still open.

Yes, it could probably be avoided. If you could limit the values to 15 bit (ie. no negative values), or use unsigned int 16 bit values, I think that should work. I'm not familiar with GDAL though, and didn't see any obvious options for controlling that...

You could probably also scale the values after reading with ImageIO (working on the raster directly), but before displaying, as the problem is with the color model, not the reading/decoding.


-- 
Harald K

**Comment by jan-tosovsky-cz** [comment]
Thanks for explanation. In my dataset I got rid of it by reducing nodata values. I tried this reduction before, but with no luck so I started to search somewhere else. But I must have made a mistake. Now it works.
While this works for my limited dataset, negative values should be definitely supported. My dataset contains elevation data which can be negative.

**Comment by haraldk** [comment]
Hi,

Did some more research into this, and I agree, negative values should be supported (that's kind of the point of using signed values...)! The sad thing is that the standard JDK `ComponentColorModel` does not support negative values (which is kind of weird, given that it has a lot of code that tests for `DataBuffer.TYPE_SHORT` vs `TYPE_USHORT`).

It's easy enough to make the exception go away, but now I'm faced with the following dilemma (or perhaps trilemma ;-):
 * I can make the 16 bit images display like the 8 bit samples you sent (but this will make everything outside the 0-255 range either solid black or solid white), and doesn't seem right for 16 bit samples. Might be a special case for GDAL elevation data.
 * I can make the images display like Preview (which is basically treating the signed data as unsigned). Your images will be pretty much all black (with white dots where the exceptions used to occur). Doesn't seem right to me. 
* I can make the images display like I think would be mathematically sound (scaled so that the range [-1...0...1] is mapped to the values [0...127...255]). Your images come out all 50% gray (with black dots where the exceptions used to occur).

I'm probably heading for the last option.


-- 
Harald K

**Comment by jan-tosovsky-cz** [comment]
To be honest, the purpose of proposed mapping is not very clear to me. The goal should be to preserve original values so resaved image should return same values. My 16-bit TIFF with elevation data is not intended for displaying. It is solely handy data format. In my use case I want to read values, crop and resize them and store them again - for further processing (I mean data processing, not image processing). The question is, if something like this can be achieved with the lack of support on JDK side.

**Comment by haraldk** [comment]
I understand. 

The reason for the mapping, is that it is required by the `ColorModel` implementation. The `ColorModel` is consulted when drawing operations are performed, like you did in [your original code](https://github.com/haraldk/TwelveMonkeys/issues/85#issuecomment-66260084) (from issue #85). It's the same API for both off-screen and on-screen (that's why I'm talking about "display"). I have a fix for this that I will check in, in not too distant future. 

But I don't think preserving the data is even possible using this approach, as it seems that all paint and draw operations are carried out in sRGB color space (which doesn't make much sense for elevation data) and in 8 bit precision (which will ruin your 16 bit samples). Not sure if it's possible to use 16 bit precision.

So... I think the conclusion is that the library supports reading and writing TIFFs in signed 16 bit precision, however, the JDK is not up to properly resampling the data at 16 bit precision. You would have to implement that, possibly looking at my [ResampleOp](https://github.com/haraldk/TwelveMonkeys/blob/master/common/common-image/src/main/java/com/twelvemonkeys/image/ResampleOp.java) class. Cropping should work fine though. :-)

-- 
Harald K

**Comment by haraldk** [comment]
Sorry this has taken so long.  The fix I had didn't really work in all cases, and I'm a little out of ideas for how to work around. I'll look into it some more though.

-- 
Harald K

**Comment by jan-tosovsky-cz** [comment]
Thanks for update. I was quite satisfied with your statement 'the library
supports reading and writing TIFFs in signed 16 bit precision, however, the
JDK is not up to properly resampling the data at 16 bit precision. You
would have to implement that (yourself). Cropping should work fine though.'

I was busy to investigate some resampling libraries able to handle 16bit
sources.

What exactly doesn't work in all cases? Reading, writing, cropping?

2015-10-23 9:34 GMT+02:00 Harald Kuhr <notifications@github.com>:

**Comment by haraldk** [comment]
Ah, 

Sorry, for the confusion. :-)

Reading, writing and cropping should work in all cases. The only problem was with my `ColorModel` workaround. It solves the exceptions, but the colors are displayed wrong. But maybe that is good enough for now. 


Regards,

-- 
Harald K

**Comment by haraldk** [comment]
Closing for now.
