### ISSUE TITLE
TIFF: Support SAMPLEFORMAT_COMPLEXINT (5)

### ISSUE THREAD

**Issue by vprivat-ads** [haraldk/TwelveMonkeys#884]
**Is your feature request related to a use case or a problem you are working on? Please describe.**

I cannot open some TIFF files from [Capella Space Open Data](https://registry.opendata.aws/capella_opendata/), and face this error:

    javax.imageio.IIOException: Unknown TIFF SampleFormat (expected 1, 2, 3 or 4): 5

**Describe the solution you'd like**

According to the [TIFF spec](https://www.awaresystems.be/imaging/tiff/tifftags/sampleformat.html), there are 6 SampleFormat values (1 to 6), but only 4 are currently supported (1 to 4).
It would be great to support the two missing values, or at least the first one:

    SAMPLEFORMAT_COMPLEXINT = 5;
    SAMPLEFORMAT_COMPLEXIEEEFP = 6;

**Describe alternatives you've considered**
N/A

**Additional context**
- https://www.awaresystems.be/imaging/tiff/tifftags/sampleformat.html
- Example file: http://capella-open-data.s3.amazonaws.com/data/2023/3/21/CAPELLA_C09_SP_SLC_HH_20230321101754_20230321101819/CAPELLA_C09_SP_SLC_HH_20230321101754_20230321101819.tif

**Comment by haraldk** [comment]
Hi @vprivat-ads, Happy new year! 🎉 

I agree that it would be great to add support for these sample formats, and I will for sure accept a PR adding handling for such formats. However, the TIFF spec does not define these sample formats, and according to the AwareSystems page you linked, they seem to be added by LibTIFF. I cannot find the specifications for these complex types anywhere. Of course, it might me possible to figure it out looking at the LibTIFF source code, but I would prefer a specification.

**Comment by haraldk** [comment]
Looking at the LibTiff source, I cannot find much special handling of the "complex" types... Maybe we can just treat them as normal integer or floating point? 

I'm not familiar with the data, so I don't know how it's interpreted or how you process them, you probably have a better understanding of this. 😀

**Comment by vprivat-ads** [comment]
Hi @haraldk! I have no idea either and will look further into it. If I can submit a PR I will let you know very soon.
