### ISSUE TITLE
Twelvemonkeys Servlet should support Jakarta

### ISSUE THREAD

**Issue by jreed-cartago** [haraldk/TwelveMonkeys#896]
We are currently upgrading our web application to use Java 17 and jakarta based packaging. We do actively use the twelvemonkeys libraries for extending the ImageIO functionality. In this case we expose the twelvemonkeys servlet project to start the integration at webservice startup. However this is no longer compatible since we are upgrading to jakarta.

We would like to have the class `com.twelvemonkeys.servlet.image.IIOProviderContextListener` upgraded to support `jakarta.servlet.*` 

Since twelvemonkeys is rather vital for us to deal with the lack of support in the ImageIO, the only option would be to create a fork of the project and make the changes ourselves, naturally offering a Pull Request to merge into the main project.

**Comment by AndrewG10i** [comment]
Just import it with classifier:
```
        <dependency>
            <groupId>com.twelvemonkeys.servlet</groupId>
            <artifactId>servlet</artifactId>
            <version>${twelvemonkeys.version}</version>
            <classifier>jakarta</classifier>
        </dependency>
````

**Comment by jreed-cartago** [comment]
@AndrewG10i Thanks for the quick reply. I didn't find any information about a jakarta branch being available.

**Comment by haraldk** [comment]
Thanks @AndrewG10i! Yes, that is the correct way. 

It is mentioned in [the readme](https://github.com/haraldk/TwelveMonkeys#maven-dependency-example) but could possibly be more clear... I'm open for a PR improving the readme. 😀

**Comment by haraldk** [comment]
Closing this for now. 😀

**Comment by haraldk** [comment]
Added a short section [here](https://github.com/haraldk/TwelveMonkeys?tab=readme-ov-file#jakarta-servlet-support) but feel free to improve on it.

**Comment by jreed-cartago** [comment]
Thanks as soon as I get a breather from this upgrade I'll see if there's anything I can add.
