### ISSUE TITLE
Please consider providing bill of materials.

### ISSUE THREAD

**Issue by jinahya** [haraldk/TwelveMonkeys#90]
Please consider providing bill of materials(BOM). It will be helpful.
I personally made one for my own project.
https://github.com/jinahya/twelvemonkeys-imageio-bom.

**Comment by haraldk** [comment]
Hi jinahya,

Thanks for your interest in the project!

Sorry for my ignorance, but what is this for? In what cases would this be helpful and solve a problem that isn't already taken care of in the projects' (Maven) POMs? I'm struggling to understand the use case here. Please enlighten me. :-)

Would I put it in the parent POM, or a separate POM altogether?


Best regards,

-- 
Harald K

**Comment by jinahya** [comment]
A case...

In my own project's parent pom I would do like this.
```
<dependencyManagement>
  <dependencies>
    <!-- importing a BOM will make all managed artifacts available without defining them -->
    <groupId>com.twelvemonkeys.imageio</groupId>
    <artifactId>imageio-bom</artifactId> <!-- if you willing to provide this -->
    <version>3.0.2</version>
    <type>pom</type>
    <scope>import</scope> <!-- wow!! -->
  </dependencies>
</dependencyManagement>
```
Then any child projects can depends on those `imageio-*` without specifying version.
```
<dependencies>
  <dependency>
    <groupId>com.twelvemonkeys.imageio</groupId>
    <artifactId>imageio-tiff</artifactId>
    <!--version>3.0.2</version--> <!-- don't need; yay~ -->
  </dependency>
  <dependency>
    <groupId>com.twelvemonkeys.imageio</groupId>
    <artifactId>imageio-jpeg</artifactId>
    <!-- something is ommited here -->
  </dependency>
</dependencies>
```
Well, anybody can say any others can use a property for this.

```
<dependencies>
  <dependency>
    <groupId>com.twelvemonkeys.imageio</groupId>
    <artifactId>imageio-tiff</artifactId>
    <version>${com.twelvemonkeys.imageio.version}</version>
  </dependency>
  <dependency>
    <groupId>com.twelvemonkeys.imageio</groupId>
    <artifactId>imageio-jpeg</artifactId>
    <version>${com.twelvemonkeys.imageio.version}</version>
  </dependency>
</dependencies>
<properties>
  <com.twelvemonkeys.imageio.version>3.0.2</com.twelvemonkeys.imageio.version>
</properteis>
```
This is very different because every dependencies has to be defined with that version-property.

A BOM is just a `pom` type project whose `<dependencyManagement>` section contains all **same versioned childrens**.
```
<groupId>com.twelvemonkeys.imageio</groupId>
<artifactId>imageio-bom</artifactId> <!-- if you willing to provide this -->
<version>3.0.2</version>
<type>pom</type>
<dependencyMangement>
  <dependencies>
    <dependency>
      <groupId>com.twelvemonkeys.imageio</groupId>
      <artifactId>imageio</artifactId>
      <version>3.0.2</version>
    </dependency>
    <dependency>
      <groupId>com.twelvemonkeys.imageio</groupId>
      <artifactId>imageio-reference</artifactId>
      <version>3.0.2</version>
    </dependency>
    <!-- keep going babe -->
  </dependencies>
</dependencyManagement>
```
Please take a look at following link for further information.
http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

**Comment by haraldk** [comment]
Ok! I'll take a look at it!

-- 
Harald K

**Comment by jinahya** [comment]
I just added `com.github.jinahya:twelvemonkeys-bom` which includes all imageio, common, and servlet.
https://github.com/jinahya/twelvemonkeys-bom

**Comment by haraldk** [comment]
Great stuff!

If possible, it would be even greater if you cloned the TwelveMonkeys project, integrate your BOM and send me a pull request. :-)

If not I'll try to use your example above as a base for a BOM when releasing 3.1. 


Thanks,

-- 
Harald K

**Comment by haraldk** [comment]
Just pushed a BOM `pom.xml` in 0232b63ed83ec6f1c06b806d5ae633ebbe7a09ed, can you look through and see if it looks good? 

Planning to make a release later today. 

-- 
Harald K

**Comment by jinahya** [comment]
@haraldk the `pom.xml` looks good to me.

**Comment by haraldk** [comment]
Great! 

And many thanks for a super-quick response! :-)

-- 
Harald K
