### ISSUE TITLE
PSD: When make PNG from PSD using TwelveMonkeys, it's different from Photoshop.

### ISSUE THREAD

**Issue by dsboo** [haraldk/TwelveMonkeys#910]
**Describe the bug**
When make PNG from PSD using TwelveMonkeys, it's different from Photoshop.
Some TEXT Layer is visible white box.

| TwelveMonkeys | Photoshop |
| - | - |
| ![35_001 (1) psd](https://github.com/haraldk/TwelveMonkeys/assets/20632677/e115a7df-76a9-442b-9785-5c785c3e39cf) | ![35_001 (1) photoshop](https://github.com/haraldk/TwelveMonkeys/assets/20632677/4cc7559d-9aaf-4dbd-b3fb-04241bd6059b) |

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
For example:  3.10.1

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
```
openjdk 11.0.22 2024-01-16
OpenJDK Runtime Environment Temurin-11.0.22+7 (build 11.0.22+7)
OpenJDK 64-Bit Server VM Temurin-11.0.22+7 (build 11.0.22+7, mixed mode)
```

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

**To Reproduce**

1. Compile the below sample code
2. Download the sample image file
3. Run the code with the sample file

**Expected behavior**
Make the same PNG as Photoshop

**Example code**
```
File psdFile = new File("src/main/resources/sample.psd");
InputStream targetStream = FileUtils.openInputStream(psdFile);
BufferedImage image = ImageIO.read(inputStream);
ImageIO.write(image, "PNG", new CustomByteArrayOutputStream());
```
Less is more. Don't add your entire project, only the code required to reproduce the problem. 😀 

**Sample file(s)**
It's over 25MB, if you need i can send your email.

**Stak trace**
Always include the stack trace you experience.

**Screenshots**
Do not add screenshots of code or stack traces. 😀 

**Additional context**

**Comment by dsboo** [comment]
@haraldk thanks for reply.

I knew it already.
>The TwelveMonkeys PSD plugin does not render PSD documents, it simply reads the bitmap data in the composite layer (or other layers)

Actually left image(it's png that made using TwelveMonkeys) was opened with mac image viewer.

I will share DropBox URL tomorrow.

**Comment by dsboo** [comment]
I can not share today:(
i will update in this week.

**Comment by haraldk** [comment]
Closing, as we still lack information to reproduce.
