### ISSUE TITLE
how to read simple Exif data 

### ISSUE THREAD

**Issue by sanatmastan** [haraldk/TwelveMonkeys#95]
Hi this is not an issue, i would like to know how to read exif data for an image, i use the same code from your ExifReader 

    public static void main(String[] args) throws IOException {
        EXIFReader reader = new EXIFReader();
		String filePath = ";";
		filePath = "/Users/syelchuri/Documents/Project/media_docs/Oracle.png";
		filePath = "/Users/syelchuri/Documents/Project/Java_Workspace/ppms/TwelveMonkeys-master/imageio/imageio-jpeg/target/test-classes/jpeg/exif-rgb-thumbnail-bad-exif-kodak-dc210.jpg";

        ImageInputStream stream = ImageIO.createImageInputStream(new File(filePath));

        long pos = 0;
        if (args.length > 1) {
            if (args[1].startsWith("0x")) {
                pos = Integer.parseInt(args[1].substring(2), 16);
            }
            else {
                pos = Long.parseLong(args[1]);
            }

            stream.setByteOrder(pos < 0 ? ByteOrder.LITTLE_ENDIAN : ByteOrder.BIG_ENDIAN);

            pos = Math.abs(pos);

            stream.seek(pos);
        }

        try {
            Directory directory;

            if (args.length > 1) {
                directory = reader.readDirectory(stream, pos);
            }
            else {
                directory = reader.read(stream);
            }

            for (Entry entry : directory) {
                System.err.println(entry);

                Object value = entry.getValue();
                if (value instanceof byte[]) {
                    byte[] bytes = (byte[]) value;
                    System.err.println(HexDump.dump(0, bytes, 0, Math.min(bytes.length, 128)));
                }
            }
        }
        finally {
            stream.close();
        }
    }

but i am getting following exception

Exception in thread "main" javax.imageio.IIOException: Invalid TIFF byte order mark '??', expected: 'II' or 'MM'
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.read(Unknown Source)
	at com.paypal.media.commons.mediautils.ImageMetadataProcessor.main(ImageMetadataProcessor.java:146)

My requirement is to read image creation date(Date/Time Original), last modified etc for an image (png, jpeg, gif) , i am not sure if gif and png can support this data or not.

Can you please help me in getting this info.

Thanks in Advance
Sanat.

**Comment by haraldk** [comment]
Hi Sanat,

As you probably know, Exif metadata is just a TIFF structure (with specific Exif-defined tags), that can be embedded in other container formats, like JFIF (JPEG). 

My `EXIFReader` does not understand the container format it is embedded in, nor does it scan the stream for the start of a TIFF structure. Instead, it expects the stream to be positioned at the beginning of the TIFF structure, and if not, it will throw the exception you see. The `main` method in `EXIFReader` isn't that useful, as you need to know the offsets to for the files you are using, and was only intended for (my own) testing.

To parse Exif from JPEG, you can use the `JPEGSegmentUtil` class to first parse the JFIF container structure, then get the Exif data from the APP1/Exif segment, like this:

    List<JPEGSegment> exifSegment = readSegments(imageInputStream, JPEG.APP1, "Exif");
    InputStream exifData = exifSegment.get(0).data();
    exifData.read(); // Skip 0-pad for Exif in JFIF
    
    CompoundDirectory exif = (CompoundDirectory) new EXIFreader().read(ImageIO.createImageInputStream(exifData)); 

    // TODO: Get values from the Exif directory
        
For the TIFF format, you can simply parse the file directly, like this:

CompoundDirectory tiff = (CompoundDirectory) new EXIFreader().read(ImageIO.createImageInputStream(new File("file.tif"))); 

For other formats, you need to first parse the container structure (like PNG chunks), and position the stream at the beginning of the Exif stream in a similar way.

Some things to note:
- You probably shouldn't need to use the `readDirectory(stream, pos)` method (and it shouldn't have been public in the first place).
- You don't have to care about the byte order, the `EXIFReader` will take care of it internally if you use the `read` method (that is what the "MM" and "II" byte order marks at the beginning of the stream is for).
- The Exif (TIFF) structure will contain offsets, these offsets are relative to the start of the structure itself. Therefore you either need to create a new `ImageInputStream` starting from that point (like for the JPEG example above), or wrap the stream in a `SubImageInputStream` before passing it the the `EXIFReader.read` method.


Best regards,

-- 
Harald K

**Comment by sanatmastan** [comment]
Thanks Harald for the inputs

**Comment by haraldk** [comment]
Good!

Closing for now. Feel free to reopen, should you have more questions.

-- 
Harald K
