### ISSUE TITLE
Dynamic images in WebP format, and even ordinary GIF images, cannot read delays after using this plugin.

### ISSUE THREAD

**Issue by ansarx** [haraldk/TwelveMonkeys#959]
After attempting and verifying, I found that it is impossible to read delays from IIOMetadata in the known ways, and I cannot obtain the frame rate.

**Comment by haraldk** [comment]
Okay..? 😕

As we don’t have a GIF plugin, and our WebP never had this feature, I’m not really sure what you are saying here. 

Perhaps show some code and try to explain better what you are trying to achieve?

**Comment by haraldk** [comment]
Closing, due to lack of detail.
