### ISSUE TITLE
heic-image

### ISSUE THREAD

**Issue by ly269nva** [haraldk/TwelveMonkeys#976]
Does this library support read Heic format images with ImageIO.read for Java ?
Which library should I reference？

**Comment by haraldk** [comment]
Hi,

No, HEIC is not supported by any TwelveMonkeys plugin, see #440 (HEIC is same as HEIF). 

You could try the [gotson/NightMonkeys](https://github.com/gotson/NightMonkeys) project, which provides ImageIO plugins using native libraries.
